### ISSUE TITLE
missing visualization type bullet

### ISSUE THREAD

**Issue by shleeable** [newrelic/terraform-provider-newrelic#1011]
### Feature Description
Trying to replicate a manually created dashboard in terraform. bullet seems to be missing.

### Describe Alternatives
NA

### Additional context
```
Error: expected widget.0.visualization to be one of [billboard gauge billboard_comparison facet_bar_chart faceted_line_chart facet_pie_chart facet_table faceted_area_chart heatmap attribute_sheet single_event histogram funnel raw_json event_feed event_table uniques_list line_chart comparison_line_chart markdown metric_line_chart application_breakdown], got bullet
```

**Comment by jpvajda** [comment]
@shleeable thanks for reporting this, could you give us a little more context by providing steps to reproduce this issue?

**Comment by sanderblue** [comment]
Hi @shleeable, currently the Terraform dashboard resource leverages the [Dashboards REST API](https://rpm.newrelic.com/api/explore/dashboards/list), which does not support the `bullet` widget type. The Dashboards API is currently undergoing a transition to our NerdGraph API and the development on the new implementation in NerdGraph is in the works. From what I can tell, the UI is leveraging a different GraphQL API for the moment, hence the difference widget type features. 

Once the new Dashboards API has been implemented in NerdGraph, we will be able to implement all the new widget features in Terraform.

We have a feature ticket for this that can be viewed here: #939 😎 

Apologies for the temporary discontinuity between the UI functionality and the Terraform functionality.

**Comment by sanderblue** [comment]
Quick update. I spoke to a colleague and they mentioned the following workaround.

> If you create a `threshold` widget with the `gauge` visualization, it will be rendered as a bullet chart.

Hope this helps 🙂
