### ISSUE TITLE
Error: 500 response returned" when performing a terraform plan/apply with data resources

### ISSUE THREAD

**Issue by aurelienlair** [newrelic/terraform-provider-newrelic#1012]
Summary

When performing a terraform plan or apply we see a "Error: 500 response returned" error response to main of the request made to https://api.eu.newrelic.com/graphql
It was occurring randomly but now it is blocking us meaning that I can no longer run these commands. Worst the same identical command (with the same synthetic checks, alert conditions so on so fourth) yesterday was working.
I have 47 modules in my codebase.

Terraform Version

Terraform v0.13.2

Affected Resource(s)

    newrelic_synthetics_monitor
    newrelic_synthetics_monitor_script
    newrelic_alert_policy
    newrelic_nrql_alert_condition
    newrelic_alert_channel

Debug Output

I can't provide the full log as there may be sensitive information but you can ask to Darren Doyle (working for New Relic) to get the logs.

Expected Behavior

A terraform plan or apply when reading configuration with modules and resources such as
    newrelic_synthetics_monitor
    newrelic_synthetics_monitor_script
    newrelic_alert_policy
    newrelic_nrql_alert_condition
    newrelic_alert_channel
it doesn't produce an error.

Actual Behavior

When attempting to run terraform plan or apply I always get a 500 error returned.

Steps to Reproduce

    terraform plan
    terraform apply

Important Factoids

Using an EU new relic account.

**Comment by zlesnr** [comment]
Hi @aurelienlair, which version of the provider are you using?  We added some retry logic a few versions back that should help the situation where the APIs are throwing 500s.

**Comment by aurelienlair** [comment]
I am using the 2.7.5

**Comment by zlesnr** [comment]
`v2.13.0` looks like the version that we added the retry.  If you can upgrade to test that out, that may help your situation.  Let us know how it goes.

**Comment by aurelienlair** [comment]
I tried with that version but it didn't change unfortunately.
2020-11-05T08:31:37.338Z [DEBUG] plugin.terraform-provider-newrelic_v2.13.3: time="2020-11-05T08:31:37Z" level=debug msg="performing request" method=GET url="https://api.eu.newrelic.com/v2/alerts_channels.json"
2020-11-05T08:31:37.973Z [DEBUG] plugin.terraform-provider-newrelic_v2.13.3: time="2020-11-05T08:31:37Z" level=debug msg="performing request" method=POST url="https://api.eu.newrelic.com/graphql"
2020-11-05T08:31:43.929Z [DEBUG] plugin.terraform-provider-newrelic_v2.13.3: time="2020-11-05T08:31:43Z" level=debug msg="performing request" method=POST url="https://api.eu.newrelic.com/graphql"

Error: An error occurred resolving this value.
Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]
Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]
2020-11-05T08:31:44.174Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]
Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]
Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]
Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]
Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]
Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]
2020-11-05T08:31:44.179Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/newrelic/newrelic/2.13.3/linux_amd64/terraform-provider-newrelic_v2.13.3 pid=1643
2020-11-05T08:31:44.180Z [DEBUG] plugin: plugin exited

**Comment by zlesnr** [comment]
Ah yes, thank you for the information.  We need to include the response `INTERNAL_SERVER_ERROR` as part of our retry logic in the client.  We did this for a `TIMEOUT` message here https://github.com/newrelic/newrelic-client-go/blob/master/internal/http/graphql.go#L76

**Comment by aurelienlair** [comment]
Is there any ETA for this fix Zach as it's a blocker for us?

**Comment by zlesnr** [comment]
https://github.com/newrelic/newrelic-client-go/pull/540 should resolve this issue once incorporated into the provider.

**Comment by aurelienlair** [comment]
> [newrelic/newrelic-client-go#540](https://github.com/newrelic/newrelic-client-go/pull/540) should resolve this issue once incorporated into the provider.

Cool :) Do you have any ETA Zach for the merge of that fix into the New Relic provider?

**Comment by zlesnr** [comment]
I should have a release out this week.

**Comment by zlesnr** [comment]
`v2.13.4` was released yesterday which includes the client update for `INTERNAL_SERVER_ERROR`.  If you can try the new version, let us know how it goes.

**Comment by aurelienlair** [comment]
I have tried and I noticed improvements as I managed to run `plan` and `apply` however sometimes I have to launch it many times before it works leaving I guess an inconsistent state on the server.
Please find below examples of issues I got:
```

Error: Request failed: :etimedout


Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]

  on ../modules/... line 59, in resource "newrelic_nrql_alert_condition" "...":


Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]

  on ../modules/... line 30, in resource "newrelic_nrql_alert_condition" "...":

```
Could you please check?
Thanks
Aurélien

**Comment by aurelienlair** [comment]
Just for the record we're using the correct version
```
Initializing provider plugins...
- Finding newrelic/newrelic versions matching "~> 2.13.0, ~> 2.13.0"...
- Installing newrelic/newrelic v2.13.4...
```

**Comment by zlesnr** [comment]
Thank you for the information.  Are all the failures related to `newrelic_nrql_alert_condition`?  Were there any changes to those resources when you started noticing this behavior?

**Comment by zlesnr** [comment]
I've included another retry in `v2.13.5` included from the client release https://github.com/newrelic/newrelic-client-go/releases/tag/v0.49.0
If you have a chance to try this also, let me know if it helps the situation.

**Comment by aurelienlair** [comment]
I just tried and got this message
```
Error: A downstream error occurred., [{"extensions":{"code":"BAD_USER_INPUT"},"message":"condition 366712 was updated concurrently"}]
```
on the apply command (I just set to DISABLE some Synthetics checks) but worst the terraform state file has been uploaded to S3 even thought I got that error (Darren Doyle will provide you with the logs).

**Comment by zlesnr** [comment]
Based on that error, it sounds like multiple processes are trying to update the same condition.  Are you getting that message consistently?  Does the error make sense to you?

**Comment by aurelienlair** [comment]
> Based on that error, it sounds like multiple processes are trying to update the same condition.
> Are you getting that message consistently? Does the error make sense to you?
really? I actually did not change anything nor I ran twice any command.
Is it normal that the state file is updated even though an error like that one occurs?
Could you please share with us the investigations you made regarding this (as I didn't change anything)?

**Comment by zlesnr** [comment]
Some folks run terraform in parallel in multiple environments, so if that were the case for you and the resource was being tracked in multiple state files, then its possible that multiple processes would try to update the same resource and the service would kick back that error message.  If that isn't happening, and you only have the resource managed in one terraform environment, and only one terraform processes is running at a time, then that probably isn't the case for you.  In that case, this might be related to the services having issues in the EU.  I know there have been some network issues in that region lately that have been causing clients, including terraform to receive more errors than lately.
