### ISSUE TITLE
Allow to manage Synthetic monitor downtimes via terraform

### ISSUE THREAD

**Issue by echoAlexey** [newrelic/terraform-provider-newrelic#1022]
Allow to manage Synthetic monitor downtimes via terraform

At the moment we are managing synthetic monitors via terraform.
Creating monitor downtimes is not possible and requires manual work.

**Comment by zlesnr** [comment]
I think this may be supported by the muting rules API soon.

**Comment by jthurman42** [comment]
Duplicate of #980
