### ISSUE TITLE
Improve error handling of "Error: resource not found"

### ISSUE THREAD

**Issue by zlesnr** [newrelic/terraform-provider-newrelic#1029]
A difficult debug session has surfaced more bad errors.  I'm unclear on some of the details, but need to write it down.

In the case where an Agent is renamed on the Agent-side, there are then two APM entities present in the system.  I'm unclear if the GUID here changed.  When a data source, which I'm guessing in this case was `newrelic_entity`, is used to search for the entity based on information from the last state, we get the `Error: resource not found` message.

We should try to reproduce the exact conditions here to improve the error that is sent back to the user.  For whatever error is being returned, probably in the structures somewhere, we should wrap the errors with something like `return fmt.Errorf("failed searching for entity %s: %s", name, err)` just to provide some context as to what was being searched.  Without that context, the user is left scratching their head as to which of the many potential resources is the one that is not found.

**Comment by hawaiian-shirt-guy** [comment]
The steps that I believe originally resulted in the error are as follows:

1) APM agent is configured with the name `foo`.
2) Terraform is run with a `newrelic_entity` and `newrelic_application_settings` looking for `foo`, adding them into tfstate.
3) APM agent is renamed `bar`.
4) The old APM entry for `foo` is deleted in the UI and `bar` is renamed `foo` also via the UI.
5) Refreshing the tfstate fails with `Error: resource not found`

Then, manually deleting the `newrelic_entity` and `newrelic_application_settings` from tfstate resolve the error.

**Comment by kidk** [comment]
I'm going to close this for now as there's been lots of improvements on the API side for `newrelic_entity`. Please don't hesitate to respond to this ticket if it's still an issue.
