### ISSUE TITLE
newrelic_nrql_alert_condition.nrql: attribute `ignore_overlap` must be set to true when `expected_groups` is 1

### ISSUE THREAD

**Issue by soumyajk** [newrelic/terraform-provider-newrelic#1030]
I am trying to convert one of the Outlier nrql alert’s newrelic provider from 1.19 to 2.13

I have removed attribute ignore_overlap as suggested in the documentation. Terraform Plan runs fine and shows below

```
~ module.outlier_cpu-nrql.newrelic_nrql_alert_condition.nrql
close_violations_on_expiration: “false” => “true”
expiration_duration: “0” => “600”
fill_option: “none” => “static”
ignore_overlap: “true” => “false”

```
But, when terraform apply runs it fails with error

```
module.outlier_cpu-nrql.newrelic_nrql_alert_condition.nrql: 1 error occurred:

newrelic_nrql_alert_condition.nrql: attribute ignore_overlap must be set to true when expected_groups is 1
It looks like terraform provider is not using attribute open_violation_on_group_overlap
```

The changes I am making are as below. 
![image](https://user-images.githubusercontent.com/25042192/99371252-93935f80-28b6-11eb-8fc1-75b42516336e.png)

![image](https://user-images.githubusercontent.com/25042192/99371285-9e4df480-28b6-11eb-8711-2ff9ef867720.png)

More details on https://discuss.newrelic.com/t/new-relic-terraform-newrelic-nrql-alert-condition-nrql-attribute-ignore-overlap-must-be-set-to-true-when-expected-groups-is-1/120963/4 

Could you please fix this as a priority as this is blocking us from upgrading to the latest version of provider. 

Thanks,
Soumya

**Comment by zlesnr** [comment]
I believe this may be resolved with https://github.com/newrelic/terraform-provider-newrelic/pull/1025.  Please try `v2.13.5` to see if this helps.

**Comment by soumyajk** [comment]
@zlesnr  Hi, i can confirm that its resolved. 
Although the plan does succeed when apply fails for many reasons in this resource type. A little bit more validation will be useful. Thanks a lot for looking into this.

**Comment by zlesnr** [comment]
Glad to hear it, thank you for confirming @soumyajk.
