### ISSUE TITLE
Migrating alert terraform projects to workspaces causes errors

### ISSUE THREAD

**Issue by jpvajda** [newrelic/terraform-provider-newrelic#1040]
### Issue 

We are migrating our alerts terraform projects to workspaces and I'm trying to apply the new alerts before removing the old ones. I'm getting consistently these two errors repeated 80 times:

we could live with this issue if we could just apply several times the terraform plan until all the alerts are created. The problem is that, every time we do `atlantis apply`, a new alert is created for each terraform entry, having multiple entries of the same alerts (see attached screenshot). Also, since the system tries to recreate all the alerts, we end up with the same "value has been requested too frequently" issues.

### Expected 

Errors aren't created when applying new alerts using terraform plan

### More Info 

According to the MaaS hero:
this is happening due to the new relic provider not using the same id.
Terraform/Atlantis is doing the same API calls but it looks like for the new relic provider are different resources

### Errors

```
Error: Resolution of this value experienced a timeout., null
  on ../modules/lag-alertable-data/main.tf line 12, in resource "newrelic_nrql_alert_condition" "warn_offset-alertable_data_lag":
  12: resource "newrelic_nrql_alert_condition" "warn_offset-alertable_data_lag" {
Error: This value has been requested too frequently., null
  on ../modules/lag-alertable-data/main.tf line 12, in resource "newrelic_nrql_alert_condition" "warn_offset-alertable_data_lag":
  12: resource "newrelic_nrql_alert_condition" "warn_offset-alertable_data_lag" {
```

![image](https://user-images.githubusercontent.com/1395158/100131090-d1593080-2e40-11eb-8ac1-b46ec178342c.png)

**Comment by mariomac** [comment]
UPDATE: we stayed working with the old projects but now we are facing the same issue:
- We get an "This value has been requested too frequently" error when we apply our plans.
- Some conditions are created in the same policy, but their IDs are not stored.
- If we replan/reapply, we get the same problem and the conditions are recreated again, having multiple instances of the same condition (and other conditions not created).

**Comment by kidk** [comment]
We're closing this ticket for lack of activity. If this is still an issue for you, please don't hesitate to reply here.
