### ISSUE TITLE
Add support for registering deployments

### ISSUE THREAD

**Issue by garbetjie** [newrelic/terraform-provider-newrelic#1042]
### Feature Description
According to the current documentation at https://registry.terraform.io/providers/newrelic/newrelic/latest/docs, there is no support for being able to register deployments on New Relic APM.

Ideally, it would be great if there was something like a `newrelic_deployment` resource, that would use the RESTv2 API to register a deployment (as shown on https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments).

### Describe Alternatives
The only other alternatives that I've been able to think of (and have used previously) is it use a combination of `curl` and `jq` to "templatise" JSON safely before sending off to the API.

### Additional context
No additional context to add.

**Comment by zlesnr** [comment]
I'm not sure how this would work in a workflow sort of situation.  What would this look like?  Each TF run would create a new deployment?  Too, just for your information, we have this functionality in the CLI.

https://github.com/newrelic/newrelic-cli/blob/master/docs/GETTING_STARTED.md#creating-a-deployment-marker

Would that satisfy your situation?

**Comment by Tensho** [comment]
We have a use case where the app stack is deployed with Terraform Kubernetes provider, including NewRelic monitoring resources. The `newrelic_deployment` resource may depend on `kubernetes_deployment` resource change.
