### ISSUE TITLE
newrelic_synthetics_multilocation_alert_condition violation_time_limit_seconds not allow 30 days

### ISSUE THREAD

**Issue by mailam-xero** [newrelic/terraform-provider-newrelic#1062]
Unable to set `violation_time_limit_seconds` for `newrelic_synthetics_multilocation_alert_condition` to max value of 2592000 (30 days) 

### Terraform Version
0.14.0

### Affected Resource(s)
- `newrelic_synthetics_multilocation_alert_condition`

### Terraform Configuration

```hcl
terraform {
  ...
required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.14.0"
    }
  }
}
```

```hcl

resource "newrelic_synthetics_multilocation_alert_condition" "synthetics_monitor_alert_condition" {
  policy_id = newrelic_alert_policy.synthetics_monitor_alert_policy.id

  name = "Synthetics Failed"
  enabled = true
  violation_time_limit_seconds = 2592000

  entities = [
    newrelic_synthetics_monitor.synthetics_monitor_login.id
  ]

  critical {
    threshold = var.synthetic_failed_location_threshold
  }
}

```

### Actual Behaviour
* Error when setting `violation_time_limit_seconds` to 2592000 (30 days) when running `terraform plan`

```
Error: expected violation_time_limit_seconds to be one of [0 3600 7200 14400 28800 43200 86400], got 2592000

in resource "newrelic_synthetics_multilocation_alert_condition" "synthetics_monitor_alert_condition":
    resource "newrelic_synthetics_multilocation_alert_condition" "synthetics_monitor_alert_condition" {
....
```

### Expected Behavior
* 30 days can be set for violation time limit (It was possible through UI)

### Steps to Reproduce
1. `terraform plan`

**Comment by progredior** [comment]
We had the same problem, if you leave it empty it defaults to 30days as per NR docs...

> The default value, if one is not supplied during configuration, is 30 days.

https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-violations/how-alert-condition-violations-are-closed#time-limit

**Comment by rjmsilveira** [comment]
This no longer works as the field is now mandatory :disappointed: 

``````
The argument "violation_time_limit_seconds" is required, but no definition
was found.
```

**Comment by NSSPKrishna** [comment]
Hi @rjmsilveira, can you raise a new issue so we can keep a track on it?
