### ISSUE TITLE
“No API key specified” error when using Terraform provider

### ISSUE THREAD

**Issue by jpvajda** [newrelic/terraform-provider-newrelic#1065]
### Actual Behavior

I’m trying to use the newrelic terraform provider, and unable to actually “apply”. I’ve whittled it down to this simple .tf file that reproduces the problem:

```

terraform {
      required_version = "~> 0.14.0"
      required_providers {
        newrelic = {
          source  = "newrelic/newrelic"
          version = "~> 2.9.0"
        }
      }
    }

    provider "aws" {
      region = "us-east-1"
    }

    provider "newrelic" {
      account_id = "my account ID"
      api_key = "NRII-..."
    }

    resource "newrelic_dashboard" "cos_tf_test" {
      title = "Cos test dashboard from Terraform"
      editable = "editable_by_owner"

      widget {
        title = "Sample title"
        visualization = "line_chart"
        row = 1
        column = 1
        nrql = "FROM ... (nrql query here)"

      }
    }
```

terraform plan works fine, but when I try to apply, I get:

```
Error: 401 response returned: No API key specified

  on main.tf line 20, in resource "newrelic_dashboard" "cos_tf_test":
  20: resource "newrelic_dashboard" "cos_tf_test" {
```

I’ve tried this with setting my environment variable NEW_RELIC_API_KEY and omitting the key from the .tf file, as well as with the key in the .tf file, and it fails the same way either way. 

### Expected Behavior

It turns out the 401 response text “No API key specified” is misleading. What it actually meant was that the key I gave was the wrong kind of key. I was on a wild goose chase wondering why terraform wasn’t giving the NR API a key at all, when in fact terraform was supplying a key - the API just didn’t accept that key. So that’s

` issue #1: Please fix that 401 response message!`

Having guessed that, I asked around and learned that until recently the API accepted admin keys but it no longer does. I wondered if they key I was using was an admin key, and if so, whether this might work with a personal API key - and confirm my guess that the 401 text was misleading.

I followed these instructions to get my personal API key:
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/getting_started 

… but that actually doesn’t work! The graphiql GUI returns obfuscated keys, like this:

`"key": "NRAK-WQW...",`

However, eventually I vaguely remembered that you can get personal API keys from “Account settings” at one.newrelic.com and once I remembered that, I was able to get the key, which made this work!

`issue #2: Please fix the “Getting Started with the New Relic Provider” I linked above, it is just plain wrong. To get your personal API key, you go to Account Settings from the menu at top right on one.newrelic.com.`

### References
https://discuss.newrelic.com/t/no-api-key-specified-error-when-using-terraform-provider/125012

**Comment by jpvajda** [comment]
@ctrombley how do we update the Terraform provider docs on terraform.io? I can resolve issue #2. Issue #1 seems to be a problem we've been hearing about around our error handling and messaging not be specific enough. - Thoughts?

**Comment by jpvajda** [comment]
@sanderblue is going to take a look at this problem today

**Comment by jpvajda** [comment]
Once resolved @jpvajda (_it me_)  will drop a comment in the corresponding zendesk issue so the communication loop is closed with support and the customer.

**Comment by jpvajda** [comment]
also will update this discuss post: https://discuss.newrelic.com/t/no-api-key-specified-error-when-using-terraform-provider/125012/2

**Comment by sanderblue** [comment]
@jpvajda this fix has been merged and released in v2.14.1 😎

**Comment by jpvajda** [comment]
@sanderblue Support let me know the customer is reporting this as unresolved, here is the feedback from the JIRA issue. 

```
It does not look like it has been fixed. This is from just now:

% export NEW_RELIC_API_KEY=invalidkey
% terraform apply
newrelic_dashboard.cos_tf_test: Refreshing state... [id=1589960]

Error: 401 response returned: No API key specified

The 401 from the API still has the misleading message.

Let us know if this helps debug this bug. 
```

**Comment by kidk** [comment]
@jpvajda Do you know if this was ever resolved?

**Comment by jpvajda** [comment]
I believe this to be done. 💯
