### ISSUE TITLE
Docs: Remove any references to legacy URLs 

### ISSUE THREAD

**Issue by sanderblue** [newrelic/terraform-provider-newrelic#1095]
### Objective
We still have some legacy URLs in our docs that could cause a bit of confusion for some folks. We should remove these. One example is [`newrelic_nrql_alert_condition`](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#import) docs regarding `import` functionality. 

i.e. 
```
alerts.newrelic.com/accounts/<account_id\>/policies/<policy_id\>/conditions/<condition_id\>/edit
```

There are likely some others lingering as well.

### Acceptance Criteria
- References to legacy URLs are removed

**Comment by ChandraIragavarapu** [comment]
Fix is available in the release: [v2.41.0-beta.2](https://github.com/newrelic/terraform-provider-newrelic/compare/v2.41.0-beta.1...v2.41.0-beta.2) - 2022-03-17
