### ISSUE TITLE
Add support for dashboards with multiple tabs/pages

### ISSUE THREAD

**Issue by schmickie** [newrelic/terraform-provider-newrelic#1098]
### Feature Description
Currently, you cannot manage any dashboards that use multiple tabs/pages in terraform. 

### Describe Alternatives
There are three alternatives 1) specify a separate dashboard for each "tab" 2) put all widgets in a single dashboard (don't use tabs) 3) manage dashboards that use multiple tabs/pages outside of terraform. My team doesn't want to have dashboard bloat, making it hard for our on-call to find the specific dashboards they need. We prefer to have a single on-call dashboard that is the go to place for on-call, rather than having them find multiple ones in the sea of dashboards in our account. Thus we have chosen not to do option 1. Option 2 is not an option in our case. We used to use this option but the dashboards wouldn't load consistently, due to NR imposed rate limits. Having dashboards that won't consistently load is a problem for on-call. Thus, we use option 3. With the widgets broken up amongst multiple tabs, we are able to gate the calls to only the widgets on the current tab and run into the rate limits less.

### Additional context
Not really. I have seen discussion of this feature over on the hub (https://discuss.newrelic.com/t/new-relic-dashboard-with-multiple-pages-via-terraform-api/105473), but wanted to officially submit it here as a feature request.

**Comment by schmickie** [comment]
How do I keep this from going stale and being closed despite the upvotes?

**Comment by rizalgowandy** [comment]
This feature gonna make our life so much easier.
Right now we ended up with too many dashboards or too long pages.

Seems like this one could provide the feature.
Forever waiting for it out of beta.
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard

**Comment by rdhar** [comment]
@rizalgowandy Looks like [newrelic_one_dashboard](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard) resource just became available, as per [v2.16.0](https://discuss.newrelic.com/t/terraform-provider-release-v2-16-0/128776). 🙌

**Comment by jthurman42** [comment]
@rdhar Correct, this was released in v2.16.0 with the GA of the updated API.

closed in #1160

**Comment by ryancastle** [comment]
Seems that this is supported via NerdGraph API now.
