### ISSUE TITLE
Widgets on Dashboard are created each time we modify a file

### ISSUE THREAD

**Issue by trebbor** [newrelic/terraform-provider-newrelic#1099]
Using version `2.13.5` with terraform version equal or greater than `0.13`, each time we modify a dashboard, all resources are created again.

After some investigation done by @zlesnr, he found it could be related with widget field `account_id`, removing this field all works as expected.

For more information, please contact `rpuig@newrelic.com` or `rfiestas@newrelic.com`

**Comment by zlesnr** [comment]
Thank you for the issue.

When I looked briefly at the issue, I think in the same way that the flatten code handles the `widget_id` here https://github.com/newrelic/terraform-provider-newrelic/blob/master/newrelic/structures_newrelic_dashboard.go#L349  a `m["account_id"] = w.AccountID` fixes the issue, but the tests should also be updated.  When I briefly looked at the issue, I wasn't able to see why the current tests weren't surfacing this issue.
