### ISSUE TITLE
Terraform import of newrelic_alert_channel fails to import the JSON payload for Webhook

### ISSUE THREAD

**Issue by Nordes** [newrelic/terraform-provider-newrelic#1142]
### Terraform Version
```
Terraform v0.14.2
+ provider registry.terraform.io/newrelic/newrelic v2.15.1

Your version of Terraform is out of date! The latest version
is 0.14.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
- `newrelic_alert_channel`

### Terraform Configuration
NewRelic provider only (empty project)

### Actual Behavior
When I do `terraform import newrelic_alert_channel.main 468....`, it does import in the TF State the configuration. Except that the webhook JSON Content is not being seen anywhere. I was able to create with the webhook content but not to _import_ it.

See config:
![image](https://user-images.githubusercontent.com/446572/105771417-84700400-5f2e-11eb-858b-f6e08f298c1a.png)

### Expected Behavior
Have the full resource as something ready to be used after import. (payload_string or payload included)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform import newrelic_alert_channel.main 468....`
3. Look at the `tfstate` file

### Debug Output
https://gist.githubusercontent.com/Nordes/813ae8a6bd98c08a9e447517f56940b6/raw/cbd988a262dd4339f0eb70c08f2adb51d49c6d5f/gistfile1.txt (enjoy)

### Panic Output
no panic

### Important Factoids
Local machine, nothing special

### References
None found regarding this specifically

**Comment by Nordes** [comment]
After a few tries, somehow, it started working. I wonder why. I am still using the same version as mentioned in the issue.

I will close the issue and if this happens again I'll reopen it.

**Comment by salemgolemugoo** [comment]
It happens to me during the import. Using:
Newrelic provider: 2.35.1
Terraform: 1.1.0

```
resource "newrelic_alert_channel" "test" {
  name = "Test"
  type = "webhook"

  config {
    base_url = "https://example.com"
    payload_type = "application/json"
    payload = {
      Json = "Payload"
    }
  }
}
```

**Comment by emetcalf9** [comment]
I was able to reproduce this and tracked the cause to the channel read function. This was checking for `payload` or `payload_string` to be set on the existing terraform resource to determine which field to use, but when importing a channel neither field is already set. PR #1755 adds an additional `else if` to check if the payload returned from the API is not blank, and adds it as the `payload_string` if it has a value.
