### ISSUE TITLE
validation of newrelic_alert_muting_rule tag condition is incorrect

### ISSUE THREAD

**Issue by jaymcgrath** [newrelic/terraform-provider-newrelic#1153]
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
v0.14.2

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alert_muting_rule`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
resource "newrelic_alert_muting_rule" "bar" {
  name = "tf-test-my-cool-rule-w-asia"
  enabled = true
  description = "terraform testing"
  condition {
    conditions {
      attribute = "tag.bazBaz_baz"
      operator = "EQUALS"
      values = [
        "barbarbar"]
    }
    conditions {
      attribute = "conditionType"
      operator = "EQUALS"
      values = [
        "static"]
    }
    operator = "AND"
  }
}
```

### Actual Behavior
Apply fails with validation error:
```
Error: expected condition.0.conditions.0.attribute to be one of [accountId conditionId policyId policyName conditionName conditionType conditionRunbookUrl product targetId targetName nrqlEventType tag nrqlQuery], got tag.bazBaz_baz

  on main.tf line 11, in resource "newrelic_alert_muting_rule" "bar":
  11: resource "newrelic_alert_muting_rule" "bar" {

```

### Expected Behavior
Rule is correct and should be accepted

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Muting Rule tag conditions take the format `tag.MyTagName`

The current validation function is `tag` like the name of a condition and failing valid tags. 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by rizalgowandy** [comment]
hi @jaymcgrath, in which version does this schedule configuration is supported?
```
  schedule {
    start_time = "2021-02-21T15:30:00"
    time_zone = "America/Los_Angeles"
    end_time = "2021-02-21T16:30:00"

    repeat = "WEEKLY"
    end_repeat = "2021-06-11T12:00:00"
    weekly_repeat_days = [
      "MONDAY",
      "FRIDAY",
      "TUESDAY",
    ]
  }
```

I am using `2.15.1` and got error
```
Terraform v0.14.5
Configuring remote state backend...
Initializing Terraform configuration...

Error: Unsupported block type

  on policies.tf line 21, in resource "newrelic_alert_muting_rule" "midnight":
  21:   schedule {

Blocks of type "schedule" are not expected here.
```

**Comment by jaymcgrath** [comment]
@rizalgowandy Hi! I'm working to add that feature right now when I discovered this issue. I opened this issue at the end of the day yesterday and accidentally posted the wrong config. 😳 

Try removing or commenting out the `schedule` block (or re-copy it from my updated comment)

Sorry about the confusion!

**Comment by rizalgowandy** [comment]
I see. Thank you for the clarification @jaymcgrath
