### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by jeanpoelie** [newrelic/terraform-provider-newrelic#1171]
### Terraform Version
Terraform v0.13.5
registry.terraform.io/newrelic/newrelic v2.15.1

### Affected Resource(s)
module.newrelic.newrelic_alert_policy

### Terraform Configuration
```hcl
resource "newrelic_alert_policy" "redis_alert_policy" {
  name                = "${var.environment} - Redis infrastructure policy"
  incident_preference = "PER_CONDITION_AND_TARGET"
}
```

### Actual Behavior
Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Canceled desc = context canceled

### Expected Behavior
odule.newrelic.newrelic_alert_policy.redis_alert_policy: comleted after ....

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Terraform Plan works fine

**Comment by jthurman42** [comment]
@jeanpoelie Can you confirm this issue is still happening on v2.20.0+ ? I'm unable to reproduce it

**Comment by harrykimpel** [comment]
@jthurman42 this issue happened again for one of my customers. He is on v2.21.0 on a Windows box.
