### ISSUE TITLE
Internal Server Error while running plan/apply on conditions or policies

### ISSUE THREAD

**Issue by SiddhantAgarwal17** [newrelic/terraform-provider-newrelic#1179]
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
`0.12.29`

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alert_condition`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```
provider "newrelic" {
  version    = "2.13.0"
  api_key    = var.api_key
  account_id = var.account_id
}
```

### Actual Behavior
Since last one week our terraform executions having been failing randomly. It's become more consistent in last 2 days with failure reporting sometime while running plan and sometime while running apply.

### Expected Behavior
The executions should proceed without any issues.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
`https://gist.github.com/SiddhantAgarwal17/ec25861045399c4d0f541de9c7c8541c`

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
`Runs via Jenkins inside a Docker Container`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by BS075209** [comment]
Hi @sanderblue  @zlesnr 

The Jenkins jobs fail with **Internal Server Error** for some environments while for others it passes successfully. Only difference in the environments are the load on them, the one with higher load is failing quite often while the ones with lower load fails with **Internal Server Error**.
Could you please suggest on the above issue.

**Comment by zlesnr** [comment]
A 500 error back from the server should result in a retry of the request up to four times I think.  I know there were some service side issues recently; do you know if that was related to this report?

**Comment by SiddhantAgarwal17** [comment]
Not sure if you were planning on to share the link to the report. However, with the recent behaviour that we see our production executions still fail with 500. All other executions go through perfectly fine. Suggestions?

**Comment by SiddhantAgarwal17** [comment]
I see that we marked it as a `bug`. Did we identify the actual issue or is it still under investigation?

**Comment by zlesnr** [comment]
Sorry for the confusion here.  We are not actively working this.  I would recommend setting up a proxy to determine which calls are the ones that are failing.  That would clue us into which part of the API to talk to the owning team about, or which area you might file a support ticket for to get more attention here.  Apologies that I don't have a better answer for you right now.

**Comment by haneev** [comment]
We sort of encountered the same issue. Also with the `newrelic_alert_condition` we get randomly this error. 

```
Error: 422 response returned: Invalid entity id(s): 143165842.
  on module/care/main.tf line 60, in resource "newrelic_alert_condition"
```

For some modules it does work. We we did not encounter this with the region=US, but now we are switching to region=EU and we not get this randomly too. Might be related?

**Comment by zlesnr** [comment]
@haneev That looks like perhaps the API keys don't have access to reference the entities in the account in question.

**Comment by haneev** [comment]
@zlesnr That would be weird right, because then I would expect other errors, like 401/403. Also it only fails for a few of our modules, some of our modules can apply that alert condition (same region, same structure). So it is just weird why the newrelic_alert_condition sometimes can be added and sometimes we get this error. This is really blocking our migration to EU now, by the way.

**Comment by zlesnr** [comment]
That I'm not sure.  If it was a permission issue a 401 or 403 would reveal the existence of that ID and might be considered information leakage.  I don't know that is what's happening, but that might be the case.  To get attention here, you probably need to work through support or escalate through your account manager.  For this, I apologize, but our small team is focused elsewhere at the moment.

If it is periodic errors for the same resource, that sounds buggish.  Otherwise, I think double checking that the credentials have access to reach the referenced entityID is a good next step.

**Comment by SiddhantAgarwal17** [comment]
New Relic support acknowledged this as an issue and a ticket https://support.newrelic.com/tickets/445517 was opened. The ticket is still open with New Relic
