### ISSUE TITLE
[Tracking] Provider compiled for darwin/arm64

### ISSUE THREAD

**Issue by skyzyx** [newrelic/terraform-provider-newrelic#1180]
### Important Factoids

Apple M1 chip is here. Porting work is occurring for everyone. Opening a tracking ticket to provide public visibility on the work.

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

* https://github.com/golang/go/issues/38485
* https://github.com/hashicorp/terraform/issues/27257
* https://github.com/hashicorp/terraform-provider-aws/issues/16948
* https://github.com/newrelic/newrelic-client-go/issues/660

**Comment by jthurman42** [comment]
Hopefully, this should _just work_ once Go 1.16 is released (the beta has [native M1 support](https://blog.golang.org/ports)).  Only action item on our side would be to update the [compile validation matrix](https://github.com/newrelic/terraform-provider-newrelic/blob/master/.github/workflows/compile.yml#L13)

**Comment by skyzyx** [comment]
That was my guess, but I didn't want to assume anything.

I'm also guessing that we would need a native build of Terraform upstream as well, although￼￼ maybe not if it's all gRPC communication.

But there are some reports of Terraform having issues under Rosetta 2, so perhaps that's something to validate as well.

**Comment by skyzyx** [comment]
**Status update:** Go 1.16 was released today with [non-prerelease, first-class support for `darwin/arm64`](https://golang.org/doc/go1.16#darwin).

**Comment by jthurman42** [comment]
I stand corrected.  The build pipeline is currently unhappy with Darwin ARM64, so it's been disabled until we can resolve the issues.  The [goreleaser config](https://github.com/newrelic/terraform-provider-newrelic/blob/v2.19.0/.goreleaser.yml#L24) will need to be updated once the build problems have been resolved.

**Comment by skyzyx** [comment]
> The build pipeline is currently unhappy with Darwin ARM64[…]

Is this related to [GoReleaser for darwin/arm64](https://github.com/goreleaser/goreleaser/issues/1952), or another issue?

**Comment by jthurman42** [comment]
Starting with [v2.19.1](https://github.com/newrelic/terraform-provider-newrelic/releases/download/v2.19.1/terraform-provider-newrelic_2.19.1_darwin_arm64.zip), Darwin arm64 releases are build automatically as part of the release process.
