### ISSUE TITLE
newrelic_one_dashboard: Heatmap are not being created/exported

### ISSUE THREAD

**Issue by Nordes** [newrelic/terraform-provider-newrelic#1181]
### Feature Description
I didn't know if I should have marked this as a bug or simply a missing feature.

As I have dashboard with **heatmap**, they are impossible to be created with the provider. I tough that by exporting and importing it would at least tell me I am destroying something (which it did). The structure should be pretty similar to the other type of dashboard widget. So, I don't know why they are simply not available. 

### Describe Alternatives
No alternative

### Additional context
None

**Comment by jthurman42** [comment]
Looks like the Heatmap configuration is returned in the `rawConfiguration` part of the API (vs the `configuration` section, which has specific implemented widgets).  Example:

```
              {
                "configuration": null,
                "id": "<REDACTED>",
                "layout": {
                  "column": 5,
                  "height": 3,
                  "row": 1,
                  "width": 4
                },
                "linkedEntities": null,
                "rawConfiguration": {
                  "nrqlQueries": [
                    {
                      "accountId": <REDACTED>,
                      "query": "FROM Transaction SELECT histogram(duration, buckets: 100, width: 0.1) FACET appName "
                    }
                  ]
                }
```

Adding another widget type to the provider that configures via the `rawConfiguration` would enable this.

@jpvajda I suggest we add a `widget_heatmap` to vet out the strategy, but overall need to audit any other missing visualization types.
