### ISSUE TITLE
500 HTTP Status Code Returned by New Relic APIs

### ISSUE THREAD

**Issue by jwmajors81** [newrelic/terraform-provider-newrelic#1186]
### Terraform Version
0.12.29

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alet_policy_channel`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```resource "newrelic_alert_policy_channel" "pagerduty_critical_policy_channel" {
  channel_ids = [var.pagerduty_alert_channel_id]
  policy_id   = var.critical_alert_policy_id
}
```

### Actual Behavior
When executing a terraform plan we get 500 errors from the new relic API

### Expected Behavior
The terraform plan should have successfully executed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Debug Output
https://gist.github.com/jwmajors81/74928e3c6e5354d7f1317f552897f383

### Important Factoids
We have a fairly sizable terraform setup for new relic that helps us monitor over 150 applications.

**Comment by jwmajors81** [comment]
Hello, we have a paid support contract with New Relic and they have requested we use the New Relic developers who are working on this repository to gain additional support.  It seems weird that they would ask us to do this, but it is what they have requested.

**Comment by sanderblue** [comment]
Hi @jwmajors81 can you share a bit more of your Terraform configuration, especially regarding the alert policy and channel configurations? That will help with some context for debugging. Also, what version of the provider are you using?
