### ISSUE TITLE
Possible Bug: Channel Provisioning via Terraform

### ISSUE THREAD

**Issue by suki-chima-ck** [newrelic/terraform-provider-newrelic#1197]
This might not be a bug ... might be a newbie issue.

### Terraform Version
0.14.6
Provider version: 2.18 

### Affected Resource(s)
newrelic_alert_channel
newrelic_alert_policy

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
[ChannelBug.tf.txt](https://github.com/newrelic/terraform-provider-newrelic/files/5973385/ChannelBug.tf.txt)
[versions.tf.txt](https://github.com/newrelic/terraform-provider-newrelic/files/5973390/versions.tf.txt)

### Actual Behavior
The channel provisioning seems to work and we get a success message at the command line with an ID for the new channel.  But that channel never shows up in the UI.  The channel ID can even be re-imported with "terraform import" but the channel cannot be added to an alert policy.

### Expected Behavior
When channel is provisioned it should show up in the NewRelic UI.  Adding the channel to an alert policy should work.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. 'terraform apply`

### Debug Output
https://gist.github.com/suki-chima-ck/2873057095444f68e421ffba2558323a

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Might be two bugs?  
1.  Provisioning a channel works but the channel does not show up
2. Can't add the channel to an alert policy ... always fails with 422

### References
None

**Comment by jthurman42** [comment]
@suki-chima-ck Looks like you're adding adding the channel to the policy twice, once within the policy, and once with `newrelic_alert_policy_channel` resource.  Adding both of them isn't expected, and removing one will help narrow down the issue.  Can you test without adding this directly into the `newrelic_alert_policy` and see if the issue persists.  Rough modification of your supplied config, untested:

```
# Provision a Slack alert channel -> #assets-money-hub-alerts
resource "newrelic_alert_channel" "money-hub-alerts-channel" {
  name = "Money Hub Alert Channel"
  type = "slack"

  config {
    url     = "<SlackHookURL>"
    channel = "assets-money-hub-alerts"
  }
}

# Provision the alert policy.
resource "newrelic_alert_policy" "money-hub-alerts-policy" {
  name = "Money Hub Alert Policy"
  incident_preference = "PER_CONDITION"
}

resource "newrelic_alert_policy_channel" "money-hub-alerts-policy-channel" {
  policy_id  = newrelic_alert_policy.money-hub-alerts-policy.id
  channel_ids = [
    newrelic_alert_channel.money-hub-alerts-channel.id
  ]
}
```

**Comment by sanderblue** [comment]
This looks like a little configuration mixup/redundancy issue. No need to use `channel_ids` in the `newrelic_alert_policy` resource if you're using the `newrelic_alert_policy_channel` resource. @jthurman42's explanation is correct and the provided example configuration should resolve the issue.
