### ISSUE TITLE
Histogram Support in `newrelic_one_dashboard` Resource

### ISSUE THREAD

**Issue by spencer-hivert-ck** [newrelic/terraform-provider-newrelic#1205]
### Feature Description
Previously, we used the `histogram` visualization type in the `newrelic_dashboard` resource, however this is not supported in the `newrelic_one_dashboard` resource type.

We'd like to be able to migrate our dashboards over to the new type however this is blocking us from doing so!

**Comment by jthurman42** [comment]
Thanks for the report! We're currently tracking this issue in #1181
