### ISSUE TITLE
newrelic_entity is case sensitive

### ISSUE THREAD

**Issue by aelmekeev** [newrelic/terraform-provider-newrelic#1214]
### Terraform Version
```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/newrelic/newrelic v2.18.0
```
### Affected Resource(s)
- `newrelic_entity`

### Terraform Configuration
```hcl
provider "newrelic" {
  account_id = <redacted>
}

data "newrelic_entity" "app_ca" {
  name   = "service (ca)"
  domain = "APM"
  type   = "APPLICATION"
}

data "newrelic_entity" "app_uk" {
  name   = "service (uk)"
  domain = "APM"
  type   = "APPLICATION"
}
```

```hcl
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.18.0"
    }
    template = {
      source  = "hashicorp/template"
      version = "~> 2.1"
    }
  }
  required_version = ">= 0.13"
}
```

### Actual Behavior
There is a number of apps that were created quite long time ago that have names like `Service (us)` vs "modern" naming like `service (ca)`.
There is no issue in reporting the data from services that have this naming issue, i.e. service with all lower case `app_name` reports to `Service (environment)`. But there is an issue when we try to find entity with `newrelic_entity` using custom module for the app that has lowercase `name`.

```
Error: the name 'service (uk)' does not match any New Relic One entity for the given search parameters

  on main.tf line 11, in data "newrelic_entity" "app_uk":
  11: data "newrelic_entity" "app_uk" {
```

### Expected Behaviour
I'm not 100% sure if this should be considered a bug in terraform provider but:
1. alias is not helping
2. since app config already has a proper name it looks like we could potentially face an issue with renaming even through some temporary name (even we would not care about historical data) unless we remove the app completely

That's why I've been asked to raise this as an issue here by NewRelic support.

### Steps to Reproduce

1. `terraform plan`

### Debug Output
https://gist.github.com/aelmekeev/110dc5db82ab754ebadfbcaeeceefe3d

### Panic Output
N/A

### Important Factoids
N/A

### References
N/A

**Comment by jthurman42** [comment]
Entity names are case sensitive, so the provider is acting as expected in this case.  Specifically APM Application names, which are used by Agents to report data are explicitly case sensitive.  Some entities, like Dashboards, the name value can change though matches are done with case in mind.  APM Aliases don't change the underlying name, but allow the UI to provide a different name for display.

Is the ask here to add an attribute to disable case-sensitivity?  Something like `ignore_case: true` or the like seems reasonable, but changing the default behavior is unfortunately not possible.

**Comment by aelmekeev** [comment]
Yes, `ignore_case: true` would resolve our issue.

> Specifically APM Application names, which are used by Agents to report data are explicitly case sensitive.

Actually, I'm not sure if this entirely true. As I've mentioned we have applications `Service` APM apps that have `service` as `app_name` in their config and reporting is totally fine.
