### ISSUE TITLE
one_dashboard fails to build or update if incorrect syntax given in widget_line query 

### ISSUE THREAD

**Issue by davenfonet** [newrelic/terraform-provider-newrelic#1248]
I am running into an issue that took some serious digging to get to the bottom of.  It boils down to the following, (I can't share my exact terraform) If you don't have a valid NRQL query for widget_line the terraform will fail to build with the generic message `entity guid required` 

```021-02-26T13:22:29.597-0500 [DEBUG] plugin.terraform-provider-newrelic_v2.19.1: 2021/02/26 13:22:29 [INFO] New Relic client configured
2021-02-26T13:22:29.597-0500 [DEBUG] plugin.terraform-provider-newrelic_v2.19.1: 2021/02/26 13:22:29 [INFO] New Relic Insights insert client configured
2021/02/26 13:22:29 [WARN] Provider "registry.terraform.io/newrelic/newrelic" produced an invalid plan for module.dashboard.newrelic_one_dashboard.exampledash, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .page[0].widget_line[0].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[1].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[2].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[3].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[4].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[5].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[6].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[7].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[8].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[9].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[10].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[11].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
      - .page[0].widget_line[12].height: planned value cty.NumberIntVal(3) does not match config value cty.NullVal(cty.Number)
module.dashboard.newrelic_one_dashboard.exampledash: Creating...
ction Create) matches planned change (action Create)
2021/02/26 13:22:29 [DEBUG] EvalApply: ProviderMeta config value set
2021/02/26 13:22:29 [DEBUG] module.dashboard.newrelic_one_dashboard.exampledash: applying the planned Create change
2021-02-26T13:22:29.615-0500 [DEBUG] plugin.terraform-provider-newrelic_v2.19.1: 2021/02/26 13:22:29 [INFO] Creating New Relic One dashboard: dashboard name
2021-02-26T13:22:30.307-0500 [DEBUG] plugin.terraform-provider-newrelic_v2.19.1: 2021/02/26 13:22:30 [INFO] Reading New Relic One dashboard 
2021/02/26 13:22:30 [DEBUG] module.dashboard.newrelic_one_dashboard.exampledash: apply errored, but we're indicating that via the Error pointer rather than returning it: Entity guid required

Error: Entity guid required

```

If I remove the offending line it will build, and if I add it in afterwards it will appear to apply correctly but does not apply the change.

```   The following problems may be the cause of any confusing errors from downstream operations:
      - .account_id: was cty.NumberIntVal(1.562951e+06), but now cty.NumberIntVal(0)
      - .guid: was cty.StringVal("MTU2Mjk1MXxWSVp8REFTSEJPQVJEfDE3MjkxMTg"), but now cty.StringVal("")
      - .name: was cty.StringVal("NAME"), but now cty.StringVal("")
      - .permissions: was cty.StringVal("public_read_write"), but now cty.StringVal("")
      - .page[0].widget_line[12].id: was null, but now cty.StringVal("")
module.dashboard.newrelic_one_dashboard.exampledash: Modifications complete after 1s [id=XXXX]
2021-02-26T13:27:47.576-0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-02-26T13:27:47.578-0500 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/newrelic/newrelic/2.19.1/darwin_amd64/terraform-provider-newrelic_v2.19.1 pid=33325
2021-02-26T13:27:47.578-0500 [DEBUG] plugin: plugin exited

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

This was in a pretty complex terraform file but it breaks down as follows 

Does not work  
 ```
 resource "newrelic_one_dashboard" "exampledash" {
  name = local.title
  permissions = "public_read_write"
  page {
  name = "i am a dashboard title" 
       widget_line {

        title = "WIDGETNAME"
          row = 5
          column = 7
          width = 3
          nrql_query {
            account_id = account_id
            query = "select count(*) from Transaction where appName like 'NAME' facet `FACET_ITEM` 30 seconds"
          }
      
      }
    }
    } #end page
    } #end dashboard
    
```

WORKS
 ```
 resource "newrelic_one_dashboard" "exampledash" {
  name = local.title
  permissions = "public_read_write"
  page {
  name = "i am a dashboard title" 
       widget_line {

        title = "WIDGETNAME"
          row = 5
          column = 7
          width = 3
          nrql_query {
            account_id = account_id
            query = "select count(*) from Transaction where appName like 'NAME' facet `FACET_ITEM`  TIMESERIES 30 seconds"
          }
      
      }
    }
    } #end page
    } #end dashboard
    
```

**Comment by mgx64** [comment]
I came across the same issue as above with the following nrql inside my Terraform

`query = "SELECT percentage(count(*), WHERE http.statusCode LIKE '5%') AS '5xx Rate' FROM Transaction WHERE appName IN ('<redacted>') FACET appName TIMESERIES LIMIT 10 SINCE 1 day ago"`

the returned `entity guid required` error made this initially very confusing but changing it to

`query = "SELECT percentage(count(*), WHERE http.statusCode LIKE '5%') AS '5xx Rate' FROM Transaction WHERE appName IN ('<redacted>') TIMESERIES LIMIT 10 SINCE 1 day ago"`

fixed it.

**Comment by davenfonet** [comment]
@mgx64 i noticed in the output file that once the terraform fails one of these NRQL calls everything it doesn't get a GUID. So its likely that the terraform module does some type of lookup and if it returns an error on an invalid query it'll fail to get a GUID, and that will fail to allow it to build the dashboard or update the dashboard. Which i feel like is sub optimal, i'd much rather have garbage on a dashboard I can fix, or it tell me my query is bad, but the current state isn't very helpful.

**Comment by jthurman42** [comment]
The TF Create flow is as @davenfonet suggests, where an API call is issued to create the dashboard, then we issue a secondary API call to fetch the entire object back ([shown here](https://github.com/newrelic/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_one_dashboard.go#L376).

There is an error check, so not sure what is coming back successful, but did not create the dashboard.  We should look into that section of code and identify what's happening and fail faster / better error messaging.

As for create with invalid NRQL, the validation is happening downstream in the API layer, and with the complexity of NRQL syntax I would say it's unlikely that the provider will perform any validation pre-API anytime soon.

**Comment by davenfonet** [comment]
@jthurman42 Should have been more clear. I meant my expectation would be that you can pass any string of NRQL no matter how bad/invalid to the terraform provider and expect it to show up on a dashboard rather then needing to pass valid NRQL. Some NRQL queries i run on my dashboards can take a long time to render in the normal NR One UI and i'll have multiple of them on a dashboard and they often will timeout. I'd be worried that i'd be chasing ghosts so to speak if we rely on the NR api to validate all queries. 

I'd think that it would make more sense to have that validation be done by a user inside of the NR UI then via semi-cryptic terraform errors.

**Comment by jthurman42** [comment]
@davenfonet Thanks for the clarification, but I know what you meant.  The API validation is in syntax only, so query time isn't a concern.  Looks like the `line` widget does NRQL validation on creation (though the `bar` widget does not) so there are some API inconsistencies.  I'll raise the issue to the internal NR Dashboard team and see if we can get consistency one way or the other.

That said, I've created #1249 which includes this failing case and throws an error back to the user that makes sense / helps track down the problem faster.
