### ISSUE TITLE
Add cross-account support to newrelic_synthetics

### ISSUE THREAD

**Issue by jthurman42** [newrelic/terraform-provider-newrelic#1263]
### Feature Description
Enable cross-account synthetics management by adding the `account_id` attribute to the resource, or inherit it from the current provider block.

### Describe Alternatives
Today, you can only manage synthetics on the account the primary account for the API key used. The alternative is to have multiple `provider` blocks defining different API keys.

### Additional context
This isn't currently supported in `newrelic-client-go` so that work needs to happen first: newrelic/newrelic-client-go#697

**Comment by kidk** [comment]
V3 now has support for multi account Synthetics
