### ISSUE TITLE
Changing secure credentials name will result in failing monitors

### ISSUE THREAD

**Issue by juliankandler** [newrelic/terraform-provider-newrelic#1277]
### Actual Behavior
I changed via Terraform the name of a secure credential. This name was also changed in the synthetic script, which are being used for monitors. Now, the monitors will fill since the updated secure credentials will be undefined.
Running the script in new relic directly will work. If you save the script (without any changed), the monitor will be OK again. It seems a bit like the monitor is using an old resource of the script with the old name.

### Expected Behavior
After changing the name of a secure credential and its reference in a synthetic script, no monitor should fail

### Steps to Reproduce
1. Have a secure credential, synthetic script and a monitor which is using the script created via TF
2. Change name of secure credential, also change reference in synthetic script
3. Monitor will fail since secret is undefinend
4. Open script in new relic and validate is -> it will work
5. Save script and check monitor -> it is back to normal

### Simplified Config ###

Secret definition: (PREPRODUCTION_SECRET will be changed to something else)
```
resource "newrelic_synthetics_secure_credential" "preproduction_secret" {
  key = "PREPRODUCTION_SECRET"
  value = data.aws_secretsmanager_secret_version.preproduction_secret.secret_string
}
```

Script (PREPRODUCTION_SECRET will be changed to something else)
```
$browser
    .waitForAndFindElement($driver.By.xpath('//*[@data-protractor-id="password-input"]'), timeout)
    .sendKeys($secure.PREPRODUCTION_SECRET),
```

Template file:
```
data "template_file" "preproduction-script" {
  template = file("synthetics/scripts/preproduction.js")
}
```

Monitor script resource:
```
resource "newrelic_synthetics_monitor_script" "preproduction-script" {
  monitor_id = newrelic_synthetics_monitor.preproduction.id
  text       = data.template_file.preproduction-script.rendered
}
```

TF providers:
```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    newrelic = {
      source = "newrelic/newrelic"
    }
    template = {
      source = "hashicorp/template"
    }
  }
  required_version = ">= 0.13"
}

```

**Comment by wolke-7** [comment]
This issue still exists in provider modul version 2.30.2

**Comment by relsqui** [comment]
Is there a workaround or a speculative timeline for this?

**Comment by kidk** [comment]
We're looking into this. At the moment it seems like a problem on the Synthetics side and we are confirming that with the team.

**Comment by Nandu-pns** [comment]
Hi @juliankandler, We did take a look on the latest version of  synthetics and we don’t encounter any such issues, everything is working as expected, could you please confirm the version you were using or if possible, would you be able to verify on the latest version and confirm it’s working ?

**Comment by Nandu-pns** [comment]
Hi, We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.
