### ISSUE TITLE
Unable to update application setting for an existing application. Getting error Error: more/less than one result from query for ml-config_int

### ISSUE THREAD

**Issue by AB077206** [newrelic/terraform-provider-newrelic#1278]
We are referring [newrelic_application_setting](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/application_settings) documentation to update the application setting for an existing application.

We are currently using 
### Terraform Version
Terraform v0.12.29

### Newrelic Provider Version
provider.newrelic v2.19.1

We have services with the name as **ml-config_int** and **ml-config_int[open-kc-k8s-corp-int-0]** in newrelic. When we use the application_setting resource to update the application setting only for ml-config_int we end up getting the following error:

Error: more/less than one result from query for ml-config_int

The resource we are using is below:
resource "newrelic_application_settings" "application_setting" {
  name                        = "ml-config_int"
  app_apdex_threshold         = "0.5"
  end_user_apdex_threshold    = "7"
  enable_real_user_monitoring = false
}

The error does not come when we have exactly one application with the same name in newrelic. Example if we have only **ml-config_int** and not **ml-config_int[open-kc-k8s-corp-int-0]** in newrelic, we do not get that error.

**Comment by AB077206** [comment]
Can you please let me know any updates on this

**Comment by SiddhantAgarwal17** [comment]
Can anyone please help out with this? Its blocking our current development

**Comment by jthurman42** [comment]
There is currently no way to specify via config the application by ID, which is likely the best answer here.  When Terraform creates a new state for the `newrelic_application_settings` resource, it searches by name, and the API returns all matching names.  However, once the resource has been created the Application ID is used to fetch the resource and ensure state.

You may be able to work-around this issue using the terraform import functionality.  Note: I have not tested this.

```hcl
resource "newrelic_application_settings" "application_setting" {
  name = "ml-config_int"
  app_apdex_threshold = "0.5"
  end_user_apdex_threshold = "7"
  enable_real_user_monitoring = false
}
```

Get the Application ID from the UI, it's available as a tag.

```
# Following the config block above for naming, and assuming that you've exported the ID as APPLICATION_ID:
terraform import newrelic_application_settings.application_setting ${APPLICATION_ID}
```

Now the ID should be associated with the configuration, and searching will not be used by Terraform anymore.

**Comment by SiddhantAgarwal17** [comment]
Yeah, we have 100s of applications for which this needs to be done. Going by the current limitations, I'm leaning more towards  doing something custom with the API. Looks like we need to get back to the drawing board and determine the most suitable solution for us. Anyway, thanks for the suggestion

**Comment by jthurman42** [comment]
Is your goal to just set the Apdex, or the Browser settings as well?  I ask as the GraphQL API only supports the APM Apdex (not the browser items).

**Comment by AB077206** [comment]
Yes our goal is to set the Apdex and not the Browser setting.
