### ISSUE TITLE
Need Syntax for Creating mutiple "entity_search_query".

### ISSUE THREAD

**Issue by arukulka** [newrelic/terraform-provider-newrelic#1279]
Hi Team,
We are trying to automate the creation of workloads and dahboards via terraform. We are able to create dashboard and workloads, however unable to create multiple "entity_search_query" for the same. Require your help in creating the same.

Can someone help me with the syntax in passing the mutiple "entity_search_query". Below is the code snippet I have created and need to implement.

Code with single condition which is working
########### Testing Workload for NewRelic#######################
resource "newrelic_workload" "Testing" {
  name = "Example Workload1 For Testing"
  account_id = 2267642

  entity_search_query {
    query = "tags.namespace like '%Alkami%' "
  }

  scope_account_ids =  [1456861]
}

Code with multiple condition which is " Not working"
########### Testing Workload for NewRelic#######################
resource "newrelic_workload" "Testing" {
  name = "Example Workload1 For Testing"
  account_id = 2267642

  entity_search_query {
    query = "tags.namespace like '%Alkami%' " 
  }
entity_search_query {
    query = "type = 'DASHBOARD' and name like '%Alkami%' "
  }
  scope_account_ids =  [1456861]
}

**Comment by kidk** [comment]
The easiest way to get the right query is to get your current version through the GraphQL api: https://api.newrelic.com/graphiql

This query will give you all the workloads in your account, and the related queries. Don't forget to replace the account id 1 with your own account ID.
```
{
  actor {
    account(id: 1) {
      workload {
        collections {
          entitySearchQueries {
            query
          }
          name
        }
      }
    }
  }
}
```

**Comment by kidk** [comment]
@arukulka We did some testing and were not able to reproduce the issue with the queries you provided. 

Are you getting a specific error when creating a multi query workload? 

Here's the example we used which worked:
```
resource "newrelic_workload" "foo" {
	name = "testing123"
	account_id = 1234

	entity_search_query {
		query = "tags.namespace like '%App%' "
	}

	entity_search_query {
		query = "type = 'DASHBOARD' and name like '%App%' "
	}
}
```
