### ISSUE TITLE
Documentation needs updating for newrelic_infra_alert_condition to support 'description' field

### ISSUE THREAD

**Issue by atawfik-elsevier** [newrelic/terraform-provider-newrelic#1280]
Hi there,

v2.4.0 newrelic_infra_alert_condition resource has description added in https://github.com/newrelic/terraform-provider-newrelic/issues/779 But documentation doesn't mention it: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/infra_alert_condition

**Comment by kidk** [comment]
Thanks for reporting this @atawfik-elsevier A fix has been merged and the docs should be updated soon.
