### ISSUE TITLE
Documentation Issue: Missing type (servers_metric) for newrelic_alert_condition

### ISSUE THREAD

**Issue by ericSpence** [newrelic/terraform-provider-newrelic#1307]
### Terraform Version
Terraform Version: Any
Doc Version: 2.22.1

### Affected Resource(s)
- `newrelic_alert_condition`

### Missing Doc
While reading the documentation for this resource it looks like ```servers_metric``` is missing from the valid list of types for newrelic_alert_condition ([docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_condition#type)) However, looking at [this code](https://github.com/newrelic/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_alert_condition.go#L62) I would expect to see ```servers_metric``` as a valid type.  The  [Markdown](https://github.com/newrelic/terraform-provider-newrelic/blob/19590bfc33803e67348cdf2dbd4244b41102a058/website/docs/r/alert_condition.html.markdown) file seems to be missing it so I am wondering whatever process that generates that either has a bug or wasn't run.

**Comment by jthurman42** [comment]
New Relic Servers and the legacy alerting features reached End-Of Life (EOL) on May 15th, 2018. [Reference](https://discuss.newrelic.com/t/important-upcoming-changes-for-new-relic-servers-and-legacy-alerting-features/49474).  This code section will be cleaned up on the next major release (per the Terraform process: deprecate, release, remove release).

The correct resource to use would be [newrelic_infra_alert_condition](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/infra_alert_condition) though, I'd advocate to use [newrelic_nrql_alert_condition](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition) as the future / most flexible configuration type.

**Comment by ericSpence** [comment]
Thanks for pointing that out! I am looking at some legacy code and didn't realize that is what it pointed at. Thanks for that clarification.

**Comment by jthurman42** [comment]
no problem, looks like we did not comment that section, so no way you would of known without the historic context.
