### ISSUE TITLE
Add support for "No Processes Running"

### ISSUE THREAD

**Issue by robison-scott** [newrelic/terraform-provider-newrelic#1317]
### Feature Description
In the infrastructure alert side, there are more types of comparisons than above, below and equal. Namely, "No Processes Running" and "At least one process is running". These are handy to have because the other types expect a number of processes to be present where as these do not. In a world where we scale up and down constantly, I can't give an exact number .

**Comment by kidk** [comment]
Thanks @robison-scott for reporting this.

There is workaround you can use. If you create a NRQL query in alerting with for example this query `FROM ProcessSample SELECT count(*) WHERE processDisplayName = 'coredns' FACET hostname`, you can use a combination of the threshold (> x) and the [loss of signal functionality](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alerts-nerdgraph/nerdgraph-api-loss-signal-gap-filling/) to achieve the same thing. 

- If there are less than x process there alert will trigger through the threshold
- If there are no processes running the alert will trigger through the loss of signal

At the moment we're not planning to add the specific alert types you've mentioned to the Terraform provider.

**Comment by robison-scott** [comment]
Ok, i'll play around and see what comes of it. Thanks!
