### ISSUE TITLE
Support newrelic partnership APIs

### ISSUE THREAD

**Issue by pdecat** [newrelic/terraform-provider-newrelic#134]
### Terraform Version

```
# terraform version
Terraform v0.11.13
+ provider.newrelic v1.5.0
```
### Affected Resource(s)

- `newrelic_partnership_account`
- `newrelic_partnership_sub_account`
- `newrelic_partnership_user`

### Terraform Configuration Files

Draft configuration example:

_**This is not yet supported**_

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

data newrelic_product apm_pro_host {
  name = "APM"
  level = "Pro (Host)"
}

data newrelic_product mobile_lite {
  name = "Mobile"
  level = "Lite"
}

resource newrelic_partnership_account test {
  name = "my_test_account"
  partner_id = "123456"

  region = "eu"

  owner {
    email = "sample_user@sample.org"
    password = "XXXXXX"
    first_name = "Sample"
    last_name = "User"
  }

  subscription {
    product_id = "${data.newrelic_product.apm_pro_host.id}"
    quantity = "10"
  }

  subscription {
    product_id = "${data.newrelic_product.mobile_lite.id}"
    quantity = "0"
  }
}

resource newrelic_partnership_user test {
  account = "${newrelic_partnership_account.test.id}"

  email = "sample_user@sample.org"
  password = "XXXXXX"
  first_name = "Sample"
  last_name = "User"
  role = "admin"
  owner = "false"
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior
What should have happened?

The resources exposed via NewRelic's partnership API are available as terraform resources.

### Actual Behavior
What actually happened?

None of the resources exposed via NewRelic's partnership API are available.

### Steps to Reproduce

N/A

### Important Factoids

N/A

### References

NewRelic Partnership API reference:
- accounts: https://docs.newrelic.com/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-account-object
- sub-accounts: https://docs.newrelic.com/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-sub-account-object
- subscriptions: https://docs.newrelic.com/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-subscription-object
- users: https://docs.newrelic.com/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-user-object
- product mapping: https://docs.newrelic.com/docs/new-relic-partnerships/partnerships/partner-api/partnership-api-subscription-object#api-product-mapping

The Newrelic endpoints used must be configurable, currently known public ones are:
- USA datacenter: https://rpm.newrelic.com/
- Europe datacenter: https://rpm.eu.newrelic.com/

https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/getting-started/introduction-eu-region-data-center#regions-availability

**Comment by hhughes0** [comment]
Is there an update on when we can expect the Terraform provider to support Partnership APIs?

**Comment by kidk** [comment]
The Partnership API is no longer the recommended way to manage users in New Relic. AUM and the SCIM API provide the recommended alternative for programmatic management of users for this use case. 

For this reason we won't be adding the Partnership API to the Terraform provider. Please reach out to your New Relic account team for support with the alternatives.
