### ISSUE TITLE
Support for "use as filter" setting for dashboard widgets

### ISSUE THREAD

**Issue by mason-jones-ck** [newrelic/terraform-provider-newrelic#1349]
### Feature Description
In the New Relic user interface when creating/editing widgets of certain types (table, bar chart) it is possible to specify the widget "use as filter" for either the current dashboard or another dashboard. This setting isn't currently supported in the `newrelic_one_dashboard` resource in the widget blocks.

### Describe Alternatives
There is currently no alternative when using Terraform to create a dashboard with those widget types.

**Comment by rdhar** [comment]
Looks to be replicating #1193.

**Comment by mason-jones-ck** [comment]
You are correct, that looks like the same issue (and in particular the multi-page dashboard complication!). I'll close this since it's duplicating. Thank you for the pointer to that other issue.

**Comment by rdhar** [comment]
It's a wee bit of a shame as I really wish this was implemented as well, especially to make bulk changes much easier across a large number of different dashboards.
