### ISSUE TITLE
[Resource] newrelic_entity

### ISSUE THREAD

**Issue by Tensho** [newrelic/terraform-provider-newrelic#1357]
### Feature Description

Register NewRelic entity (APM) with `newrelic_entity` resource. At the moment I have to make 2 separate actions – deploy application first to register APM entity within agent in NewRelic and then refer to it within `newrelic_entity` data source. However it would be nice to get all in one run.

```
resource newrelic_entity wakemeup {
  name   = "wakemeup"
  type   = "APPLICATION"
  domain = "APM"
}
```

### Describe Alternatives

It's probably possible to run API request (I don't know which one, TBH) within `null_resource`.

**Comment by kidk** [comment]
Hi @Tensho 

Thanks for the feature request. As far as I can tell there's no API available yet to create entities. Once it becomes available we will look at adding it to the Terraform provider.

**Comment by arhill05** [comment]
@kidk any movement on this? It would be really nice to be able to configure our APM entities via Terraform instead of having to create them by hand and then referencing them in our code.

**Comment by kidk** [comment]
After talking to the internal teams it's unlikely there will be an API for creating entities, and if there is it won't support creating APM entities. Our internal systems are not currently build to handle custom entities that are not bound to a certain domain, and there's assumptions made on the data that's available.

There are a bunch of workarounds though:
- You can use [Open Telemetry](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/introduction-opentelemetry-new-relic/) or the [C SDK](https://docs.newrelic.com/docs/apm/agents/c-sdk/get-started/introduction-c-sdk/)
- If you goal is create entities from data in your system you can contribute to the [Entity Synthesis project](https://github.com/newrelic/entity-definitions)

I'd be helpful if you share your use-cases, that way we can match them to the right system, or open the case for a entity create API.

**Comment by kidk** [comment]
I'm going to close this for now as there is no immediate action the Terraform team can take. As mentioned this a platform limitation. Feel free to add comments and use-cases to support this request so we can continue the conversation with the New Relic platform team.

**Comment by Tensho** [comment]
There is a use-case where k8s app is deployed along with NewRelic APM alerts and synthetics. Right now there is a race condition workaround with the extra delay:
```
resource "kubernetes_deployment" "fancy-api" {
   ...
}

# Wait 60 seconds to let app get up & running
resource "null_resource" "fancy-api" {
  provisioner "local-exec" {
    when    = destroy
    command = "sleep 60"
  }

  depends_on = [kubernetes_deployment.fancy-api]
}

data "newrelic_entity" "fancy-api" {
  count  = var.newrelic["enabled"] ? 1 : 0
  name   = "fancy-api"
  type   = "APPLICATION"
  domain = "APM"

  depends_on = [null_resource.fancy-api] # <= Without delay this data source fetches info before it actually appeared at NR side
}

resource "newrelic_alert_policy" "default" {
  count = var.newrelic["alerts"] ? 1 : 0
  ...
}

resource "newrelic_nrql_alert_condition" "errors_500" {
  count     = var.newrelic["alerts"] ? 1 : 0
  ...
}
```
However, it would be nice to create NewRelic identity before on in parallel with the app.
