### ISSUE TITLE
 Error: maximum retries reached: A downstream error occurred., [{"extensions":{"code":"BAD_USER_INPUT"},"message":"Not Found"}]

### ISSUE THREAD

**Issue by hjain4** [newrelic/terraform-provider-newrelic#1364]
I am getting below error when creating a alert policy using terraform
 Error: maximum retries reached: A downstream error occurred., [{"extensions":{"code":"BAD_USER_INPUT"},"message":"Not Found"}]

Terraform config used by me

`# Configure terraform
terraform {
  required_version = "~> 1.0.0"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.21.0"
    }
  }
}

# Configure the New Relic provider
provider "newrelic" {
  account_id = "deleted"
  api_key = "deleted"   # usually prefixed with 'NRAK'
  region = "US"                    # Valid regions are US and EU
}

data "newrelic_entity" "app_name" {
  name = "Name"
  type = "APPLICATION"
  domain = "APM"
}

resource "newrelic_alert_policy" "alert_policy_name" {
  name = "My Alert Policy Name"
}

# NRQL alert condition
resource "newrelic_nrql_alert_condition" "foo" {
  policy_id                    = newrelic_alert_policy.alert_policy_name.id
  type                         = "static"
  name                         = "foo"
  description                  = "Alert when transactions are taking too long"
  runbook_url                  = "https://www.example.com"
  enabled                      = true
  value_function               = "single_value"
  violation_time_limit_seconds = 3600

  nrql {
    query             = "SELECT average(duration) FROM Transaction where appName = '${data.newrelic_entity.app_name.name}'"
    evaluation_offset = 3
  }

  critical {
    operator              = "above"
    threshold             = 5.5
    threshold_duration    = 300
    threshold_occurrences = "ALL"
  }
}`

**Comment by aelmekeev** [comment]
@hjain4 try to upgrade 2.23. We had the same error which was resolved by upgrading to the latest provider.
I guess there was some breaking change in API?

**Comment by hjain4** [comment]
ok
