### ISSUE TITLE
Terraform updates to alert conditions are not labeled with the user name

### ISSUE THREAD

**Issue by jfornango** [newrelic/terraform-provider-newrelic#1369]
I'm in the process of implementing Terraform with our New Relic alerting.  Along the way, I have discovered that when I do an apply, rather than having my name in the "Last modified:" field, I am seeing my user number and redacted API key.

Not sure if this is by design, or really a bug, but I have been asked if it is possible to get the human name filled in, instead.
So far, I do not see a way.

- [ ] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
terraform {
  required_version = "= 0.15.0"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.21.0"
    }
  }
}

provider "newrelic" {
  account_id = var.loc["nr_account"]            # Account number for COMM-STAGEUS 
  api_key    = var.PRODCA_API_KEY             # Call from local environment
  region     = var.loc["nr_region"]                  # Valid regions are US and EU
}

- [ ] A list of [affected resources](#affected-resources) and/or data sources
New Relic Alert Conditions

- [ ] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report 
resource "newrelic_nrql_alert_condition" "nrql_alert" {
    count                                           = var.alert_nrql ? 1 : 0
    policy_id                                      = var.policy_id
    type                                             = "static"
    name                                           = var.name
    description                                 = "Created with: TF:${var.loc["path"]}"
    runbook_url                                = var.runbook
    enabled                                      = var.enable
    value_function                           = "single_value"
    violation_time_limit_seconds    = var.vtls
    expiration_duration                   = var.signal_loss
    close_violations_on_expiration = var.signal_loss_enabled
    fill_option                                   = "none"
    aggregation_window                 = 60

  nrql {
    query                    = var.nrql_query
    evaluation_offset = 3
  }

  critical {
    operator                     
![Screen Shot 2021-06-24 at 1 03 58 PM](https://user-images.githubusercontent.com/19195906/123313851-834bfe80-d4ef-11eb-93f5-6d53e9584ce5.png)
    = var.operator
    threshold                        = var.threshold
    threshold_duration        = var.threshold_duration
    threshold_occurrences = "ALL"
  }
}

- [ ] Description of the [current behavior](#actual-behavior) (the bug)
Current label is "Last modified 11:36 am by User 1896607 via NRAK-E6A************************"

- [ ] Description of the [expected behavior](#expected-behavior)
Desired label is "Last modified 11:36 am by Jim Fornango"

- [ ] Any related [log output](#debug-output)
No debug output, other than a completely successful terraform apply.

### Terraform Version
Terraform v0.15.0

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_nrql_alert_condition`
- `newrelic_infra_alert_condition`
- `newrelic_synthetics_alert_condition`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

**Comment by baNROne** [comment]
This issue sounds like it's due to a known issue, affecting V2 users, which prevents lookup of the user name. We have a ticket to track this, but cannot say when it will be resolved.
