### ISSUE TITLE
depends_on missing in the documentation for synthetic_monitor_script

### ISSUE THREAD

**Issue by pako-grape** [newrelic/terraform-provider-newrelic#1388]
Hi, according to https://github.com/newrelic/terraform-provider-newrelic/issues/401 `depends_on` is needed in the script resource, otherwise, the script fails after creation (I just faced this problem).

https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor_script should have the proper code example

Sorry for not using the template, but I didn't find any for docs changes :)

**Comment by kidk** [comment]
@pako-grape  We've released V3 version of our provider which includes all of the new Synthetics features: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v3 

With this release the script monitor is now a single resource: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_script_monitor This removes the need for `depends_on`.

Please let us know if you have any questions. If you encounter any issues please don't hesitate to create a new ticket or continue the discussion here.
