### ISSUE TITLE
[One Dashboard] Page, Widget to be a resource, instead of being nested in newrelic_one_dashboard / newrelic_one_dashboard_raw

### ISSUE THREAD

**Issue by tommyongsf** [newrelic/terraform-provider-newrelic#1391]
### Feature Description
Currently `newrelic_one_dashboard` has pages nested within itself. When there are many pages, this resource will become too big, i.e. the tf file will be very long, which affects readability and management of the pages.

### Describe Alternatives
Page is a resource, and tied to One Dashboard by `one_dashboard_id`. Similar to how `newrelic_alert_condition` -> `newrelic_alert_policy`.

Example:

```
# New Relic One Dashboard
resource "newrelic_one_dashboard" "foo" {
  name = "foo"
}

resource "newrelic_one_dashboard_page" "bar" {
  one_dashboard_id = newrelic_one_dashboard.foo.id
}
```

```
# New Relic Alert
resource "newrelic_alert_policy" "foo" {
  name = "foo"
}

resource "newrelic_alert_condition" "foo" {
  policy_id = newrelic_alert_policy.foo.id
```

**Comment by tommyongsf** [comment]
It should also apply to `widget_*` (* stands for _area, _bar, _billboard etc) For example

```
resource "newrelic_one_dashboard_page_widget_*" "xyz" {
   one_dashboard_page_id = newrelic_one_dashboard_page.bar.id
}
```

**Comment by tommyongsf** [comment]
Just a note that this should also apply to `newrelic_one_dashboard_raw`

**Comment by jddcarreira** [comment]
Hi!
There is any update on this? Or an ETA?
Thanks

**Comment by cdobbyn** [comment]
At the very least allow for pages to be created as a separate resource. But ideally each widget could be it's own resource as well.

For a complex dashboard this can easily scale to thousands of lines.

**Comment by kidk** [comment]
We are planning to work on a new resource this year, and would love to hear your thoughts (beside this one) in our community forum: https://github.com/newrelic/terraform-provider-newrelic/discussions/1480

The current API does not easily allow us to create separate resources, and would add a lot of complexity to our code. We're working with the dashboard team at New Relic to find workarounds and maybe develop new API endpoints. 

The current timeline for the new resource is end of summer.

**Comment by kidk** [comment]
We've recently added support for JSON dashboards: https://github.com/newrelic/terraform-provider-newrelic/discussions/2044

I think that might be a workaround for this issue as you're able to use the template functionality in Terraform.

**Comment by kidk** [comment]
I'm going to close this as this is a high complexity item with low amount of requests. To achieve this we would need significant changes on the API and Terraform side. Please feel free to continue the conversion, and let us know why `resource_one_dashboard_json` would not be a valid workaround for you.

Thanks all ❤️
