### ISSUE TITLE
`Too many widgets, maximum allowed is 40`

### ISSUE THREAD

**Issue by eduherminio** [newrelic/terraform-provider-newrelic#1393]
The **same** terraform code worked one day and failed the next one due to this `too many wdigets per page` limitation, so this seems more related to NewRelic itself than to the terraform provider, but hopefully someone can pick it up from here or shed more light on it.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
v0.12.31

### Provider Version
v2.22.1
v2.23.0

### Affected Resource(s)
- `newrelic_one_dashboard`

### Terraform Configuration
Any configuration with 40+ widgets

### Actual Behavior
Error in `terraform apply:`

```
[0m[0m[1merr: newrelic_one_dashboard Create failed: [INVALID_INPUT: Input: [[PageInput: [too many widgets: 60, maximum allowed is: 40]]]]
```

### Expected Behavior
Either:
* Success
* Error in `terraform plan`, a way to overcome that limitation if needed and documentation about this

### Steps to Reproduce
`terraform apply` any configuration with 40+ widgets

**Comment by bbraunstein** [comment]
+1 

I am having the same issue. I was previously using v2.21.0 where I was successfully able to deploy a page with 52 widgets, then upgraded my provider to v2.24.1 where it complains that my template has too many widgets.

**Comment by rdhar** [comment]
Same here, 40 appears to be an arbitrarily small number of widgets for NR1 dashboards.

**Comment by wilson-riquelme** [comment]
Same problem, we have old implementation over 40 widgets too.

**Comment by kidk** [comment]
This is a new limit that was set on API level: https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/dashboards-api/#limits

Not much we can do on the Terraform side.

**Comment by kidk** [comment]
I've just heard that we are raising it to 60.

**Comment by rdhar** [comment]
As someone who had 58 widget on a dashboard (all relevant, I swear!), this is really great to hear. As an aside, does the new [`one_dashboard_raw`](https://github.com/newrelic/terraform-provider-newrelic/issues/1211#issuecomment-887054523) support filtering via linked entity guid or the likes?

I do wonder why this limit exists in the first place. I get that users can be stupid and make a ridiculous dashboard full of widgets. If the impact of their action is only limited to their own experience of the dashboard, should they not be allowed to do that?

I'm also assuming that widgets are lazy-loaded upon scroll via Intersection Observer API, so the page should remain performant upon load.

**Comment by eduherminio** [comment]
Is there any way of being properly informed about this kind of API changes @kidk?
It was annoying to suddenly find these kind of surprises while in the middle of preparing for #1297.

**Comment by rdhar** [comment]
Does this appear to be resolved now for anyone else, despite no update on the [Dashboard page limits](https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/dashboards-api/#page-limits) documentation which was linked by @kidk?

**Comment by kidk** [comment]
I think the team still needs to update the docs. Last I heard the limit was set at 100. 

Thanks all for your patience on this. The dashboard team set the limit for performance reasons both in the UI and backend. 95% of dashboards were below the limit, but it seems Terraform users are the 5% 😄
