### ISSUE TITLE
Account id support for newrelic_alert_channel resource

### ISSUE THREAD

**Issue by DmitryLobachov** [newrelic/terraform-provider-newrelic#1394]
### Feature Description
It's very convenient to have the **account_id** setting for NR resources in a multi-account environment. Most of the resources already have it, but for some reason it's not possible to specify account id for **newrelic_alert_channel**

### Describe Alternatives
The only workaround is to run terraform multiple times with different root account id

### Additional context
-

**Comment by tryangul** [comment]
Given policies can be created cross-account, it would stand to reason channels—the thing that connect to policies to, you know, make them actually doing something—should be creatable cross-account.

**Comment by aelmekeev** [comment]
+ 1 to this request. As an MVP it would be great to at least add `account_id` to `newrelic_alert_channel` data source so we can at least create policies manually after fetching alert channel from a proper account.

**Comment by trustthewhiterabbit** [comment]
+1 this would be very useful

**Comment by baNROne** [comment]
We've added a feature request to our internal tracking tool for making `account_id` an optional argument for the `newrelic_alert_channel` resource.
