### ISSUE TITLE
newrelic_entity_tags attempting to delete user added tags

### ISSUE THREAD

**Issue by timbrammer910** [newrelic/terraform-provider-newrelic#1412]
Hey all, I'm seeing some odd behavior in the new version of the provider.

When doing plans/applies against an existing tag resource, we're suddenly seeing it try to remove other tags on the entity. Previously, this resource would show no changes, now we see approximately the following - 

```
~ resource "newrelic_entity_tags" "dashboard_tags" {
        id   = "sanitized"
        # (1 unchanged attribute hidden)

      - tag {
          - key    = "createdBy" -> null
          - values = [
              - "sanitized@sanitized.com",
            ] -> null
        }
      - tag {
          - key    = "isDashboardPage" -> null
          - values = [
              - "false",
            ] -> null
        }
      - tag {
          - key    = "permissions" -> null
          - values = [
              - "PUBLIC_READ_WRITE",
            ] -> null
        }
      - tag {
          - key    = "slug" -> null
          - values = [
              - "sanitized",
            ] -> null
        }
        # (2 unchanged blocks hidden)
    }
```

None of these tags are defined on the resource, and the two which are,  are unchanged.

In looking through the diff between the latest version and the previous, I found this -
https://github.com/newrelic/terraform-provider-newrelic/compare/v2.23.0...v2.24.1#diff-e2ac9cf2bc502dba7eddd8043ab326231737f12dc963bdbc5f24b170b8b4b561L82

Looks like the function for adding tags has changed and there's a new "ctx" param. Is this what is causing this behavior?

**Comment by kidk** [comment]
Hi @timbrammer910 sorry for the delayed response.

Are you still seeing this issue?
