### ISSUE TITLE
Add tag property to newrelic resources that support tags

### ISSUE THREAD

**Issue by fajanssen** [newrelic/terraform-provider-newrelic#1420]
### Feature Description
Add a tags property to the newrelic terraform resources so we can set that on creation already.

### Describe Alternatives
The way it works now is very uncomfortable, as you have to create the resource, await it being created, scrape the data source again to find its id and then use the newrelic_entity_tags resource to add tags.

### Additional context
It would be great if we could add tags as a property in all resources in the newrelic provider that support tags.

**Comment by MAN98** [comment]
I believe this is related to this issue https://github.com/newrelic/terraform-provider-newrelic/issues/756

**Comment by zeffron** [comment]
For us, this is related to #756 in that the synthetics are what we'd like to be able to tag. However, I don't believe this should _depend on_ #756. It should be entirely possible to add a `tags` section to entities supporting tags and have the provider wait for the GUID to become available (if the resource is being created and a wait is necessary) regardless of which API is being used in the backend (REST or NerdGraph).
