### ISSUE TITLE
Immutable newrelic_entity_tags are not filtered anymore

### ISSUE THREAD

**Issue by b-viguier** [newrelic/terraform-provider-newrelic#1422]
Hello 👋 😃 

Since `2.24.1`, immutable newrelic_entity_tags are not filtered, it means that immutable tags like `monitorStatus` or `monitorType` are listed for deletion by the provider (fortunately, it's not possible to delete them).
It has already been reported in https://github.com/newrelic/terraform-provider-newrelic/issues/766 and fixed in https://github.com/newrelic/newrelic-client-go/pull/462 : the `ListTags` function calls a new function `filterMutable`.

But recently, `ListTags` has been deprecated and replaced by `GetTagsForEntity` (see https://github.com/newrelic/terraform-provider-newrelic/pull/1347/files#diff-e2ac9cf2bc502dba7eddd8043ab326231737f12dc963bdbc5f24b170b8b4b561 ). This function doesn't call `filterMutable`, then _built-in_ NewRelic tags are listed for modification 😕 

Thanks for your work 🙇‍♂️

**Comment by joshuaakelly** [comment]
This issue is still occuring in v2.25

**Comment by kidk** [comment]
Thanks for report @joshuaakelly and @b-viguier 

We'll take a look.
