### ISSUE TITLE
terraform import newrelic_nrql_alert_condition imports deprecated violation_time_limit argument 

### ISSUE THREAD

**Issue by krajewf** [newrelic/terraform-provider-newrelic#1433]
### Terraform Version
```
Terraform v1.0.6
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.25.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_nrql_alert_condition`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~>2.0"
    }
  }
}

provider "newrelic" {
  region     = "US"
  account_id = "****"
}
```

### Actual Behavior
What actually happened?
Trying to use `terraform import` and take the current state to build a terraform configuration similar to as detailed in Import [Terraform Configuration](https://learn.hashicorp.com/tutorials/terraform/state-import?in=terraform/state&utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS#create-configuration)

`terraform import newrelic_nrql_alert_condition.foo <policy_id>:<condition_id>:<conditionType>` creates a terraform state where the attributes related to "Close open violations after" have the ENUM value for `violation_time_limit` and `violation_time_limit_seconds` is `null` 
```
            "violation_time_limit": "TWENTY_FOUR_HOURS",
            "violation_time_limit_seconds": null,
```

### Expected Behavior
What should have happened?
[Documentation](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#import)  notes that "Also note that deprecated arguments will not be set when importing" If `violation_time_limit` is deprecated, then `violation_time_limit` should not be set and `violation_time_limit_seconds` should be set to the correct currently configured limit in seconds.
```
            "violation_time_limit_seconds": 86400,
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import newrelic_nrql_alert_condition.foo <policy_id>:<condition_id>:<conditionType>`
2. `terraform show` - `violation_time_limit` is configured and not `violation_time_limit_seconds`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1015

**Comment by emetcalf9** [comment]
I was able to reproduce this, and put in pull request #1564 to update the provider to use `violation_time_limit_seconds` when importing conditions.
