### ISSUE TITLE
Error: API is Receiving too many Requests

### ISSUE THREAD

**Issue by SiddhantAgarwal17** [newrelic/terraform-provider-newrelic#1434]
We create a significant number of dashboards in one of the New Relic sub-accounts. While running the execution we often run into the following error:

```
Error: API is receiving too many requests

  on .terraform/modules/newrelic_dashboards/main.tf line 55, in resource "newrelic_one_dashboard" "managed_dashboards":

  55: resource "newrelic_one_dashboard" "managed_dashboards" {
```
This seems to be occurring because of the fact that too many resources (refresh + creation/upgrade) leads to a lot of request being sent to the New Relic servers in a short period of time. I guess because of throttling on the server side, it results in the error above.

We have tried to run our Jenkins jobs which are responsible to create these resources in sequential order to prevent overloading the same account at once.

**New Relic Provider Used:**
v2.23.0

**Terraform Version Used**:
v0.14.11

Appreciate a fix or suggestions to minimize or eliminate this issue.

**Comment by SiddhantAgarwal17** [comment]
Any suggestion?

**Comment by kidk** [comment]
@SiddhantAgarwal17 Can you reach out to support to request to increase the limits? There's not much we can do on the Terraform side.

**Comment by SiddhantAgarwal17** [comment]
The support had increased the limits once in the past. I'm not sure how the requests are internally sent to New Relic, is it batched in some way to avoid too much of querying at once?

**Comment by kidk** [comment]
We don't do any batching right now, but it's something we can explore in the future. For now the workaround will be to ask for another increase in limit, or to slow down the terraform execution somehow.

**Comment by SiddhantAgarwal17** [comment]
Sure Thanks! Let me see how we can break down the terraform execution further for now. However, for batching request, should we log a separate required?

**Comment by rdhar** [comment]
I've also run into similar issues when managing vast numbers of: dashboards, alerts and monitors. Out of interest, did you just raise a Support ticket to request the limit be raised for your main account + associated sub-accounts?

There are 2 methods I use to workaround this limitation:

1. Reduce number of concurrent operations during Terraform execution. This can be done by `terraform apply -parallelism=5`, where the default is `10`. See [documentation](https://www.terraform.io/docs/cli/commands/apply.html#parallelism-n).
1. Skip synchronisation of Terraform state during execution. This can be done by `terraform apply -refresh=false`. To avoid configuration drift, the state should be regularly updated separately. See [documentation](https://www.terraform.io/docs/cli/commands/plan.html#refresh-false).

**Comment by SiddhantAgarwal17** [comment]
@rdhar  `Out of interest, did you just raise a Support ticket to request the limit be raised for your main account + associated sub-accounts?`

We actually haven't done that yet. Partly because we have already gone through a limit increase earlier this year. However, we
did the following:

- We used to run `terraform plan` followed by `terraform apply`. By default, the apply command re-runs the plan command. To reduce double execution, we store the plan in a file by doing `terraform plan -out=/path_to_file` followed by `terraform apply <path_to_file>`. [Documentation](https://www.terraform.io/docs/cli/commands/plan.html#out-filename)
- Secondly, we had multiple modules run by individual Jenkins job in parallel. We are currently working to execute it job by job, basically sequential Jenkins jobs to reduce the number of requests on the New Relic server.

Reducing the parallelism seems to be a good option. However, I'm hoping I would be able to manage a lot of it with sequential run of my Jenkins jobs responsible to execute the modules.

**Comment by oniGino** [comment]
This is a bug NOT an enhancement,

**Comment by kidk** [comment]
If possible it would be great to have a trace debug log from a terraform run that hits the rate limits. This would allow us debug which GraphQL endpoints are causing the issue. 

Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist. If you have concerns about sensitive data and would rather not post the trace output publicly, please email it to svandamme@newrelic.com. The team will use the data to debug and immediately remove it after.

**Comment by kidk** [comment]
Can anyone check with the [latest release](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v2.46.2) to see if there is any improvement? We've made some changes to the retry mechanism.

**Comment by rdhar** [comment]
I think there's definite improvement! 

The NR estate I work on includes: dashboards, workloads, service levels, APM/Synthetic NRQL alerts and notification channels -- all of which are integrated across ~60 accounts. Lately I've found I can reliably run at the default `-parallelism 10` without any rate-limiting/throttling errors. 

Any faster, and it's usually Synthetic related endpoints which are the first to error out. With any luck, this too might be improved by the next iteration of the provider. Thank you.

**Comment by kidk** [comment]
Thanks a lot @rdhar 

I will leave this open until we release the Synthetics work.

**Comment by kidk** [comment]
We've released V3 version of our provider which includes all of the new Synthetics features: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v3 

This should be the final piece to lower the amount of API requests. I'm going to close this ticket for now, please let us know if  this remains a problem.
