### ISSUE TITLE
Automate hmac calc for synthetics_monitor_script

### ISSUE THREAD

**Issue by albsga** [newrelic/terraform-provider-newrelic#1436]
### Feature Description
We are using `Private Locations` secured by a passhprase. As how the provider is coded we need to specify the `hmac` it's an hs256 using the text of the script and the passphrase to sign it. After it'd encoded as `base64`.

https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor_script#nested-location-blocks

We will need an automated calc of the hmac just adding the passphrase, as if not we need to run local commands to get it.

### Describe Alternatives
I see that exists the possibility of adding this HS256 calculation: 
https://github.com/hashicorp/terraform-provider-terraform/blob/master/vendor/github.com/dgrijalva/jwt-go/hmac.go

**Comment by mbazhlekova** [comment]
Support for VSE Password is available with version 2.34.0
