### ISSUE TITLE
newrelic_alert_policy_channel "Provider produced inconsistent result after apply" error on Terraform 0.12 with NR 2.25.0

### ISSUE THREAD

**Issue by syed-shafiullah** [newrelic/terraform-provider-newrelic#1442]
When applying newrelic_alert_policy_channel resource using Terraform 0.12 I get a terraform error about inconsistency:

Error: Provider produced inconsistent result after apply

When applying changes to
When applying changes to newrelic_alert_policy_channel.pagerduty, provider
"registry.terraform.io/-/newrelic" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by baNROne** [comment]
There is not enough information to be able to investigate the issue. Please resubmit this issue using the project's [bug report issue template](https://github.com/newrelic/terraform-provider-newrelic/blob/main/.github/ISSUE_TEMPLATE/bug_report.md).
