### ISSUE TITLE
Support for SSL Certificate Expiration Synthetic

### ISSUE THREAD

**Issue by jasonmfehr** [newrelic/terraform-provider-newrelic#1447]
### Feature Description
Please add support for managing synthetics of type SSL Certificate Expiration.

### Describe Alternatives
none

### Additional context
n/a

**Comment by kidk** [comment]
Thanks for the feature request @jasonmfehr 

This is related to #1453 so we won't be able to add this until that work has been completed.

**Comment by NSSPKrishna** [comment]
This issue has been resolved in the latest release. Please feel free to raise a new issue if you fell this is still valid.
