### ISSUE TITLE
Unable to upgrade to v2.26.0 provider

### ISSUE THREAD

**Issue by rdhar** [newrelic/terraform-provider-newrelic#1451]
Hi there,

Following on from the recent v2.26.0 release, it appears that I'm unable to upgrade to this version. Here's my provider block.

```terraform
terraform {
  required_version = "~> 1.0.0"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.26.0"
    }
  }
}
```

And here's the associated error received after `terraform init -upgrade`.

```bash
Initializing provider plugins...
- Finding newrelic/newrelic versions matching "~> 2.25.0, ~> 2.26.0"...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider newrelic/newrelic: no available releases match the 
│ given constraints ~> 2.25.0, ~> 2.26.0
╵
```

Here's my output of `terraform -v`.

```bash
Terraform v1.0.8
on windows_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.25.0
```

Everything appears to be above board, so I'm not sure where the issue is rooted. Any guidance/troubleshooting steps would be appreciated.

Thanks for your time,
Rishav

**Comment by kidk** [comment]
Thanks @rdhar 

I've just tried to reproduce this, but no luck. Are you still experiencing the issue? It might be that there was a slow sync job.

**Comment by rdhar** [comment]
Hi @kidk, thanks for checking on my behalf.

This is really odd, if it was a slow-sync, I'd have expected this to be resolved by now as well. However, I'm still experiencing the issue: i.e., I'm unable to `terraform init -upgrade` from v2.25.0 to v2.26.0. It's the same error shown as in the original post.

I amended the provider block to make it more generic with no improvement.

```diff
- version = "~> 2.26.0"
+ version = "~> 2.0"
```

Would you mind sharing your provider block and upgrade command, in case I'm missing something silly?

**Comment by rdhar** [comment]
Welp, this is embarrassing: it was a [PEBCAK](https://www.urbandictionary.com/define.php?term=PEBCAK) issue!

A single module called by `main.tf` had its version pinned to v2.25.0 and, hence, it prevented the upgrade as a whole. With it removed, the upgrade proceeded without issues.

Many thanks for taking time out to look into this issue on my behalf, I'm very appreciative of it! Thanks for bearing with me.

**Comment by kidk** [comment]
Ah awesome, happy you were able to find it @rdhar!
