### ISSUE TITLE
Migrate synthetics resources to GraphQL API

### ISSUE THREAD

**Issue by kidk** [newrelic/terraform-provider-newrelic#1453]
### Objective
The current synthetics resources are based on the REST API. The New Relic GraphQL library now supports Synthetic calls: https://api.newrelic.com/graphiql?#query=mutation%20%7B%0A%20%20syntheticsCreateMonitor%0A%7D%0A This work will track the migration of the resources to the new API.

### Open questions
- Will we be able to keep backwards compatibility?

**Comment by rdhar** [comment]
Hey @kidk, it looks like the next generation of synthetic monitoring runtime was recently announced on the [forum](https://discuss.newrelic.com/t/182939) and [blog](https://newrelic.com/blog/nerdlog/next-gen-synthetics-runtime), including Nerdgraph/GraphQL API additions - which is great!

Would you happen to know when these changes are expected to make their way into the Terraform provider (and help take a big chunk out of the [Synthetics GraphQL](https://github.com/newrelic/terraform-provider-newrelic/milestone/11)?

**Comment by kidk** [comment]
As soon as we can 😄  Currently targeted for this quarter

**Comment by rdhar** [comment]
Fingers-crossed, looking forward to it! 

Outta interest, would it include _all_ types of monitors, such as the Broken Links and SSL Cert Expiration (#1585) which are currently outside the scope of the Terraform provider?

**Comment by kidk** [comment]
It should 😄  at the moment our priority is to get feature parity, without too much change on the resource definition side. Depending on the effort required to get these new features in they might come at a later date. I hope to have more information over the coming weeks. I'll update this thread when I do.

**Comment by rdhar** [comment]
Thank you, really appreciate you sharing some background.

**Comment by kidk** [comment]
We currently have it planned to have this ready end of June. There's already a couple of PR's open with first draft of changes.

**Comment by eileenhayes** [comment]
Any update as to when this will be available?

**Comment by kidk** [comment]
We hit some API blockers during the implementation. The work is planned to continue in September.

**Comment by kidk** [comment]
We've released V3 version of our provider which includes all of the new Synthetics features: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v3 

This completes the migration of synthetics resources from REST to GraphQL 🥳 

Please let us know if you have any questions. If you encounter any issues please don't hesitate to create a new ticket. 

I'll close this ticket as the work has been delivered. Feel free to continue the discussion if needed.
