### ISSUE TITLE
Idea: Enable GitHub Discussion?

### ISSUE THREAD

**Issue by rdhar** [newrelic/terraform-provider-newrelic#1468]
I can't begin to imagine how many issues you just resolved with the release of [v2.28.0](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v2.28.0): it's huge!

Wonder if it might be worth enabling [GitHub Discussions](https://docs.github.com/en/discussions) for an open forum of transient communication between folks that isn't strictly issue-related.

For example, a thread dedicated to discuss changes implemented in the latest release and the benefits they bring would be ideal for boths devs and users alike to learn how to get the most value out of the tooling.

Cheers,
Rishav

**Comment by kidk** [comment]
Thanks for the idea @rdhar We appreciate your activity in our community. ❤️ 

Now go an discuss on https://github.com/newrelic/terraform-provider-newrelic/discussions 🥳  🎈
