### ISSUE TITLE
[newrelic_workload] entity_search_query as an array of strings, instead of single string

### ISSUE THREAD

**Issue by xmariopereira** [newrelic/terraform-provider-newrelic#1515]
### Feature Description
I want to do this:

```
resource "newrelic_workload" "edgeLocations" {
  for_each = var.edgeLocations
  name = each.key
  account_id = xxx

  entity_search_query {
    query = [for value in each.value: "type = Synthetic Monitor and name = ${value}"]
  }
}
```

Like I do here with entities:

```
resource "newrelic_synthetics_multilocation_alert_condition" "synthetics_alert_e2e" {
  policy_id = newrelic_alert_policy.synthetics_monitor_alert_policy.id

  count = length(newrelic_synthetics_monitor.opcua_e2e_monitor) > 0 ? 1 : 0

  name                         = "Synthetics Monitor Alert for E2E"
  enabled                      = true
  violation_time_limit_seconds = "86400"

  entities = [for value in newrelic_synthetics_monitor.opcua_e2e_monitor: value.id]

  critical {
    threshold = 2
  }

  warning {
    threshold = 1
  }
}
```
Only works if I do this

```
resource "newrelic_workload" "edgeLocations" {
  for_each = var.edgeLocations
  name = each.key
  account_id = xxx

  entity_search_query {
    query = "type = Synthetic Monitor and name = ${each.value[0]}"
  }
}
```

But the content of each.value list is dynamic.

### Describe Alternatives
I don't have a solution for this. I want to do multiple entity_search_query in a single workload. 

Use case: An edge IoT Location (Workload) can have multiple Edge IoT Gateways (entities).

**Comment by xmariopereira** [comment]
Ok, got a workaround for it.

```
resource "newrelic_workload" "edgeLocations" {
  for_each = var.edgeLocations
  name = each.key
  account_id = xxx

  dynamic "entity_search_query" {
    for_each = each.value
    content {
      query = "type = 'Synthetic Monitor' and name = '${entity_search_query.value}'"
    }

  }
}
```

But still being limited to string is not cool. Maybe feature request? :)

**Comment by asanuy** [comment]
Hi @xmariopereira,

Thanks a lot for the feedback. We're triaging old issues and I wanted to follow up your question.

Back in time it was decided to model lists of entities search queries as nested `entity_search_query` blocks, changing the contract is likely to involve breaking changes.

The workaround you shared in your last comment is actually the recommended approach for what you were trying to achieve 🙂

We'll proceed to close the issue.
