### ISSUE TITLE
newrelic_alert_policy does not report state change of channel_ids

### ISSUE THREAD

**Issue by ebdekock** [newrelic/terraform-provider-newrelic#1523]
### Terraform Version
```
terraform version
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/newrelic/newrelic v2.30.0
```

### Affected Resource(s)

- `newrelic_alert_policy`
- `newrelic_alert_channel`

### Terraform Configuration
Basic Terraform setup, with S3 backend, DynamoDB lock and AWS and NewRelic providers.

### Actual Behavior
Add a newrelic_alert_policy with `channel_ids` specified. Remove one of the notification channels in the GUI. Terraform plan or apply, it reports zero changes to state.

### Expected Behavior
I expect Terraform to warn about state changes. The provider should either re-add the notification channel or recreate the policy.

### Steps to Reproduce
- Add either of the following configs

```
resource "newrelic_alert_channel" "slack" {
  name = "our-channel"
  type = "slack"

  config {
    channel = "our-channel"
    url          = "our-slack-url"
  }
}

resource "newrelic_alert_policy" "policy" {
  name                = "Policy"
  channel_ids         = [newrelic_alert_channel.slack.id]
}
```

or

```
data "newrelic_alert_channel" "slack" {
  name = "our-channel"
}

resource "newrelic_alert_policy" "policy" {
  name                = "Policy"
  channel_ids         = [data.newrelic_alert_channel.slack.id]
}
```

 - `terraform apply`

- Go to GUI and delete the notification channel from the policy

 - `terraform plan`

- See no changes to be applied

### Debug Output
```
No changes. Your infrastructure matches the configuration.
```

**Comment by emetcalf9** [comment]
The Policy resource does not have a way to read the currently linked channels on the policy, so changes to the linked channels will not show a difference in Terraform when using that resource. Changing the channels on the Policy in your Terraform config also forces a new Policy to be created for the same reason. If you use the `newrelic_alert_policy_channel` resource to link your channels to the Policy, then Terraform will properly detect that a channel was removed and add it back. The config would then look something like this:
`resource "newrelic_alert_policy" "policy" {
  name = "TF Test Policy"
}

resource "newrelic_alert_channel" "channel1" {
  name = "Test channel 1"
  type = "email"

  config {
    recipients = "foo@example.com"
    include_json_attachment = "false"
  }
}

resource "newrelic_alert_channel" "channel2" {
  name = "Test channel 2"
  type = "email"

  config {
    recipients = "bar@example.com"
    include_json_attachment = "false"
  }
}

resource "newrelic_alert_policy_channel" "policychannels" {
  channel_ids = [
    newrelic_alert_channel.channel1.id,
    newrelic_alert_channel.channel2.id
  ]
  policy_id   = newrelic_alert_policy.policy.id
}`

On a related note, Alerts Channels are also being EOLed in the near future. More information is available here: https://discuss.newrelic.com/t/big-news-for-alerts-and-applied-intelligence/161436
