### ISSUE TITLE
infra_host_not_reporting is triggered for hosts not matching where condition

### ISSUE THREAD

**Issue by 2ZZ** [newrelic/terraform-provider-newrelic#1529]
Hi,

I have been asked to raise this here by New Relic support ticket #477463.

With the infra_host_not_reporting configuration below an alert is still generated for hosts matching linuxDistribution 'Ubuntu 18.04.%'. 

```
resource "newrelic_infra_alert_condition" "host_not_reporting" {
  policy_id = newrelic_alert_policy.infra_alerts.id

  name = "Host Not Reporting"
  type = "infra_host_not_reporting"
  runbook_url = "https://x"
  violation_close_timer = 12
  where = "ec2Tag_AppRole not like '%ZZZ%' AND linuxDistribution NOT LIKE 'Ubuntu 18.04.%' AND hostname NOT LIKE '%zzr%' AND hostname NOT LIKE '%zzk%' AND hostname NOT LIKE '%zzz%' AND hostname NOT LIKE '%zzd%' AND hostname NOT LIKE '%zzsk%'"
  critical {
    duration = 5
  }
}
```

I am not sure what other information will be relevant for this but can provide anything needed.

**Comment by kidk** [comment]
Thanks for report @2ZZ and apologies for the delay in response.

We would advice to use the `newrelic_nrql_alert_condition` resource, as the `newrelic_infra_alert_condition` will disappear in the future. There's some details on workaround in the explorer hub: https://discuss.newrelic.com/t/host-not-reporting-with-a-nrql-alert/172823/2

I'm going to close this for now, as we don't plan to do any work on `newrelic_infra_alert_condition`. Feel free to continue the thread on the explorer hub if you are unable to recreate your use-case.
