### ISSUE TITLE
Muting Rule with 'repeat' variable results in plugin crash. 

### ISSUE THREAD

**Issue by MadhuraDhananjaya** [newrelic/terraform-provider-newrelic#1542]
### Terraform Version
terraform version: 1.0.8

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alert_muting_rule`

### Terraform Configuration
Provider version : 2.32.0
Provider: Newrelic

### Actual Behavior
Muting rules with `repeat` value set to null, fail to succeed on terraform apply, but results in a plugin crash logs.
And also can see the Muting rule created on Newrelic application. When on destroy that do not recognize the rules that seen on application.

### Expected Behavior
Smooth run of terraform apply to create muting rules when repeat variable it set to null as per the document provided.

`Repeat` value can either be omitted or set to null when not in use. In both the cases terraform apply results in plugin crash error.
Ref doc where it says repeat can be omitted or set to null
Ref: newrrelic docs : https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications
terraform docs: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_muting_rule#repeat

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Panic Output
Gist of plugin crash logs: https://gist.github.com/MadhuraDhananjaya/5fbcbd6c69c52819d8b4fef32db091d6

**Comment by kevinfrommelt-wf** [comment]
We also ran into this. A user manually added a schedule to a muting rule in through the UI, which broke `terraform plan/apply`. The schedule data in the terraform debug logs looked like this:
```
      "schedule": {
       "endRepeat": null,
       "endTime": "2021-11-29T23:59:00-07:00",
       "repeat": null,
       "repeatCount": null,
       "startTime": "2021-11-23T00:00:00-07:00",
       "timeZone": "America/Denver",
       "weeklyRepeatDays": null
      }
```
The error was a nil pointer dereference coming from https://github.com/newrelic/terraform-provider-newrelic/blob/v2.32.0/newrelic/structures_newrelic_alert_muting_rule.go#L371

We manually removed the schedule to get around the issue.

**Comment by emetcalf9** [comment]
I was able to reproduce using `repeat = null` and by removing the `repeat` from a Muting Rule that previously had one.

This was happening because of the line referenced in the previous comment. We were trying to check the value of the `repeat` when it didn't exist, which caused the crash. I have a PR to update this to check if `repeat` is nil before checking the value, which works successfully in my testing: https://github.com/newrelic/terraform-provider-newrelic/pull/1571
