### ISSUE TITLE
Support for Alerts and AI

### ISSUE THREAD

**Issue by TheQueenIsDead** [newrelic/terraform-provider-newrelic#1559]
### Feature Description
As an engineer that uses Terraform to manage everything in NewRelic I want to be able to configure the new Alerts flow via Terraform instead of resorting to the Alerts Classic entities

### Describe Alternatives
-

### Additional context
I can not create Destinations, and the way that the documentation is laid out leads me to setup a classic workflow. If it's possible already I would love to be pointed in the right direction, but it's not immediately evident to me

**Comment by baNROne** [comment]
We've added a feature request to our internal tracking tool for Terraform support for Destinations.
