### ISSUE TITLE
"nrql.0.evaluation_offset" must be between 0 and 20 inclusive, got: 0

### ISSUE THREAD

**Issue by loloDawit** [newrelic/terraform-provider-newrelic#1561]
https://github.com/newrelic/terraform-provider-newrelic/blob/320bdd7298137a8f3f673daa4a8f7ee964867b54/newrelic/resource_newrelic_nrql_alert_condition.go#L192

if zero inclusive, why are we checking `< 1` ?

**Comment by sandeepkumar-kagitha** [comment]
Hi @loloDawit,

This is to inform you that ‘[evaluation_offset](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#evaluation_offset)’ was deprecated  and introduced  a new field called as  ‘[aggregation_delay](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#aggregation_delay)’. 

This field is going away we won't be fixing this issue, and advise you to use ‘[aggregation_delay](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#aggregation_delay)’. Let us know if there's anything we can help with.

Please look into the documentation for more information

https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#aggregation_method
