### ISSUE TITLE
newrelic_synthetics_multilocation_alert_condition

### ISSUE THREAD

**Issue by bergamut** [newrelic/terraform-provider-newrelic#1562]
Hi there,

Thank you for opening an issue.

In newrelic site, minimal settings for newrelic_synthetics_multilocation_alert_condition = 300.
in your provider minimal settings is newrelic_synthetics_multilocation_alert_condition = 3600
Please fix it :)

Error: expected violation_time_limit_seconds to be one of [0 3600 7200 14400 28800 43200 86400], got 300

**Comment by mbazhlekova** [comment]
Hi @bergamut 👋  good catch! Looks like the API has changed and I opened a PR to reflect that in the TF Provider #1566

**Comment by mbazhlekova** [comment]
This was fixed with #1566. It will be out with the next release.
