### ISSUE TITLE
Document the VSE password support for `newrelic_synthetics_monitor_script`

### ISSUE THREAD

**Issue by zeffron** [newrelic/terraform-provider-newrelic#1577]
### Feature Description
Please document the VSE password support for `newrelic_synthetics_monitor_script`. The HMAC support is documented, but it looks like when VSE support was added, the documentation was missed.

### Describe Alternatives
N/A

### Additional context
See [documentation](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor_script) and 
#1533

**Comment by mbazhlekova** [comment]
@zeffron Good catch! I opened a PR #1580

**Comment by mbazhlekova** [comment]
This change went out with version 2.35.0
