### ISSUE TITLE
Issue with violation_time_limit_seconds when importing NRQL conditions.

### ISSUE THREAD

**Issue by andrewward** [newrelic/terraform-provider-newrelic#1581]
### Terraform Version
terraform 1.x
newrelic provider 2.x

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_nrql_alert_condition`

### Actual Behavior
When importing an NRQL condition the statefile is populated with:

```
            "violation_time_limit": "ONE_HOUR",
            "violation_time_limit_seconds": null,
```

### Expected Behavior
```
            "violation_time_limit": "ONE_HOUR",
            "violation_time_limit_seconds": 3600,
```

### Steps to Reproduce
Import any nrql condition into a statefile.

I'm not too sure how the import process works with terraform but I believe the issue might be with this [piece of code](https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/structures_newrelic_nrql_alert_condition.go#L610).

I believe [1567](https://github.com/newrelic/terraform-provider-newrelic/pull/1567/files) has introduced a bug that prevents both the deprecated violation_time_limit and violation_time_limit_seconds from being imported and previous versions of that code didn't properly import both even though both are returned by GraphQL:

```
{
  actor {
    account(id: xxxx) {
      alerts {
        nrqlConditionsSearch(searchCriteria: {policyId: "yyyy"}) {
          nrqlConditions {
            violationTimeLimit
            violationTimeLimitSeconds
          }
        }
      }
    }
  }
}

...
"nrqlConditions": [
  {
    "violationTimeLimit": "ONE_HOUR",
    "violationTimeLimitSeconds": 3600
  },
  {
     "violationTimeLimit": "ONE_HOUR",
    "violationTimeLimitSeconds": 3600
  }
]
...
```

Should something like this be be used instead?

```
diff --git a/newrelic/structures_newrelic_nrql_alert_condition.go b/newrelic/structures_newrelic_nrql_alert_condition.go
index f7ab8afd..4e5a152c 100644
--- a/newrelic/structures_newrelic_nrql_alert_condition.go
+++ b/newrelic/structures_newrelic_nrql_alert_condition.go
@@ -607,9 +607,11 @@ func flattenNrqlAlertCondition(accountID int, condition *alerts.NrqlAlertConditi
 		}
 	}
 
-	if _, ok := d.GetOk("violation_time_limit_seconds"); ok {
+	if condition.ViolationTimeLimitSeconds != 0 {
 		_ = d.Set("violation_time_limit_seconds", condition.ViolationTimeLimitSeconds)
-	} else if _, ok := d.GetOk("violation_time_limit"); ok {
+	}
+
+	if condition.ViolationTimeLimit != "" {
 		_ = d.Set("violation_time_limit", condition.ViolationTimeLimit)
 	}

```

I think `violation_time_limit_seconds` is always returned from the API so we might be able to remove the guard clause altogether.

**Comment by kidk** [comment]
Thanks for the detailed report @andrewward We'll take a look

**Comment by emetcalf9** [comment]
Thanks @andrewward for the suggested fix. I did some manual testing on this, and the new results look great. I have a PR open to make those changes.
