### ISSUE TITLE
newrelic provider missing the resource creation for synthetic monitoring of SSL certificate expiration

### ISSUE THREAD

**Issue by atul29mehta** [newrelic/terraform-provider-newrelic#1585]
![new view](https://user-images.githubusercontent.com/78490054/149278670-61ffb5bb-a3a2-4a06-b2b4-c938fb26411b.png)
We are using newrelic as monitoring tool for our production cloud based application. The newrelic deployment on production is processed using terraform code. Now we have to add the monitoring of SSL expiration for our domain names. This functionality is present in new relic but the terraform [resource](url) creation for it is not present. The resource creation which is present for it in terraform is "newrelic_synthetics_monitor" but the type is present for SIMPLE, BROWSER, SCRIPT_BROWSER, and SCRIPT_API which is also present in newrelic but in the new view there are some additional types are present and SSL certificate is one of them.I have attached the screenshot of old and new view.
![old view](https://user-images.githubusercontent.com/78490054/149278684-6d94ab15-4519-46b9-8dd4-0e920dc13d25.png) 
 Please look into the issue as it is creating delay in our production deployment. Please suggest the alternate way to do this or please let us know the ETA for newrelic provider upgrade to add this attribute. I shall be very thankful to you.
Thank you,
Atul Mehta
Senior DevOps Engineer

**Comment by kidk** [comment]
Thanks for the suggestion @atul29mehta At the moment the API's we are using do not allow us to implement this functionality. The synthetics team at New Relic is creating a new API that will add this, but at the moment that's not available yet for all customers. Once it is, we will add this functionality to terraform.

**Comment by garry-jeromson** [comment]
This can be done using a `newrelic_synthetics_monitor_script` resource and the script shown here: https://discuss.newrelic.com/t/relic-solution-monitoring-ssl-certificate-expiration/51240.

**Comment by atul29mehta** [comment]
Thanks, I'll check it out.

**Comment by kidk** [comment]
@atul29mehta @garry-jeromson  We've released V3 version of our provider which includes all of the new Synthetics features: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v3 

The SSL check is now available as a new resource: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor_cert_check

Please let us know if you have any questions. If you encounter any issues please don't hesitate to create a new ticket. 

I'll close this ticket as the work has been delivered. Feel free to continue the discussion if needed.
