### ISSUE TITLE
Can't set filter_current_dashboard if linked_entity_guids is set

### ISSUE THREAD

**Issue by joshua-paypay** [newrelic/terraform-provider-newrelic#1604]
> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [V ] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [V ] A list of [affected resources](#affected-resources) and/or data sources
- [V ] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [V ] Description of the [current behavior](#actual-behavior) (the bug)
- [V ] Description of the [expected behavior](#expected-behavior)
- [V] Any related [log output](#debug-output)

### Terraform Version
```
$ terraform -version
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.34.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_one_dashboard`

### Terraform Configuration

```hcl
provider "newrelic" {
  region = "US"
}
terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
    }
  }
}
```

### Actual Behavior
What actually happened?
Can't set `filter_current_dashboard` if `linked_entity_guids` is set

### Expected Behavior
- can remove `linked_entity_guids`
- can add `filter_current_dashboard`

### Steps to Reproduce
I had some issue setting up dashboards originated from a json file copy from an old dashboard.
The original dashboard had `linked_entity_guids = []` to the old dashboard.

```
widget_bar {
  # omitting details
  linked_entity_guids = ["old-dashboard-guid"]
}
```
This works fine, however, it is pointing to the old dashboard.

So, I've changed the config to 
```
widget_bar {
  # omitting details
  filter_current_dashboard = true
}
```

The dashboard still points to the old one.

## Experiments
I did some experiments
1. I created a dashboard like my real dashboard (business details omitted). Then both work fine. Widget 1 can filter the test dashboard.
```
resource "newrelic_one_dashboard" "test-dashboard" {

  page {
    widget_bar {
      name = "widget 1"
      filter_current_dashboard =  true
    }

    widget_bar {
       name = "widget 2"
      linked_entity_guids = ["old-dashboard-guid"]
    }
  }
}
```
2. I removed the guids from widget 2. Then Widget 2 had no filters. This is also fine.
```
resource "newrelic_one_dashboard" "test-dashboard" {

  page {
    widget_bar {
      name = "widget 1"
      filter_current_dashboard =  true
    }

    widget_bar {
       name = "widget 2"
      linked_entity_guids = []
    }
  }
}
```
3. I add `filter_current_dashbaord = true` to widget 2. However **no filter is generated**.
```
resource "newrelic_one_dashboard" "test-dashboard" {

  page {
    widget_bar {
      name = "widget 1"
      filter_current_dashboard =  true
    }

    widget_bar {
       name = "widget 2"
      filter_current_dashboard =  true
    }
  }
}
```
![Screen Shot 2022-01-05 at 11 26 26](https://user-images.githubusercontent.com/91855917/148151616-8c9b23e5-db6a-4706-873b-284ee388e14e.png)

### References
[filter_current_dashboard of newrelic_one_dashboard is not handled properly #1494](https://github.com/newrelic/terraform-provider-newrelic/issues/1494#issuecomment-1005331411)

**Comment by rdhar** [comment]
Hey @joshua-paypay, could you retry your use-case?

Following the release of [v2.38.0 ](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v2.38.0), I've found it addressed some issues relating to dashboard filters.

**Comment by joshua-paypay** [comment]
Hello the issue is still there. Thanks.

**Comment by mbazhlekova** [comment]
@joshua-paypay Only one of either `linked_entity_guids` or `filter_current_dashboard` can be set. Both values set the `linked_entity_guids` so we want to avoid conflict. It seems like you're having an issue when setting `filter_current_dashboard` on an existing dashboard.  We are aware of the issue. There is a bug on update. We have a fix currently in review #1662 and we're hoping to roll it out next week.

**Comment by mbazhlekova** [comment]
@joshua-paypay We rolled out a fix for the `filter_current_dashboard` on update with (v2.41.0-beta.1)[https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v2.41.0-beta.1]. Please update to this version and let us know if it fixes the issues you're seeing.

**Comment by joshua-paypay** [comment]
Hello, I think the issue still exists.  You can use some entity guids to test.
The workaround is to set all pages manually on new relic GUI...but we have a lot of dashboards.
I've also tried set linked_entity_guids to null. Didn't work.

**Comment by kidk** [comment]
Hi @joshua-paypay Are you now using `filter_current_dashboard`? Could you share your updated code?

**Comment by kidk** [comment]
We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.
