### ISSUE TITLE
newrelic_entity data source cannot find entity with exact name

### ISSUE THREAD

**Issue by antonblr** [newrelic/terraform-provider-newrelic#1609]
### Terraform Version
```
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.29.0`
```
### Affected Resource(s)
- `newrelic_entity` data resource

### Terraform Configuration

```hcl
provider "newrelic" {
  account_id    = var.account_id
  admin_api_key = var.admin_api_key
  api_key       = var.api_key
  region        = var.region
}
```

```hcl
data "newrelic_entity" "uvrg_prod_gcp_us-west1" {
  name = "Universal Video Recorder Gateway - Prod - GCP - us-west1"
}

resource "newrelic_alert_condition" "apdex_warning_uvrg" {
  condition_scope = "application"

  entities = [
    data.newrelic_entity.uvrg_prod_gcp_us-west1.application_id,
  ]

  metric      = "apdex"
  name        = "Universal Video Recorder Gateway Apdex (Low)"
  policy_id   = data.newrelic_alert_policy.content_asset_notify_slack.id
  runbook_url = "https://www.example.com"

  term {
    duration      = 15
    operator      = "below"
    priority      = "critical"
    threshold     = "0.85"
    time_function = "all"
  }

  type = "apm_app_metric"
}
```

### Actual Behavior
The data resource `data.newrelic_entity.uvrg_prod_gcp_us-west1` fails to resolve with:
```
Error: the name 'Universal Video Recorder Gateway - Prod - GCP - us-west1' does not match any New Relic One entity for the given search parameters (ignore_case: false)
```
I've confirmed that the entity with exact this name does exist in account defined for provider block (`var.account_id`)

### Expected Behavior
Entity with the name specified found.

### Steps to Reproduce
`terraform plan`

### Important Factoids
After some debugging I found that the query used for entity search returns ~500 entities - see results in https://gist.github.com/antonblr/acac55197b16f403a262f5736aef4f5c. And the desired entity is not even there.

The same query works as expected once I replaced `LIKE` with `=` (`"name = 'Universal Video Recorder Gateway - Prod - GCP - us-west1'"`) - only expected entity was returned.

The question is - should we distinct between exact string search and string matching in `newrelic_entity` data resource? 
Thankfully all the unrelated entities are in "INFRA" domain, so we could work around it by specifying "APM" domain. But it still a problem if we will search in the "INFRA" domain.

**Comment by kidk** [comment]
Hi @antonblr 

Have you recently had issues with this? There's been some changes on the API side to improve this.

**Comment by antonblr** [comment]
Hi @kidk, this looks good now (even with the same provider version). Running the same query (from the description) in https://api.newrelic.com/graphiql indeed gives better results now (returns single item/exact match). Feel free to close it.

**Comment by kidk** [comment]
Awesome, great to hear. Thanks for coming back to us.
