### ISSUE TITLE
Validation on threshold_duration in newrelic_nrql_alert_condition is wrong.

### ISSUE THREAD

**Issue by WinterNis** [newrelic/terraform-provider-newrelic#1613]
### Terraform Version

Terraform version: `1.1.2`
Newrelic provider version:  `2.35.1`

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_nrql_alert_condition`

### Terraform Configuration
```hcl
terraform {
  required_version = ">= 1.1.2"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = ">= 2.35.1"
    }
  }
}

provider "newrelic" {
  region     = "EU"
  account_id = "XXXXXX"
}
```

### Actual Behavior
I tried to defined a static condition with an aggregation window of `59 seconds`, and a critical threshold_duration  of `118 seconds`.
The terraform module validation ([code here](https://github.com/newrelic/terraform-provider-newrelic/blob/66086f6c9b3b1adbc1fa5bf394edeb2a2877d76c/newrelic/resource_newrelic_nrql_alert_condition.go#L81)) threw the following error:

```
╷
│ Error: "critical.0.threshold_duration" must be a factor of 60, got: 118
│ 
│   with newrelic_nrql_alert_condition.xxxx,
│   on main.tf line 57, in resource "newrelic_nrql_alert_condition" "xxxx":
│   57:     threshold_duration    = 118
│ 
╵
```

But through newrelic one UI (and I suppose, the api behind) , creating the same condition works, as the requirement is "Threshold duration must be a multiple of the aggregation window".

Setting the threshold duration to 120 in terraform, and applying throw another error, since it’s not matching the api requirement:

```
╷
│ Error: Validation Error: BAD_USER_INPUT
│ 
│   with newrelic_nrql_alert_condition.xxxxx,
│   on main.tf line 35, in resource "newrelic_nrql_alert_condition" "xxxxx":
│   35: resource "newrelic_nrql_alert_condition" "xxxxx" {
│ 
│ terms[].thresholdDuration: must be a multiple of the aggregation window
```

### Expected Behavior
Newrelic terraform provider should match UI validation and should not throw error when passing a `threshold_duration` that is actually a multiple of the aggregation window.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create resources

```hcl
resource "newrelic_alert_policy" "foo" {
  name = "foo"
}

resource "newrelic_nrql_alert_condition" "foo" {
  policy_id                    = newrelic_alert_policy.foo.id
  name                         = "myname"
  violation_time_limit_seconds = 3600
  aggregation_window           = 59
  aggregation_delay            = 120
  value_function               = "single_value"
  aggregation_method           = "event_flow"
  fill_option                  = "none"

  nrql {
    query = "myquery"
}

  critical {
    operator              = "above"
    threshold             = 1
    threshold_duration    = 118
    threshold_occurrences = "ALL"
  }
}
```
2. `terraform plan`

**Comment by kidk** [comment]
Thanks @WinterNis 

This indeed doesn't look right. I've forwarded this to our alert team.

**Comment by emetcalf9** [comment]
PR #1630 fixes this validation issue and has been merged, but not released yet. Closing this issue now as the problem will be resolved in the next release.

**Comment by dotnetagarwal** [comment]
It's still happening. It's still allowing to setup threshold less than AggregateWindow interval via UI. When you deploy it via terraform, it works as expected.
