### ISSUE TITLE
Feature Request : Add xmatters to Alert Channel Types

### ISSUE THREAD

**Issue by dsinang** [newrelic/terraform-provider-newrelic#1615]
Hope someone can add xmatters to the Alert Channel Types.

**Comment by kidk** [comment]
Hi @dsinang 

This will become available once the new API destinations is available and implemented in Terraform. At the moment we still use the old API. This should happen around the summer.

**Comment by baNROne** [comment]
We've added a feature request to our internal tracking tool for adding xMatters as a destination.
