### ISSUE TITLE
Feature Request : Add Browser Monitor Resource

### ISSUE THREAD

**Issue by dsinang** [newrelic/terraform-provider-newrelic#1616]
There doesn't seem to be a way for me to create a New Relic One Browser monitor via Terraform.

Hope someone can add this feature / resource.

**Comment by kidk** [comment]
Hi @dsinang I'm not sure what you mean?

Do you mean the [New Relic browser monitoring agent](https://docs.newrelic.com/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring/), or [synthetic browser monitoring](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/view-simple-scripted-monitor-results)?

Could you add some more information about your use-case?

**Comment by kidk** [comment]
We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.
