### ISSUE TITLE
Add guid to newrelic_synthetics_monitor output

### ISSUE THREAD

**Issue by megaloni** [newrelic/terraform-provider-newrelic#1618]
In order to add tags to a newly created newrelic_synthetics_monitor, the GUID is required. Returning this as part of the exported attributes would remove the need for a (sometimes flaky) re-read of the entity.

https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor

**Comment by kidk** [comment]
Thanks for the idea @megaloni This will be possible once the new API for Synthetics becomes available. We expect this to happen later this year.

**Comment by alejandrodnm** [comment]
Another use case is for adding the monitor entity to a specific workloads via the `entity_guids` argument.

**Comment by kidk** [comment]
@megaloni @alejandrodnm We've released V3 version of our provider which includes all of the new Synthetics features: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v3 

The GUID is now available from the synthetics resources with the `id` attribute. 

Please let us know if you have any questions. If you encounter any issues please don't hesitate to create a new ticket. 

I'll close this ticket as the work has been delivered. Feel free to continue the discussion if needed.
