### ISSUE TITLE
Filtering is not working (not clickable) on the Last page tab of a new dashboards if there is a page in front of it without any data

### ISSUE THREAD

**Issue by chrlai** [newrelic/terraform-provider-newrelic#1640]
Hello, using Terraform “newrelic_one_dashboard” / page with dynamic “page”  --- The page filtering doesn’t seem to work (not clickable) on the LAST page if there is a page in front of it without any data.   
Ie.,  if we have pages 1/2/3/4 ,  if any one of the page 1,2,3 does not have data, page 4 data filtering does not work (not clickable).

Terraform Version: v0.14.3
terraform-provider-newrelic version: 2.35.0

sample dashboard file:
 ```
EDIT by @kidk : New snippet below
```

**Comment by rdhar** [comment]
Hey @chrlai, you've shared a 1097 lines long code snippet which makes it tricky to parse the exact root cause of the issue.

Can you share a bare-minimum sample which just replicates the erroneous behaviour? It it's modular enough, it might even become a test case for future releases.

**Comment by shiva-bandari** [comment]
Hello @chrlai,

Could you please share your dashboard link to my email(sbandari@newrelic.com) , this will help us to troubleshoot further.

**Comment by kidk** [comment]
Hi @chrlai We haven't heard back from you so I'll close this ticket for now.

If this is still an issue, feel free to respond here with more information and we will reopen it.
