### ISSUE TITLE
Not able to use negative numbers in alert threshold in terraform but are allowed in New Relic UI

### ISSUE THREAD

**Issue by jduarteihm** [newrelic/terraform-provider-newrelic#1643]
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [ ] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [ ] A list of [affected resources](#affected-resources) and/or data sources
- [ ] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [ ] Description of the [current behavior](#actual-behavior) (the bug)
- [ ] Description of the [expected behavior](#expected-behavior)
- [ ] Any related [log output](#debug-output)

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```bash
terraform --version                                                                                
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.36.2
```
### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_nrql_alert_condition`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
// Define the New Relic Terraform Provider
provider "newrelic" {
}
```

### Actual Behavior
What actually happened?
After setting a threshold value to a negative value, running `terraform plan` results in an error:
```bash
Error: expected critical.0.threshold to be greater than or equal to 0, got -140
 
   with newrelic_nrql_alert_condition.nonprod_base_alert_conditions["Nonprod Player Decibel Level"],
   on conditions.tf line 49, in resource "newrelic_nrql_alert_condition" "nonprod_base_alert_conditions":
   49:     threshold             = each.value.threshold
```

### Expected Behavior
What should have happened?
If I make that same configuration to an alert using the New Relic UI, there is no longer an error in the UI preventing me from using negative values. I expect the ability to use negative values should be the same when using the terraform new relic provider.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by kidk** [comment]
Thanks for report @jduarteihm 

We'll look at this as soon as we can.
