### ISSUE TITLE
Custom Workload Status Rules

### ISSUE THREAD

**Issue by guhcampos** [newrelic/terraform-provider-newrelic#1672]
### Feature Description

New Relic supports the definition of custom Workload status rules. Sensible defaults are provided, but some applications require the definition of custom rules. A common use case is a _when any of these services are ok_ type of rule, for which New Relic itself provides a "rollup of the best status" option within a group of entities.

The `newrelic_workload` Terraform resource does not, however, allow for the creation of such rules, making it impossible to manage non-trivial workloads with the Terraform provider.

### Describe Alternatives

I don't think there are any.

**Comment by kidk** [comment]
Thanks for the request @guhcampos We will look at this an prioritise it with all the other requests. 

If you or anyone else is interested in creating a PR for this, we'll be more than happy to assist.

**Comment by guhcampos** [comment]
I was reviewing the open issues and noticed this might me a dupe of #1314

**Comment by NSSPKrishna** [comment]
This issue has been resolved in the release 3.6.0.
