### ISSUE TITLE
Value Function property made optional in TF provider whilst NewRelic API still requires it

### ISSUE THREAD

**Issue by JamesPeiris** [newrelic/terraform-provider-newrelic#1699]
### Information

In the NR provider [this PR](https://github.com/newrelic/terraform-provider-newrelic/pull/1656) was [merged into v2.38.0](https://github.com/newrelic/terraform-provider-newrelic/commit/99fdfffda1a4ea652bbc65ef28b466ce0bf7aa6c#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR10) that made the `value_function` property optional and added the deprecation warning. However, this change was merged before the NR API was updated to make that property optional.

So the API itself errors, per it's current [documentation](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/alerts-conditions-api-field-names/#user_defined_value_function) on this property.

### Checklist

- [x] Your New Relic `provider` configuration
- [x] A list of affected resources and/or data sources:
- [x] The configuration of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the current behavior (the bug)
- [x] Description of the expected behavior
- [x] Any related log output

### Terraform Version

`v1.0.7`

### Affected Resource(s)

`newrelic_nrql_alert_condition`

### Terraform Configuration

<details>
<summary>CLICK to expand</summary>
<p>

```hcl
# providers.tf

terraform {
  required_version = ">= 1.0.7"
  
  # NOTE: Our CI uses pinned version v1.0.7

  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = ">= 2.36.2"
      
      # NOTE: Our CI chooses the latest - v2.39.0
    }
  }
}

provider "newrelic" {
  account_id = "XXX"
  api_key    = data.redacted.api_key
  region     = "XXX"
}

# alerts.tf

resource "newrelic_nrql_alert_condition" "our_condition" {
  name                           = XXX
  account_id                     = XXX
  policy_id                      = XXX
  type                           = "static"
  description                    = XXX
  enabled                        = true
  value_function                 = "single_value"
  fill_option                    = "static"
  fill_value                     = 1.0
  aggregation_window             = 60
  aggregation_method             = "event_flow"
  aggregation_delay              = 120
  expiration_duration            = 120
  open_violation_on_expiration   = true
  close_violations_on_expiration = true
  slide_by                       = 30

  nrql {
    query = XXX
  }

  critical {
    operator              = "above"
    threshold             = 10
    threshold_duration    = 60
    threshold_occurrences = "ALL"
  }
}
```

</p>
</details>

#### Including the `value_function` property

```
  ╷
  │ Warning: Argument is deprecated 
  │ 
  │  with module.alerts.newrelic_nrql_alert_condition.rds_update_rejected, 
  │  on .terraform/modules/alerts/alerts/alerts.tf line 8, in resource "newrelic_nrql_alert_condition" "rds_update_rejected": 
  │  8: value_function = "single_value" 
  │ 
  │ 'value_function' is deprecated. Remove this field and condition will 
  │ evaluate as 'single_value' by default. To replicate 'sum' behavior, use 
  │ 'slide_by'. 
  ╵
```

#### Excluding the `value_function` property

```
  ╷
  │ Error: attribute `value_function` is required for nrql alert conditions of type `static`
  │
  │   with module.alerts.newrelic_nrql_alert_condition.rds_update_rejected,
  │   on .terraform/modules/alerts/alerts/alerts.tf line 1, in resource "newrelic_nrql_alert_condition" "rds_update_rejected":
  │    1: resource "newrelic_nrql_alert_condition" "rds_update_rejected" {
  │
  ╵
```

#### Including the `value_function` property:

No warning - the property is not yet marked as deprecated.

#### Excluding the `value_function` property:

```
  ╷
  │ Error: attribute `value_function` is required for nrql alert conditions of type `static`
  │
  │   with module.alerts.newrelic_nrql_alert_condition.rds_update_rejected,
  │   on .terraform/modules/alerts/alerts/alerts.tf line 1, in resource "newrelic_nrql_alert_condition" "rds_update_rejected":
  │    1: resource "newrelic_nrql_alert_condition" "rds_update_rejected" {
  │
  ╵
```

#### Including the `value_function` property:

```
  ╷
  │ Warning: Argument is deprecated 
  │ 
  │  with module.alerts.newrelic_nrql_alert_condition.rds_update_rejected, 
  │  on .terraform/modules/alerts/alerts/alerts.tf line 8, in resource "newrelic_nrql_alert_condition" "rds_update_rejected": 
  │  8: value_function = "single_value" 
  │ 
  │ 'value_function' is deprecated. Remove this field and condition will 
  │ evaluate as 'single_value' by default. To replicate 'sum' behavior, use 
  │ 'slide_by'. 
  ╵
```

#### Excluding the `value_function` property:

NR API does not error, as property is optional.

### Steps to Reproduce

1. `terraform apply`

### Debug Output

N/A

### Panic Output

N/A

### Important Factoids

N/A

### References

#1656 - PR that added deprecation warning/made property optional

**Comment by kidk** [comment]
Thanks for the detailed report @JamesPeiris I've flagged this with the alerting team.

**Comment by baNROne** [comment]
Hi from Alerts! Thanks for the report @JamesPeiris

When you see thees messages, are you creating a condition or updating a condition? I'm not sure it would make a difference, but it could be a useful data point as we look into this.

The warning message you've shared was added in the same PR that removed the error message, so it's confusing that you're receiving both. Are both examples from the same version of the provider? Or are you seeing the warning message when using `2.38.0` and then using an older version when you try to remove `value_function` and `terraform apply`?

So far, I've been unable to replicate this issue. I've successfully omitted `value_function` when creating static NRQL conditions with provider version `2.38.0`, the Alerts REST API, and Nerdgraph.

This deprecation message is only a warning and shouldn't prevent applying a plan. It's intended to notify users that this property will be going away soon. I think there's room to improve the messaging here, which we're discussing amongst the team.

**Comment by baNROne** [comment]
Since we haven't heard anything on this in a bit, I'm going to close the issue. Please feel free to re-open if you have any additional details to share.

**Comment by ybindu** [comment]
Hi, we are facing same issue as explained by JamesPeiris
We are not able to update alert using terraform without value_function in it. It keep on erroring below 

Error: attribute `value_function` is required for nrql alert conditions of type `static`

We are on terraform version 1.1.7 and newRelic providers version is 2.38.0

**Comment by baNROne** [comment]
@ybindu Please provide all of the information requested in the issue template found [here](https://github.com/newrelic/terraform-provider-newrelic/blob/723581c0a38a4194a193d6ac8e92cd80e990da31/.github/ISSUE_TEMPLATE/bug_report.md), and we'll be happy to take a look.

**Comment by greenkiwi** [comment]
@baNROne We are experiencing this issue too.  

We have this error during apply:
```
Error: attribute `value_function` is required for nrql alert conditions of type `static`
```

The `docs` clearly state that it is optional and `DEPRECATED`:
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#value_function
```
[value_function](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#value_function) - (Optional if type is static, omit when type is baseline) DEPRECATED Use signal.slide_by instead.
```

Please reopen and correct the docs or the provider.

**Comment by baNROne** [comment]
Hey @greenkiwi . It looks like you're using provider version 2.34.1 which did still require `value_function` when `type` is `static`. See the docs for version 2.34.1 [here](https://registry.terraform.io/providers/newrelic/newrelic/2.34.1/docs/resources/nrql_alert_condition#value_function).

There are a couple of options here. You could set `value_function` to `single_value` or you could use a newer version of the provider that doesn't require `value_function`. Our recommendation is always to use the newest version of the provider whenever possible.

**Comment by greenkiwi** [comment]
Hi @BarNROne -

Thanks. We will get that sorted one way or the other. Probably upgrading.

-greenkiwi
