### ISSUE TITLE
newrelic_nrql_drop_rule should support adding source attributes.

### ISSUE THREAD

**Issue by SeanWally2** [newrelic/terraform-provider-newrelic#1700]
### Feature Description
New Relic documentation states that to see a Drop Rule created with NerdGraph in the one.newrelic.com UI you have add a source attribute for Logging.  The newrelic_nrql_drop_rule provider does not appear to support adding additional attributes.

https://docs.newrelic.com/docs/logs/ui-data/drop-data-drop-filter-rules/#nerdgraph

The following example mutation can be applied through the API but appears to not be possible with through Terraform.

`mutation {
  nrqlDropRulesCreate(accountId: 3268595, rules: {action: DROP_ATTRIBUTES, description: "Description", nrql: "SELECT * FROM Logs", source: "Logging"})
}`

### Additional context
We manage all of our drop rules with Terraform.  It would be handy to be able to see them in the New Relic One ui instead of having to query them through NerdGraph.

**Comment by kidk** [comment]
We've reached out internally to have this field added to our public API, but it seems the team is unable to do so. This means there's nothing we can do on the Terraform side so we're closing this ticket for now. 

Hopefully the situation will improve in the future.

**Comment by brenwhyte** [comment]
Another organization here requesting this. Is there any way to band-aid this with a local-exec or something similar?

**Comment by kidk** [comment]
Not that I know off @brenwhyte I'd suggest to create a feature request for this on https://issues.newrelic.com/secure/Dashboard.jspa
