### ISSUE TITLE
Terraform plan fails with error "KILLED(exit code 137)"

### ISSUE THREAD

**Issue by MadhuraVp7** [newrelic/terraform-provider-newrelic#1722]
### Terraform Version
`Terraform version : 1.1.6`
`Provider version : 2.37.0`

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_one_dashboard`

### Actual Behavior
What actually happened?

`Terraform plan for dashboards is failing with error ‘KILLED’(exit code 137) which means the process is getting killed due to OOM.
On debug I did not see any helpful information. It just refreshed data from s3 backend and again resulted with exit code 137 and message **KILLED**.`

### Expected Behavior
What should have happened?

`Easy workflow of terraform plan and apply.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan and apply`

### Debug Output

Attaching logs with masked/ truncated sensitive data
https://gist.github.com/MadhuraVp7/9cbe75671c065eba9d8d59fafdea782a 

Issue posted on discuss.newrelic:  https://discuss.newrelic.com/t/terraform-plan-fails-with-error-killed-with-exit-code-137/180129

**Comment by shiva-bandari** [comment]
Hi @MadhuraVp7,
Could you provide sample TF script

**Comment by CHALUVADHIVENKATESH** [comment]
Will this cause because of high memory utilisation of server???
