### ISSUE TITLE
trace observer terraform resource

### ISSUE THREAD

**Issue by nosmolovskiy** [newrelic/terraform-provider-newrelic#1725]
### Feature Description
I need to create trace observers using terraform

### Describe Alternatives
I've tried to create trace observers using GraphQL and newrelic cli.

### Additional context
Distributed tracing is deprecated and trace observers becoming mandatory component of environments.
Lot's of environments are using Terraform as IaC tool.

**Comment by pranav-new-relic** [comment]
Closing this issue as advised by @kidk, since this is currently not in the roadmap.
