### ISSUE TITLE
newrelic_entity data source should not use a "fuzzy" search for searches by entity name

### ISSUE THREAD

**Issue by nathanweddle** [newrelic/terraform-provider-newrelic#1726]
### Terraform Version
`0.13.7`
New Relic Provider version `2.39.0`

### Affected Resource(s)
- `newrelic_entity`

### Terraform Configuration
```hcl
provider "newrelic" {
  alias      = "ace"
  region     = ""
  api_key    = 
  version    = "~> 2.39.0"
  account_id =
}

data "newrelic_entity" "app" {
  name = var.service

  # Query with specific tags
  # to get an exact match.
  tag {
    key   = "account"
    value = local.account_name
  }
}
```

### Actual Behavior
Error when applying plan
```
Error: 422 response returned: Invalid entity id(s): 18271798.

  on ../modules/no-web-throughput/main.tf line 17, in resource "newrelic_alert_condition" "warn_no_web_throughput":
  17: resource "newrelic_alert_condition" "warn_no_web_throughput" {
```
This is caused by the GraphQL endpoint using a fuzzy search. Too many entities are returned by the call and the data source picks the first one in the list, which in my case in incorrect. Example GraphQL request and response
```json
{
  actor {
    entitySearch(queryBuilder: {domain: APM, type: APPLICATION, name: "Condition API - Production"}) {
      query
      results {
        entities {
          name
          entityType
          guid
          ... on ApmApplicationEntityOutline {
            guid
            name
            applicationId
          }
        }
      }
    }
  }
}
```
```json
           {
              "name": "Condition API - EU Production"
            },
            {
              "name": "Condition API - Production"
            },
            {        
              "name": "Condition API - Production (canary)"
            },
            {           
              "name": "Condition Registration API - EU Production"
            },
            {
              "name": "Condition Registration API - Production"
            },
            {
              "name": "Condition Registration API - Production (canary)"
            },
            {
              "name": "condition-recommendation-api (eu-production)"
            },
            {
              "name": "condition-recommendation-api (production)"
            }
``` 

### Expected Behavior
Returned an entity id that matches the name of  `Condition API - Production`

### Steps to Reproduce
Perform a  GraphQL entity search by name in an account where there are multiple apps with similar names. Use the `queryBuilder` functionality in GraphQL. After speaking with the Entity Platform team, there is a way to get the exact match. 
Don't do this `entitySearch(queryBuilder: {domain: APM, type: APPLICATION, name: "Condition API - Staging"}) {` with the `queryBuilder`. This does a `LIKE` query. 

Do this instead
`entitySearch(query: "domain = 'APM' AND type = 'APPLICATION' AND name LIKE 'Condition API - Production'") {`
This will give you the exact match, which we want in this case

### Debug Output
N/A

### Panic Output
N/A

### Important Factoids
This issue has occurred in the past. There are various work arounds but all involve manual steps. I encountered this when I was consolidating alert conditions from three separate accounts (staging/prd/eu) into one account. So we have apps with similar names in one account (Condition API - Production, Condition API - EU Production, Condition API - Staging), etc, see above

### References
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/entity

**Comment by kidk** [comment]
Thanks @nathanweddle We'll take a look at how we can improve this. 

I'm thinking we add an 'exact' parameter, to switch off the fuzzy search. Any thoughts? 
```
data "newrelic_entity" "app" {
  name = var.service

  # Query with specific tags
  # to get an exact match.
  tag {
    key   = "account"
    value = local.account_name
  }

  exact = true
}
```

**Comment by kidk** [comment]
I think we're going to go with `fuzzySearch`, with default value of `true` not to break existing usage.

**Comment by kidk** [comment]
Hi @nathanweddle 

After some digging we've come to the conclusion that although the API does a fuzzy search we have some additional logic in the provider to do an exact match on the name: https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/data_source_newrelic_entity.go#L120

Could you share some more details on the specific use-case where you encounter this as an issue? You mention that it's related to moving alerts from one account to another. Feel free to reach out internally on #help-observability-as-code if needed. 

Thanks

**Comment by sanderblue** [comment]
Just closing the loop here. We were able to confirm this is a non-issue yesterday 🙂
