### ISSUE TITLE
Duplicate Policies alert New Relic

### ISSUE THREAD

**Issue by jjan123** [newrelic/terraform-provider-newrelic#1740]
**Terraform Version**
Terraform required_version = "~> 1.0.6"
required_providers source  = "hashicorp/local" version = ">= 2.1.0"

**Affected Resource(s)**
newrelic_alert_policy

**Actual Behavior**
If we run this code below twice:
```
resource "newrelic_alert_policy" "policy" {
  name                = "myAlert1"
  incident_preference = "PER_CONDITION_AND_TARGET"
  channel_ids = [
    12345
  ]
}
```

we will get duplicated "myAlert1" policies.

**Expected Behavior
What should have happened?**
I would expect the code to not create the duplicated policies although the code above run twice. should it be smart enough to know that it already exist and if it already exists, do not create another policy.

**Steps to Reproduce**
Please list the steps required to reproduce the issue, for example:

terraform plan and apply twice the following code
```
resource "newrelic_alert_policy" "policy" {
  name                = "myAlert1"
  incident_preference = "PER_CONDITION_AND_TARGET"
  channel_ids = [
    12345
  ]
}
```

**Comment by kidk** [comment]
Hi @jjan123 

Thanks for the ticket. We were unable to reproduce your issue on the latest version of our provider. It seems you are running a very old version, so we would advice to upgrade to the latest. Any version below 2.37.0 will soon be deprecated.

Let us know if you still encounter the issue on the latest version and I will reopen the ticket.

Kind regards
