### ISSUE TITLE
Add support Synthetics private location(Resource output and Data Source)

### ISSUE THREAD

**Issue by kaojiri** [newrelic/terraform-provider-newrelic#1753]
### Feature Description
Add support Synthetics private location

### Describe Alternatives
To deploy synthetics private location and create monitor execute by created private location.

### Additional context
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/private-locations-overview-monitor-internal-sites-add-new-locations/

**Comment by ChandraIragavarapu** [comment]
Thank you @kaojiri. We will prioritise it with all the other requests.

**Comment by ChandraIragavarapu** [comment]
Hi @trustthewhiterabbit 

Sure. Will update the documentation, Also this enhancement is in our first priority list.
