### ISSUE TITLE
Invalid address to set: []string{"config", "0", "payload_string"}

### ISSUE THREAD

**Issue by travisroberts-sf** [newrelic/terraform-provider-newrelic#1761]
### Description of Error
After the release earlier today, we are getting the following error when trying to create alert policies and alert policy channels:
```
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vault_generic_secret.nr-dev-api: Refreshing state...
data.newrelic_alert_channel.slack_users: Refreshing state...
module.ad-itss-alert-policy.data.newrelic_alert_channel.insights_webhook_channel: Refreshing state...

Error: Invalid address to set: []string{"config", "0", "payload_string"}

  on .terraform/modules/ad-itss-alert-policy/newrelic/modules/alerts/alert_policy/nr_alert_policy.tf line 2, in data "newrelic_alert_channel" "insights_webhook_channel":
   2: data "newrelic_alert_channel" "insights_webhook_channel" {
```
 This is our own modules created internally, the modules reference the provider directly and was working perfectly until after v2.43.0 was release earlier today.
### Terraform Version
v0.13.7

### Affected Resource(s)
- newrelic_alert_policy
- newrelic_alert_channel

### Terraform Configuration
provider "newrelic" {
  account_id = data.vault_generic_secret.nr-dev-api.data["account-number"]
  api_key    = data.vault_generic_secret.nr-dev-api.data["personal-api-key"]
  region     = "US"
}

terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
    }
    vault = {
      source = "hashicorp/vault"
    }
  }
  required_version = ">= 0.13"
}

### Actual Behavior
What actually happened?

### Expected Behavior
What should have happened?

### Steps to Reproduce
1. terraform apply

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
n/a

### Important Factoids
It looks like this all started about 8 or so hours ago (as of the writing of this issue with the release referenced below.

### References
https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v2.43.0

**Comment by kidk** [comment]
Thanks for details @travisroberts-sf We'll take a look

**Comment by emetcalf9** [comment]
Thanks for pointing this out. This is related to a recent change that allows the payload to be properly loaded into state when importing a webhook channel, but this broke the read function for the "data_source" version of the channel because it is missing the `payload_string` field. I just put in a PR to add this field to the data_source, which fixed this issue in my testing.
