### ISSUE TITLE
Add "filter_current_dashboard" option to Pie/Bar Chart Widgets 

### ISSUE THREAD

**Issue by khpeet** [newrelic/terraform-provider-newrelic#1762]
### Feature Description
Add "filter_current_dashboard" option to Pie/Bar Chart Widgets - Currently this only exists for table widgets:

https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#filter_current_dashboard

But Pie/Bar chart widgets do have a filter current dashboard option available. Requesting this option is added for both of these widget types as well.

**Comment by kidk** [comment]
Fixed with https://github.com/newrelic/terraform-provider-newrelic/pull/1764
