### ISSUE TITLE
Linked entity GUIDs require the page GUID, not the dashboard entityId as stated in the documentation

### ISSUE THREAD

**Issue by billycn20** [newrelic/terraform-provider-newrelic#1765]
---
Hello,

Attempting to link GUIDs to a dashboard widget table of the same dashboard does not work unless you use the page GUID. Additionally, the page GUIDs are not available anywhere in the newrelic UI. The only way to obtain them was by enabling the DEBUG=true logs in terraform provider which prints out the dashboard GUIDs in stdout. 

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Provider
```
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.32.0"
    }
  }
}
```
### Terraform Version
Terraform version: 1.1.3

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_one_dashboard `

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
module "error_detection_dashboard" {
  source                  = "./modules/newrelic_one_dashboard"
  newrelic_dashboard_name = "[TF] New Error Detection Dashboard"
  permissions             = "public_read_write"
  page_name               = "All Application Errors"
  widget_table = [{
    title                    = "Application's Specific Filter"
    row                      = 1
    column                   = 1
    height                   = 4
    width                    = 6
    account_id               = var.newrelic_account_id
    nrql_query               = "SELECT earliest(timestamp) FROM TransactionError where appName != 'xxx' FACET appName  SINCE 4 WEEKS AGO limit max order by earliest"
    filter_current_dashboard = false
    linked_entity_guids      = []
    },
    {
      title                    = "Team's Specific Filter"
      row                      = 1
      column                   = 7
      height                   = 4
      width                    = 6
      account_id               = var.newrelic_account_id
      nrql_query               = "SELECT earliest(timestamp) FROM TransactionError where appName != 'xxx' FACET `tags.cai_catalog_tier4-team-name`  SINCE 4 WEEKS AGO limit 200 order by earliest"
      filter_current_dashboard = false
      linked_entity_guids      = []
    },
    {
      title                    = "Application's New Errors"
      row                      = 2
      column                   = 1
      height                   = 6
      width                    = 12
      account_id               = var.newrelic_account_id
      nrql_query               = "SELECT earliest(timestamp), earliest(error.message), earliest(http.statusCode), earliest(request.method) FROM TransactionError where appName != 'xxx' FACET appName, error.class  SINCE 4 WEEKS AGO limit 200 order by earliest"
      filter_current_dashboard = false
      linked_entity_guids      = []
  }]
}

```

### Actual Behavior
Adding the GUID of the dashboard created in terraform and using it in the `linked_entity_guids` parameter and apply the changes does not enable the filtering by hovering over the widgets as expected. However, using the page GUID of this dashboard, in this field **does** enable the filter hover over the widgets. Because the page GUID is not available in the UI it is difficult to obtain this information. 

### Expected Behavior
As the documentation [states](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#linked_entity_guids) the following:
```
linked_entity_guids: (Optional) Related entity GUIDs. Currently only supports Dashboard entity GUIDs.
```
The expected behavior is that if you provide the dashboard GUID, it will reflect and allow you to hover over the widgets for applying filter.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Obtain the Dashboard GUID of the created dashboard
3. Update the `linked_entity_guids = []` to include that GUID
4. `terraform apply` again
5. Dashboard will **not** allow for filter on widgets by hovering
6. Use the Current dashboards page GUID obtained from terraform logs
7. Update the `linked_entity_guids = []` to use the page GUID
8. `terraform apply`
9. Verify that the dashboard now **does** allow the filtering of widgets by hovering

### Debug Output
```
2022-04-20T13:21:58.619-0400 [WARN]  Provider "provider[\"registry.terraform.io/newrelic/newrelic\"]" produced an unexpected new value for module.error_detection_dashboard.newrelic_one_dashboard.dashboard, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .page[0].widget_table[0].linked_entity_guids: element 0 has vanished
      - .page[0].widget_table[1].linked_entity_guids: element 0 has vanished
module.error_detection_dashboard.newrelic_one_dashboard.dashboard: Modifications complete after 1s [id=MTYxMDU5N3xWSVp8REFTSEJPQVJEfGRhOjExODI3ODU]
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Trying to update the currently managed dashboard with filtering.

### References
N/A

**Comment by sandeepkumar-kagitha** [comment]
@billycn20 Thank you for reporting the issue. We will look into the issue on priority basis.

**Comment by mbazhlekova** [comment]
Hi @billycn20 👋 if you want to link a widget to its page, set the `filter_current_dashboard` property to `true`. This will automatically set the page GUID in the `linked_entity_guids` for you.

**Comment by billycn20** [comment]
@mbazhlekova i tried that approach but since this field `linked_entity_guids` has its own parameter in the terraform which must be filled in with a GUID in the resource  it doesn't save just by  having `filter_current_dashboard=true`

**Comment by mbazhlekova** [comment]
@billycn20 Can you try updating the provider to the latest version? We fixed some bugs around `filter_current_dashboard` in version 2.41.1

**Comment by billycn20** [comment]
@mbazhlekova  thank you, the issue is resolved after updating to the latest version of the provider! this issue can be closed.
