### ISSUE TITLE
"LIMIT" field for bullet widgets being required when it should be optional

### ISSUE THREAD

**Issue by tyau-invitae** [newrelic/terraform-provider-newrelic#1768]
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [X] Description of the [current behavior](#actual-behavior) (the bug)
- [X] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version

Terraform version 1.1.9

### Affected Resource(s)

- newrelic_one_dashboard

### Terraform Configuration

```hcl
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = ">=2.43.2"
    }
  }
}

provider "newrelic" {
  account_id = "<redacted>"
  region     = "US"
}

resource "newrelic_one_dashboard" "default" {
  name        = "Ticket 1768"
  description = "Managed via Terraform"

  page {
    name        = "Simple Page"
    description = "Simple Page"

    # Bullet chart
    widget_bullet {
      title  = "Number of Hosts by Cluster"
      row    = 1
      column = 1
      height = 5
      width  = 6
      # limit  = 2000

      nrql_query {
        account_id = <redacted>
        query      = "FROM K8sClusterSample select uniqueCount(hostname) FACET clusterName limit max since 15 minutes ago"
      }
    }
  }
}
```

### Actual Behavior

When using widget_bullet in a new-relic-dashboard tf file, the following error is received when the `LIMIT` field is omitted:
**Missing required limit field for BULLET chart type.**

### Expected Behavior

Based on the documentation:  https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#limit
the `LIMIT` field should be optional for widget_bullet

### Debug Output

newrelic_one_dashboard.default: Creating...
╷
│ Error: query error; Missing required limit field for BULLET chart type. Widget id = '<none>'.
│ 
│   with newrelic_one_dashboard.default,
│   on 1768.tf line 18, in resource "newrelic_one_dashboard" "default":
│   18: resource "newrelic_one_dashboard" "default" {
│ 
╵

### Important Factoids

A New Relic support engineer for our account says:
"According to our team, this error is coming from the Dashboards API. Looks like the API has changed to make the field required instead of optional. Terraform follows the API so it will have to be required in Terraform as well."

**Comment by MrColeC** [comment]
Thanks @tyau-invitae for raising this.
Thanks @mbazhlekova for fixing the schema/docs so quickly.
