### ISSUE TITLE
Add the ability to create sub-accounts

### ISSUE THREAD

**Issue by aschmid13** [newrelic/terraform-provider-newrelic#1770]
### Feature Description
Add the ability to create New Relic sub-accounts through the Terraform Provider

### Describe Alternatives
Now that the GraphQL API is available to create/update sub-accounts it would be great to be able to manage it through Terraform.

### Additional context
GraphQL API available: https://api.newrelic.com/graphiql?#query=mutation%20%7B%0A%20%20accountManagementCreateAccount%0A%7D%0A

**Comment by ChandraIragavarapu** [comment]
Thank you @aschmid13. We will prioritise it with all the other requests.

**Comment by RavitejaSurampudi** [comment]
@aschmid13 Now the [account management](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/account_management) features are available via terraform.
Closing this issues. Please raise a new issue if you have any further queries or issues.
