### ISSUE TITLE
Cloud Azure Integrations do not Apply with no Integration Blocks Defined

### ISSUE THREAD

**Issue by ironf1st** [newrelic/terraform-provider-newrelic#1772]
### Terraform Version
Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.43.3

### Affected Resource(s)
- `newrelic_cloud_azure_integrations`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl

resource "newrelic_cloud_azure_link_account" "test" {

  account_id      = <redacted>
  application_id  = <redacted>
  client_secret   = <redacted>
  subscription_id = <redacted>
  tenant_id       = <redacted>
  name            = "test integration"

resource "newrelic_cloud_azure_integrations" "test" {

  linked_account_id = newrelic_cloud_azure_link_account.test.id
  account_id             = <redacted>
}
```

### Actual Behavior
On apply terraform errors with the following:

```hcl
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to newrelic_cloud_azure_integrations.test, provider "provider[\"registry.terraform.io/newrelic/newrelic\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

If I run this on an imported integration or change an integration that has some blocks configured, it successfully applies but does not remove the firewall block and any settings configured in that Integration block.

### Expected Behavior
The Integration should have successfully applied. 

If it is not desired for us to create a `newrelic_cloud_azure_integrations` resource with no Integration blocks defined then the documentation should be updated to say that.

### Steps to Reproduce
Attempt to create a new `newrelic_cloud_azure_integrations` with no Integration blocks defined.

**Comment by mbazhlekova** [comment]
@ironf1st This is a bug on updating the Firewalls integration. I opened a PR to fix it.

**Comment by ironf1st** [comment]
Great thanks @mbazhlekova
