### ISSUE TITLE
Undocumented Azure Integrations Metrics Polling Minimum

### ISSUE THREAD

**Issue by ironf1st** [newrelic/terraform-provider-newrelic#1776]
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
Terraform v1.1.9
on darwin_amd64
provider registry.terraform.io/newrelic/newrelic v2.43.4

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_cloud_azure_integrations`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
```hcl
resource "newrelic_cloud_azure_link_account" "test" {

  account_id      = <redacted>
  application_id  = <redacted>
  client_secret   = <redacted>
  subscription_id = <redacted>
  tenant_id       = <redacted>
  name            = "test integration"

resource "newrelic_cloud_azure_integrations" "test" {

  linked_account_id = newrelic_cloud_azure_link_account.test.id
  account_id             = <redacted>

  storage {
    metrics_polling_interval = 300
  }

  virtual_networks {
    metrics_polling_interval = 300
  }
}
```

### Actual Behavior
Terraform errors on apply:
`Error: ERR_INVALID_DATA Validation failed: Metrics polling interval must be greater than 900`

Then on a followup plan, the storage and virtual_networks metrics show that the `metrics_polling_interval` has changed outside of terraform:
```hcl
  # newrelic_cloud_azure_integrations.test has changed
  ~ resource "newrelic_cloud_azure_integrations" "test" {
        id                = <redacted>
        # (2 unchanged attributes hidden)

      ~ storage {
          ~ metrics_polling_interval = 300 -> 900
            # (1 unchanged attribute hidden)
        }


      ~ virtual_networks {
          ~ metrics_polling_interval = 300 -> 900
            # (1 unchanged attribute hidden)
        }
```

### Expected Behavior
Terraform to error with a less generic error and for the resource's documentation to give more information about the limits on `metrics_polling_interval`.

Based on my testing `storage` and `virtual_networks` have a metrics_polling_interval minimum of 900 seconds and `cost_management` has a metrics_polling_interval minimum of 3600 seconds. The rest of the metrics all have a minimum metrics_polling_interval of 300 seconds. This would be very helpful to have documented.

**Comment by sandeepkumar-kagitha** [comment]
@ironf1st Thanks for your feedback. We will look into it on priority basis.

**Comment by kidk** [comment]
@sandeepkumar-kagitha has made some improvements: https://github.com/newrelic/terraform-provider-newrelic/pull/1889 Hopefully this will improve the experience @ironf1st. let us know if you have any other feedback. It's greatly appreciated.
