### ISSUE TITLE
Workload import requires workload id which is deprecated

### ISSUE THREAD

**Issue by jsbnr** [newrelic/terraform-provider-newrelic#1784]
Importing a workload requires thee workload ID as well as the GUID, e.g:

`terraform import newrelic_workload.foo 12345678:1456:MjUyMDUyOHxBUE18QVBRTElDQVRJT058MjE1MDM3Nzk1z`

However, the workload ID is not used and it is not visible in New Relic via the UI or the GraphQL entity search schema. This makes it very difficult to find. (It can be discoved by base64 decoding the url paramter!)

It seems workload ID is no longer relevant, can it be removed as a  requirement from the provider import?

**Comment by sandeepkumar-kagitha** [comment]
@jsbnr Thanks for addressing the issue, we will look into the issue.

**Comment by kidk** [comment]
Similar to #817 

We will track the work there.
