### ISSUE TITLE
Newrelic APM Alert Condition Not working as expected

### ISSUE THREAD

**Issue by rajaramsurimenu2011** [newrelic/terraform-provider-newrelic#1789]
Hi ,

I will be using same alert condition as provided in example for apm alert configuration. But everytime I am hitting an error 

 "msg": "Failed to initialize Terraform modules:\r\n\u001b[31m\n\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mArgument or block definition required\u001b[0m\n\n\u001b[0mOn ../modules/alerts/main.tf line 136: An argument or block definition is\nrequired here.\n\u001b[0m\u001b[0m\n\u001b[31m\n\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mArgument or block definition required\u001b[0m\n\n\u001b[0mOn ../modules/alerts/main.tf line 136: An argument or block definition is\nrequired here.\n\u001b[0m\u001b[0m\n"
}

Example I am using is - https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_condition

can someone please help

Thank you

**Comment by shiva-bandari** [comment]
Hi @rajaramsurimenu2011, 
Thanks for addressing the issue, we will look into it.

**Comment by shiva-bandari** [comment]
Hi @rajaramsurimenu2011 ,
The error says that you are missing the arguments/attribute required for the resource.
Could you provide us your alert condition code block to see which attributes you are currently using.

**Comment by rajaramsurimenu2011** [comment]
resource "newrelic_alert_policy" "alert_policy" {
  name                = var.alert_policy_name
  incident_preference = var.incident_preference
}
data "newrelic_application" "app" {
  name = "raj- Platform"
  type = "APPLICATION"
  domain = "APM"
}

# Creates apm metric alert conditions under the alert policy
resource "newrelic_alert_condition" "apm_alert_condition" {
  for_each = var.apm_conditions
  policy_id             = newrelic_alert_policy.alert_policy.id
  name                  = each.value.name
  type                  = each.value.type
  entities              = [data.newrelic_alert_condition.app.application_id]
  enabled               = each.value.enabled
  metric                = each.value.metric
  runbook_url           = each.value.runbook_url
  condition_scope       = each.value.condition_scope
   term {
        duration           = each.value.term.duration
        operator           = each.value.term.operator
        priority           = each.value.term.priority
        threshold          = each.value.term.threshold
        time_function      = each.value.term.time_function
        }
}

**Comment by rajaramsurimenu2011** [comment]
apm_conditions:
  ##### Apdex Alerts
  - alertkey: apdexShortWindow
    name: "Apdex ( Short Window )"
    type: "apm_app_metric"
    metric: "apdex"
    runbook_url: "https://www.example.com"
    condition_scope: "application"
    term:
        duration:      5
        operator: "below"
        priority: "critical"
        threshold: "0.85"
        time_function: "all"

**Comment by kidk** [comment]
This seems to be a syntax error `Argument or block definition required`, and not an issue with our provider. 

From what I can tell the code that you posted is correct, but it could be you have some hidden character somewhere, or you're missing quotes around a variable. I'd check around the line where you get the error.
