### ISSUE TITLE
Support for AI Workflows

### ISSUE THREAD

**Issue by mmattos-newrelic** [newrelic/terraform-provider-newrelic#1790]
### Feature Description
AI Workflows is a very strategic feature for large environments, with a lot of rules and peculiarities.
Because of that, it makes sense to have this feature here.

### Describe Alternatives
No alternative solutions

### Additional context
I'm filling this issue on behalf of a New Relic customer (NuBank Brazil)

**Comment by kidk** [comment]
At the moment we can't add these API's as they are still only available internally to New Relic. The team responsible for these will tackle the work in the summer, so we should see movement soon. We will update this ticket once we know more.

**Comment by alanbort** [comment]
Will this include `destinations` as well?

**Comment by bkalcho** [comment]
> Will this include `destinations` as well?

Also interested in `destinations`.

**Comment by kidk** [comment]
Looks like destinations will be included. The team is currently working on this, so expect updates soon.
