### ISSUE TITLE
Inconsistent "Not Found" Errors When Creating Service Level Indicators

### ISSUE THREAD

**Issue by usfdmiller** [newrelic/terraform-provider-newrelic#1792]
I was asked to open an issue here by New Relic support.  If it helps for reference, the support case is #00040088.  Please let me know if this isn't actually the appropriate place for this issue.  

### Terraform Version
The Terraform version we are currently running is v1.1.5.

### Affected Resource(s)
- `newrelic_service_level`

### Terraform Configuration
```hcl
terraform {
  backend "s3" {
    region      = "us-west-2"
  }
  required_providers {
    aws = {
      source    = "hashicorp/aws"
      version   = "4.12.0"
    }
    newrelic = {
      source    = "newrelic/newrelic"
      version   = "2.43.4"
    }
  }
}

provider "newrelic" {
  region = "US"
  account_id = var.account_id
}

locals {
  entities = csvdecode(file("${path.module}/slo-entities.csv"))
}

resource "newrelic_service_level" "apm_slo_success" {
  for_each = { for entity in local.entities: entity.name => entity }
  
  guid = each.value.guid
  name = "${each.value.name} - Success"

  events {
    account_id = var.account_id
    valid_events {
      from = "Transaction"
      where = join(" AND ", compact([
        "entityGuid = '${each.value.guid}'", 
        each.value.endpoint != "" ? "request.uri LIKE '${each.value.endpoint}'" : ""
      ]))
    }
    bad_events {
      from = "TransactionError"
      where = join(" AND ", compact([
        "entityGuid = '${each.value.guid}'",
        "error.expected IS FALSE",
        each.value.endpoint != "" ? "request.uri LIKE '${each.value.endpoint}'" : ""
      ]))
    }
  }

  objective {
    target = each.value.success_target
    time_window {
      rolling {
        count = 7
        unit = "DAY"
      }
    }
  }
}

resource "newrelic_service_level" "apm_slo_latency" {
  for_each = { for entity in local.entities: entity.name => entity }
  
  guid = each.value.guid
  name = "${each.value.name} - Latency"

  events {
    account_id = var.account_id
    valid_events {
      from = "Transaction"
      where = join(" AND ", compact([
        "entityGuid = '${each.value.guid}'",
        "(transactionType='Web')",
        each.value.endpoint != "" ? "request.uri LIKE '${each.value.endpoint}'" : ""
      ]))
    }
    good_events {
      from = "Transaction"
      where = join(" AND ", compact([
        "entityGuid = '${each.value.guid}'",
        "(transactionType='Web')",
        "duration < ${each.value.latency_duration}",
        each.value.endpoint != "" ? "request.uri LIKE '${each.value.endpoint}'" : ""
      ]))
    }
  }

  objective {
    target = each.value.latency_target
    time_window {
      rolling {
        count = 7
        unit = "DAY"
      }
    }
  }
}
```

### Actual Behavior
Out of 50 service level indicators being created, on the most recent run 2 failed with the following error -

> SLI with id=[account id]:[sli id]:[entity guid] not found.

However, I can find these service level indicators in the New Relic portal, as well as query them successfully via the GraphQL API.  Keep in mind the number of failures is highly variable, and previous runs have seen up to 15 errors, it just depends on (what I'm assuming to be) how saturated New Relic's back end is at the time.

### Expected Behavior
I would expect if a service level indicator is _actually_ created without an error, viewable in the website and queryable through the API, the New Relic provider would not throw an error.  

### Steps to Reproduce
Run `terraform apply` against a configuration containing multiple service level indicator resources.  This is a really inconsistent error, but I suspect the more service level indicators being created, the higher chance of seeing failures.  

### Debug Output
My employer was not comfortable with the full log output being made publicly accessible prior to security reviewing it for sensitive information, so I can't share the full debug output right now.

### Panic Output
No panic.  

### Important Factoids
My suspicion is this inconsistency results from the service level indicator not being immediately available after it is written to whatever data store New Relic is using behind the scenes.  Probably why a 2 second sleep was added between the create and read calls.

https://github.com/newrelic/terraform-provider-newrelic/blob/98363e8458047c3c2a228787115e77c20b249647/newrelic/resource_newrelic_service_level.go#L226

### References
https://support.newrelic.com/s/case-details?caseId=5008W00000ndcwuQAA

**Comment by shiva-bandari** [comment]
@usfdmiller Thanks for addressing the issue, we will look into it.

**Comment by ouranos** [comment]
I'm having the same issue with a relatively simple configuration (only 2 SLI with associated objective).

It failed on all my runs but they're present on the dashboard (and are being recreated at each apply because they're tainted)

**Comment by lucasmessinar** [comment]
Hi @usfdmiller and @ouranos,
First of all thanks for reporting the issue, a new version of the provider 2.47.1 was released yesterday addressing this issue, everything should work ok and the apply should be also be way faster.
In case of having any issue don't hesitate to reach us again.
Thanks!
