### ISSUE TITLE
How To Disable Signal Loss in case of Nested Query

### ISSUE THREAD

**Issue by NGavankar** [newrelic/terraform-provider-newrelic#1799]
Hello team 
We have received a request from one of our dev to configure Netsed NRQL Quesry via terraform. 

But the Terraform apply fails with below error : 

An unexpected error occurred: registering: NRQL query has invalid nested query: Signal loss is not enabled for nested queries. 

Same thing happens when we try to set the query from UI and do not remove "Signal is lost after:" parameter. 

Which takes us to the conclusion that we need to disable the Signal loss parameter from Terraform. 

But there is no option for achiving this. 

can you please suggest how to achieve this via Terraform. This is a blocker for one of the devs,

Query : 
FROM (SELECT rate(count(session), 5 minutes) AS sessionCount FROM PageView WHERE appName='TL pr1 DesktopWeb' FACET buildVersion) SELECT count(sessionCount) WHERE sessionCount > 100

Thank you
Nitish
### Feature Description
Way to disable the Signal Loss in case of Nested NRQL Query at Terraform level 

### Describe Alternatives
So We had to create the alert condition from the UI.

**Comment by shiva-bandari** [comment]
Hi @NGavankar, Thanks for addressing the issue. we will look into it

**Comment by baNROne** [comment]
Hi @NGavankar. Signal loss can be configured with the [expiration_duration](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#expiration_duration), [open_violation_on_expiration](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#open_violation_on_expiration), and [close_violations_on_expiration](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#close_violations_on_expiration) arguments. To disable signal loss for a condition, set both `open_violation_on_expiration` and `close_violation_on_expiration` to `false`.

**Comment by NGavankar** [comment]
Hey @baNROne 
We are using the same settings but terraform apply still fail. 
DO we have any designated terraform flag to achieve this ?

**Comment by jodem** [comment]
Tested with pulumi work if you do not set expirationDuration at all (and openViolationOnExpiration & closeViolationsOnExpiration to false)
