### ISSUE TITLE
On Signal Loss Configuration

### ISSUE THREAD

**Issue by jjan123** [newrelic/terraform-provider-newrelic#1805]
**Terraform Version**
Terraform required_version = "~> 1.0.6"
required_providers source  = "hashicorp/local" version = ">= 2.1.0"

**Affected Resource(s)**
newrelic_nrql_alert_condition

**Actual Behavior**
I can't find in the documentation (https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition)  on how to set the following signal loss with terraform.
1. check the Open new "lost signal" violation
2. un-check the Close all current open violations 
upon googling, turned out that it's not supported as per the link below? 
https://discuss.newrelic.com/t/loss-of-signal-with-terraform/100596/2

would like to perform the following 

![image](https://user-images.githubusercontent.com/64254300/168213833-4c225d79-1aa3-4d15-a277-7b2a4227ad61.png)

instead I got this:

![image](https://user-images.githubusercontent.com/64254300/168214294-a1699308-205b-47d2-8dc4-95db4da0c386.png)

**Expected Behavior**

I should be able to set this using terraform

![image](https://user-images.githubusercontent.com/64254300/168213881-35241120-d811-4644-8761-d205461790ea.png)

**Steps to Reproduce**

create any newrelic_nrql_alert_condition and you will always get the following configuration and seems not configurable via terraform. 

![image](https://user-images.githubusercontent.com/64254300/168214308-a63ef5cf-ac43-46cd-bf84-ddcbe3734a04.png)

**Comment by lsnetsinger** [comment]
I would also like to know how this is configured

**Comment by Fallenstedt** [comment]
You will want `fill_option` https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#fill_option

And optionally `fill_value` 
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#fill_value

Additionally, did you know that from the Condition Builder UI at New Relic, you can generate terraform code for your NRQL Alert condition? Look for this dropdown and click "Terraform". 

<img width="302" alt="Screenshot 2023-07-20 at 8 28 41 AM" src="https://github.com/newrelic/terraform-provider-newrelic/assets/13971824/005b9a1a-92c4-45c2-b846-6da5af9f4b4c">
