### ISSUE TITLE
How to create an SLO for Synthetic Check programmatically

### ISSUE THREAD

**Issue by trustthewhiterabbit** [newrelic/terraform-provider-newrelic#1808]
The terraform module for a Service Level requires an entity GUID. The terraform module for a synthetic monitor currently does not export a GUID only an id. How is it best to be able to reference the GUID of the synthetic check object?

I see I can reference the GUID for a workload (exported by the terraform resource) and use this with the SLO (and then create my query statements appropriately). Is this the best way to solve the issue?

**Comment by mbazhlekova** [comment]
Hi @trustthewhiterabbit 👋 the Synthetics resources use our legacy REST API which doesn't use GUIDs. We're currently working on migrating the resources to the new GraphQL API which will return a GUID that you can use to create Service Levels.

**Comment by kidk** [comment]
@trustthewhiterabbit and @mayureshbhardwaj  We've released V3 version of our provider which includes all of the new Synthetics features: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v3 

The GUID is now available from the synthetics resources with the `id` attribute. 

Please let us know if you have any questions. If you encounter any issues please don't hesitate to create a new ticket. 

I'll close this ticket as the work has been delivered. Feel free to continue the discussion if needed.
