### ISSUE TITLE
Please add "ignore time picker" option to dashboard

### ISSUE THREAD

**Issue by ulisse31** [newrelic/terraform-provider-newrelic#1829]
### Feature Description
via GUI, it is possible to set "ignore time picker" for most if not all the widgets. We do not have the same option for TF code.
### Describe Alternatives
in Terraform code, there is no alternative. Even when selected via the GUI, the option is reset at the next terraform run
### Additional context

![Screenshot 2022-06-01 at 11 49 04](https://user-images.githubusercontent.com/56721660/171377577-0e5d40bd-c1e5-41bf-8681-da485c69cfdb.png)

**Comment by kidk** [comment]
This has been added in our latest release: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#nested-widget-blocks Let us know if you experience any issues.
