### ISSUE TITLE
Add support for `log-table-widget` type widgets

### ISSUE THREAD

**Issue by alexrosenfeld10** [newrelic/terraform-provider-newrelic#1831]
### Feature Description
There is no `widget_log_table` type available in the `content` for the `newrelic_one_dashboard` resource. It'd be great if there was!

### Describe Alternatives
None. I'd love to use some generic `widget_raw` kind of component that just takes widget json outright in the interim, but it doesn't seem like that exists either.

### Additional context
Add any other context here.

**Comment by sandeepkumar-kagitha** [comment]
@alexrosenfeld10  Thanks for reporting the issue. We will look into it .

**Comment by sandeepkumar-kagitha** [comment]
@alexrosenfeld10  Thanks for reporting the issue. We will look into it .

**Comment by alexrosenfeld10** [comment]
Thanks @sandeepkumar-kagitha . I'm happy to brush up the two PRs I opened up for this (with New Relic's help / guidance). I'm also happy to hand them off to someone else to take over, and close them 😄

**Comment by sandeepkumar-kagitha** [comment]
@alexrosenfeld10 We appreciate for your contribution and will review your PR's ASAP.

**Comment by alexrosenfeld10** [comment]
Thanks for merging my PR and closing this issue. @mbazhlekova when can I expect a new release to be published?
