### ISSUE TITLE
NRQL Dashboard issue with terraform deployment

### ISSUE THREAD

**Issue by dewshannisitha** [newrelic/terraform-provider-newrelic#1837]
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/92777656/172415135-e0217655-8299-410e-b429-b6f9efa85d5d.png">

Hi all,

can you please guide me on how to fix this issue,

error module - platform overview=main.tf file

resource "newrelic_one_dashboard" "platform_overview" {
  name = "Platform Overview"
  permissions = "public_read_only"

  dynamic "page" {
    for_each = var.platform_details
    content {
      name = page.value["platform_name_prefix"]

       # row 1
      # widget_markdown {
      #   title = "Title"
      #   row    = 1
      #   column = 1
      #   width  = 12
      #   height = 1

      #   text = "${page.value["platform_name_prefix"]}"
      # }
      widget_line {
        title = "Load Balancer Active Requests"
        row    = 1
        column = 1
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT average(aws.applicationelb.ActiveConnectionCount) FROM Metric where aws.accountId = '${page.value["account_id"]}' FACET aws.applicationelb.LoadBalancer  SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
      }
      widget_area {
        title = "Bet Requests Per Minute"
        row    = 1
        column = 3
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT rate(count(*), 1 minute) FROM Transaction WHERE appName = '${page.value["platform_name_prefix"]}-api-app'  and transactionType = 'Web' and request.uri = '/api/v2/bets' FACET request.uri TIMESERIES 1 minute"
        }
      }
      widget_line {
        title = "SQS Messages Visable"
        row    = 1
        column = 5
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT max(`aws.sqs.ApproximateNumberOfMessagesVisible`) FROM Metric where aws.accountId = '${page.value["account_id"]}' facet aws.sqs.QueueName SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
      }
      widget_line {
        title = "RDS DB % CPU Utilisation"
        row    = 1
        column = 7
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT max(`aws.rds.CPUUtilization`) FROM Metric where aws.accountId = '${page.value["account_id"]}' and aws.rds.DbClusterIdentifier NOT LIKE '%replication%' facet aws.rds.DbClusterIdentifier  SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
      }
      widget_table {
        title = "Beanstalk Queues with messages > 60 seconds"
        row    = 1
        column = 9
        width  = 4
        height = 5
        nrql_query {
          query      = "SELECT latest(`json.logs.ready_age`) as 'Ready Age (Seconds)', latest(`json.logs.current-jobs-ready`) as 'Ready Jobs' FROM Log WHERE `app_name` = 'queue' AND `platform_name` = '${page.value["platform_name_prefix"]}' AND `json.logs.ready_age` >  60 and json.logs.name != 'default' and json.logs.name NOT LIKE '%report-data%' SINCE 2 minutes ago UNTIL NOW  FACET json.logs.name as 'Queue Name' ORDER BY json.logs.ready_age DESC LIMIT 1000"
        }
      }
      widget_line {
        title = "Load Balancer Error Rates"
        row    = 2
        column = 1
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT max(aws.applicationelb.HTTPCode_Target_4XX_Count), max(aws.applicationelb.HTTPCode_ELB_5XX_Count) FROM Metric where aws.accountId = '${page.value["account_id"]}' FACET aws.applicationelb.LoadBalancer  SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
      }
      widget_area {
        title = "% Application Errors"
        row    = 2
        column = 3
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT (count(apm.service.error.count) / count(apm.service.transaction.duration) * 100) as 'Error rate' FROM Metric WHERE appName LIKE '${page.value["platform_name_prefix"]}%' SINCE 900 seconds AGO  TIMESERIES 1 minute FACET appName"
        }
      }
      widget_line {
        title = "SQS age of oldest message (seconds)"
        row    = 2
        column = 5
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT max(aws.sqs.ApproximateAgeOfOldestMessage) FROM Metric where aws.accountId = '${page.value["account_id"]}' and aws.sqs.QueueName ='platform-api-bet-resulting.fifo' SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
      }
      widget_line {
        title = "RDS DB Latency (ms)"
        row    = 2
        column = 7
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT max(`aws.rds.SelectLatency`), max(`aws.rds.InsertLatency`) FROM Metric where aws.accountId = '${page.value["account_id"]}' and aws.rds.DbClusterIdentifier NOT LIKE '%replication%' facet aws.rds.DbClusterIdentifier SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
      }

      widget_line {
        title = "ASG % Utilisation"
        row    = 3
        column = 1
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT max(aws.ec2.CPUUtilization) FROM Metric where aws.accountId = '${page.value["account_id"]}' FACET aws.ec2.AutoScalingGroupName SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
      }
      widget_line {
        title = "Worker % Utilisation"
        row    = 3
        column = 3
        width  = 2
        height = 2
        nrql_query {
          query      = "select max(host.memoryUsedPercent), max(host.cpuPercent) FROM Metric where apmApplicationNames like '%${page.value["platform_name_prefix"]}%wor%' FACET apmApplicationNames TIMESERIES 1 minute"
        }
      }
       widget_line {
        title = "ECS Service % Utilisation"
        row    = 3
        column = 5
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT max(`aws.ecs.CPUUtilization.byService`), max(`aws.ecs.MemoryUtilization.byService`) FROM Metric where aws.accountId = '${page.value["account_id"]}' and aws.ecs.ServiceName = 'bet-resulting-worker' SINCE  30 MINUTES AGO TIMESERIES 1 minute"
        }
      }

      widget_line {
        title = "RDS Serverless Capacity Units"
        row    = 3
        column = 7
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT max(`aws.rds.ServerlessDatabaseCapacity`) FROM Metric where aws.accountId = '${page.value["account_id"]}' and aws.rds.DbClusterIdentifier NOT LIKE '%replication%' facet aws.rds.DbClusterIdentifier SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
      }
      widget_line {
        title = "APM Response Time"
        row    = 4
        column = 1
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT average(duration * 1000) AS 'Response time' FROM Transaction WHERE appName LIKE '${page.value["platform_name_prefix"]}-api-app' OR appName = '${page.value["platform_name_prefix"]}-risk-app' OR appName = '${page.value["platform_name_prefix"]}-ser-app' SINCE 1800 seconds AGO TIMESERIES FACET appName"
        }
      }
      widget_area {
        title = "Web transactiong time api-app (ms)"
        row    = 4
        column = 3
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT average(apm.service.overview.web * 1000) FROM Metric FACET segmentName WHERE appName LIKE '${page.value["platform_name_prefix"]}-api-app%' TIMESERIES"
        }
      }

      widget_line {
        title = "ECS task count"
        row    = 4
        column = 5
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT max(`aws.usage.ResourceCount`) FROM Metric where aws.accountId = '${page.value["account_id"]}' and aws.usage.Service = 'Fargate' until 30 minutes ago TIMESERIES 1 minute"
        }
      }
      widget_line {
        title = "Redis Cache % Utilisation"
        row    = 4
        column = 7
        width  = 2
        height = 2
        nrql_query {
          query      = "SELECT max(`aws.elasticache.DatabaseMemoryUsagePercentage`) FROM Metric where aws.accountId = '${tostring(page.value["account_id"])}' SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
        nrql_query {
          query      = "SELECT max(`aws.elasticache.CPUUtilization`) FROM Metric where aws.accountId = '${page.value["account_id"]}' SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
        nrql_query {
          query      = "SELECT max(`aws.elasticache.CacheHitRate`) FROM Metric where aws.accountId = '${page.value["account_id"]}' SINCE 30 MINUTES AGO TIMESERIES 1 minute"
        }
      }

      widget_table {
        title = "ECS Task error Logs"
        row    = 4
        column = 9
        width  = 4
        height = 3
        nrql_query {
          query      = "SELECT container_name, message From Log where  ecs_task_arn LIKE '%${page.value["account_id"]}%' and message LIKE '%production.ERROR%' LIMIT 2000"
        }
      }
    }
  }
}

Thanks
Nisitha Dewshan

**Comment by kidk** [comment]
It seems you've lost permissions to edit that specific dashboard. I would check if you still have access to the account in New Relic.

**Comment by dewshannisitha** [comment]
Hi kidk,

thank you very much, issue is sorted.
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/92777656/172524671-172fd440-df48-4ecd-86f1-6cb6788dc947.png">
facing new issue

**Comment by sandeepkumar-kagitha** [comment]
It shows that you are exceeding the number of pages in a dashboard. You can use a maximum of 20 Pages in a dashboard. Please find information as mentioned in our docs URL: https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/dashboards-api/#limits

**Comment by dewshannisitha** [comment]
We can't use a different dashboard or can we integrate same dashboard?

**Comment by dewshannisitha** [comment]
![image](https://user-images.githubusercontent.com/92777656/172765709-396188cd-a5a3-4da4-8098-59126982de12.png)
![image](https://user-images.githubusercontent.com/92777656/172765732-407f2868-5dd4-4b4d-bb96-8f525ff675c0.png)

**Comment by dewshannisitha** [comment]
@kidk @sandeepkumar-kagitha Hi,

**Comment by kidk** [comment]
Did you get it working @dewshannisitha?

**Comment by dewshannisitha** [comment]
@kidk not working mate, max pages 20

**Comment by mbazhlekova** [comment]
@dewshannisitha 20 pages is a limitation from the dashboards API. We don't have any control over it from the Terraform Provider.
