### ISSUE TITLE
Request: Add support for custom headers on SIMPLE synthetic monitor

### ISSUE THREAD

**Issue by chauncey-garrett** [newrelic/terraform-provider-newrelic#1843]
There's an option in the GUI to add _Custom headers_ when creating a `Ping` synthetic monitor but this option doesn't appear to exist under the `SIMPLE` type in `newrelic_synthetics_monitor` (which appears to be analogous to `Ping`). Please add this option for parity.

**Comment by mbazhlekova** [comment]
@chauncey-garrett We're working on it currently! It will be available in v3.0.0 of the Terraform Provider coming this summer.

**Comment by kidk** [comment]
@chauncey-garrett We've released V3 version of our provider which includes all of the new Synthetics features: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v3 

Please let us know if you have any questions. If you encounter any issues please don't hesitate to create a new ticket. 

I'll close this ticket as the work has been delivered. Feel free to continue the discussion if needed.
