### ISSUE TITLE
Allow specifying runtime/Node.js version for Synthetics Scripted API

### ISSUE THREAD

**Issue by MartinSMadsen** [newrelic/terraform-provider-newrelic#1861]
### Feature Description
I would like to be able to specify the desired version of the runtime (that is, Node.js) used for Synthetics Scripted API, the same way I can if creating the monitor in the interface.

### Describe Alternatives
Alternatively, version 16 could be used by default instead of version 10 (legacy).

**Comment by MartinSMadsen** [comment]
Not sure if this will be solved by #1453

**Comment by mbazhlekova** [comment]
Hi @MartinSMadsen 👋 we're currently working on #1453 and when we complete the API migration the new Synthetics Monitor resource will support setting different runtimes. We expect to have the release out this summer.

**Comment by MartinSMadsen** [comment]
Thanks, @louhnmn!
