### ISSUE TITLE
Allow specifying browser runtime environment for Synthetics Scripted Browser 

### ISSUE THREAD

**Issue by PhilippTreupel** [newrelic/terraform-provider-newrelic#1871]
### Feature Description
Please add a parameter  to the resource `newrelic_synthetics_monitor ` for defining the browser runtime environment for the monitor type `SCRIPT_BROWSER`.  Currently you can select `Chrome 100 `or `Chrome 72 (Legacy) ` via the New Relic UI.

**Comment by bearfoot** [comment]
Hello, this highly expected since my scripts are only compatible with Chrome 100, I need manual manipulation on each terraform apply which is quite annoying.

**Comment by badeball** [comment]
Seconded. A new runtime has been sought-after for a while and it's frustrating to await adaptation due unrelated refactoring without any ETA («this summer» is unfortunately meaningless for practical purposes).

**Comment by Emmet-McGuire** [comment]
I am also eagerly awaiting an update.  Thanks in advance.

**Comment by thomazfohr** [comment]
Runtime configuration is now available using [newrelic_synthetics_script_monitor](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_script_monitor).

**Comment by kidk** [comment]
Well spotted @thomazfohr The V3 release is indeed out which supports the latest runtime. You can find a migration guide here: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v3 

We have some documentation changes in pipeline which should be released this week. I think this might be relevant for whoever wants to start playing with it.

```
  runtime_type_version                    = "100"
  runtime_type                            = "CHROME_BROWSER"
  script_language                         = "JAVASCRIPT"
```

I'm going to close this ticket as the functionality has been released, but feel free to continue the discussion.
