### ISSUE TITLE
Dashboard - error 500 on update 

### ISSUE THREAD

**Issue by Benoit382** [newrelic/terraform-provider-newrelic#1877]
Hi
I try to update my dashboard, i have an error : 
Error: maximum retries reached: Operation on dashboard entity failed with guid:*** with cause: Error 500 calling Insights with url https://insights-api.service.eu.nr-ops.net/rpm_api/1/accounts/XXXXXX/collections: {"status":"500","error":"Internal Server Error"}

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [ ] Any related [log output](#debug-output)

### Terraform Version
Terraform v1.2.2

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_one_dashboard_raw`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
terraform {
  required_version = ">= 1"

  // provider versions are locked because it's a PITA to have to run the following command after each update:
  // terraform providers lock -platform=darwin_amd64 -platform=linux_amd64 -platform=windows_amd64
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.45.0"
    }
  }
}

```

### Actual Behavior
The dashboard is not updated
Error: maximum retries reached: Operation on dashboard entity failed with guid:*** with cause: Error 500 calling Insights with url https://insights-api.service.eu.nr-ops.net/rpm_api/1/accounts/XXXXXX/collections: {"status":"500","error":"Internal Server Error"}

### Expected Behavior
The dashboard is updated

### Steps to Reproduce
I send a curl Damien Cascalès on slack https://bedrockstreaming.slack.com/files/T108ZKPMF/F03LBKCP2JX

**Comment by kidk** [comment]
Thanks @Benoit382 This looks like an internal API error. I'll escalate with the team that owns this API and see what they say.

**Comment by NSSPKrishna** [comment]
Hi @Benoit382, the issue has been fixed. Please try it again.

**Comment by NSSPKrishna** [comment]
We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.

**Comment by StrahinjaDucic** [comment]
This happened to me today, I just got something like this `Error 502 calling Insights with url [https://insights-api.service.nr-ops.net/rpm_api/1/accounts/***/collections](https://insights-api.service.nr-ops.net/rpm_api/1/accounts/***/collections:)`. What can be solution, thanks? @NSSPKrishna @kidk
