### ISSUE TITLE
:warning: Duplicate name resource

### ISSUE THREAD

**Issue by daviddsp** [newrelic/terraform-provider-newrelic#1880]
Hi there,

I have problems with the resource because accept add the same name more many times and not validate if the resource is exist with the same name. 

I have idea how can resolver this fix?

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [] Any related [log output](#debug-output)

### Terraform Version
`0.14.11`

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alert_policy`
- `newrelic_alert_channel`
- `newrelic_alert_condition`
- `data.newrelic_alert_policy`
- `data.newrelic_alert_channel`
- `data.newrelic_alert_condition`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      #version = "<= 2.41.1"
    }
  }
  required_version = ">= 0.13"
}

```

### Actual Behavior
What actually happened?
I have resources duplicate

### Expected Behavior
What should have happened?
Show on error because exist on resource with same name

**Comment by kidk** [comment]
Name is not a unique identifier within New Relic so Terraform does not check if resources with existing name exist. Internally we store the UUID or ID of resources to validate if we need to create or update. If you want to use existing elements within New Relic you should import those into Terraform.

For example for existing alert policies you can use the import command in the documentation: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_policy#import

Closing this for now as this is expected behaviour. Feel free to continue the conversation.
