### ISSUE TITLE
newrelic_one_dashboard ignore_time_range not working

### ISSUE THREAD

**Issue by klrsnw** [newrelic/terraform-provider-newrelic#1891]
Hello,
I have tried including the **_ignore_time_range_** argument into my terraform widget - sample below

    widget_billboard {
      title = "Average DAILY usage month to date - GB's"
      column = 9
      row = 1
      height = 1
      width = 4
      ignore_time_range = true

      nrql_query {
        account_id = "123456"
        query       = "FROM NrConsumption SELECT rate(sum(GigabytesIngested), 1 day) AS 'Average DAILY Ingestion MTD - GBs', sum(GigabytesIngested) AS 'MTD TOTAL Ingestion - GBs' WHERE productLine = 'DataPlatform' LIMIT MAX SINCE this month"
      }
    }
-----
The above setting is disabled after applying the change above to the dashboard with no errors thrown.
Manually editing the dashboard and enabling the above feature achieves the outcome required until the next dashboard change.

Is there another step that I am missing or does this feature perhaps not work with billboards?

Some additional information - I have tried deleting and recreating the dashboard, the dashboard ALWAYS ends up with the above setting disabled.  If I manually over-ride the setting on the dashboard, and then reapply the terraform script, terraform then disables the setting again.

If I run the "terraform plan" command right after the successful apply comment, the following is shown as never completing (ie no matter how many times I "apply" the following is reported as incomplete).
          ~ widget_billboard {
                id                = "some id was here"
              ~ ignore_time_range = false -> true
                # (5 unchanged attributes hidden)

                # (1 unchanged block hidden)
            }

If I manually enable the setting on the dashboard and reapply the terraform script with the above setting commented out, the setting is disabled by terraform and the changed recorded as following

                id                = "some id was here"
              - ignore_time_range = true -> null
                # (5 unchanged attributes hidden)

                # (1 unchanged block hidden)
It is interesting that the boolean value is being set to null as opposed to false - not sure if this is a clue or not.

Many thanks.

**Comment by NSSPKrishna** [comment]
This is issue has been resolved in the version 3.3.0.
