### ISSUE TITLE
newrelic_nrql_alert_condition: aggregation_method and aggregation_delay show diff when not provided

### ISSUE THREAD

**Issue by antonblr** [newrelic/terraform-provider-newrelic#1900]
### Terraform Version
```
Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.49.1
```

### Affected Resource(s)
- `newrelic_nrql_alert_condition`

### Terraform Configuration

```hcl
provider "newrelic" {
  account_id    = var.account_id
  admin_api_key = var.admin_api_key
  api_key       = var.api_key
  region        = var.region
}
```
Example:
```hcl
resource "newrelic_nrql_alert_condition" "max_critical" {
  policy_id                    = var.policy_id_critical
  type                         = "static"
  name                         = "Test alert"
  description                  = "Test alert description"
  runbook_url                  = "tbd"
  enabled                      = true
  violation_time_limit_seconds = 3600

  nrql {
    query = local.running_node_count
  }

  critical {
    operator              = "equals"
    threshold             = var.max_node_count
    threshold_duration    = 300
    threshold_occurrences = "ALL"
  }
}
```

### Actual Behavior
Subsequent terraform plans will show diff for `aggregation_delay` and `aggregation_method`, if they are not provided.

### Expected Behavior
Should not show diff for `aggregation_delay` and `aggregation_method` if they are not provided. Instead, use their defaults.

### Steps to Reproduce
1. Create a resource as provided above, without deprecated `evaluation_offset`.
1. `terraform apply`
2. `terraform plan`
3.  Observe the following diff:
```hcl
Terraform will perform the following actions:

  # newrelic_nrql_alert_condition.max_critical will be updated in-place
  ~ resource "newrelic_nrql_alert_condition" "max_critical" {
      - aggregation_delay              = "120" -> null
      - aggregation_method             = "event_flow" -> null
        id                             = "1024960:26935418"
        name                           = "Test alert"
        # (16 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```

### Workaround
Set these attributes with default values:
```hcl
aggregation_delay  = 120
aggregation_method = "event_flow" 
```

### References
Same issue and fix attempt from the past:
- https://github.com/newrelic/terraform-provider-newrelic/issues/1544
- https://github.com/newrelic/terraform-provider-newrelic/pull/1574

**Comment by antonblr** [comment]
Seems to be a regression after https://github.com/newrelic/terraform-provider-newrelic/pull/1620

**Comment by kidk** [comment]
Thanks for the PR @antonblr I've asked the alert team to take a look.
