### ISSUE TITLE
`newrelic_alert_channel` creation giving an `Error: POST https://api.newrelic.com/v2/alerts_channel.json giving up after 4 attempts()`

### ISSUE THREAD

**Issue by abudri** [newrelic/terraform-provider-newrelic#1912]
Hello,

This is related to a support case I already have open(Steve Miller of NR is aware of the case).  I'm trying to create a `newrelic_alert_channel` resource ([doc](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_channel)) and am getting the following error since yesterday:

```
 `Error: POST https://api.newrelic.com/v2/alerts_channel.json giving up after 4 attempts()`
```

This started yesterday.

I was made aware of an [announcement](https://discuss.newrelic.com/t/plan-to-upgrade-alert-notification-channels-to-workflows-and-destinations/188205) starting in August 2022 that there would be a transition from the alert channel to workflows/destinations, however I was told our account should NOT have been transitioned at this time - the first day of the month at that.  Additionally, the announcement appeared to indicate that the `newrelic_alert_channel` should be available still even through June of 2023:

> current APIs for Notification Channels and Channels-to-Policy will remain available through June, 2023

So of course, I'm not prepared for this error (Didn't notice an email announcement or anyone announcing it in June).

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)

`providers.tf`:

```terraform
provider "newrelic" {
  account_id = *redacted*
  api_key = *redacted*
}
```

`versions.tf`:

```terraform
terraform {
  required_version = "~> 1.0.8"
  
  required_providers  {
    ...
    newrelic = {
      source = "newrelic/newrelic"
      version = "~> 2.21.1"
    }
  }
}
```

- [x] A list of [affected resources](#affected-resources) and/or data sources

Our `newrelic_alert_channel` can not be created.

- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)

```terraform
resource "newrelic_alert_channel" "redacted" {
  name = "redacted"
  type = "webhook"

  config {
    base_url  = "*redacted*"
    payload_type = "application/json"
    payload_string = templatefile("*redacted*", {})
  }
}
```

Keep in mind, nothing has change in our configuration be it versions, providers, or the configuration for the above resource in a long time. So the error appears to be something changing on New Relic's end.

- [x] Description of the [current behavior](#actual-behavior) (the bug)

Described above already, upon the `terraform apply`, we get the error,

```
Error: POST https://api.newrelic.com/v2/alerts_channel.json giving up after 4 attempts()
```

then just a description of the resource and no other error details, then a `script returned exit code ` after `Releasing state lock.`.  So the only error is the `POST` one above.

- [x] Description of the [expected behavior](#expected-behavior)

Resource has always created for us. It does a destroy and create each terraform apply. I want to fix that and may use `file()` instead of `templatefile()`, another engineer said that might prevent the needless destroy and create each time we `terraform apply`.  Nothing has changed in the resource in our payload or code, but it appears TF detects a change somewhere on its end.

- [x] Any related [log output](#debug-output)

Shared above, that's all we have.

### Terraform Version

While our configuration has `version = "~> 2.21.1"`, our pipeline actually Installs `v2.40.0`, we may need to have a lock file to lock the version we want.  Regardless, the latest version or a later version should not have a bug, and this appears to be a bug, if the alert channel resource is to be available via api and on the console through June 2023.

from pipeline output:

```
Installed newrelic/newrelic v2.40.0 (signed by HashiCorp partner, key ID *redacted*)
```

### Affected Resource(s)
- `newrelic_alert_channel`

### Terraform Configuration
Shared above earlier, our `versions.tf` and `providers.tf`

### Actual Behavior
Described earlier.

### Expected Behavior
Our resource always creates.  The configuration and resource and payload have not changed in a long time.  Thus, it appears to be an issue on New Relic's end.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

Have our above configuration, and attempt to `terraform plan` for a resource similar to ours, a `newrelic_alert_channel`.

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Not that I am aware.

### References
I did search this issue in the past, and it appears that the conclusion was that this was an issue on NR's end and the API, and got escalated to the alert API team.

https://github.com/newrelic/terraform-provider-newrelic/issues/1739#issuecomment-1087619652

**Comment by HafnerJAE** [comment]
We are also seeing this using provider version 2.49.1.  
Exact same behavior, also began on Monday.

**Comment by abudri** [comment]
I was able to create the resource yesterday. I also put in a `lifecycle` `ignore_changes` `[content]` attribute to prevent the regular destroy/create behavior the alert channel had, apparently due to it having a payload.

Perhaps people can try now.  Haven't otherwise heard official word or fix on this.

**Comment by mbazhlekova** [comment]
@abudri @HafnerJAE This was related to an issue in the alerts API. Should be resolved now. Can you confirm that it's working?

**Comment by HafnerJAE** [comment]
> @abudri @HafnerJAE This was related to an issue in the alerts API. Should be resolved now. Can you confirm that it's working?

Looks like we're good to go. Thanks for the quick fix!

**Comment by abudri** [comment]
Thanks!

**Comment by aaasenbanjo** [comment]
how was this resolved as I am currently having the same issue

**Comment by kidk** [comment]
I'd reach out to support if you still have this issue. This is not a problem with Terraform but with the alerting API's.
