### ISSUE TITLE
Add support for nested sub-queries

### ISSUE THREAD

**Issue by leonardo-nickel** [newrelic/terraform-provider-newrelic#1913]
### Feature Description
Add support for nested sub-queries when building New Relic Alerts using NRQL syntax.

### Describe Alternatives
No alternatives. I'd like to be able to have nested subqueries when building my New Relic alerts using NRQL syntax.

### Additional context
When I run `terraform apply` in a New Relic alert configuration file which I've added a query with a nested sub-query I get the following error message:

```
Error: registering: Unable to parse NRQL query: Validation failed. Error at line 1 position 172, SELECT is not permitted here: BAD_USER_INPUT
```

This is because my query contains a nested subquery e.g.: `SELECT count(*) FROM Transaction WHERE duration > (SELECT average(duration) FROM Transaction)`

New Relic alerts already provide support for this feature as shown [here](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/subqueries-in-nrql/) hence this feature request is to add support on this provider library and have parity on both sides of the flow.

Additionally I'm sending a screenshot that shows this nested sub-query feature on New Relic. The section highlighted in green shows the nested sub-query.
<img width="1169" alt="Screenshot 2022-08-02 at 17 54 20" src="https://user-images.githubusercontent.com/88378189/182432969-fc59da82-6bf2-49fd-b416-0fdf0025afba.png">

Thanks!

**Comment by kidk** [comment]
Hi @leonardo-nickel 

At the moment subqueries are not supported in the alerting system: https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions/#reformatting

> Subqueries are not compatible with streaming alerts because subquery execution requires multiple passes through data.

I'd suggest creating a [support](https://support.newrelic.com/s/) or [community](https://discuss.newrelic.com/) for this request. Terraform will support it once it's available. 

I'm going to close this for now as there's no action we can take. Feel free to continue the conversation if needed.
