### ISSUE TITLE
Broken documentation link at registry.terraform.io/providers/newrelic/newrelic/latest/docs

### ISSUE THREAD

**Issue by northyg** [newrelic/terraform-provider-newrelic#1914]
## Please include the following with your bug report

On this page 
[https://registry.terraform.io/providers/newrelic/newrelic/latest/docs]()  this link [https://newrelic.github.io/developer-toolkit/roadmap/]() for Roadmap is broken, site not found. 

<img width="687" alt="image" src="https://user-images.githubusercontent.com/27694443/182736429-fbb067ae-c54e-4517-b740-eda4c2988133.png">

**Comment by kidk** [comment]
We no longer have a public roadmap. We might add this again in the future, but for now we will remove the link.
