### ISSUE TITLE
Invalid NRQL query error trying to create a newrelic_workload

### ISSUE THREAD

**Issue by anandhs** [newrelic/terraform-provider-newrelic#1926]
Hi there, 

I am trying to create a workload and running into the following error

```
Error: maximum retries reached: Invalid query label.cai:catalog:tier3-team-name=Buy AND type = 'DASHBOARD', details: Provided filter: [label.cai:catalog:tier3-team-name=Buy AND type = 'DASHBOARD'] is not a valid NRQL query
```

## Expected Behavior

A new workload should be created. 

## Terraform version: 

```
terraform -v
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.49.1

```

code snippet: 

```
terraform {
  required_version = "~> 1.2"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.48"
    }
  }
}

resource "newrelic_workload" "workload" {
    name = "Buy"
    account_id = xxxxxxx
    

    entity_search_query {
        query = "label.cai:catalog:tier3-team-name=Buy"
    }

    scope_account_ids =  [xxxxxxxx]
}

```

## Steps to reproduce: 

1. `terraform init`
2. `terraform plan` - successful and as expected. 
3. `terraform apply`

## References

Looks similar to https://github.com/newrelic/terraform-provider-newrelic/issues/1416 , but the recommended suggestions of using `tag` did not work for me.

**Comment by NSSPKrishna** [comment]
Hey @anandhs,
Thanks for raising the issue, as the error says the query is invalid, can you please provide further information regarding the query used.

**Comment by shiva-bandari** [comment]
We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.
