### ISSUE TITLE
`newrelic_synthetics_multilocation_alert_condition` creation giving an `Error: 422 response returned: Could not find monitor for account.`

### ISSUE THREAD

**Issue by louhnmn** [newrelic/terraform-provider-newrelic#1929]
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/newrelic/newrelic v2.49.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_synthetics_multilocation_alert_condition`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.

`provider.tf`:

```
terraform {
  # Require Terraform version 1.0 (recommended)
  required_version = "~> 1.0"

  # Require the latest 2.x version of the New Relic provider
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
    }
  }
}

provider "newrelic" {
  account_id = var.accountId
  api_key    = var.apiKey
  region     = "EU"
}
```

alerts.tf

```
resource "newrelic_alert_policy" "ssl_certs" {
  name                = "SSL Certificates PROD"
  incident_preference = "PER_CONDITION_AND_TARGET"
}

resource "newrelic_synthetics_multilocation_alert_condition" "ssl_cond" {
  policy_id = newrelic_alert_policy.ssl_certs.id

  name                         = "SSL CDN (W/TF)"
  enabled                      = true
  violation_time_limit_seconds = "43200" #3 days

  # used a single ssl monitor guid here for testing reasons 
  entities = ["<SOME_SYNTH_MONITOR_GUID_HERE>"]

  warning { threshold = 1 }
  critical { threshold = 2 }

  depends_on = [
    newrelic_alert_policy.ssl_certs
  ]
}

```

### Actual Behavior
What actually happened?

- Running `terraform apply` results in this log messages:

```
newrelic_synthetics_multilocation_alert_condition.ssl_cdn_cond: Creating...

│ Error: 422 response returned: Could not find monitor for account.
│ 
│   with newrelic_synthetics_multilocation_alert_condition.ssl_cdn_cond,
│   on alerts.tf line 22, in resource "newrelic_synthetics_multilocation_alert_condition" "ssl_cdn_cond":
│   22: resource "newrelic_synthetics_multilocation_alert_condition" "ssl_cdn_cond" {
```
### Expected Behavior
What should have happened?

- The `multilocation_alert_condition` should have been created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

- [log output gist link](https://gist.github.com/louhnmn/f4f8a7f7920f04b1ad4e2da6c54c9b76)

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

- Not that I'm aware of.

**Comment by ryanv94** [comment]
Hi @louhnmn - I've replied to your message in the forum with a solution for you -> https://discuss.newrelic.com/t/terraform-synthetics-multilocation-alert-condition-error-422-could-not-find-monitor-for-account/188951/2

The issue for the Terraform team to look into is more about wording on the registry docs - and making them super clear in what info is required. I'll reach out to them for you.
