### ISSUE TITLE
Add a data source for alert channels of type `user`

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#193]
### Enhancement 

A Customer is looking to use Push notifications for their Alerting strategy. In order to do this, you need to  Add the user channel to the alert policy.

Looking at the terraform docs -> Resource: newrelic_alert_channel -> type - email, slack, opsgenie, pagerduty, victorops, or webhook. https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_channel#type

I don’t see type user which is shown in the UI. This request is to add the user type to terraform provider. 

## Related issues 

As previously requested in #139.

### Screen shots

<img width="972" alt="Screenshot 2020-11-25 at 14 43 33" src="https://user-images.githubusercontent.com/1395158/100267906-793e2f00-2f11-11eb-86f6-9f9fb95848f7.png">

![image1](https://user-images.githubusercontent.com/1395158/100267916-7d6a4c80-2f11-11eb-9ed6-0bc9a2857537.png)

![image2](https://user-images.githubusercontent.com/1395158/100267923-7f341000-2f11-11eb-97b5-8a4577ed7cd0.png)

**Comment by rseuchter-vw** [comment]
I believe that this request is already somewhat solved. In particular what was requested in https://github.com/newrelic/terraform-provider-newrelic/issues/139#issuecomment-537616442 is already feasible. It's undocumented and a bit cumbersome though.

But for me this worked fine:
```
# full disclosure: in my sample case the policy was imported and not created through terraform from scratch
resource "newrelic_alert_policy" "demo" {
  name                = "foo policy"
  incident_preference = "PER_CONDITION"
}

data "newrelic_alert_channel" "foomail" {
  name = "Foo Bar <foo.bar@example.com>"
}

resource "newrelic_alert_policy_channel" "notification" {
  policy_id = newrelic_alert_policy.demo.id
  channel_ids = [
    data.newrelic_alert_channel.foomail.id,
  ]
}
```

When you display the state / data source with `tf show` you can see that the channel's type actually is `user`.

What's messy is that you need to search the right _user_ channel by the full name made up from the actual name and the e-mail address as seen in the UI. It'd be cleaner and preferable to search the user channel by e-mail address only. But then again, even the underlying NR REST API appears to be using the compound field `name` and doesn't even have the e-mail address in its own field.

FYI:
```
$ tf version
Terraform v1.0.3
on windows_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.24.1
```

**Comment by emetcalf9** [comment]
Alerts Notification Channels will be going away, and will be replaced by "Destinations". More info is available here: https://discuss.newrelic.com/t/big-news-for-alerts-and-applied-intelligence/161436

Because of that, we will not be adding support for "User" type notification channels in Terraform, but the workaround posted above of using a `data` block to pull in the channel by name will allow you to link them to policies with Terraform if needed. User channels are not editable, so modifying them with Terraform is not possible and once they are correctly linked with a `data` block there is no chance of any drift unless the User is deleted.
