### ISSUE TITLE
newrelic_alert_channel data source ignores the provider's account id

### ISSUE THREAD

**Issue by ksanta-10x** [newrelic/terraform-provider-newrelic#1931]
### Terraform Version
```
terraform -v

Terraform v1.2.7
on darwin_arm64
+ provider registry.terraform.io/newrelic/newrelic v2.49.1
```

### Affected Resource(s)
- `newrelic_alert_channel` data source

Other resources and data sources that use RESTv2 APIs may be impact, too.

### Terraform Configuration
```hcl
terraform {
  backend "local" {}
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.0"
    }
  }
}

provider "newrelic" {
  account_id = "123456"  # This is ignored, and the "default" account for the API key is used
  api_key    = "NRAK-*****"
  region     = "EU"
}

data "newrelic_alert_channel" "slack" {
  name  = "Slack Alerts"
}
```

### Steps to Reproduce

1. Create two New Relic accounts. I'll call the accounts "A" and "B".
2. Create a user that has access granted for both accounts
3. Create an alert channel on account B
4. Create an API key for the user for account A
5. In the Terraform provider configuration, add `account_id = B`
6. `terraform plan` and see the error

### Actual Behavior
I get an error from Terraform because the API key does not have access to query alert channels on account A.
```
Error: 403 response returned: You do not have privileges to perform this action
```
The account id in the provider configuration is ignored.

In our case, the API key does not have access to query much in account A, so an error is returned. It is possible in other people's cases that the key DOES have access to query account A, and will silently return data from account A instead of account B.

### Expected Behavior
We expect the alerts channel data source to use the account id defined in the provider configuration to query account B.

### Debug Output
I won't include the output here, but I spotted from debug output that the "X-Account-ID" header is not added to calls from the `newrelic_alert_channel` data source - but it IS added when using the "resource".

### Panic Output
No panic produced.

### Important Factoids
These [lines of code](https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_alert_channel.go#L304-L306) that add the `X-Account-Id` header are missing from the data source.

**Comment by kidk** [comment]
Thanks for the detailed report @ksanta-10x We'll take a look

**Comment by shiva-bandari** [comment]
Hi @ksanta-10x ,

Is account B a sub account of account A ?

**Comment by ksanta-10x** [comment]
Not that I am aware of. I believe they are sibling accounts. Is there a way to check this? I browsed the NerdGraph API and couldn't spot any obvious way to get this information. We are using the "new" user management model.

**Comment by ksanta-10x** [comment]
Closed this issue as the duplicate issue was closed.
