### ISSUE TITLE
Creating a newrelic_notification_destination requires auth attribute

### ISSUE THREAD

**Issue by bkalcho** [newrelic/terraform-provider-newrelic#1938]
### Terraform Version
```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.49.1
```

### Affected Resource(s)
- `newrelic_notification_destination`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
terraform {
  required_version = "~> 1.0.0"

  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.49"
    }
  }
}
```

### Actual Behavior
When trying to create WEBHOOK type NR Destination for Microsoft Teams channel, it requests `auth` type defined, despite MS Teams does not use authentication, just a unique webhook URL.

### Expected Behavior
It should allow the creation of MS Teams NR destination without the `auth` attribute.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. add the following config to `main.tf`:
```hcl
resource "newrelic_notification_destination" "msteams" {
  name = "test"
  type = "WEBHOOK"

  properties {
    key   = "url"
    value = "<redacted>"
  }
}
```
2. `terraform apply`

**Comment by wendell-fcsa** [comment]
+1.  This is a blocking issue for me.
`
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.0"
    }
  }
  required_version = ">= 0.13"
}

resource "newrelic_notification_destination" "email_destination" {
  account_id = <account>
  name = "<name>"
  type = "EMAIL"

  property {
    key = "email"
    value = <email>
  }
}
'

**Comment by NSSPKrishna** [comment]
Hi @wendell-fcsa, thanks for raising the issue. Please use latest version (3.2.1) of [New Relic terraform provider](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs).
