### ISSUE TITLE
Can't create destinations without the auth field.

### ISSUE THREAD

**Issue by yuzujoe** [newrelic/terraform-provider-newrelic#1939]
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```shell
$ terraform -v
Terraform v1.2.7
on darwin_arm64
```

### Affected Resource(s)

- `newrelic_notification_destination`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
resource "newrelic_notification_destination" "slack" {
  name = "newrelic_notification_slack"
  type = "WEBHOOK"

  properties {
    key   = "url"
    value = "<webhook url>"
  }
}
```

### Actual Behavior
Creation fails if auth field is not set

### Expected Behavior
Successful creation of destinations without setting the auth field

### Steps to Reproduce
1. `terraform apply`

### Debug Output
https://gist.github.com/yuzujoe/dc48d43014a1281be75208078a59e246

### Panic Output
Nothing is output in `crash.log`

### Important Factoids
No, we are creating them as usual.

**Comment by yuzujoe** [comment]
Looking at the source code, it returns an error if I don’t set auth.
From the UI, it is possible to add a destination without setting auth.

[https://github.com/newrelic/terraform-provider-newrelic/blob/5847ac479b7eab7e775ad[…]0214c2f/newrelic/resource_newrelic_notifications_destination.go](https://github.com/newrelic/terraform-provider-newrelic/blob/5847ac479b7eab7e775ad6f4fdd83d4cf0214c2f/newrelic/resource_newrelic_notifications_destination.go#L74)

[https://github.com/newrelic/terraform-provider-newrelic/blob/5847ac479b7eab7e775ad[…]14c2f/newrelic/structures_newrelic_notifications_destination.go](https://github.com/newrelic/terraform-provider-newrelic/blob/5847ac479b7eab7e775ad6f4fdd83d4cf0214c2f/newrelic/structures_newrelic_notifications_destination.go#L274)

**Comment by kidk** [comment]
Confirmed with code mentioned in ticket.

**Comment by kidk** [comment]
Closing for #1938 which was created first.
