### ISSUE TITLE
Add Slack as a notification destination type

### ISSUE THREAD

**Issue by arhill05** [newrelic/terraform-provider-newrelic#1957]
### Feature Description
I would like to configure a Slack notification destination to use with the new Workflows.

### Describe Alternatives
The New Relic UI for configuring workflows and notification destinations allows Slack as a destination, but it is not documented as a supported type in the [New Relic Terraform provider docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination#type). I would love to use the same functionality in the Terraform provider that the UI provides instead of having to rely on a webhook.

**Comment by isaac-patterson-xero** [comment]
+1 we're getting the notice on our slack alerts to upgrade to workflows but we cant because our alerts are defined via terraform

**Comment by arhill05** [comment]
@NSSPKrishna any chance the above PR can be reviewed? It looks rather simple - almost as if Slack was unintentionally left out as a notification channel.

This is the final blocker our team has to migrating to Workflows.

**Comment by NSSPKrishna** [comment]
Issue is resolved in the release V3.2.1
