### ISSUE TITLE
destination_configuration attribute on newrelic_workflow resource is incorrectly documented

### ISSUE THREAD

**Issue by arhill05** [newrelic/terraform-provider-newrelic#1958]
## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [ x ] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [ x ] A list of [affected resources](#affected-resources) and/or data sources
- [ x ] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [ x ] Description of the [current behavior](#actual-behavior) (the bug)
- [ x ] Description of the [expected behavior](#expected-behavior)
- [ x ] Any related [log output](#debug-output)

### Terraform Version
1.2.8

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_workflow`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
provider "newrelic" {
  api_key    = var.api_key
  account_id = redacted
  region     = "US"
}
```

### Actual Behavior
An error occurs when using an attribute with the name supplied in documentation

### Expected Behavior
An error should not occur and the terraform plan should be successful

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a newrelic_workflow resource following the examples in documentation. My resource is below:
```hcl
resource "newrelic_workflow" "issue_alerting_workflow" {
  name = "TF_Dev Slack Synthetic Check Alerts"
  enrichments_enabled = false
  destinations_enabled = true
  workflow_enabled = true
  muting_rules_handling = "NOTIFY_ALL_ISSUES"

  issues_filter {
    name = "environment_is_dev"
    type = "FILTER"

    predicates {
      attribute = "tag.environment"
      operator = "EQUAL"
      values = ["dev"]
    }
  }

  destination_configurations {
    channel_id = newrelic_notification_destination.slack_destination.id
  }
}
```
2. Run `terraform plan`
3. See error

### Debug Output
https://gist.github.com/arhill05/dbf65eba33cf9af01be5b479a4f69735

**Comment by NSSPKrishna** [comment]
Hi @arhill05, thanks for raising the issue. Kindly create the resource using `newrelic_notification_destination` instead of using `newrelic_workflow`.

**Comment by NSSPKrishna** [comment]
Hi @arhill05, thanks for raising the issue, please check the latest updated documentation(V3.0.1).
