### ISSUE TITLE
Error: Argument "guid" has invalid value $guid - newrelic_synthetics_monitor

### ISSUE THREAD

**Issue by endriu0** [newrelic/terraform-provider-newrelic#1959]
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
terraform 1.2.3

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_synthetics_private_location`
- `newrelic_synthetics_monitor`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.

provider:
```hcl
    newrelic = {
      source = "newrelic/newrelic"
    }
```

Existing private location:
```hcl
data "newrelic_synthetics_private_location" "my-awesome-location" {
  name = "BEST-EVER-Location"
}
```

```hcl
resource "newrelic_synthetics_monitor" "nr_synthetics_monitor" {
  name              = "my-synthetics-monitor"
  type              = "SIMPLE"
  period            = "EVERY_MINUTE"
  status            = "ENABLED"
  locations_private = [data.newrelic_synthetics_private_location.my-awesome-location.id]

  uri                 = "http://my-awesome-url"
  validation_string   = "success"
  bypass_head_request = true
  verify_ssl          = false
}
```

### Actual Behavior
What actually happened?
Plan fails with : 
```
│ Error: Argument "guid" has invalid value $guid.
│
│   with module.synthetics.newrelic_synthetics_monitor.nr_synthetics_monitor,
│   on ../modules/synthetics/main.tf line 39, in resource "newrelic_synthetics_monitor" "nr_synthetics_monitor":
│   39: resource "newrelic_synthetics_monitor" "nr_synthetics_monitor" {
│
```

### Expected Behavior
What should have happened?
Plan goes through

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

```
2022-08-29T14:05:21.479+0200 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/newrelic/newrelic"
2022-08-29T14:05:21.502+0200 [INFO]  backend/local: plan operation completed
╷
│ Error: Argument "guid" has invalid value $guid.
│
│   with module.synthetics.newrelic_synthetics_monitor.nr_synthetics_monitor,
│   on ../modules/synthetics/main.tf line 39, in resource "newrelic_synthetics_monitor" "nr_synthetics_monitor":
│   39: resource "newrelic_synthetics_monitor" "nr_synthetics_monitor" {
│
╵

2022-08-29T14:05:22.706+0200 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/newrelic/newrelic/3.0.0/darwin_arm64/terraform-provider-newrelic_v3.0.0 pid=59672
2022-08-29T14:05:22.706+0200 [DEBUG] provider: plugin exited
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

**Comment by endriu0** [comment]
To add to above : Tested the 

```
  location_private {
    guid         = newrelic_synthetics_private_location.private_location.id
    vse_password = secret
  }
```

That appears in documentation but that also is not supported.

**Comment by hwoarang** [comment]
I am having the exact same problem ever since we updated to v3 (tested both v3.0.0 and v3.0.1) version of the provider but without even using `location_private` at all. We explicitly use `locations_public` only.

```
╷
│ Error: Argument "guid" has invalid value $guid.
│ 
│   with newrelic_synthetics_monitor.monitor["https://xxxxxxx"],
│   on monitors.tf line 29, in resource "newrelic_synthetics_monitor" "monitor":
│   29: resource "newrelic_synthetics_monitor" "monitor" {
│ 
```
And the resource looks like this

```
resource "newrelic_synthetics_monitor" "monitor" {
  for_each = { for monitor, config in local.all_monitors : monitor => config }
  type     = "SIMPLE"
  name     = each.key

  period              = local.common.period
  status              = upper(each.value.status) # valid values are: ENABLED|MUTED|DISABLED
  locations_public    = local.common.locations
  uri                 = each.value.url
  verify_ssl          = try(each.value.verify_ssl, true)
  bypass_head_request = try(each.value.bypass_head_request, true)

  dynamic "tag" {
    for_each = merge(
      local.default_monitor_tags,
      { "env" : each.value.env },
      { "team" : each.value.team }
    )
    content {
      key    = tag.key
      values = [tag.value]
    }
  }
}
```

**Comment by kidk** [comment]
I'm having a really hard time reproducing this. Has anyone been able to catch a debug log? https://www.terraform.io/internals/debugging `TF_LOG= TRACE`

**Comment by meyerkev** [comment]
[newrelic.log](https://github.com/newrelic/terraform-provider-newrelic/files/9456561/newrelic.log)

Done.

**Comment by kidk** [comment]
Thanks a lot @meyerkev You can delete the tracelog if you wish.

This seems to be an API issue. When reading the Synthetics checks again from our API we are sending an invalid value for the GUID which is where the error is coming from. 

```
{
 "errors": [
  {
   "locations": [
    {
     "column": 2,
     "line": 4
    }
   ],
   "message": "Argument \"guid\" has invalid value $guid."
  }
 ]
}
```

As we don't do anything special with the [GUID except to save it after the create operation](https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_synthetics_monitor.go#L202) I believe we might not be getting the GUID back from the API, or at least in an incorrect form. 

Can someone take a look at their `terraform.tfstate` file and look for the value of `id` in the `newrelic_synthetics_monitor` block and share the value?

In meantime I will raise this with the Synthetics team.

**Comment by hwoarang** [comment]
The state of a `newrelic_synthetics_monitor` resource looks like this for me
```
resource "newrelic_synthetics_monitor" "monitor" {
    bypass_head_request       = true
    frequency                 = 1
    id                        = "d6d82f37-a254-49d4-bd43-90049bf64403"
    locations                 = [
        "AWS_US_EAST_2",
        "AWS_US_WEST_1",
    ]
    name                      = "https://xxxx"
    sla_threshold             = 7
    status                    = "ENABLED"
    treat_redirect_as_failure = false
    type                      = "SIMPLE"
    uri                       = "https://xxxx"
    verify_ssl                = true
}
```

**Comment by kidk** [comment]
Thanks @hwoarang You gave me the last clue to figure this out. The code didn't keep into account the change of ID for existing `newrelic_synthetics_monitor`. There's a fix ready for review in #1970

**Comment by kidk** [comment]
[3.0.2] is out with fix https://registry.terraform.io/providers/newrelic/newrelic/3.0.2

**Comment by endriu0** [comment]
Can confirm 3.0.2 works fine on my side. Thanks for that - will close the issue - if it doesn't work for anybody else feel free to reopen.

**Comment by meyerkev** [comment]
I will also confirm that 3.0.2 works on our side.
