### ISSUE TITLE
newrelic_notification_destination requires an authentication type even if no auth is required

### ISSUE THREAD

**Issue by arhill05** [newrelic/terraform-provider-newrelic#1963]
## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [ x ] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [ x ] A list of [affected resources](#affected-resources) and/or data sources
- [ x ] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [ x ] Description of the [current behavior](#actual-behavior) (the bug)
- [ x ] Description of the [expected behavior](#expected-behavior)
- [ x ] Any related [log output](#debug-output)

### Terraform Version
1.2.8

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_notification_destination`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
provider "newrelic" {
  api_key    = var.api_key
  account_id = redacted
  region     = "US"
}
```

### Actual Behavior
An error occurs when not supplying a block for either auth_basic or auth_token in the `newrelic_notification_destination` resource, even when auth is not required.

### Expected Behavior
An error should not occur and the terraform plan should be successful

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a `newrelic_notification_destination` resource following the [examples in documentation](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination#account_id). My resource is below:

```hcl
resource "newrelic_notification_destination" "slack_destination" {
  name = "TF_slack_destination"
  type = "WEBHOOK"

  property {
    key = "url"
    value = "redacted"
  }
}
```
3. Run `terraform plan`

### Debug Output
https://gist.github.com/arhill05/8c3b0ac20a6d19b8eac847e93dcd2761

### Additional context
I can get around this by adding an `auth_basic` block with some dummy data in the `user` and `password` attributes, but having blank strings for those attributes results in an error directly from the terraform-provider-newrelic plugin. Debug output in below gist:
https://gist.github.com/arhill05/d6d4d5557a669d5512fee6a869167e5d

**Comment by shiva-bandari** [comment]
Hi @arhill05 ,
Thanks for raising the issue.
We are able to reproduce, we will prioritise this issue.

**Comment by NSSPKrishna** [comment]
The fix is available in the latest release.
