### ISSUE TITLE
Synthetic monitor for private location documentation is incorrect.

### ISSUE THREAD

**Issue by wendell-fcsa** [newrelic/terraform-provider-newrelic#1975]
For Data Source: [newrelic_synthetics_private_location](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/synthetics_private_location) the example usage in the resource shows:

`location_private = [data.newrelic_synthetics_monitor_location.example.id]`

This did not validate in terraform, 

` Error: Unsupported argument
│
│   on ..\my_modules\terraform\newrelic\modules\alert_policy\my_app_alert_policy.tf line 175, in resource "newrelic_synthetics_script_monitor" "monitor":
│  175:   location_private = [ data.newrelic_synthetics_private_location.my_minion.id ]
│
│ An argument named "location_private" is not expected here. Did you mean to define a block of type "location_private"?`

This did validate and worked correctly:

`  location_private {
    guid = data.newrelic_synthetics_private_location.my_minion.id
  }
`

**Comment by NSSPKrishna** [comment]
Hi @wendell-fcsa, thanks for raising the issue. We will update the docs.
