### ISSUE TITLE
`newrelic_synthetics_monitor` SimpleBrowser cannot be created or updated with new runtime_version

### ISSUE THREAD

**Issue by louhnmn** [newrelic/terraform-provider-newrelic#1977]
## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version

```
terraform -v
Terraform v1.2.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.28.0
+ provider registry.terraform.io/newrelic/newrelic v3.0.1
```

### Affected Resource(s)
- `newrelic_synthetics_monitor`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.

`provider.tf`:

```
terraform {
  # Require Terraform version 1.0 (recommended)
  required_version = "~> 1.2.8"

  # Require the latest 2.x version of the New Relic provider
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.0"
    }
  }
}

provider "newrelic" {
  region = var.newrelic_region
}
```

`main.tf`
```
resource "newrelic_synthetics_monitor" "ttfb_test_browser_mon" {
  for_each = var.ttfb_checks #set of domains with uri's

  name                                    = "TTFB TEST ${each.key}"
  type                                    = "BROWSER"
  period                                  = "EVERY_5_MINUTES"
  status                                  = "ENABLED"
  locations_public                        = var.locations_eu
  runtime_type                            = "CHROME_BROWSER"
  runtime_type_version                    = "100"
  enable_screenshot_on_failure_and_script = true

  uri        = each.value
  verify_ssl = false
}

variable "ttfb_checks" {
  type = map(string)
  default = {
    "example_com - Item"     = "https://some_uri1"
    "example_com - Start"  = "https://some_uri2"
    "example_com - Category" = "https://some_uri3"
  }
}

variable "locations_eu" {
  type = list(string)
  default = [
    "EU_CENTRAL_1",
    "EU_NORTH_1",
    "EU_SOUTH_1",
    "EU_WEST_1",
    "EU_WEST_2",
    "EU_WEST_3"
  ]
}
```

### Actual Behavior
What actually happened?

Following the [terraform-registry](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor)

- I created some browser monitor with the legacy runtime (if you don't specify runtime_type they get created with `Chrome 72 (Legacy)` ) -> terraform plan -> terraform apply
- Everything gets created perfectly.
- Then I try to update them, alter the resource and add:

```
runtime_type                      = "CHROME_BROWSER"
runtime_type_version              = "100"
```

-> terraform plan -> terraform apply

- The resources are modifying but then terraform is throwing errors:

```
╷
│ Error: maximum retries reached: Exception while fetching data (/updateSimpleBrowserMonitor) : null
│ 
│   with newrelic_synthetics_monitor.ttfb_test_browser_mon["example_com - Item"],
│   on main.tf line 165, in resource "newrelic_synthetics_monitor" "ttfb_test_browser_mon":
│  165: resource "newrelic_synthetics_monitor" "ttfb_test_browser_mon" {
│ 
╵
...
```

***

While trying to create monitors directly with runtime_type `CHROME_BROWSER` and runtime_type_version `100`,
it will throw:

```
╷
│ Error: maximum retries reached: Exception while fetching data (/createSimpleBrowserMonitor) : null
│ 
│   with newrelic_synthetics_monitor.ttfb_test_browser_mon["example_com - Item"],
│   on main.tf line 165, in resource "newrelic_synthetics_monitor" "ttfb_test_browser_mon":
│  165: resource "newrelic_synthetics_monitor" "ttfb_test_browser_mon" {
│ 
╵
```

### Expected Behavior
What should have happened?

- The resources should update/create the monitor with the correct `runtime_type` and `runtime_type_version`

### Steps to Reproduce

for creating:
- only `terraform apply`

for updating:
- `terraform apply` with legacy runtime
- alter code to new runtime
- `terraform apply` 

### Debug Output
 
- [gist](https://gist.github.com/louhnmn/3f78cf3cf29a6ec90d5babda3573d698)

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here?

- not that I'm aware of

**Comment by NSSPKrishna** [comment]
Hi @louhnmn, thanks for raising the issue, kindly use `script_language = "JAVASCRIPT" ` field. We will update the docs regarding the issue.

**Comment by NSSPKrishna** [comment]
Thanks for the update.
