### ISSUE TITLE
No resource schema found for `newrelic_synthetics_monitor_script`

### ISSUE THREAD

**Issue by mark-hingston** [newrelic/terraform-provider-newrelic#1987]
Terraform v1.2.8 (Windows x64)
NewRelic Provider: v3.1.0

Hi there,

I'm getting the following error when running a plan:

`Error: no schema available for module.common.module.new_relic_monitor["mydomain"].newrelic_synthetics_monitor_script.health_check_script while reading state; this is a bug in Terraform and should be reported`

```terraform
resource "newrelic_synthetics_script_monitor" "health_monitor" {
  name                  = "${local.GroupAndRegion} ${title(var.environment)} API Health Monitor (${var.app_service_uri})"
  type                  = "SCRIPT_API"
  locations_public      = ["AWS_EU_WEST_1", "AWS_EU_WEST_2"]
  period                = "EVERY_5_MINUTES"
  status                = "ENABLED"
  script                = data.template_file.health_check.rendered
  script_language       = "JAVASCRIPT"
  runtime_type          = "NODE_API"
  runtime_type_version  = "16.10"
}

data "template_file" "health_check" {
  template = templatefile("${path.cwd}/templates/health-check.tftpl", { uri = "https://${var.app_service_uri}/health" })
}
```

**Comment by shiva-bandari** [comment]
Hi @mark-hingston , 
Thanks for raising the issue.
Synthetic_monitor_script resource has been deprecated from the new release V3.1.0. you need to update your module code by removing the deprecated resources.

**Comment by mark-hingston** [comment]
Thanks @shiva-bandari, however the project contains no references to the deprecated resource `newrelic_synthetics_monitor_script`.

![image](https://user-images.githubusercontent.com/97893030/188602908-c7a0acba-d6e6-4de2-8152-702270cbf57f.png)

I've replaced the resource with the new `newrelic_synthetics_script_monitor` resource as shown in my original post.

**Comment by hwoarang** [comment]
I am having the same issue following the v3 migration guide
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v3

The problem seems to be coming from reading existing `newrelic_synthetics_script_monitor` resources from an existing state as the message suggests.

**Comment by zeffron** [comment]
Exactly what @hwoarang said. The 3.x version of the provider is still too unstable to remove the old 2.x resources completely. I've been trying to upgrade since 3.0.1 and continue to hit blocking bugs. I cannot migrate through iterative use of minor versions of 3.x because of this. Essentially, with this bug, I'd be forced to destroy and then apply fresh, which would cause problems for my monitoring.

**Comment by leslie-alldridge** [comment]
Also have this issue, cannot safely use terraform state move commands either. Very poor upgrade path to be honest. 

The workaround is to do `terraform state rm <your_broken_resource>`

And then `terraform import <resource.name> guid` where the guid is your synthetic monitor

This way you shouldn't have any downtime, just a brief moment where Terraform isn't tracking your resources.

**Comment by zeffron** [comment]
If we cannot update the provider to assist with the migration from old resource to new, can we at least update the migration guide with [the workaround](https://github.com/newrelic/terraform-provider-newrelic/issues/1987#issuecomment-1248578765)?

**Comment by xmariopereira** [comment]
I have the same issue. Migrating to 3.4.4 right now.

**Comment by leslie-alldridge** [comment]
> I have the same issue. Migrating to 3.4.4 right now.

It will be the same issue for everyone. The fix is simple if you reference the docs or the linked issue above. I've updated 20 monitors many weeks ago and haven't had any issues since. It's a bit annoying but faster to just fix manually and move on.

**Comment by Mahanotrahul** [comment]
Having the same issue. Not just the `newrelic_synthetics_monitor_script` has been deprecated but the data source has also been deprecated and I make heavy use of data source in my state files. 
`The provider provider.newrelic does not support data source
"newrelic_synthetics_monitor".`
I haven't figured out a workaround for this yet and doing a total manual overhaul of the statefiles isn't going to be an easy task

**Comment by NSSPKrishna** [comment]
Hi @Mahanotrahul can you raise a new issue?

**Comment by mbazhlekova** [comment]
Hi @Mahanotrahul all synthetics monitors are now entities. So using `data_source_newrelic_entity` is the way to read synthetics monitors. This should give you the monitor information:

`data "newrelic_entity" foo {
  name = "my-monitor"
  type = "MONITOR"
  domain = "SYNTH"
}`

Let us know if there is any monitor specific data that you are using which is missing from the newrelic_entity data source.
