### ISSUE TITLE
newrelic_notification_destination: Mobile push

### ISSUE THREAD

**Issue by wuetz** [newrelic/terraform-provider-newrelic#1992]
### Feature Description
NR supports the notification destination "Mobile push". 
It seems to me, that this destination is currently not confgurable via TF. 

Is this maybe already in your pipeline, i couldn't find any related ticket regarding this.

**Comment by NSSPKrishna** [comment]
HI @wuetz thanks for raising the issue. The [PR](https://github.com/newrelic/terraform-provider-newrelic/pull/1990) is under review. We will let you know once it's released.

**Comment by NSSPKrishna** [comment]
This was released as a part of V3.2.1
