### ISSUE TITLE
"property" is required on newrelic_notification_destination but documentation says it's optional 

### ISSUE THREAD

**Issue by kohbis** [newrelic/terraform-provider-newrelic#1993]
## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version

```bash
$ terraform -v
Terraform v1.2.9
```

### Affected Resource(s)

- [`newrelic_notification_destination `](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination)
- Probably the same in [`newrelic_notification_channel`](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_channel)

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.

```hcl
provider "newrelic" {
  api_key    = redacted
  account_id = redacted
  region     = "US"
}
```

### Actual Behavior

An error occurs when not supplying the `property` attribute for a newrelic_notification_destination

### Expected Behavior

An error should not occur and the terraform plan should be successful

### Steps to Reproduce

1. Create a `newrelic_notification_destination` resource following [an example of PagerDuty in documentation](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination#additional-examples)
    ```hcl
    resource "newrelic_notification_destination" "pagerduty" {
      account_id = redacted
      name = "pagerduty"
      type = "PAGERDUTY_SERVICE_INTEGRATION"
    
      auth_token {
        prefix = "Token token="
        token  = redacted
      }
    }
    ```
1. `terraform plan`
2. See error

### Debug Output

https://gist.github.com/kohbis/32dd49a91c8683fe408ee6ca9786276b

### References

- Seems similar to https://github.com/newrelic/terraform-provider-newrelic/issues/1960

**Comment by NSSPKrishna** [comment]
Hi @kohbis, thanks for raising the issue. We will update the document.
