### ISSUE TITLE
"account_id" is required in `newrelic_notification_channel` but documentation says it's optional

### ISSUE THREAD

**Issue by louhnmn** [newrelic/terraform-provider-newrelic#1994]
Hi there,

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version

terraform -v                                                                                                                        
Terraform v1.2.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.30.0
+ provider registry.terraform.io/newrelic/newrelic v3.2.0

### Affected Resource(s)
- `newrelic_notification_channel`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.

`provider.tf`:

```hcl
terraform {
  required_version = "~> 1.2.9"

  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.2.0"
    }
  }
}

provider "newrelic" {
  region = var.newrelic_region
}

provider "aws" {
  region = var.aws_region
}
```

`alerts.tf`:

```hcl
resource "newrelic_notification_destination" "google_chat_temp" {
  name = "TF Google Chat"
  type = "WEBHOOK"

  property {
    key   = "url"
    value = "the-webhook-url-redacted"
  }
}

resource "newrelic_notification_channel" "google_chat_channel" {
  name = "TF Google Chat Channel"
  type = "WEBHOOK"
  destination_id = newrelic_notification_destination.google_chat_temp.id
  product        = "IINT"

  property {
    key = "payload"
    value = "{\"text\": \"test\"}"
    label = "Payload Template"
  }

  depends_on = [
    newrelic_notification_destination.google_chat_temp
  ]
}
```

### Actual Behavior
What actually happened?
- creation of `newrelic_notification_channel` throws:
```
╷
│ Error: Missing required argument
│ 
│   on alerts.tf line 12, in resource "newrelic_notification_channel" "google_chat_channel":
│   12: resource "newrelic_notification_channel" "google_chat_channel" {
│ 
│ The argument "account_id" is required, but no definition was found.
╵
```

### Expected Behavior
What should have happened?
- `newrelic_notification_channel` should have been created

### Steps to Reproduce
1. `terraform plan` is sufficient

### References

With newrelic-plugin v3.2.0 I thought this would be fixed but seems like it is only fixed for `newrelic_notification_destination`
- #1960 
- #1971

**Comment by NSSPKrishna** [comment]
Hi @louhnmn thanks for raising the issue. We will prioritise it.
