### ISSUE TITLE
Can resources/synthetic_monitor output the period as a number in seconds?

### ISSUE THREAD

**Issue by meyerkev** [newrelic/terraform-provider-newrelic#1997]
### Feature Description
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor

So period used to be a number and you used to be able to set that number as a local and use it to do math with elsewhere.  

And then they limited it down to a small set of strings, but I was using that number to do math with in some of my modules.  threshold_duration = max(300, 2*var.synthetic_period), things like that.  

I absolutely get that change, but can we get a number back out?  EVERY_10_MINUTES is 600 seconds and so on. 

### Describe Alternatives
I could make it myself ala {EVERY_MINUTE=60, EVERY_5_MINUTES=300}, but I'd really prefer to have it be first-party just for the backwards compatibility.  What happens if/when NewRelic changes the API?

**Comment by kidk** [comment]
Thanks for the request @meyerkev I think this makes sense to add it to Terraform. It might take some time before we have the bandwidth as we are currently focussing hard on the workflows and synthetics bugs. 

> What happens if/when NewRelic changes the API?
I won't expect this to happen often, if at all. So I think it's a valid workaround.

If you're feeling confident you can try making the change yourself and pushing a PR 😄 You need to add a computed field, and set the value in the read functions.

**Comment by meyerkev** [comment]
Unfortunately, I'm losing access to my NewRelic account tomorrow, but yes if my new employer uses NewRelic, I will definitely be looping back.

**Comment by Nandu-pns** [comment]
Hi @meyerkev, We are thinking of adding the minutes (not in seconds) as an attribute, which means you won’t be able to set it, but only retrieve it after the creation of the synthetic check.

**Comment by Nandu-pns** [comment]
Hi @meyerkev, We had a new Terraform provider release yesterday and we've added [support](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor#period_in_minutes) to output period in minutes, could you please check and confirm if it works as expected ? Thank you !

**Comment by Nandu-pns** [comment]
Hi, We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue. Thanks !
