### ISSUE TITLE
newrelic_notification_destination | PagerDuty Service Integration requires at least 1 property block

### ISSUE THREAD

**Issue by AdrienKuhn** [newrelic/terraform-provider-newrelic#2000]
### Terraform Version

```
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.2.0
```

### Affected Resource(s)

- `newrelic_notification_destination`

### Terraform Configuration

Similar to the example mentioned in the documentation:

```hcl
resource "newrelic_notification_destination" "destination" {
  name       = "Test | PagerDuty Global Event Rules"
  type       = "PAGERDUTY_SERVICE_INTEGRATION"

  auth_token {
    prefix = "Token token="
    token = "routing_key"
  }
}
```

### Actual Behavior

Plan is failing:

```
│ Error: Insufficient property blocks
│
│   on [..]/main.tf line 1, in resource "newrelic_notification_destination" "destination":
│    1: resource "newrelic_notification_destination" "destination" {
│
│ At least 1 "property" blocks are required.
```

### Expected Behavior

The property block should be optional since it's not required for PagerDuty Service Integration.
The only workaround right now is to add the following property to the destination:

```
  property {
    key = ""
    value = ""
  }
```

### Steps to Reproduce

1. Add the resource mentioned above to the configuration
2. `terraform plan`

### Debug Output
N/A

### Panic Output
N/A

### Important Factoids
N/A

### References
N/A

**Comment by NSSPKrishna** [comment]
This issue has be resolved in the latest release.

**Comment by pragatihegde** [comment]
can some one please what exactly is added to the code.
We have received Service Name and Integration Key from the user.
