### ISSUE TITLE
TF apply fails on newrelic_synthetics_multilocation_alert_condition (Provider v3.2.0)

### ISSUE THREAD

**Issue by jwfornan** [newrelic/terraform-provider-newrelic#2003]
- [ X] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [ X] A list of [affected resources](#affected-resources) and/or data sources
- [ X] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [ X] Description of the [current behavior](#actual-behavior) (the bug)
- [ X] Description of the [expected behavior](#expected-behavior)
- [X ] Any related [log output](#debug-output)

### Terraform Version
Terraform v1.0.3

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_synthetics_multilocation_alert_condition`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
This issue occurs with all multi-location Synthetics alert condition resources.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.

```
terraform {
  required_version = "= 1.0.3"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.2.0"  # was 2.27.0
    }
  }
}

variable "loc" {
  default = {
    # Configure NR variables needed for use in building names, etc.
    nr_name    = "********"
    nr_account = "********"
    nr_region  = "US"
    comm_name  = "********"
    path       = "********"

  }
}

provider "newrelic" {
  account_id = var.loc["nr_account"]
  api_key    = var.STAGEUS_API_KEY
  region     = var.loc["nr_region"]
}


```

A list of affected resources and/or data sources
- newrelic_synthetics_multilocation_alert_condition

The configuration of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)

```
resource "newrelic_synthetics_multilocation_alert_condition" "multiloc_endpoint_avail" {
    policy_id = module.endpoint_availability_non.alert_policy_id

  name                         = "MultiLoc Endpoint Availability"
  runbook_url                  = ""
  enabled                      = true
  violation_time_limit_seconds = "3600"

    entities = [
      "*****",
      "*****",
      "*****",
    ]

    critical {
    threshold = 4
    }
}


```

### Actual Behavior
All terraform is passing plans with no indications of issues.
Synthetics monitors and NRQL alert conditions build as expected. However, Synthetics multi-location alerts are failing to build with the error, `"The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details."`

### Expected Behavior
All alert conditions should build correctly on apply.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Debug Output
`Stack trace from the terraform-provider-newrelic_v3.2.0 plugin:

panic: runtime error: index out of range [3] with length 1

goroutine 11 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.getMonitorID({0xc000146690?, 0x1a8e13b?})
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_helpers_synthetics.go:376 +0x7d
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandMultiLocationSyntheticsCondition(0x100d287?)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_synthetics_multilocation_alert_condition.go:31 +0x33f
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicSyntheticsMultiLocationAlertConditionCreate({0x1c0a530, 0xc0004be8a0}, 0x0?, {0x193fee0?, 0xc00036db00?})
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_synthetics_multilocation_alert_condition.go:96 +0xcd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00045d180, {0x1c0a568, 0xc0006aeba0}, 0xd?, {0x193fee0, 0xc00036db00})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00045d180, {0x1c0a568, 0xc0006aeba0}, 0xc00031e9c0, 0xc0002d6c00, {0x193fee0, 0xc00036db00})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003ee588, {0x1c0a568?, 0xc0006aea80?}, 0xc000240960)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003cd0e0, {0x1c0a568?, 0xc0006ae240?}, 0xc0003c8070)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:813 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1a39e40?, 0xc0003cd0e0}, {0x1c0a568, 0xc0006ae240}, 0xc0003c8000, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ea1e0, {0x1c0de70, 0xc0002949c0}, 0xc000522000, 0xc00044f140, 0x21d2520, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0001ea1e0, {0x1c0de70, 0xc0002949c0}, 0xc000522000, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-newrelic_v3.2.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
╷
│ Error: Plugin did not respond
│
│   with newrelic_synthetics_multilocation_alert_condition.multiloc_endpoint_avail,
│   on alerts.tf line 176, in resource "newrelic_synthetics_multilocation_alert_condition" "multiloc_endpoint_avail":
│  176: resource "newrelic_synthetics_multilocation_alert_condition" "multiloc_endpoint_avail" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
`

**Comment by louhnmn** [comment]
@jwfornan Did you use monitor id's or guid's for the entity field?
Mine crashes too if I use the *normal* monitor id's (with the dashes in between) but guid's work fine.

**Comment by jwfornan** [comment]
Well, funny that.  The v2.27.0 provider wouldn't work with the GUID; only the Monitor ID.
Switching to the GUID (as per docs) results in a successful build.

Silly me.  Thank you.  We can mark this closed.
