### ISSUE TITLE
v3 Provider No longer detects changes in synthetic scripts

### ISSUE THREAD

**Issue by olvap377** [newrelic/terraform-provider-newrelic#2015]
### Current Provider:
```
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.2.0"
    }
  }

  # Azure backend for maintaining states through various PRs
  backend "azurerm" {
    resource_group_name  = "rg-terraform-hub-001"
    storage_account_name = "***"
    container_name       = "prod-storage"
    key                  = "newrelic-services.terraform.tfstate"
    use_msi              = true
    client_id            = "***"
    subscription_id      = "***"
    tenant_id            = "***"
  }
}

# Configure the New Relic provider
provider "newrelic" {
  account_id = var.env_id
  api_key    = var.newrelic_prod_key
  # Valid regions are US and EU
  region = "US"
}
```
### Terraform Version:
```
/ $ terraform -v
Terraform v1.2.4
on linux_amd64
```

### Affected Resource(s)
- `newrelic_synthetics_script_monitor`

### Actual Behavior
Changes made to the synthetic script are not recognized as "changed" by Terraform

### Expected Behavior
Changes should be noticed by Terraform and it should be detected as a "change". See screenshot below for behavior as it was with the v2 provider.
![Snag_5db2ac12](https://user-images.githubusercontent.com/32314784/190703967-3a5ff12d-b6af-4e5a-9dce-64bd5cd69985.png)

### Steps to Reproduce
On the new v3 provider use the script field to pass it the path to the file. E.G.:
`script    = replace(file("${path.module}/files/${var.synthetic_file}"), "ENDPOINTS", var.endpoints)`
(We are using a template script and replacing the endpoints to check by pulling them from variables)

Synthetic is created successfully with the script passed in correctly.

Modify the endpoints by changing the variables you are passing in. E.G. Example tied to above screenshot.
```
variable "endpoints_myserv" {
  type    = string
  default = <<-EOT
  'qla01myserv.qa.fundserv.com:7180/monitor/health',
  'qlb01myserv.qa.fundserv.com:7180/monitor/health',
  'qla11myserv.qa.fundserv.com:7180/monitor/health',
  'qlb11myserv.qa.fundserv.com:7180/monitor/health'
  EOT
}
```

At this point when running the Terraform plan it should notice the change like it did in the above v2 provider screenshot however with the v3 provider now it just says "No changes detected". This also works backwards such that any changes made in the UI to the script are not noticed by Terraform so there is no message saying "Changes have been made outside of the terraform state file"

This seems to be related to the fact that in the v2 provider the synthetic itself and the script for it were 2 separate resources that were then linked together vs now with the v3 provider it is one new resource. When the script was it's own resource with the v2 provider, Terraform noticed any small change to the script such as spaces or newlines and now it seems the way the new resource 'newrelic_synthetics_script_monitor` handles the script, Terraform can no longer see the changes.

**Comment by NSSPKrishna** [comment]
Hi @olvap377 thanks for raising the issue. We will prioritise it.

**Comment by olvap377** [comment]
This has been resolved as of the latest provider update, thanks
