### ISSUE TITLE
Creation of newrelic_notification_channel fails

### ISSUE THREAD

**Issue by npreiser** [newrelic/terraform-provider-newrelic#2023]
NR Provider version 3.3.0
TF Version: 1.2.9

When attempting to run the full workflow example here: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workflow#full-scenario-example

which includes the creation of both a destination and a channel,  the example fails with the following: 

```
**Error: INVALID_PARAMETER: A channel with id 5e916938-8ce4-41d4-8390-ed39fb330eb7 was not found
│
│   with newrelic_workflow.product_1_workflow,
│   on alerts.tf line 56, in resource "newrelic_workflow" "product_1_workflow":
│   56: resource "newrelic_workflow" "product_1_workflow" {**
```

We have confirmed that the channel id never gets created in NRDB, (confirmed via Nerdgraph).   It does not exist. 

A bit of investigation, one thought is that for terraform "id" is a reserved word, yet ,we are using it 
when linking a newrelic_notification channel to a workflow

**Comment by mbazhlekova** [comment]
@npreiser Can you send me the TF config you're using with any sensitive information removed?

**Comment by npreiser** [comment]
All I did was use the example provided on our provider page: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workflow  under workflow,  at the bottom (the full example),  which includes the creation of the destination, dest channel, ..and then the workflow itself..

**Comment by npreiser** [comment]
@mbazhlekova ,  let me know if you need anything else,

**Comment by mbazhlekova** [comment]
@npreiser I'm having some trouble reproducing the issue to debug. I'm able to run the full example without problems. I just removed the `account_id` argument from the resources and let Terraform use the one I have defined in my environment.

**Comment by npreiser** [comment]
i'll try again in a few and post

**Comment by npreiser** [comment]
Turns out it was a syntax issue,  however I was using the example in the docs .   (see here).   Issue was that the product needed to be IINT 
![image](https://user-images.githubusercontent.com/6842827/194588973-4356988c-8608-45ee-8645-1299b859bab4.png)
