### ISSUE TITLE
After importing newrelic_notification_destination of type SLACK it tries to delete auth_token

### ISSUE THREAD

**Issue by alisson276** [newrelic/terraform-provider-newrelic#2025]
### Terraform Version
```
Terraform v1.3.0
on linux_arm64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_notification_destination`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.3"
    }
  }
}

provider "newrelic" {
  account_id = **********
  api_key = **********
  region = "US"
}

resource "newrelic_notification_destination" "slack" {
  name = "*********"
  type = "SLACK"

  auth_token {
    prefix = "Bearer"
  }

  property {
        key   = "scope"
        label = "Permissions"
        value = "app_mentions:read,channels:join,channels:read,chat:write,chat:write.public,commands,groups:read,links:read,links:write,team:read,users:read"
    }
    property {
        key   = "teamName"
        label = "Team Name"
        value = "******"
    }
}
```

### Actual Behavior
I've imported the slack `newrelic_notification_destination` like described in the documentation. Then I did a `terraform state show newrelic_notification_destination.slack` and I've made the required changes in my main.tf. The final resource is like the mentioned before (including the `auth_token` block).

After this, I did a plan and it shows me an error saying:
```
 Error: Missing required argument
│ 
│   on main.tf line 10, in resource "newrelic_notification_destination" "slack":
│   10:   auth_token {
│ 
│ The argument "token" is required, but no definition was found.
```

If I remove the block `auth_token` then it says me it will be removed (what I think it shouldn't be)

### Expected Behavior

The `auth_token.token` should be optional in the resource when the type is slack or shouldn't be imported.

**Comment by NSSPKrishna** [comment]
Hi @alisson276, thanks for raising the issue. We will prioritise it.

**Comment by yuto727** [comment]
@NSSPKrishna 
Has this issue already been resolved?

**Comment by JBallin** [comment]
Can you clarify the proper way to import the Slack destination? [Instructions](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination#:~:text=Import%20Slack%20Destination) say:

> 1. Add an empty resource to your terraform file
> 2. Run import command

Are we expected to copy the state values into the resource definition like OP did? My guess is that we leave the block empty and it gets the data from state. The issue is that the current destination validation requires `type`, `name` `property` - should those actually not be required when the destination is slack?

Either way, I think some clarity in the above linked documentation would be helpful.

**Comment by JBallin** [comment]
For now, here's my workaround:

```
resource "newrelic_notification_destination" "slack" {
  lifecycle {
    # attributes are only being set to pass validation (not actually used)
    # https://github.com/newrelic/terraform-provider-newrelic/issues/2025
    ignore_changes  = all
    # destination requires manual import & therefore should not be destroyed
    prevent_destroy = true
  }

  type = "SLACK"
  name = ""
  property {
    key   = ""
    value = ""
  }
}
```

Note my suggestion of `prevent_destroy` - may want to document this too.

Docs: https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle

**Comment by lzaga-newrelic** [comment]
Hi everyone,
The token in `auth_token` attribute doesn't return from our API, because it’s sensitive data. After deeper investigation, `ignore_changes` is the only way to avoid this issue (as mentioned below). We'll add this information to the docs.
> 
> ```
>   lifecycle {
>     ignore_changes = [auth_token]
>   }
> ```
> 
> For example:
> 
> ```
> resource "newrelic_notification_destination" "slack" {
>   lifecycle {
>     ignore_changes = [auth_token]
>   }
> 
>   name = "*********"
>   type = "SLACK"
> 
>   auth_token {
>     prefix = "Bearer"
>   }
> 
>   property {
>         key   = "scope"
>         label = "Permissions"
>         value = "app_mentions:read,channels:join,channels:read,chat:write,chat:write.public,commands,groups:read,links:read,links:write,team:read,users:read"
>     }
>     property {
>         key   = "teamName"
>         label = "Team Name"
>         value = "******"
>     }
> }
> ```

**Comment by zeffron** [comment]
> After deeper investigation, ignore_changes is the only way to avoid this issue (as mentioned below).
Disagree. The provider can be taught to automatically ignore changes for the relevant fields when  the type is `SLACK` so that users do not have to add a lifecycle block.

**Comment by JBallin** [comment]
Agree with @zeffron that this is just an edge case in your validation not taking slack destinations into account. I like the idea of allowing empty when `type === "SLACK" and updating docs to recommend this:

```tf
resource "newrelic_notification_destination" "slack" {
  type = "SLACK"
}
```

Extra credit: If there was a way to automatically prevent destroy, that may be useful?

**Comment by zeffron** [comment]
> Extra credit: If there was a way to automatically prevent destroy, that may be useful? Although I guess this would already be the case if it was in use by a workflow...?

I think this is doable, but I don't know if it really fits well with the Terraform paradigm. Terraform can't distinguish between a resource that was made manually and then imported explicitly for this configuration (in which case destroy might be correct behavior) and one where it's being imported for reuse, or where it will be needed again post destroy.
Having the user explicitly set the lifecycle to prevent destruction does seem appropriate to me because knowing if destruction is desired or not does require extra information from the user.
Might be possible to default to not destroying and require setting `prevent_destroy` to false (if that's even possible?), but that seems very esoteric.

**Comment by JBallin** [comment]
Right it wouldn't be explicit, which is confusing. Maybe a note in the docs is enough.

**Comment by TheQueenIsDead** [comment]
Throwing 2c in here, would being able to reference the destination as `data` instead of `resource` be better? Seems like it would fit better with the ethos of referencing something created outside of the modules control.

**Comment by JBallin** [comment]
Tried `data`:

```
│ Error: Invalid data source
│ 
│   on main.tf line 1, in data "newrelic_notification_destination" "slack":
│    1: data "newrelic_notification_destination" "slack" {
│ 
│ The provider newrelic/newrelic does not support data source
│ "newrelic_notification_destination".
│ 
│ Did you intend to use the managed resource type
│ "newrelic_notification_destination"? If so, declare this using a "resource"
│ block instead of a "data" block.
```

**Comment by lzaga-newrelic** [comment]
Hi everyone,
We are working on creating destinations as data sources as well.

**Comment by MAN98** [comment]
@lzaga-newrelic - do we have a date when destinations as data source will go live? Thanks!

**Comment by lzaga-newrelic** [comment]
Hi @MAN98 ,
We are working on that right now. Hopefully, next week you'll see it in the next version of the provider. I'll update here as well.

**Comment by MAN98** [comment]
Thanks for the prompt response @lzaga-newrelic ^_^

**Comment by davidkiser** [comment]
@lzaga-newrelic Any updates on this?  Im still running into this issue with the 3.20 version of the provider,  and for some reason terraform isnt respecting the ignore lifecycle block to the auth token,  so im stuck currently trying to import this into management
