### ISSUE TITLE
Workflow support slack notifications

### ISSUE THREAD

**Issue by huzie** [newrelic/terraform-provider-newrelic#2035]
### Feature Description
Currently it doesn't look like the Terraform provider supports creating a workflow and sending notifications to Slack.

I want to be able to configure the below via Terraform and link it to an existing policy. 

![image](https://user-images.githubusercontent.com/5070757/193016652-e5b349a0-d385-48f7-9a0b-df51f305f9f4.png)

**Comment by lzaga-newrelic** [comment]
Hi @huzie , @mbazhlekova is correct. Slack requires interactive authentication through OAuth, therefore Slack destinations can only be imported to terraform after creating through the UI. Slack channels can be created via Terraform.

**Comment by xvella97** [comment]
Hi @mbazhlekova and @lzaga-newrelic, thank you for your advice.
We have tried the approach outlined here: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workflow however seeing " Error: CONNECTION_ERROR: Unable to connect to external service to perform this action"
It seems to be a problem with the new relic notification channel resource.

**Comment by huzie** [comment]
Hi @mbazhlekova @lzaga-newrelic, further to @xvella97 comment, we want to be able to create an alert policy which has an alert condition which is then linked to a workflow which has the slack destination. Is this possible?

**Comment by trustthewhiterabbit** [comment]
Hi.

I am not sure I understand the situation. We are already creating Slack Channels in Terraform using the newrelic_notification_channel resource.

I am not sure I understand why we are now not able to do this in the new newrelic_notification_destination resource?

For us this appears to be a step backwards in functionality.

**Comment by NSSPKrishna** [comment]
Hi @tormodmacleod, the channel ID mentioned in the docs is the notifications channel but the channel ID you are trying to use is from the alerts channel. You can find the notifications channels as a section in workflows. At the moment you can get the ID of notifications channels from [Nerd Graph](https://api.newrelic.com/graphiql?# ).
<img width="1104" alt="Screenshot 2022-10-12 at 7 04 58 PM" src="https://user-images.githubusercontent.com/107837335/195356897-8ea1acb9-4097-49fb-b003-a11861e10a2a.png">

**Comment by gdubroeucq** [comment]
We struggle too with the new workflow with Slack.

I imported the slack destination as described.

In the newrelic UI, "destination" are set for Slack Workspace and "workflow" you specifiy the slack channel according the destination.

But in the workflow resource in Terraform, you can only put channel id who is the slack workspace.

How do you specify the Slack channel in terraform?

**Comment by ayk33** [comment]
> Hi @tormodmacleod, the channel ID mentioned in the docs is the notifications channel but the channel ID you are trying to use is from the alerts channel. You can find the notifications channels as a section in workflows. At the moment you can get the ID of notifications channels from [Nerd Graph](https://api.newrelic.com/graphiql?#). <img alt="Screenshot 2022-10-12 at 7 04 58 PM" width="1104" src="https://user-images.githubusercontent.com/107837335/195356897-8ea1acb9-4097-49fb-b003-a11861e10a2a.png">

If I'm creating the workflow & notification channel via terraform how will this work? The Nerd Graph link you sent requires a workflow to exist already right?

**Comment by lzaga-newrelic** [comment]
@gdubroeucq You can get the Slack channel id from this NerdGraph [query](https://api.newrelic.com/graphiql?#query=%7B%0A%20%20currentUser%20%7B%0A%20%20%20%20account%28id%3A%201705020%29%20%7B%0A%20%20%20%20%20%20aiNotifications%20%7B%0A%20%20%20%20%20%20%20%20channels%20%7B%0A%20%20%20%20%20%20%20%20%20%20entities%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A). You can add filters as you wish, like the channel name etc.

Also, if you imported the destination to your terraform, you can use a reference as described [here]([gdubroeucq](https://github.com/gdubroeucq)):
<img width="585" alt="Screen Shot 2022-10-30 at 11 21 29" src="https://user-images.githubusercontent.com/69894591/198871408-d5ddb920-dd9d-4a68-8996-87c6cad40dbd.png">

**Comment by lzaga-newrelic** [comment]
Hi @huzie, @xvella97, @trustthewhiterabbit, @tormodmacleod, @gdubroeucq, @ayk33 

Looks like there are several misunderstandings on several different topics in this issue. I'll try to explain how to create a Slack destination and channel and connect it to an alert policy and to a workflow.

First, as I mentioned [here](https://github.com/newrelic/terraform-provider-newrelic/issues/2035#issuecomment-1264177007), There is no option to create a Slack destination via New Relic Terraform provider. Slack requires interactive authentication through OAuth, therefore Slack destinations can only be imported to terraform after creating through the UI. 

Second, Slack channels can be created via Terraform. To create a Slack channel you'll have to provide a Slack channel id. We are working on adding to our docs more information on how to export the Slack channel id from Slack API.

---

Steps to create all resources mentioned in this issue:
1. Create an [Alert Policy](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_policy):
```
resource "newrelic_alert_policy" "my-policy" {
  name = "my_policy"
}
```
2. Create a Slack destination via the UI and authenticate:
In New Relic One -> Alerts & AI Tab -> Under Destinations -> Choose Slack:
<img width="1187" alt="Screen Shot 2022-11-22 at 16 04 13" src="https://user-images.githubusercontent.com/69894591/203333778-c644a1f1-33d6-42a4-914b-4053ad432631.png">

3. Import the Slack [notification destination](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination) into terraform:
 * Get the destination id from the UI Destinations Table:
In New Relic One -> Alerts & AI Tab -> Under Destinations -> Destinations Tab (attached photo) -> Filter Slack and pick your Slack destination -> Copy the destination Id in the 3 dots menu to the right:
<img width="448" alt="Screen Shot 2022-11-22 at 16 07 46" src="https://user-images.githubusercontent.com/69894591/203334898-96c4a1f6-0b71-4547-85c0-e9d3abfda4e1.png">
<img width="325" alt="Screen Shot 2022-11-22 at 16 08 41" src="https://user-images.githubusercontent.com/69894591/203334902-9c35e255-f62e-448f-8d7d-80b3f713bdb9.png">

 * Add an empty resource to your terraform file:
```
resource "newrelic_notification_destination" "slack-imported-destination" {
}
```
* Run import command: terraform `import newrelic_notification_destination.foo <destination_id>`. The destination Id is the one you picked in the previous step.
4. Create a Slack [notification channel](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_channel) via terraform:
```
resource "newrelic_notification_channel" "my-channel" {
  account_id = 12345678
  name = "slack-example"
  type = "SLACK"
  destination_id = "00b6bd1d-ac06-4d3d-bd72-49551e70f7a8"
  product = "IINT"

  property {
    key = "channelId"
    value = "123456"
  }
}
```
**Notice**: you have to provide the Slack channel id here!

5. Create [workflow](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workflow) via terraform and connect it to the Slack notification channel:
```
resource "newrelic_workflow" "my-workflow" {
  name = "workflow-example"
  muting_rules_handling = "NOTIFY_ALL_ISSUES"

  issues_filter {
    name = "Filter-name"
    type = "FILTER"

    predicate {
      attribute = "labels.policyIds"
      operator = "EXACTLY_MATCHES"
      values = [ newrelic_alert_policy.my-policy.id ] # Here is the policy you created in step #1
    }
  }

  destination {
    channel_id = newrelic_notification_channel.my-channel.id # Here is the notification channel you created in step #4
  }
}
```

**Notice**: if you want to use another notification channel, that is not created via Terraform, you can look for it in NerdGraph API [here](https://api.newrelic.com/graphiql?#query=%7B%0A%20%20currentUser%20%7B%0A%20%20%20%20account%28id%3A%201705020%29%20%7B%0A%20%20%20%20%20%20aiNotifications%20%7B%0A%20%20%20%20%20%20%20%20channels%20%7B%0A%20%20%20%20%20%20%20%20%20%20entities%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A).

Hope this helps to answer all of your questions.

**Comment by Maxwell2022** [comment]
you cannot create an empty `newrelic_notification_destination` block, it's not a valid resource.

```
resource "newrelic_notification_destination" "slack-imported-destination" {}
```

> Too few blocks specified for "property": At least 1 block(s) are expected for "property"Terraform

At least that's what my IDE is telling me.

My resource look like this:

```hcl
resource "newrelic_notification_destination" "slack" {
  name = "Slack Integration"
  type = "SLACK"

  property {
    key   = "scope"
    label = "Permissions"
    value = "app_mentions:read,channels:join,channels:read,chat:write,chat:write.public,commands,groups:read,links:read,links:write,team:read,users:read"
  }

  property {
    key   = "teamName"
    label = "Team Name"
    value = "xxx"
  }

  lifecycle {
    ignore_changes = [auth_token]
  }
}
```

I'm importing this resource using the import directive
```hcl
import {
  id = "xxxxxx-xxxxxx-xxxxx-xxxxx-xxxxxx"
  to = newrelic_notification_destination.slack
}
```

and I still get this error
```
╷
│ Error: CONNECTION_ERROR: Unable to connect to external service to perform this action
│ 
│   with newrelic_notification_destination.slack,
│   on newrelic.tf line 1, in resource "newrelic_notification_destination" "slack":
│    1: resource "newrelic_notification_destination" "slack" {
│ 
╵
```

**Comment by Maxwell2022** [comment]
It seems that you cannot rename a slack destination. The import seems to have worked, but applying new name is failing with the error above.

 I wonder what is the point of having a `resource` if you cannot update it, the documentation should recommend to use `data` instead for slack. Note that the plan is happy with renaming the destination, and it's not suggesting that it will re-create it either.

**Comment by csiepka** [comment]
I'm having the same issue with renaming after import.  @Maxwell2022 did you find any workaround?

**Comment by Maxwell2022** [comment]
I believe the workaround is to create a new slack destination manually in the UI with the name you want and import it again. If you don't want to delete the existing destination you can remove it from your terraform state 
```hcl
terraform state rm newrelic_notification_destination.slack
```
