### ISSUE TITLE
Cannot set runtime_version for Chrome 72 in newrelic_synthetics_script_monitor

### ISSUE THREAD

**Issue by a-hat** [newrelic/terraform-provider-newrelic#2062]
Hi,

I cannot create a script monitor with the Chrome 72 runtime over terraform. Chrome 100 works, but we have a private location, and as I understand it this does not support the latest Chrome version. I tried different values for the `runtime_version` field, none worked. Maybe there is a list with the supported values?

Thanks

### Terraform Version
Terraform v1.3.2

### Affected Resource(s)

- `newrelic_synthetics_script_monitor`

### Terraform Configuration
```hcl
resource "newrelic_synthetics_script_monitor" "monitor" {
  name                 = "Login"
  type                 = "SCRIPT_BROWSER"
  location_private {
    guid               = data.newrelic_synthetics_private_location.private_location.id
  }
  period               = "EVERY_HOUR"
  status               = "ENABLED"
  script               = templatefile("file.ftpl")
  script_language      = "JAVASCRIPT"
  runtime_type_version              = "72"
  runtime_type                            = "CHROME_BROWSER"
}
```

### Actual Behavior
 TF produces the following error:

`Error: BAD_REQUEST: Runtime values are invalid combination.`

### Expected Behavior
I would like to have a script monitor created with the Chrome 72 (Legacy) runtime, as it appears in the NewRelic UI.

**Comment by mbazhlekova** [comment]
@a-hat Private locations on the new runtime are now available [https://docs.newrelic.com/whats-new/2022/09/whats-new-9-23-synthetics-job-manager/](https://docs.newrelic.com/whats-new/2022/09/whats-new-9-23-synthetics-job-manager/)
