### ISSUE TITLE
resource "newrelic_cloud_aws_link_account" cannot recreate a new link if the existing link is gone

### ISSUE THREAD

**Issue by sdhuang32** [newrelic/terraform-provider-newrelic#2065]
I used "newrelic_cloud_aws_link_account" resource in the newrelic terraform provider (https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/cloud_aws_link_account) to link my AWS account to my New Relic account.

During an experiment I manually unlink my AWS account via "Infrastructure -> AWS" console on https://one.newrelic.com/, and in the next deployment Terraform prompted the error `"Error: maximum retries reached: Linked account 'xxxxxx' for account 'xxxxxxx' not found."`

Given I cannot modify the Terraform state file, this leads to a dilemma that I cannot do any deployment anymore.
If I manually delete an AWS resource using Terraform "hashicorp/aws" provider, during "terraform plan" Terraform can detect that and recreate a new resource. Is it appropriate to implement a similar solution?

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version

Terraform v1.2.8

### Affected Resource(s)

- `newrelic_cloud_aws_link_account`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.33.0"
    }

    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.5.0"
    }
  }
}

provider "newrelic" {
  alias            = "new-relic-integration"
  account_id = var.new_relic_account_id
  api_key       = var.new_relic_api_key
  region         = "US"
}


resource "aws_iam_role" "newrelicAccountAwsRole" {
  name = "newrelicAccountAwsRole"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
      {
          "Effect": "Allow",
          "Action": "sts:AssumeRole",
          "Principal": {
              "AWS": "754728514883"
          },
          "Condition": {
              "StringEquals": {
                  "sts:ExternalId": "${var.new_relic_account_id}"
              }
          }
      }
  ]
}
EOF
}

resource "aws_iam_role_policy" "newrelicAccountAwsPolicy" {
  name = "newrelicAccountAwsPolicy"
  role = aws_iam_role.newrelicAccountAwsRole.id

  policy = <<EOF
{
   "Version":"2012-10-17",
   "Statement":[
      {
         "Effect": "Allow",
         "Action": [
            "config:BatchGetResourceConfig",
            "config:ListDiscoveredResources",
            "tag:GetResources",
            "budgets:ViewBudget"
         ],
         "Resource": "*"
      }
   ]
}
EOF
}

resource "aws_iam_role_policy_attachment" "newrelicAccountROPolicy" {
  role       = aws_iam_role.newrelicAccountAwsRole.name
  policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}

resource "newrelic_cloud_aws_link_account" "newrelicAccountLink" {
  provider = newrelic.new-relic-integration

  arn = aws_iam_role.newrelicAccountAwsRole.arn
  metric_collection_mode = "PUSH"
  name = "infra-new-relic-integration"
}

# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our [GPG public key](https://github.com/newrelic/observability-as-code/blob/master/docs/developer-toolkit.asc).
# For more information on how to encrypt files check out the [GPG Privacy handbook](https://www.gnupg.org/gph/en/manual/x110.html).
```

### Actual Behavior
If you manually unlink your AWS account accidentally or that link is gone out of some reason, resource "newrelic_cloud_aws_link_account" cannot recreate it and cause the `terraform plan` to be stuck every time.

### Expected Behavior
If an AWS resource deployed by official Terraform "hashicorp/aws" provider is gone, during "terraform plan" Terraform can detect that and recreate a new resource. I suppose there should be a similar solution in this provider, or at least there should be a documentation saying how to deal with such a situation, otherwise people wouldn't be able to do Terraform deployments anymore.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` & `terraform apply`
2. Check via "Infrastructure -> AWS" console on https://one.newrelic.com/ to verify your AWS account link is created, and there will be a "Provider account" ID number for that link.
3. Manually unlink your AWS account
5. `terraform plan` again and there should be an error popped up `"Error: maximum retries reached: Linked account 'xxxxxx' for account 'xxxxxxx' not found."`

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
The error message `"Error: maximum retries reached: Linked account 'xxxxxx' for account 'xxxxxxx' not found."` was mentioned in the following Github issue but was not addressed
- https://github.com/newrelic/terraform-provider-newrelic/issues/62#issuecomment-1092905235

**Comment by mbazhlekova** [comment]
Hi @sdhuang32 👋 this seems like a bug. TF should be re-creating the resource if it's deleted from the UI. I'll create a ticket for us to address soon.

**Comment by sasamuku** [comment]
Hi @mbazhlekova,
Any progress?

I also ran into the similar situation shown as the following error:

```
Error: ERR_INVALID_DATA : Validation failed: The ARN you entered does not permit the correct access to your AWS account - please check the ARN and try again.
```

This was happend when I recreate a "newrelic_cloud_aws_link_account" after deleting another one.
The Role permissions are the same as successfully creating a "newrelic_cloud_aws_link_account".
