### ISSUE TITLE
Log partitions

### ISSUE THREAD

**Issue by alexrosenfeld10** [newrelic/terraform-provider-newrelic#2066]
### Feature Description
Can we please get support for terraforming [log partitions](https://docs.newrelic.com/docs/logs/ui-data/data-partitions/)?

### Describe Alternatives
Manual configuration. Ugly when you want to automate and permission this across many many applications.

### Additional context
Add any other context here.

**Comment by ayk33** [comment]
Second

**Comment by kidk** [comment]
We are working on it. Looks like it might be ready before the end of the year. We'll update here once it's released.

**Comment by loganhang** [comment]
+1

**Comment by alexrosenfeld10** [comment]
Any updates here @kidk ? Thanks in adv. for the comms.

**Comment by alexrosenfeld10** [comment]
Any update here? @kidk  @NSSPKrishna 

cc @fzolp

**Comment by kidk** [comment]
Still in holding pattern till the new API is released. 😴

**Comment by kidk** [comment]
The API team is expecting it this quarter, so soon. Apologies, the emoji was a bad joke.

**Comment by alexrosenfeld10** [comment]
Gotcha. No worries, I get you 😄. I'm good w/jokes, I just need'em to have real answers mixed in. Thanks for the extra detail, I appreciate it!

**Comment by kidk** [comment]
That's definitely fair and good feedback @alexrosenfeld10 We'd really like to finish this and we get the frustration. Once we have an update on the API I'll share it here, but feel free to keep pingen us.

**Comment by ChandraIragavarapu** [comment]
Released as part of v3.16.0

**Comment by alexrosenfeld10** [comment]
@ChandraIragavarapu what's the resource name? I see these: `newrelic_data_partition_rule` and `newrelic_log_parsing_rule`, but neither look like they _create_ partitions, they only make rules that reference existing partitions?

**Comment by ChandraIragavarapu** [comment]
@alexrosenfeld10 , https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/data_partition_rule - might helps

**Comment by alexrosenfeld10** [comment]
Got it. The naming `target_data_partition` to me implies that it's targeting an existing partition.
