### ISSUE TITLE
Argument "channel" has invalid value $channel. In field "name": Expected type "String!", found null.

### ISSUE THREAD

**Issue by ChrisAndrews** [newrelic/terraform-provider-newrelic#2069]
Looks like when you set up a notification channel of type 'SLACK', you now need to specify the 'display_value' along with the key ("channelId") and value. 
In the UI deploying via terraform looks correct, however in NerdGraph the actor shows a NULL displayValue and testing the notification channel produces the error:

> Argument "channel" has invalid value $channel. In field "name": Expected type "String!", found null.

Solution would be to either note the display_value is now mandatory, or for terraform to automatically populate it when the notification channel is created/updated?

**Comment by arhill05** [comment]
+1 to this. We migrated to the new workflows and everything appeared to work as we expected, but things weren't working due to this exact issue.

**Comment by lzaga-newrelic** [comment]
Hi @ChrisAndrews , @arhill05 , I confirmed this is a bug and a fix will be deployed soon.
Thank you for informing us.

**Comment by lzaga-newrelic** [comment]
Hi @ChrisAndrews , @arhill05 
A fix was deployed today for this issue.
