### ISSUE TITLE
alert_policy_channel resource giving error while creating using terraform, but the resource is shown as created in new relic website

### ISSUE THREAD

**Issue by RAGHAVA998998** [newrelic/terraform-provider-newrelic#2075]
### Terraform Version and new relic provider verion
`terraform version =  1.3.0
new relic providr version = "~> 3.3.0"`

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alert_policy`
- `newrelic_alert_channel`
- `newrelic_alert_policy_channel`     ------>this resource is giving the error

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration

# Configure the New Relic provider
provider "newrelic" {
  region = "US" # Valid regions are US and EU

}
resource "newrelic_alert_channel" "alert_channel_slack" {
  name = "newrelic-sample-channel-1"
  type = "slack"

  config {
    url     = var.var_newrelic_alert_channel_slack_webhook_url
    channel = var.var_newrelic_alert_channel_slack_channel_name
  }
}
resource "newrelic_alert_policy" "alert_policy" {
  name                = "sample-policy-1"
  incident_preference = "PER_CONDITION"
}
resource "newrelic_alert_policy_channel" "alert_policy_channel" {
  depends_on = [
    newrelic_alert_channel.alert_channel_slack,
    newrelic_alert_policy.alert_policy
  ]
  policy_id = newrelic_alert_policy.alert_policy.id
  channel_ids = [
    newrelic_alert_channel.alert_channel_slack.id,
  ]
}

### Actual Behavior
 alert_channel, alert policy resources are getting created. but alert_policy_channel is giving below error. but when i checked newrelic website the resource is created. i.e alert_policy and alert_channel are getting mapped. but terraform apply is giving the below error

### Error output for terraform apply
newrelic_alert_policy.alert_policy: Creating...
newrelic_alert_channel.alert_channel_slack: Creating...
newrelic_alert_policy.alert_policy: Creation complete after 2s [id=3676127]
newrelic_alert_channel.alert_channel_slack: Creation complete after 2s [id=7250880]
newrelic_alert_policy_channel.alert_policy_channel: Creating...
newrelic_alert_policy_channel.alert_policy_channel: Still creating... [10s elapsed]
╷
│ Error: PUT https://api.newrelic.com/v2/alerts_policy_channels.json?channel_ids=7250880&policy_id=3676127 giving up after 4 attempt(s): Put "https://api.newrelic.com/v2/alerts_policy_channels.json?channel_ids=7250880&policy_id=3676127": EOF
│ 
│   with newrelic_alert_policy_channel.alert_policy_channel,
│   on main.tf line 29, in resource "newrelic_alert_policy_channel" "alert_policy_channel":
│   29: resource "newrelic_alert_policy_channel" "alert_policy_channel" {
│ 
╵

### Expected Behavior
create alert_channel, alert policy, alert_policy channel resources.

### Steps to Reproduce
1. `terraform apply`

**Comment by pranav-new-relic** [comment]
Hi @RAGHAVA998998, thank you for reporting this issue. We have tried to reproduce the issue, following the steps you've mentioned; however, we currently find no discrepancy when `terraform apply` is run. Upon testing, we've found that the created alert policy is linked to the created alert channel in the New Relic UI - and terraform shows no error either.

We'd kindly urge you to try this with the [latest version](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs) of the New Relic Terraform Provider. Please let us know if the issue persists. Thank you!
