### ISSUE TITLE
Service Levels not appearing in Workload

### ISSUE THREAD

**Issue by travisroberts-sf** [newrelic/terraform-provider-newrelic#2080]
We are starting to work with Workloads and Service levels and noticed that when you create a Workload and Service Level(s) using terraform, the Service Level doesn't appear in the workload tab.  It does show that its attached to the workload when you look at the Service Level directly, but its not appearing in the tab.  When I delete the Service Level (and leave the Workload) and recreate the Service Level it shows up in the Workload tab.  I also tried adding a "depends_on" clause in the service level code block so that it would wait for the workload to be created first and that didn't work either.

### New Relic Provider: 
- 3.2.1 and greater

### Terraform Version:
- `Terraform v0.13.7`

### Affected Resources:
- [newrelic_workload](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workload)
- [newrelic_service_level ](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/service_level)

#### Terraform Modules
```hcl
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = ">= 3.2.1"
    }
  }
  required_version = ">= 0.13"
}

provider "newrelic" {
  account_id = "removed"
  api_key    = "removed"
  region     = "US"
}

module "active_directory_workload" {
  source = "../../modules/workloads/workload"

  account_number = "removed"
  tags           = local.tags
}

module "active_directory_adws_service" {
  source = "../../modules/service_levels/infrastructure/service/windows"

  account_number       = "removed
  description          = "The uptime of the adws service."
  service_level_target = 99
  service_name         = "adws"
  tags                 = local.tags
  workload_guid        = module.active_directory_workload.guid
}
```
#### Terraform resources referenced by modules
```hcl
resource "newrelic_workload" "workload" {
    name = "${title(lookup(var.tags, "bt.technology"))} - ${title(lookup(var.tags, "bt.swimlane"))}"
    account_id = var.account_number

    entity_search_query {
        query = "`tags.bt.technology` = '${lookup(var.tags, "bt.technology")}' OR `tags.bt.technology.id` = '${lookup(var.tags, "bt.technology.id")}' AND `tags.bt.swimlane` = '${lookup(var.tags, "bt.swimlane")}'"
    }

    scope_account_ids =  [var.account_number]
}

resource "newrelic_service_level" "service_level" {
  guid        = var.workload_guid
  name        = "${title(lookup(var.tags, "bt.technology"))} - (${var.service_name}) ${title(lookup(var.tags, "bt.swimlane"))} Windows Service SLO"
  description = var.description

  events {
    account_id = var.account_number
    valid_events {
      from = "Metric"
      select {
        attribute = "windows_service_state"
        function  = "SUM"
      }
      where = "state IS NOT NULL AND service_name = '${var.service_name}'"
    }
    bad_events {
      from  = "Metric"
      where = "state != 'running' AND service_name = '${var.service_name}'"
    }
  }

  objective {
    target = var.service_level_target
    time_window {
      rolling {
        count = var.time_window_count
        unit  = var.time_window_unit
      }
    }
  }
}
```
### Actual Behavior
- The workload is created successfully and correctly
- The service level(s) are created successfully
- The service level(s) are NOT showing up on the Service Level tab of the Workload.
- The service level(s) do show that they are associated with the workload when viewing the service level directly.

### Expected Behavior
- The workload should be created as is currently happening.
- The service level(s) should be created as is currently happening, however the service levels should also show up in the Service Level tab of the workload.

### Steps to Reproduce
Before logging this issue, I took a few steps to determine that this was in fact a bug.  
1. I removed the SLA's and had terraform recreate ONLY the SLA's.  When i did this they showed up in the Workload SLA tab.
2. I removed the SLA's and the Workload and added a "depends_on" clause to all of the SLA code blocks and recreated both again.  Still the SLA's did not show up on the SLA tab in the workload.

**Comment by asanuy** [comment]
Hi @travisroberts-sf,

Thanks a lot for describing the issue so thoroughly, and apologies for taking so long to get back.

As far as I can tell, the problem was due to a race condition that should be addressed already. The fix was on the server side, so you don't need to upgrade the Terraform provider version, although it is advisable to do so.

Don't hesitate to let us know if you need further help.

**Comment by pranav-new-relic** [comment]
Thank you for the update, @asanuy 😄 closing this issue, since it appears the fix is now out.
