### ISSUE TITLE
Increase the limit of one tag into newrelic_entity

### ISSUE THREAD

**Issue by silanpa** [newrelic/terraform-provider-newrelic#2095]
### Feature Description
Increase the number of tag posible to pass in datasource new relic entity for searching the resource. Actually is set into 1, but is a number very limited when you have different types of entity and environment with the same tags and application name.
### Describe Alternatives
I solved now this limitation, setting the limit to 10 and compiled the project locally, but could be a good feature/configuration is your considered this and increase the limit for tag. This feature could be consistent how you could create tag with the resource newrelic_entity_tags with not limit.

### Additional context

File with related [data_source_newrelic_entity.go](https://github.com/newrelic/terraform-provider-newrelic/blob/0e0a0720b8f5548c29ae0c570303936249f72e01/newrelic/data_source_newrelic_entity.go)

```HCL
"tag": {
      Type:        schema.TypeList,
      MaxItems:    10, # <-- Change this value or delete this line
      Optional:    true,
      Description: "A tag applied to the entity.",
      Elem: &schema.Resource{
	      Schema: map[string]*schema.Schema{
		      "key": {
			      Type:        schema.TypeString,
			      Required:    true,
			      Description: "The tag key.",
		      },
		      "value": {
			      Type:        schema.TypeString,
			      Required:    true,
			      Description: "The tag value.",
		      },
	      },
      },
},
```

**Comment by mbazhlekova** [comment]
Hi @silanpa that is strange since we can send a list of tags to the API. This was added before my time so I'll have to investigate some more. I'll make a ticket for us to address in an upcoming sprint.

**Comment by silanpa** [comment]
@mbazhlekova  In the documentation of provider the parameter is actually defined as tags, but the example and description specifies only one tag. Thank you very much for considering this.
