### ISSUE TITLE
"sla_threshold" is not expected here in v3

### ISSUE THREAD

**Issue by dribblor** [newrelic/terraform-provider-newrelic#2119]
When migrating from v2.50.2 to 3.7.1, our synthetic scripts can no longer be created, with the error below.

_sla_threshold_ is missing from the docs in 3.00.0 and upwards.

How can we now specify this value to set different apdex bases on a per-synthetic basis.

`Error: Unsupported argument

  on Hiscox_plus.tf line 118, in resource "newrelic_synthetics_script_monitor" "my_mon":
 118:   sla_threshold    = 4

An argument named "sla_threshold" is not expected here.`

### Terraform Version
0.14.8

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_synthetics_script_monitor`

### Terraform Configuration
`terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.7"
    }
  }
}

provider "newrelic" {
  
  account_id = "1234567"
  api_key    = "NRAK1234"
  region     = "EU"
}`

### Actual Behavior
Error saying **sla_threshold not expected here**.

### Expected Behavior
Synthetic script monitor is created without errors with an apdex score

### Steps to Reproduce
Have an existing synthetic script monitor with an sla_threshold created in v2. Follow the [migration guide](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v3) to update to v3.

**Comment by mbazhlekova** [comment]
Hi @dribblor 👋 v3 of the TF Provider uses the new Synthetics API which removed the `sla_threshold` value so we removed it from TF.
