### ISSUE TITLE
Webhook custom payload alert channels must be replaced

### ISSUE THREAD

**Issue by dribblor** [newrelic/terraform-provider-newrelic#2124]
### Summary

We create `newrelic_alert_channel` resources of type "webhook" using the "payload_string" attribute **instead of** "payload", and we **do not** set a "header".

Whenever a terraform plan runs, it detects changes to "headers" and "payload" and tries to recreate the whole alert channel resource which we don't want.

A knock-on effect of this is the alert channel has a new id, which means all the `newrelic_alert_policy` resources are also recreated.

### Terraform Version
0.14.8

### Affected Resource(s)
- `newrelic_alert_channel`
- `newrelic_alert_policy`

### Terraform Configuration
```hcl
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.7"
    }
  }
}

provider "newrelic" {
  
  account_id = "1234567"
  api_key    = var.nr_api_key
  region     = "EU"
}

resource "newrelic_alert_channel" "teams" {
  name = "teams_webhook"
  type = "webhook"
  config {
    base_url       = "https://myorg.webhook.office.com/webhookb2/reallylongguid@reallylonguuid/IncomingWebhook/anotherlongid/anotherlongidagain"
    payload_type   = "application/json"
    payload_string = var.payload_string
  }
}
```

I also tried it with headers and payload ignored. When these are ignored, the plan no longer tries to recreate the resources, but now unfortunately it no longer detects differences so it doesn't bring the new relic custom payload back in line with the terraform. E.g. if i change the custom payload in the One portal and run the plan again, it says no changes.

```hcl
  lifecycle {
    ignore_changes = [
      config["headers"],
      config["payload"],
    ]
  }
```

### Actual Behavior
New relic tries to recreate alert channels along with policies referencing that channel.

```hcl
  # newrelic_alert_channel.devops_teams must be replaced
-/+ resource "newrelic_alert_channel" "my_team" {
      + account_id = (known after apply)
      ~ id         = "372175" -> (known after apply)
        name       = my_webhook"
        # (1 unchanged attribute hidden)

      ~ config {
          - headers        = (sensitive value)
          - payload        = (sensitive value)
          ~ payload_string = (sensitive value)
            # (2 unchanged attributes hidden)
        }
    }

  # newrelic_alert_policy.Azure_vm_host must be replaced
-/+ resource "newrelic_alert_policy" "my_policy" {
      ~ account_id          = 1234567 -> (known after apply)
      ~ channel_ids         = [
          - 351927,
          - 372175,
        ] -> (known after apply) # forces replacement
      ~ id                  = "850235" -> (known after apply)
        name                = My Policy"
        # (1 unchanged attribute hidden)
    }

```

### Expected Behavior
Alert channels should not be recreated

### Steps to Reproduce
1. Create an alert channel using a custom payload (payload_string)
2. Run a terraform plan and terraform apply

### Important Factoids
New Relic provider is 3.7.1. This same behaviour happend in 2.50.2 as well.

**Comment by ChandraIragavarapu** [comment]
@dribblor , As `newrelic_alert_channel` is deprecated and EOL is on [June 2023](https://github.com/newrelic/terraform-provider-newrelic/issues/2286), we recommend you to use workflows

**Comment by pranav-new-relic** [comment]
Hi @dribblor - we haven’t heard back from you in a long time so we'll close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue. Thanks!
