### ISSUE TITLE
newrelic_entity data source cannot lookup OTEL services

### ISSUE THREAD

**Issue by harkeet** [newrelic/terraform-provider-newrelic#2135]
### Terraform Version

```
Terraform v1.3.2
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.8.0
```

### Affected Resource(s)

- `newrelic_entity` data resource

### Terraform Configuration

```hcl
provider "newrelic" {
  account_id = var.newrelic_account_id
  api_key    = var.newrelic_apikey
  region     = var.newrelic_region
}

terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
    }
  }
}
```

```hcl
data "newrelic_entity" "otel_app" {
  name = "otel-app-to-search"
  tag {
    key   = "accountId"
    value = data.vault_generic_secret.newrelic.data["account_id"]
  }
  domain = "APM"
  type   = "APPLICATION"
  ignore_case = true
}
```

Querying the service details from NerdGraph API explorer with following query-

```
{
  actor {
    user {
      name
    }
    entitySearch(query: "name LIKE 'otel-app-to-search'") {
      count
      results {
        entities {
          name
          type
          domain
        }
      }
    }
  }
}
```
Query output shows that domain and type is now different that what it is present in TF state.

```
{
  "data": {
    "actor": {
      "entitySearch": {
        "count": 1,
        "results": {
          "entities": [
            {
              "domain": "EXT",
              "name": "otel-app-to-search",
              "type": "SERVICE"
            }
          ]
        }
      }
    }
  }
}
```

### Actual Behavior

When using `domain = "APM"` and  `type   = "APPLICATION"`, we get following error message

```
Error: the name 'otel-app-to-search' does not match any New Relic One entity for the given search parameters (ignore_case: true)
│   with module.newrelic.data.newrelic_entity.otel_app["otel-app-to-search"]
```

and when using `domain = "EXT"` and  `type   = "SERVICE"`, we get following error message as these values are not supported by latest version of the provider.

```
│ Error: expected domain to be one of [APM BROWSER INFRA MOBILE SYNTH VIZ], got EXT
│ Error: expected type to be one of [APPLICATION DASHBOARD HOST MONITOR WORKLOAD], got SERVICE
```

### Expected Behavior

Entity with the name specified should have returned.

**Comment by Spagette** [comment]
This same issue happens when trying to grab type "AWSLAMBDAFUNCTION". Is there plans to add the rest of the types from within New Relic?

**Comment by kidk** [comment]
There's an example in our docs on how to lookup a Otel entity:

```
data "newrelic_entity" "app" {
  name = "my-otel-app"
  domain = "EXT"
  tag {
    key = "accountID"
    value = "12345"
  }
}
```

We have plans to improve the resource soon, so it's able to use the raw `query` instead of `queryBuilder` which will add support for all types and domains.

**Comment by sanderblue** [comment]
Hi @Spagette, per @kidk's comment, we recently released an update to how we query for an entity in the `newrelic_entity` data source.

Can you try again with the latest version [**v3.16.1**](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.16.1)?

Please let us know if this is working for you after upgrading. Thanks! 🙂

**Comment by Spagette** [comment]
Yes, I tried again and was able to filter to the "AWSLAMBDAFUNCTION" type. Thanks for the update!

**Comment by NSSPKrishna** [comment]
@Spagette Thank you for the feedback. I'm closing this issue. Please raise a new issue if you have any further queries or issues.
