### ISSUE TITLE
Import Resource newrelic_synthetics_monitor Return unmarshal JSON Error

### ISSUE THREAD

**Issue by ahmedmabrouk56** [newrelic/terraform-provider-newrelic#2137]
### Terraform Version
```
Terraform v1.3.6
on windows_386
+ provider registry.terraform.io/newrelic/newrelic v3.8.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_synthetics_monitor`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
provider "newrelic" {
  account_id = var.newrelic_account_id
  api_key    = var.newrelic_apikey
  region     = var.newrelic_region
}

terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
    }
  }
}

resource "newrelic_synthetics_monitor" "monitor" {

}
```

### Actual Behavior
When we ran `terraform import newrelic_synthetics_monitor.monitor <id>` it works fine for a couple of our resources, but for the majority, we got the below error
```
Error: json: cannot unmarshal number 0123456789 into Go struct field entityResponse.data.actor of type int
```
We Enabled `TF_LOG="DEBUG"` and below is the detailed error message
```
[ERROR] provider.terraform-provider-newrelic_v3.7.0.exe: Response contains error diagnostic: @caller=/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/diag/diagnostics.go:56 diagnostic_detail= diagnostic_severity=ERROR tf_resource_type=newrelic_synthetics_monitor @module=sdk.proto diagnostic_summary="json: cannot unmarshal number 0123456789 into Go struct field entityResponse.data.actor of type int" tf_proto_version=5.3 tf_provider_addr=provider tf_req_id=<id> tf_rpc=ReadResource timestamp=2022-12-01T17:21:32.438+0200
```
We changed the number for security reasons

This Number was the value of `recentAlertViolations->violationId`

**Again, this works fine with many synthetics monitors but still fails with much more**

### Expected Behavior
we expect the resource to be imported to our tfstate file with the below message
```
Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform import newrelic_synthetics_monitor.monitor <id>`

### Debug Output
[Terraform Debug output](https://gist.github.com/ahmedmabrouk56/05f9f23fef7a761d0d83ec176b4256b2)

**Comment by mbazhlekova** [comment]
@ahmedmabrouk56 We've been looking into this issue and having trouble reproducing it. Are you by any chance running a 32 bit system? This might be an overflow issue if that's the case.

**Comment by ahmedmabrouk56** [comment]
@mbazhlekova I'm running an x64-based PC, and I agree you couldn't reproduce the issue, as I mentioned, I have tried to import about 250 Synthetics monitors and 100 got imported successfully, and about 150 got failed because of this error.

**Comment by sanderblue** [comment]
@ahmedmabrouk56 we've learn that Terraform is sometimes downloading the 32bit version for some reason. If you're still seeing the issue, can you see if that's the case here?

**Comment by sanderblue** [comment]
Confirmed this issue was due to the 32-bit version of Terraform being downloaded on a 64-bit machine.
