### ISSUE TITLE
newrelic_workflow channel_id not found

### ISSUE THREAD

**Issue by ciechonp** [newrelic/terraform-provider-newrelic#2145]
- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
Terraform v1.1.9

### Affected Resource(s)
- `newrelic_workflow`
- `newrelic_notification_channel`
- `newrelic_notification_destination`

### Terraform Configuration
provider.tf
```
locals {
  newrelic_secrets = jsondecode(data.aws_secretsmanager_secret_version.newrelic.secret_string)
  license_key      = local.newrelic_secrets["NRAK"]
  account_id = "xxx"
}

data "aws_secretsmanager_secret" "newrelic" {
  name = "xxx"
}

data "aws_secretsmanager_secret_version" "newrelic" {
  secret_id = data.aws_secretsmanager_secret.newrelic.id
}

provider "newrelic" {
  account_id = local.account_id
  api_key    = local.license_key
  region     = "US"
}

```
workflow.tf
```
resource "newrelic_workflow" "foo" {
  name                  = "workflow-example"
  muting_rules_handling = "NOTIFY_ALL_ISSUES"

  issues_filter {
    name = "filter-name"
    type = "FILTER"

    predicate {
      attribute = "accumulations.tag.team"
      operator  = "EXACTLY_MATCHES"
      values    = ["growth"]
    }
  }

  destination {
    channel_id = newrelic_notification_channel.foo.id
  }
}

resource "newrelic_notification_channel" "foo" {
  account_id     = local.account_id
  name           = "webhook-example"
  type           = "WEBHOOK"
  destination_id = newrelic_notification_destination.foo.id
  product        = "ERROR_TRACKING"

  property {
    key   = "payload"
    value = "{name: foo}"
    label = "Payload Template"
  }
}

resource "newrelic_notification_destination" "foo" {
  account_id = local.account_id
  name       = "webhook-example"
  type       = "WEBHOOK"

  property {
    key   = "url"
    value = "https://webhook.site/#!/7b91a230-ff1a-4751-b2ec-592935c7e656/e3538dae-d89a-4157-b65a-7168b4e6d46c"
  }
} 
```

### Actual Behavior

Workflow is not getting created as channel_id is missing.

newrelic_notification_destination.foo: Creating...
newrelic_notification_destination.foo: Creation complete after 1s [id=da608570-5f46-4d3c-a2f6-818a1afcd56e]
newrelic_notification_channel.foo: Creating...
newrelic_notification_channel.foo: Creation complete after 2s [id=f7852796-a86c-4cfb-9328-7f332fb2155a]
newrelic_workflow.foo: Creating...

 Error: INVALID_PARAMETER: A channel with id f7852796-a86c-4cfb-9328-7f332fb2155a was not found

   with newrelic_workflow.foo,
   on newrelic_workflow.tf line 1, in resource "newrelic_workflow" "foo":
    1: resource "newrelic_workflow" "foo" {

### Expected Behavior

Workflow created with previously created channel.

### Steps to Reproduce
`terraform apply`

### Important Factoids
We have also tried to use hardcoded already created from NR GUI destination channel with same error.

**Comment by mxncson** [comment]
Having the same issue, did you found any workaround ?

**Comment by mxncson** [comment]
@ciechonp Fixed the issue on my side.
The `newrelic_notification_channel` product should be `IINT` as indicated [here](https://www.pulumi.com/registry/packages/newrelic/api-docs/notificationchannel/#inputs)

**Comment by ciechonp** [comment]
@mxncson thanks! It is working now.
