### ISSUE TITLE
Enhancements needed so Drop Rules created with terraform can be viewed and accessed using the NR's console UI

### ISSUE THREAD

**Issue by vjcubas** [newrelic/terraform-provider-newrelic#2152]
### Feature Description

We need to be able to achieve the following 
- Set the **name** field when using Graph*I*QL, Terraform, CLI, or REST interface
- Be able to view and access DFRs created with Graph*I*QL, Terraform, CLI, or REST interface in the UI

---
### Describe Alternatives
None that we can think of at this time.

---
### Additional Context
DFR (Drop Filter Rules) can be created via:
- New Relic UI
- NerdGraph

##### New Relic UI Channel
> This channel is acceptable for a small number of DFRs; however, beyond a dozen or two, managing DFRs becomes unsustainable, and it could lead to an inconsistent operational outcome. Also, we cannot view or access DFRs created with Graph*I*QL, Terraform, CLI, or REST interface because the **source** field is set to "NerdGraph," but the UI only shows DFRs whose **source** field is set to **Logging**.

##### NerdGraph
NerdGraph is used in the following scenarios:
- Graph*i*QL Explorer
- Terraform
- REST API calls
- CLI 

DFRs created using any of the above channels result as follows:
1. The **source** field is set to **NerdGraph** which prevents them from being listed in the UI
2. The **name** field is probably not set

---

**Comment by kidk** [comment]
Thanks for request @vjcubas 

I'm afraid we're blocked on this one as the internal team that owns this API is not able to make this field public.

https://github.com/newrelic/terraform-provider-newrelic/issues/1700

If I remember correctly the name field is same as description field in the provider: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_drop_rule

The UI calls it `name` but API uses `description`. 

I'm going to close this as there's nothing we can do right now. Feel free to continue the conversion.
