### ISSUE TITLE
Policy with ID xxxx not found: BAD_USER_INPUT. Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by Praveenmj95** [newrelic/terraform-provider-newrelic#2157]
## But in fact policy is present both in NewRelic dashboard and Terraform state

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version

`Terraform v1.3.2`

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alert_policy`
- `newrelic_nrql_alert_condition`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration

```terraform
terraform {
  # Require Terraform version 0.13.x (recommended)
  #required_version = "~> 0.13.0"
  required_version = "> 1.0.1"

  # Require the latest 2.x version of the New Relic provider
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "> 3.7.0"
    }
  }
}
```

### Actual Behavior
``` 
newrelic_alert_policy.alert_policy_name: Creating...
newrelic_alert_policy.alert_policy_name: Creation complete after 2s [id=3783254]
newrelic_nrql_alert_condition.nrql_alert_condition_high_cpu_utilization: Creating...

╷
| Error : Provider produced inconsistent result after apply
| When applying changes to newrelic_alert_channel.alert_notification_email 
| provider "provider[\"registry.terraform.io/newrelic/newrelic\"]" produced an unexpected new value: Root resource was present, 
| but now absent. 
| This is a bug in the provider, which should be reported in the provider's own issue tracker.
| Error :  Policy with ID 3783254 not found: BAD_USER_INPUT
| Error : resource not found with newrelic_alert_condition.low_apdex_score
```

### Expected Behavior
When I run `terraform apply`, I see planned changes and after approve it should go smoothly and create policy and alert conditions without throwing above errors.

### Steps to Reproduce

1 . Create an `newrelic_alert_policy` resource.
2 . Create multiple  `newrelic_nrql_alert_condition` resources which will be linked to the above alert policy.

### Important Factoids
The error says that ID 3783254 not found but as you can see on the picture below it is exists in New Relic.

```
| Error :  Policy with ID 3783254 not found: BAD_USER_INPUT
|  with newrelic_nrql_alert_condition.nrql_alert_condition_transaction_duration, "newrelic_nrql_alert_condition" 
| on resource.tf line 52, in resource in resource "newrelic_nrql_alert_condition"  "nrql_alert_condition_transaction_duration":
```

Also I see that this policy exists in Terraform state

```
    newrelic_alert_policy.alert_policy_name    will be created      
             resource "newrelic_alert_policy" "alert_policy_name" {
                    account_id                = (known after apply)
                    id                        = (known after apply)
                    incident_preference       = "PER_POLICY"
                    name                      = "REDACTED_POLICY"
  }

```

### References
The above reported issue is same as the issues which have been previously reported. Please find below.

#2071 
#1865

**Comment by pranav-new-relic** [comment]
We haven’t heard back from you in a long time so we will close the ticket - also because this is duplicated by #2071 .If you feel this is still a valid request or bug, feel free to create a new issue.
