### ISSUE TITLE
Creating many `newrelic_service_level` resources generates duplicates

### ISSUE THREAD

**Issue by watson-lovevery** [newrelic/terraform-provider-newrelic#2158]
### Terraform Version

```
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/newrelic/newrelic v3.9.0
```

### Affected Resource(s)
- `newrelic_service_level`

### Terraform Configuration
```hcl
resource "newrelic_service_level" "foo" {
    count = 100
    guid = "ABCDXXXXGUID"
    name = "Latency"
    description = "Proportion of requests that are served faster than a threshold."

    events {
        account_id = 12345678
        valid_events {
            from = "Transaction"
            where = "appName = 'Example application' AND (transactionType='Web')"
        }
        good_events {
            from = "Transaction"
            where = "appName = 'Example application' AND (transactionType= 'Web') AND duration < 0.1"
        }
    }

    objective {
        target = 99.00
        time_window {
            rolling {
                count = 7
                unit = "DAY"
            }
        }
    }
}

```

### Actual Behavior
Deploying multiple service levels in a single plan creates duplicates in new relic. The duplicates are not tracked by terraform, so they still exist after running `terraform destroy`. The duplication gets worse with higher quantities.

My results from a few rounds of testing:
`count=10`: No duplicates
`count=20`: 1-4 duplicates
`count=100`: 70-75 duplicates
`count=441`: Deployed 268/441 before hitting the new relic service level cap of 500 & failing, meaning 232 duplicates were generated.

### Expected Behavior
No duplicates should be created, and all service levels created by terraform should remain tracked/managed by terraform

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Debug Output
I forgot to check exact pre/post apply numbers, but this run generated 70-75 duplicates, same as the previous 3 runs at this size.
https://gist.github.com/watson-lovevery/c321662f40a67942b08530572a59075f

### Important Factoids
We're using `for_each` to generate our service levels, which causes the same behavior as using `count` like in the example above. No errors in either case.

**Comment by NSSPKrishna** [comment]
Hi @watson-lovevery thank you for raising the issue. We will try to reproduce it.

**Comment by watson-lovevery** [comment]
Hi @NSSPKrishna , any updates here?

**Comment by NSSPKrishna** [comment]
Hi @watson-lovevery, sorry for the late response. I am unable to reproduce this issue. Could you please try `terraform apply` with parallelism=1 ?

**Comment by NSSPKrishna** [comment]
”We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.”
