### ISSUE TITLE
Improve error message on incorrect guid (JIRA request)

### ISSUE THREAD

**Issue by kidk** [newrelic/terraform-provider-newrelic#2176]
**Shared with us on public JIRA** Moved to Github for tracking.

> When running "terraform import newrelic_synthetics_private_location.location GUID" with an incorrect GUID argument, I get this error message:
> 
> Error: Argument "guid" has invalid value $guid. 
> It looks like it's supposed to dereference a variable but is treating it as a literal instead, so I get the variable's name in the error message rather than its value.
> 
> 
> When I got this error message I did not know that the value I was passing in as the GUID argument was incorrect, so this error message misled me by making it look like something in the API was broken and it wasn't correctly using the GUID I gave it.  If the error message had, correctly, shown me the value that I passed in and told me that was invalid, I would have know what the problem was more quickly.
> 
> Please fix this so that the error message shows the value that is invalid.
>

**Comment by kidk** [comment]
Ref: https://github.com/newrelic/terraform-provider-newrelic/pull/2177/files

**Comment by NSSPKrishna** [comment]
Fix available in version v3.12.0.
