### ISSUE TITLE
No 3.x Migration Guide

### ISSUE THREAD

**Issue by jevon71-work** [newrelic/terraform-provider-newrelic#2187]
### Feature Description
There does not appear to be a migration guide from 2.x to 3.x

### Additional context
There are a number of issues when attempting to upgrade from version 2.x to 3.x - e.g. https://github.com/newrelic/terraform-provider-newrelic/issues/2020.  It would be nice to see a list of steps you need to take for differing resources in order to upgrade from 2.x to 3.x

**Comment by jevon71-work** [comment]
Never mind - found the (not so useful) migration guide for synthetics.

**Comment by kidk** [comment]
Thanks for reaching out @jevon71-work I'd love to hear what you feel is missing from our guide. We're always looking to improve our documentation so any feedback is more than welcome.
