### ISSUE TITLE
can't create an empty newrelic_notification_destination resource

### ISSUE THREAD

**Issue by hokugawa** [newrelic/terraform-provider-newrelic#2196]
Trying to use slack destination with workflow, so I tried to create an empty resource as doc mentioned (https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination#additional-examples).
However, terraform requires more arguments and a property block, hence I got stuck.

I tried with several newrelic provider version, but so far, no luck.

### Terraform Version
```
> terraform -v
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.11.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_notification_destination`

### Terraform Configuration

main.tf

```
terraform {
  required_version = ">= 0.13.0"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.11.0"
    }
  }
}

provider "newrelic" {
    account_id = ***
    api_key    = "***"
    region     = "US"
}

resource "newrelic_notification_destination" "foo" {}
```

### Actual Behavior
When I ran `terraform plan` with the above main.tf. tf outputs the following errors.

```
╷
│ Error: Missing required argument
│
│   on main.tf line 17, in resource "newrelic_notification_destination" "foo":
│   17: resource "newrelic_notification_destination" "foo" {}
│
│ The argument "name" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   on main.tf line 17, in resource "newrelic_notification_destination" "foo":
│   17: resource "newrelic_notification_destination" "foo" {}
│
│ The argument "type" is required, but no definition was found.
╵
╷
│ Error: Insufficient property blocks
│
│   on main.tf line 17, in resource "newrelic_notification_destination" "foo":
│   17: resource "newrelic_notification_destination" "foo" {}
│
│ At least 1 "property" blocks are required.
╵
```

### Expected Behavior
No error

### Steps to Reproduce
1. `terraform plan` with the above main.tf

### Debug Output
-

### Panic Output
-

### Important Factoids
-

### References
-

**Comment by lzaga-newrelic** [comment]
Hi @hokugawa ,
As you can see in the docs, you first add an empty resource only to your code, and then you **import** a Slack destination to it:

> 1. Add an empty resource to your terraform file:
resource "newrelic_notification_destination" "foo" {
}
> 2. Run import command: terraform import newrelic_notification_destination.foo <destination_id>

**Comment by hokugawa** [comment]
@lzaga-newrelic I tried but I couldn't create an empty resource as I described in the description. Did you try to reproduce the problem?

**Comment by lzaga-newrelic** [comment]
@hokugawa If you try to `terraform apply` after adding this resource to your code, then you shouldn't.
You just need to write this empty resource in the terraform file, **not** run `terraform apply` but `terraform import` instead.

**Comment by hokugawa** [comment]
@lzaga-newrelic ah, got it. Thanks!  After importing it, what is the best way to update the main.tf to reflect the imported status?

**Comment by hokugawa** [comment]
nvm looks like the doc has been updated. closing this.
