### ISSUE TITLE
newrelic_synthetics_alert_condition: resource not found

### ISSUE THREAD

**Issue by wuetz** [newrelic/terraform-provider-newrelic#2201]
Hi there,

I'm facing an issue with the `newrelic_synthetics_alert_condition` resource and receive an `resource not found` error.  

I wanted to have a an alert condition (of type "Synthetics") where the monitor is one of my synthetic monitors (which are type of Scripted API).  
This is possible if I do it via the WebGUI. But as soon as I try it with Terraform it will fail.

### Terraform Version
Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.36.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/newrelic/newrelic v3.12.0

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)
- `newrelic_synthetics_alert_condition` here the error occures

### Terraform Configuration  
```hcl
resource "newrelic_synthetics_script_monitor" "script_api" {
  name   = "monitor"
  period = "EVERY_10_MINUTES"
  type   = "SCRIPT_API"
  status = "ENABLED"
  script = REDACTED
  account_id = "REDACTED"
  script_language      = ""
  runtime_type         = ""
  runtime_type_version = ""

  location_private {
    guid = REDACTED
  }
  tag {
    key    = "Name"
    values = ["monitor"]
  }

  tag {
    key    = "Environment"
    values = [var.env]
  }
}

data "newrelic_entity" "synthetic_monitor" {  
  name   = "monitor"
  type   = "MONITOR"
  domain = "SYNTH"
}

resource "newrelic_synthetics_alert_condition" "this" {
  policy_id   = "REDACTED"
  name        = "synthetics"
  monitor_id  = data.newrelic_entity.synthetic_monitor.guid
}
```

### Actual Behavior
```hcl
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.check.newrelic_synthetics_alert_condition.this will be created
  + resource "newrelic_synthetics_alert_condition" "this" {
      + enabled    = true
      + id         = (known after apply)
      + monitor_id = "MzQ2ODE4MnxTWU5USHxNT05JVE9SfGFlZDQ4ZTc2LThiMDQtNGYyYy1iNmVhLTZjMGY4MmI1MTI3Ng"
      + name       = "synthetics"
      + policy_id  = 879053
    }
Plan: 1 to add, 0 to change, 0 to destroy.
```  

after the apply:  

```hcl
╷
│ Error: resource not found
│
│   with module.check.newrelic_synthetics_alert_condition.this,
│   on .terraform/modules/check/new-relic-tcp-port-check/alert.tf line 44, in resource "newrelic_synthetics_alert_condition" "this":
│   44: resource "newrelic_synthetics_alert_condition" "this" {
│
╵
```  

The mentioned `monitor_id` above does match the synthetic monitor and the policy_id is correct. So I don't know where this error happens.

### Expected Behavior  

I wanted to have a an alert condition (of type "Synthetics") where the monitor is of type of a synthetic script.

### Steps to Reproduce  

Create the above resources and try to `apply`  

### Debug Output  

Enabled the terraform debugging, but there nothing special could be found which leads to further information.

**Comment by pranav-new-relic** [comment]
We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.
