### ISSUE TITLE
Provider Produced an Unexpected New Value for newrelic_one_dashboard during Refresh after Upgrade

### ISSUE THREAD

**Issue by tcgbrett** [newrelic/terraform-provider-newrelic#2204]
- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
```
terraform -v
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.12.0
```

### Affected Resource(s)
- `newrelic_one_dashboard`

### Terraform Configuration
[Dropbox Link](https://www.dropbox.com/s/kptanoqum6g3oz8/minimal-dashboard%203.zip?dl=0) - Includes `crash.log`, tfstate (no secrets), and all config

### Actual Behavior
Tried to upgrade from provider 2.36.2 -> 3.12.0 for new features. All I ran was a `plan`, but a panic happens related to `/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_one_dashboard.go:768`. This happened in my main repo which has 15+ production dashboards. I made a new repo with a minimum viable [failure] dashboard. Essentially what you need is:
* More than 1 page
* critical/warning setting on Billboard tile

### Expected Behavior
Shouldn't have panicked, and should've just accepted the current state from NR.

### Steps to Reproduce
1. Use NR provider 2.36.2 in main.tf
2. TF apply the dashboard to your account
3. Switch to provider 3.12.0 and run `tf init -upgrade` to get the new provider
4. TF plan
5. Failure

### Debug Output
Included in DB link above

### Panic Output
Included in DB link above

### Important Factoids
Just the fact that it requires +1 page (easily observed via code path). I was first using 0.14.0 of TF and it actually gave me a great output in the logs - 
```
2023/01/13 13:26:40 [WARN] Provider "registry.terraform.io/newrelic/newrelic" produced an unexpected new value for module.dashboards.newrelic_one_dashboard.SRE---Admin---NR-Synthetics-Overview during refresh.
      - .page[0].widget_billboard[0].warning: was cty.StringVal("0"), but now cty.StringVal("")
      - .page[0].widget_billboard[0].critical: was cty.StringVal("0"), but now cty.StringVal("")
```

### References
I didn't find any related issues

**Comment by kidk** [comment]
Thanks for all the information @tcgbrett I think I've spotted the issue.

The API seems to be returning a `null` value for the `CRITICAL` threshold which our code is not handling at the moment.  
```
"thresholds": [
          {
           "alertSeverity": "CRITICAL",
           "value": null
          },
          {
           "alertSeverity": "WARNING",
           "value": 0.1
          }
]
```

```
if len(rawCfg.Thresholds) > 0 {
  for _, v := range rawCfg.Thresholds {
    // No null check in sight 👀 
    switch v.AlertSeverity {
	case entities.DashboardAlertSeverityTypes.CRITICAL:
		out["critical"] = strconv.FormatFloat(*v.Value, 'f', -1, 64)
	case entities.DashboardAlertSeverityTypes.WARNING:
		out["warning"] = strconv.FormatFloat(*v.Value, 'f', -1, 64)
    }
  }
}
```
Reference code: https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/structures_newrelic_one_dashboard.go#L767

I have a PR ready, but I want to get it validated by the team.

Thanks again for the detailed report. It helped a lot pinpointing the issue.

**Comment by tcgbrett** [comment]
Hey @kidk - I just saw your comment. Thank you for digging into this so rapidly! I saw the update in the new 3.13.0 version. I greatly appreciate it :)
