### ISSUE TITLE
Error: UNAUTHORIZED: Required capability not found

### ISSUE THREAD

**Issue by shaharr-ma** [newrelic/terraform-provider-newrelic#2205]
- [X] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [X] A list of [affected resources](#affected-resources) and/or data sources
- [X] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [X] Description of the [current behavior](#actual-behavior) (the bug)
- [X] Description of the [expected behavior](#expected-behavior)

### Terraform Version
Terraform v0.13.5

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_synthetics_script_monitor`

### Terraform Configuration
provider "newrelic" {
  account_id = my-account-id
  api_key    = NRII-xxxxxxxxxxx 
}

### Actual Behavior
Any `newrelic_synthetics_script_monitor` resource creation failed due to `Error: UNAUTHORIZED: Required capability not found.`. No issue with non-synthetics resources.

### Expected Behavior
Create `newrelic_synthetics_script_monitor` resources.

### Steps to Reproduce
Init and apply `newrelic_synthetics_script_monitor` resource using the above TF and Provider versions.

**Comment by kidk** [comment]
Thanks for report @shaharr-ma 

Which version of our provider are you using?

**Comment by shaharr-ma** [comment]
> Thanks for report @shaharr-ma
> 
> Which version of our provider are you using?

3.12.0

**Comment by shaharr-ma** [comment]
Hi, any update on this?

**Comment by kidk** [comment]
This looks like an API permission issue. I'll ask internally to see where this is coming from.

**Comment by kidk** [comment]
@shaharr-ma It seems you don't have the right permissions on your API key to create or update Synthetic checks, so this isn't a Terraform issue. I'll close the ticket for now, but let us know if you need any more help.

**Comment by shaharr-ma** [comment]
Hi @kidk - what permissions is missing ? when creating a new key there is no any option to set the permission type but just key type: user, ignest - license, ingest - browser.

**Comment by kidk** [comment]
@shaharr-ma It's linked to your user, so you either need to ask your admin to add the Synthetics permissions, or do it yourself if you can.

Here are some documentation links that should help:
- https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts/#capabilities
- https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/user-capabilities/
