### ISSUE TITLE
newrelic_account data source should work defaulting to NEW_RELIC_ACCOUNT_ID env without providing account_id or name

### ISSUE THREAD

**Issue by trunet** [newrelic/terraform-provider-newrelic#2215]
Using `newrelic_account` data source should use by default NEW_RELIC_ACCOUNT_ID environment variable as a default instead of having to specify any parameter.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
```
❯ terraform -v
Terraform v1.2.9
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.13.0
```

### Affected Data Source
- `newrelic_account`

### Terraform Configuration
```hcl
terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
      version = "3.13.0"
    }
  }
}

provider "newrelic" {
}

data "newrelic_account" "acc" {
  scope = "global"
}

output "newrelic_accout_id" {
  value = data.newrelic_account.acc.account_id
}
```

### Actual Behavior
```
❯ terraform apply
data.newrelic_account.acc: Reading...
╷
│ Error: one of "name" or "account_id" is required to locate a New Relic account
│
│   with data.newrelic_account.acc,
│   on newrelic.tf line 14, in data "newrelic_account" "acc":
│   14: data "newrelic_account" "acc" {
│
```

### Expected Behavior
It should work using `NEW_RELIC_ACCOUNT_ID` environment variable.

### Steps to Reproduce
1. Set NEW_RELIC_ACCOUNT_ID environment variable to you new relic account id
2. `terraform apply`

**Comment by pranav-new-relic** [comment]
Hi, this feature has been released with the latest version of Terraform, [v3.22.0](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.22.0). Closing this issue, thank you for reporting.
