### ISSUE TITLE
feature: dashboard template variables

### ISSUE THREAD

**Issue by TheQueenIsDead** [newrelic/terraform-provider-newrelic#2217]
### Feature Description
Templated variables have recently (ish) been added to NewRelic dashboards per this blogpost:
https://newrelic.com/blog/how-to-relic/dashboard-template-variables

This is a really exciting feature that had been missing for a while, and I would love to start using it on our dashboards.

This does not seem to be supported in the `newrelic_one_dashboard*` resources currently. 

### Describe Alternatives
I can create statically configured dashboards, but the power of the templates is the dynamicism that populates the drowpdowns.

### Additional context
I understand that we may need to wait for functionality to be exposed in the client, is it worth opening an issue upstream?
https://github.com/newrelic/newrelic-client-go/

**Comment by kidk** [comment]
It's already available in the `newrelic_one_dashboard` and `newrelic_one_dashboard_json` resource: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#nested-variable-blocks 

Is this what you were looking for?

**Comment by kidk** [comment]
If you're able to migrate to `newrelic_one_dashboard_json` I would advise it as the functionality is very close to `newrelic_one_dashboard_raw`, but it benefits from quickly getting the latest dashboard features. If that's not possible we can explore adding the variables to `newrelic_one_dashboard_raw`.

**Comment by TheQueenIsDead** [comment]
Ah I see, we templates our dashboards before the json resource was available, seems quite recent:
https://github.com/newrelic/terraform-provider-newrelic/commits/main/newrelic/structures_newrelic_one_dashboard_json.go

I'll try convert the dashboards over to JSON, I think the big reason we used RAW was for custom widgets / vizualizations.
As long as we can maintain that it'll be a suitable way forwards 👍 

Will report back here once confirmed

**Comment by TheQueenIsDead** [comment]
Hmm, I'm really not liking what I see so far :sweat_smile: 

Looks like there is no useful diff reported, though I suppose a Git PR allows for a chance to see the change before it's rolled.
The biggest downside to lack of diff is that changes made via UI can not easily be isolated and merged in when Terraform checks for changes made outside of the module.

AFAICT the proposed workflow with the JSON dashboards is to tweak in the UI then (Assuming a dashboard is repeated a few times), override the file and re-interpolate account id's etc?

**Comment by TheQueenIsDead** [comment]
Huh, on further testing, it's capable of isolating the difference in changes lines in JSON, I'm not sure why it spat out a change with every line as "new" on initial apply, might have been a quirk.

I think we can work with this, thanks for the suggestion :-) And apologies for seemingly jumping to conclusions there!

**Comment by kidk** [comment]
@TheQueenIsDead 

> AFAICT the proposed workflow with the JSON dashboards is to tweak in the UI then (Assuming a dashboard is repeated a few times), override the file and re-interpolate account id's etc?
That or making the changes manually in the JSON, but it's a lot harder to do as the JSON format isn't documented anywhere as far as I know. You could look at the `newrelic_one_dashboard` resource as the attributes are close to the JSON format, but not always exactly the same. 

> Huh, on further testing, it's capable of isolating the difference in changes lines in JSON, I'm not sure why it spat out a change with every line as "new" on initial apply, might have been a quirk.
The way our `newrelic_one_dashboard_json` works is by comparing `updated_at` on the API side. So it's not doing a full compare of the remote and local json, mostly because the formats are widely different. I've been thinking about making that diff, but without adding a bunch of error prone code it's going to be hard to do. 

> I think we can work with this, thanks for the suggestion :-) And apologies for seemingly jumping to conclusions there!
No worries, happy you got it sorted out. Please let us know if you encounter any other issues or questions.
