### ISSUE TITLE
Issue with newrelic_entity data source when a single quote is present in the entity name

### ISSUE THREAD

**Issue by lauracraciun90** [newrelic/terraform-provider-newrelic#2223]
Terraform Version
v0.14.11

Affected Resource(s)
Please list the resources as a list, for example:

`data newrelic_entity`

Terraform Configuration
Please include your provider configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.

```
data newrelic_entity kubernetes_default_replicaset {
  name = "ReplicaSet doesn't have desired amount of pods"
}
```

Actual Behavior
Error: Provided filter: [name LIKE 'ReplicaSet doesn't have desired amount of pods'] is not a valid NRQL query

Expected Behavior
Should be able to escape the single quote automatically.

Steps to Reproduce

Implement a data source for retrieving information about an entity which already exists in Newrelic.
Ensure the spelling of the alert condition in both the Terraform code and Newrelic matches and has a single quote in its name, just like in the example above.
Terraform fails to generate a plan in this case because it considers the NRQL query not valid due to the spelling of the word "doesn't".

Thanks.

**Comment by NSSPKrishna** [comment]
Hi @lauracraciun90 thanks for raising the issue. We will try to reproduce it.

**Comment by lauracraciun90** [comment]
Hi @NSSPKrishna, no worries at all, thank you! Please let me know should you need further information.

**Comment by NSSPKrishna** [comment]
@lauracraciun90 we were able to reproduce it. Raised a ticket in our backlog to resolve it.

**Comment by pranav-new-relic** [comment]
Hi @lauracraciun90 , the issue has now been resolved. You can now try using the `newrelic_entity` data source with a single quote in the name of the entity, with the latest Terraform provider release, v3.20.0. Closing this issue, as we've tested this too, with the latest Terraform provider comprising the fix, and it now works fine (more details below)

**Terraform Configuration**
```
data "newrelic_entity" "sample_newrelic_entity" {
  name = "App with ' in it"
}
```

**Results upon running `terraform plan`**
```
user % terraform plan
data.newrelic_entity.sample_newrelic_entity: Reading...
data.newrelic_entity.sample_newrelic_entity: Read complete after 2s [id=REDACTED]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

```
