### ISSUE TITLE
Add Widget `units` to newrelic_one_dashboard

### ISSUE THREAD

**Issue by tcgbrett** [newrelic/terraform-provider-newrelic#2242]
### Feature Description
It would be awesome if Units were added into widgets of type viz.line. This is a very desirable feature that's been requested from NR for a long time, and it's great that we have them. But, it's unfortunate to manage dashboards at scale and have to manually update every Response Time graph to say `ms`.

### Describe Alternatives
Maybe use the dashboard_json, but then that doesn't allow for filter_current_dashboard, which is another critical feature.

**Comment by pranav-new-relic** [comment]
Hi @tcgbrett - this feature is now live, please check with the latest version of the Terraform Provider. You can find details on the same here in the [documentation](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#nested-units-blocks). Thanks for reporting this issue!

cc @RavitejaSurampudi
