### ISSUE TITLE
customer headers are not assigning for newrelic_notification_channel with webhooks

### ISSUE THREAD

**Issue by Gobikannan** [newrelic/terraform-provider-newrelic#2246]
Hi there,

- [x] Your New Relic `provider` (sensitive details redacted)
- [x ] A list of affected resources
- [x] The configuration of the resources and/or data sources related to the bug report 
- [x] Description of the bug
- [x] Description of the expected behavior
- [x] Any related log output

### Terraform Version
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/newrelic/newrelic v3.12.0

### Affected Resource(s)
Please list the resources as a list:
- `newrelic_notification_channel`

### Terraform Configuration
terraform {
  required_version = "~> 1.0"

  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
      version = "3.12.0"
    }
  }
}

provider "newrelic" {
  account_id = var.nr_account_id # Your New Relic account ID
  api_key    = var.nr_api_key    # Your New Relic user key
  region     = var.nr_region    # US or EU (defaults to EU)
}

### Actual Behavior
It is not adding customer headers to webhook channel

### Expected Behavior
It should add customer headers to webhook channel

### Steps to Reproduce
Create a webhook destination and attach it to the channel (below is the example code) then do `terraform apply`.

resource "newrelic_notification_destination" "nr_webhook_destination" {
  account_id = var.nr_account_id
  name       = "test Destination"
  type       = "WEBHOOK"
  property {
    key   = "url"
    value = var.alert_webhook_url
  }
}

resource "newrelic_notification_channel" "nr_webhook_destination_channel" {
    account_id     = var.nr_account_id
    name           = "test Adapter Channel"
    type           = "WEBHOOK"
    destination_id = var.destination_id
    product        = "IINT" 
    property {
      key   = "payload"
      value = file(var.alert_webhook_payload_file_name)
      label = "Payload Template"
    }
    
    dynamic "property" {
      for_each = { for index, header in var.headers : index => header }
      content {
        key = property.value.key
        label = "headers"
        value = property.value.value
      }
    }
  }

### Debug Output
 here is the terraform plan for above code,
 module.alert_webhook_destination_channel_wrapper[0].module.alert_webhook_destination_channel_wrapper[1].newrelic_notification_channel.nr_webhook_destination_channel will be created
  + resource "newrelic_notification_channel" "nr_webhook_destination_channel" {
      + account_id     = redacted
      + active         = true
      + destination_id = (known after apply)
      + id             = (known after apply)
      + name           = "test Adapter Channel"
      + product        = "IINT"
      + status         = (known after apply)
      + type           = "WEBHOOK"

      + property {
          + key   = "Content-Type"
          + label = "headers"
          + value = "application/json"
        }
      + property {
          + key   = "X-SERVICE-AK"
          + label = "headers"
          + value = "test"
        }
      + property {
          + key   = "payload"
          + label = "Payload Template"
          + value = <<-EOT
                {
                        "issueid": {{ json issueId }}
                }
            EOT
        }
    }

![Webhook channel](https://user-images.githubusercontent.com/2910744/218719891-a123ec7f-174e-47f4-8d08-e686473bc92d.png)

**Comment by lzaga-newrelic** [comment]
Hi @Gobikannan ,
Do you get any errors while applying?

Also, there should be only one property of headers and all of the headers should be chained in one JSON string for example:
```
  property {
    key = "headers"
    value = "{\"header1\": \"value1\", \"header2\": \"value2\"}"
  }
```

**Comment by Gobikannan** [comment]
Hi @lzaga-newrelic - No errors though. I will try this and let you know. Thanks.

**Comment by m4t22** [comment]
Solution proposed by @lzaga-newrelic worked for me! Provider version: 3.14.0.

**Comment by Gobikannan** [comment]
Thanks @lzaga-newrelic, this worked.
