### ISSUE TITLE
Add other polling integrations to `newrelic_cloud_aws_integrations` resource

### ISSUE THREAD

**Issue by nedl86** [newrelic/terraform-provider-newrelic#2253]
### Feature Description
The `newrelic_cloud_aws_integrations` resource currently only supports configuring the integrations _not_ supported by CloudWatch Metric Streams. For companies/teams who can't (or won't) use Metric Streams, this limits their ability to define and manage their New Relic <> AWS integrations via Terraform.

It would be great to see the provider updated to support managing all of the AWS integrations that are configurable via the `cloudConfigureIntegration` mutation in Nerd Graph.

### Describe Alternatives
No alternative that I'm aware of, apart from calling Nerd Graph directly or falling back to click-ops via the New Relic UI.

### Additional context
The AWS Polling integrations are still a supported option (and [the doco](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/connect-aws-new-relic-infrastructure-monitoring/) even links to this provider) and commonly used by customers, so it makes sense to have first-class Terraform support for them.

**Comment by muhd-aslm** [comment]
Yes, people who want to employ the polling approach really require this. It would be preferable if terraform could be used to integrate polling for all AWS services that are available via newrelic UI.

**Comment by pranav-new-relic** [comment]
Hi @nedl86 @muhd-aslm - all AWS integrations available in the NerdGraph API (to support AWS integration via API Polling) have been added to the latest release of the Terraform Provider, [v3.24.0](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.24.0). Please check out the [docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/cloud_aws_integrations) of this resource for more details.

Closing this issue, thank you for reporting.

(ref: [latest comment](https://github.com/newrelic/terraform-provider-newrelic/issues/2258#issuecomment-1568092460) posted on [this similar issue](https://github.com/newrelic/terraform-provider-newrelic/issues/2258))
