### ISSUE TITLE
`newrelic_notification_destination` data source is empty

### ISSUE THREAD

**Issue by ianpushee** [newrelic/terraform-provider-newrelic#2257]
We're trying to use the `newrelic_notification_destination` data source to create a `newrelic_notification_channel` from an existing destination (so we can assign it to a workflow). It appears that this datasource never actually loads any resource information from New Relic -- the resource is empty always empty, and no error is given when a non-sense [destination] id is provided (unlike other types of datasources we use elsewhere). 

### Terraform Version
Terraform v1.3.6
+ provider registry.terraform.io/newrelic/newrelic v3.14.0

### Affected Resource(s)
- `newrelic_notification_destination` (data source)

### Terraform Configuration
```hcl
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.14.0"
    }
  }

  required_version = "~> 1.3.6"
}

data "newrelic_notification_destination" "email" {
  id = "[REDACTED]"
}

resource "newrelic_notification_channel" "email" {
  name = data.newrelic_notification_destination.email.name
  type = data.newrelic_notification_destination.email.type
  destination_id = data.newrelic_notification_destination.email.id
  product = "IINT"

  property {
    key = "subject"
    value = "{{ issueTitle }} - Issue {{issueId}}"
  }
}
```

### Actual Behavior
```
│ Error: Missing required argument
│ 
│   with module.email-only-workflow.newrelic_notification_channel.email,
│   on ../modules/newrelic_workflow/main.tf line 11, in resource "newrelic_notification_channel" "email":
│   11:   name = data.newrelic_notification_destination.email.name
│ 
│ The argument "name" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   with module.email-only-workflow.newrelic_notification_channel.email,
│   on ../modules/newrelic_workflow/main.tf line 12, in resource "newrelic_notification_channel" "email":
│   12:   type = data.newrelic_notification_destination.email.type
│ 
│ The argument "type" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   with module.email-only-workflow.newrelic_notification_channel.email,
│   on ../modules/newrelic_workflow/main.tf line 13, in resource "newrelic_notification_channel" "email":
│   13:   destination_id = data.newrelic_notification_destination.email.id
│ 
│ The argument "destination_id" is required, but no definition was found.
```

Additionally, we tried updating the state with this datasource defined but the resulting element in the state is empty:
```
# module.email-only-workflow.data.newrelic_notification_destination.email:
data "newrelic_notification_destination" "email" {
}
```

### Expected Behavior
Form the [documentation](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/notifications_destination) I would expect the data source to contain information about the notification_destination resource, including name and type.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by sanderblue** [comment]
@ianpushee Thanks for reporting. We'll take a look.

**Comment by NSSPKrishna** [comment]
We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.
