### ISSUE TITLE
Add dashboard color options

### ISSUE THREAD

**Issue by bartbriek** [newrelic/terraform-provider-newrelic#2272]
### Feature Description
At the moment it is not possible to my knowledge to set the color of your dashboards via pure terraform code for the resource `newrelic_one_dashboard`. It is possible to do it with the JSON setup via the `newrelic_one_dashboard_json` resource, however in the situation that your are dynamically creating your dashboard via dynamic variables and outputs this is resulting in a lot of extra code that is not needed and lowers the readability of the code.

possible solution: 
```HCL
resource "newrelic_one_dashboard" "exampledash" {
  name        = "New Relic Terraform Example"
  permissions = "public_read_only"

  page {
    name = "New Relic Terraform Example"

    widget_bar {
      title  = "Average transaction duration, by application"
      row    = 1
      column = 7
      width  = 6
      height = 3

      nrql_query {
        account_id = 12345
        query      = "FROM Transaction SELECT average(duration) FACET appName"
        color = #00ff02
      }

      # Must be another dashboard GUID
      linked_entity_guids = ["abc123"]
    }
 }
 ```

I can see some conflicting issues when the query would use FACET with this solution, because this would result in two or more lines that all have the same color. 

### Describe Alternatives
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard_json is an alternative.

**Comment by rakwal** [comment]
Can someone provide input here?I am trying to automate Newrelic dashboard creation using Terrfaorm.Currently having issue with nested loops while making widgets dynamic..Attaching my variable file and terraform script below.

I get errors with the lines below from DASHBOARD.TF

title = upper(page.value["lines"]["title"][widget_line.key])
query = page.value["lines"]["query"][widget_line.key]
------------------------------------------VARIABLES.TF------------------
variable “pages” {
type = list(object({
pagename = string
lines = list(object({
title = list(string)
query = list(string)
}))
billboards = list(object({
title = list(string)
query = list(string)
}))
}))
}
-------------------------------------------------------DEV.TFVARS-----------------------------------
pages = [{
pagename = “netflix”
lines = [{
query = [“FROM Transaction SELECT rate(count(), 1 minute)"]
title = [“title_1”]
}]
billboards = [ {
query = ["FROM Transaction SELECT rate(count(), 1 minute)”]
title = [“title_2”]
} ]
}]

--------------------------------------DASHBOARD.TF----------------------------
resource “newrelic_one_dashboard” “exampledash” {
name = “New Relic Terraform Example”
permissions = “public_read_write”

dynamic “page” {
for_each = var.pages
content {
name = page.value[“pagename”]
dynamic “widget_line” {
for_each = page.value[“lines”]
content {
title = upper(page.value[“lines”][“title”][widget_line.key])
row = 1
column = 1
width = 6
height = 3

nrql_query {
query = page.value[“lines”][“query”][widget_line.key]
}

}

}

}
}

}
