### ISSUE TITLE
An error occurs when defining newrelic_notification_destination as a data source.

### ISSUE THREAD

**Issue by solomon-maeng** [newrelic/terraform-provider-newrelic#2277]
We are trying to remove the `newrelic_notification_destination` defined in the `tfstate` and use it as a data source by defining it as a data source. Although the `terraform plan` succeeds when defining `newrelic_notification_destination` as a data source, it fails during `apply` with the error message "This operation could not be completed because the entity is in use". What should we do?

## Terraform Version
Terraform v0.13.0

provider registry.terraform.io/newrelic/newrelic v3.15.0

## Affected Resource(s)
- newrelic_notification_destination (data source)

Terraform Configuration
```
data "newrelic_notification_destination" "slack" {
  id = "destination_id"
}

resource "newrelic_notification_channel" "slack_channel" {
  active         = true
  destination_id = data.newrelic_notification_destination.slack.id
  name           = var.alert_slack_channel_name
  product        = "IINT"
  type           = "SLACK"

  property {
    key           = "channelId"
    value         = var.alert_slack_channel_id
  }
}
```

## Actual Behavior

```
Error: ENTITY_IN_USE: This operation could not be completed because the entity is in use
```

**Comment by pranav-new-relic** [comment]
Hi @solomon-maeng  - we haven’t heard back from you in a long time so we'll close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue. Thanks!
