### ISSUE TITLE
unable to create newrelic_workflow resource

### ISSUE THREAD

**Issue by overlordchin** [newrelic/terraform-provider-newrelic#2283]
### Issue description:
I am unable to create a newrelic_workflow resource in terraform. I was successfully able to create a newrelic_alert_policy and a newrelic_nrql_alert_condition with my terraform. This indicates my provider (using the latest version) does not have an issue with the account or apikey.  Unfortunately I am greeted with the following error when attempting to create a workflow in order to connect a channel_id I previously created to the workflow:

 Error: maximum retries reached: An error occurred resolving this field
│
│   with module.my_condition.newrelic_workflow.workflow,
│   on modules/my_module/main.tf line 34, in resource "newrelic_workflow" "workflow":
│   34: resource "newrelic_workflow" "workflow" {

### Code associated 

```
resource "newrelic_workflow" "workflow" {
  account_id                    = var.account_id
  name                            = "workflow_name"
  muting_rules_handling = "NOTIFY_ALL_ISSUES"
  enabled                        = true

  issues_filter {
    name = "${var.name}filter"
    type = "FILTER"

    predicate {
      attribute = "accumulations.conditionName"
      operator  = "EXACTLY_MATCHES"
      values    = [ "${var.name}" ]
    }
  }

  destination {
    channel_id = 123456 # substituted fake id here. The number in the actual resource corresponds to the id field from a channel created previously under workflows. I have tried changing this to a string and also using the channel name instead 
  }
}
```

### Affected Resource(s): 
`newrelic_workflow`
Steps taken: 
- Terraform init
- Terraform plan
- Terraform apply

### Expected Behavior
workflow created or error indicating which arguments within the resource were invalid is provided as output

### Actual Behavior
Error: maximum retries reached: An error occurred resolving this field

### Terraform Version
1.3.6

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `Terraform plan`
2. `Terraform apply`

### Debug Output
No additional output was provided with TF_LOG="DEBUG"

**Comment by overlordchin** [comment]
Possibly related to https://github.com/newrelic/terraform-provider-newrelic/issues/1999 which looks very similar. The only fundamental difference I see is that I am using a destination channel that was created via the UI and this person was using one created in terraform.

**Comment by sanderblue** [comment]
Hi @overlordchin, can you provide the additional configuration that sets up your resource? Or are you hardcoding the `channel_id`?

**Comment by pranav-new-relic** [comment]
We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.
