### ISSUE TITLE
newrelic_one_dashboard_json template: add the ability to set the thresholds

### ISSUE THREAD

**Issue by jamieaugustus** [newrelic/terraform-provider-newrelic#2284]
### Feature Description
Add the ability to set thresholds on the billboard widget from the newrelic_one_dashboard_json module's template file. 

### Describe Alternatives
Unless it is automated we have to manually add the thresholds

### Additional context
Unless it is automated we have to manually add the thresholds

**Comment by RavitejaSurampudi** [comment]
Hi @jamieaugustus ,
ability to set thresholds on the billboard widget using newrelic_one_dashboard_json resource is already available.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/99236372/224299931-3fab6d29-c552-4306-96ab-84ca6dd3bd8e.png">

```
resource "newrelic_one_dashboard_json" "foo" {
   json = file("dashboard.json")
}
```

We will update the documentation with an example as well.

Please try and let us know

**Comment by NSSPKrishna** [comment]
Hi @jamieaugustus, we have an updated doc in the latest release [V3.17.0 ](https://registry.terraform.io/providers/newrelic/newrelic/3.17.0/docs/resources/one_dashboard_json#setting-thresholds). Closing this issue for now. Please let us know if you find any other issues or questions.
