### ISSUE TITLE
Documentation: newrelic_synthetics_cert_check_monitor example uses unsupported resource argument

### ISSUE THREAD

**Issue by rseuchter-vw** [newrelic/terraform-provider-newrelic#2309]
### Terraform Version
```
Terraform v1.4.2
on windows_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.17.1
```
The exact versions don't matter, it's a documentation problem.

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_synthetics_cert_check_monitor`

### Terraform Configuration
This is the broken example
```hcl
resource "newrelic_synthetics_private_location" "location" {
  description               = "Test Description"
  name                      = "private_location"
  verified_script_execution = false
}
resource "newrelic_synthetics_cert_check_monitor" "monitor" {
  name              = "cert_check_monitor"
  uri               = "https://www.one.example.com"
  locations_private = [newrelic_synthetics_private_location.location.id]
  period            = "EVERY_6_HOURS"
  status            = "ENABLED"
  tag {
    key    = "some_key"
    values = ["some_value"]
  }
}
```

### Actual Behavior
The documentation contains an example (see above) that at https://github.com/newrelic/terraform-provider-newrelic/blob/f406bb5b64e6a25e612489202a1ad48a0bb901dc/website/docs/r/synthetics_cert_check_monitor.html.markdown?plain=1#L69 uses the argument `uri` which `newrelic_synthetics_cert_check_monitor` does not have or support.

### Expected Behavior
The example should use `domain`.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Debug Output
none

### Panic Output
none

### Important Factoids
none

### References
none

**Comment by NSSPKrishna** [comment]
Hi @rseuchter-vw thanks for raising the issue. We will prioritise it.

**Comment by Nandu-pns** [comment]
Hi @rseuchter-vw,  We had a new release [V3.20.0](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_cert_check_monitor) which covers the update for the doc. issue reported, hence closing the issue for now. Please let us know if you still have any issues or questions related to this, Thank you.
