### ISSUE TITLE
Broken Link In Alert Channel Resource Page

### ISSUE THREAD

**Issue by CharlyCDeF** [newrelic/terraform-provider-newrelic#2313]
Broken `Slack Webhook URL` link in the [Alert Channel](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_channel#slack) resource page. The current link leads to an empty page with no helpful information related to getting the slack webhook url.

### Terraform Version
n/a

**Comment by pranav-new-relic** [comment]
Hi @CharlyCDeF , thank you for identifying the broken link. We've updated the docs with an [appropriate replacement](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/notification-channels-control-where-send-alerts/#slack) from Slack, and have also added a reference to [New Relic's docs](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/notification-channels-control-where-send-alerts/#slack) on the same, which would guide users through setting up New Relic Alerts on Slack. You will see the updated docs with the next release of the Terraform Provider - thanks for letting us know about this.

P.S. We'd also like you to know that the `newrelic_alert_channel` resource is nearing its EOL (as announced [here](https://github.com/newrelic/terraform-provider-newrelic/issues/2286)), which has also been added as a warning to the docs of `newrelic_alert_channel` - and would hence, suggest you to consider moving to [`newrelic_notification_channel`](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_channel) instead. Thanks!

**Comment by pranav-new-relic** [comment]
Corrected URL released with the [docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_channel#nested-config-blocks) of the latest Terraform Provider, v3.20.2.

Closing this issue, thanks for reporting!
