### ISSUE TITLE
newrelic/newrelic v3.21.2 checksum list has unexpected SHA-256 hash; terraform init fails

### ISSUE THREAD

**Issue by TechIsCool** [newrelic/terraform-provider-newrelic#2352]
The most recent Terraform Provider has a broken SHA in the HashiCorp Terraform Registry the SHA256SUMS are correct though.

Error from Terraform on init
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [X] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- v3.21.2
- [X] A list of [affected resources](#affected-resources) and/or data sources
- Global Provider Issue
- [X] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- N/A
- [X] Description of the [current behavior](#actual-behavior) (the bug)
- Provider Won't INIT
- [X] Description of the [expected behavior](#expected-behavior)
-  INIT Should happen successfully
- [x] Any related [log output](#debug-output)
```
╷
│ Error: Failed to install provider
│
│ Error while installing newrelic/newrelic v3.21.2: checksum list has unexpected SHA-256 hash c9aa72f96e23a5404e0a874c17b1b967908f73f6144331c3172029e4375c1bc0 (expected
│ fa4ed982e2831ae8d35f88644aed89750f819681448ba2236e3c97d8349e1666)
╵
```

If you check the SHASUM256 they match but the actual metadata in the registry is wrong

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```
Terraform v1.3.9
on darwin_arm64
```

### Affected Resource(s)
Please list the resources as a list, for example:

Global Provider Issue

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention thi
### Important Factoids
If you check the registry you can see that the JSON payload is wrong
https://registry.terraform.io/v1/providers/newrelic/newrelic/3.21.2/download/linux/amd64

```
{
  "protocols": [
    "5.0"
  ],
  "os": "linux",
  "arch": "amd64",
  "filename": "terraform-provider-newrelic_3.21.2_linux_amd64.zip",
  "download_url": "https://github.com/newrelic/terraform-provider-newrelic/releases/download/v3.21.2/terraform-provider-newrelic_3.21.2_linux_amd64.zip",
  "shasums_url": "https://github.com/newrelic/terraform-provider-newrelic/releases/download/v3.21.2/terraform-provider-newrelic_3.21.2_SHA256SUMS",
  "shasums_signature_url": "https://github.com/newrelic/terraform-provider-newrelic/releases/download/v3.21.2/terraform-provider-newrelic_3.21.2_SHA256SUMS.sig",
  "shasum": "03182fb83f88bac284601e0657e79ca8ba06b58ad452d16fb690be43552cdeeb",
  "signing_keys": {
    "gpg_public_keys": [
      {
        "key_id": "EAFC5253DEFEAD23",
        "ascii_armor": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQINBGRK8QsBEADDgpacctSfAC7iQbLjhvxdxqbM7pA1qTO+J34xAwv1wVXFM9Yn\nQ2WAr5z+6brMS2zVLWtQ/fUqgGqGvQTzdkDpqZPzsYfZWRpHnALsQQChCcfagZo8\nPrZn5Qs9bzf5ctGX6LQyZChKNwwUW8hnF/e4vcuZ3l6TWmvaCANPTOOqKXAZIarB\nw+F+32YP5lYRG932SV/D8nbTHKFyTJZlBLNbvUcMeIP4P7ZYS2bdpsKsF1wqhJyw\n6GZBSzEBpzgLswn7LxizMZExkQLg9BMg1uPoXg6nJQAgdRrxhxsSFAqy+vboZyYv\nHqwK6g1GOcnXu+8GV03XtJcWMGoZXq1gOkQ++UxPcjdDkozm1e+7MkdGjdvo96hO\nrYzCasMKl+bFahe+keHlM1KtPg+hUKfUrDunEApI97mEd5BkOb/Z9EAdnFwiaV1S\njywBCx0csi1gSknLHD27CeLVu7iscOGir/6QlbePNz0YNr98KpF/o8g3M9e0JEg7\n4eUx8JpzbmZsMmMEAGLSJadpsdx4i3cLXdYLXhFL6XiBrYkgjojtZUxM6uZp5DQi\nZCKq8sppxvuGQOVNnniRqjQ3VQqO+18a97B8lPcn2MopbrtRCTW0KX0RGzOk96ln\nW0CQhtiDwi5slPTNysczuZBJqOlUbZdyCfCmOIgUrhAWhKBstDs04UpMzwARAQAB\ntDlOZXcgUmVsaWMgPG5yLWRldmVsb3Blci10b29sa2l0QHVzZXJzLm5vcmVwbHku\nZ2l0aHViLmNvbT6JAlcEEwEIAEEWIQQBSrOeYWSW2SnyU+bq/FJT3v6tIwUCZErx\nCwIbAwUJA8JnAAULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRDq/FJT3v6t\nI/DUD/0f6POhy2fsSBBIK/zteJyRYFUH7tuZ1Rwg3ElSDxgkIXe+BPoSy5aUgjic\nGLZLXhmJQ9WzwM/w20P3QSqYtC+Jd8R9vBEyd1s82bAubHClY5IiHOHZKSRMm22V\nLPjOAHuXwrV0YI0CwmNg8sInw8LJFed0srxd12Y/sVC/0+BCEJJJfnR33gHsH/k/\nw/6hS0/CGy3GpgjcWNVdHBOq8xOV2eT9TJhINO8Kk7vNTzS9OJhq0t5xBqzaYfeH\nNgqErUQ5nmcKxaeX8peXDYAZhbWsodoqWbW8ZTQZP4nXIXRGIoEtWtLR3CUwa679\noJJQFsQ2n11FRO7nlcBQCD//Xgxzr++RwLANGWyhkytDuU9H97WMsG3Y/fyTF5OI\n1Oqh3sqh8AOjXoem3mZsFiK9QdNaC0fdMsBRUqGXA9C0ActL1ryejqBfQgPmDOHE\nQR519MWwkza8VXDVgxxcpqWX+VKwjwF3WOGXAD/T8UGaRuhayHx8dvB6OxbbrOCN\nb/Aq7zeLCHxofXpH53tYiGsYJ1dE5HTDyutnrrJkSOqy8aDLy+6c8DkRkj65OowG\nzmH4dAjajRJ8CAKX6US3acb44alaYoFvZPv+AHbI6UC5TvqRuvkicTNwbSq9VaSh\nqN4O8WUICPBdb/zZRTjNdvoitCiJXXs1S7MCkKsZHR8Z7PV4ag==\n=JJRI\n-----END PGP PUBLIC KEY BLOCK-----",
        "trust_signature": "-----BEGIN PGP SIGNATURE-----\n\niQIzBAABCAAdFiEEUYkGV8Ws20uCMIZWfXLUJo5GYPwFAmRMKiwACgkQfXLUJo5G\nYPxYYw/+NkxBaKzMKsQ4RubTGtPuk8KMwfHTqUUkzkN3lW2YEYYw5esy916mJRJo\n1ZHw3c+oa7Diw2c8/HbCxMLeTUQ2eOfY84WUzrnlgygMAQ0ijae5nc4wfM9ZE98n\nSgA6SFfgKGZmQzMKXw6l7rDFgm0GCeDChzZAHk+eazLSSIte/7FYUUV2/A393orH\nSZSu+ozP1A3hwgq031E8d80cBdPIFjAJOMx86b7vo9LOMLzsspH/IMfhUz4/F3CU\n1iTf3SI/NLH7X8RxN/Abm4EY3tPpGbEJiCjB9XTdUVfEISde3O9FB6QUl++ssptK\ngubNrdkLdaLW6wkGpsJHPp3xxRHOxa3rO2b2hldXWtlxisetV42Dw+WJU7QG85bt\n/k9QbyHR0+ocC2necfZDJmOMhHUJ73+JtNd30PhtBJ/WSgplXdKe+oqzlIA8RVm6\nIOJjySXqge/lzODHZEDAQHXLLpu5hf/PK1Kna0L4tq89+lRs/L3N1P2eJ8JWWZQu\nuJFhk7kGt6Pxr1OimFuPnTUeX3S1sdePcgejrzwX9KQqHXjSLhOxOLjATLYV2tvO\n3jMcVz6l4tO5VKocwSd9jIfUGG+C1jJVDX01ctQdBrAG/U4FnXENAXp5FVjSQPx5\niu2TqbL4FNl4pFkXr9Jjg3ZJKrgtzVPulfeK6om+yoPcu0aB7ko=\n=Jc1Q\n-----END PGP SIGNATURE-----",
        "source": "",
        "source_url": null
      }
    ]
  }
}
```

**Comment by TechIsCool** [comment]
Filled a support case with NewRelic (#00110681)
Also talked with our Technical Account Manager via Slack about this, it looks like there is a bug upstream based on the way that The Terraform Registry consumes via Webhook. But I can't tell for sure. There is a new release in the oven it looks like.

**Comment by sanderblue** [comment]
Hi @TechIsCool, we had a git tag that was out of sync with the registry. This should be working now as of version **v3.21.3**.

**Comment by TechIsCool** [comment]
Confirmed working with v3.21.3
Thanks so much for the fast response, appreciate it
