### ISSUE TITLE
Checksum mismatch when installing 3.21.2

### ISSUE THREAD

**Issue by sean-hernon** [newrelic/terraform-provider-newrelic#2353]
Apologies for not following the prescribed format, but I think this one is quite obvious.

Output from `terraform init`:

```
╷
│ Error: Failed to install provider
│ 
│ Error while installing newrelic/newrelic v3.21.2: checksum list has unexpected SHA-256 hash b3333612c996203ecc663d3c6efd028a084f5820c304e977195e587ba52345eb (expected 1eba8ea5566492f0194ecc201d1f8c58e6dd4bbd4385f43094b603204b8f2d81)
╵
```

**Comment by sean-hernon** [comment]
Duplicates https://github.com/newrelic/terraform-provider-newrelic/issues/2352

**Comment by sanderblue** [comment]
Hi @sean-hernon, we had a git tag that was out of sync with the registry. This should be working now as of version v3.21.3.
