### ISSUE TITLE
Getting issue with newrelic_workflow resource: Cannot query field "aiWorkflows" on type "Account"

### ISSUE THREAD

**Issue by rakibkamal-mcd** [newrelic/terraform-provider-newrelic#2354]
- [ ] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [ ] A list of [affected resources](#affected-resources) and/or data sources
- [ ] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [ ] Description of the [current behavior](#actual-behavior) (the bug)
- [ ] Description of the [expected behavior](#expected-behavior)
- [ ] Any related [log output](#debug-output)

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_workflow`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
terraform {
  required_version = ">= 0.13.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.0.0"
    }
    newrelic = {
      source  = "newrelic/newrelic"
    }
  }
    backend "s3" {
        region  = "us-east-1"
    }
}
provider "newrelic" {
}
```

### Actual Behavior
Getting error message in terraform plan stage for resource newrelic_workflow. I tried editing my existing workflow in terraform, and started a fresh terraform project to create a workflow and received the same error.
"Cannot query field "aiWorkflows" on type "Account"."

### Expected Behavior
Normal updates to newrelic_workflow resource. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a newrelic_workflow, newrelic_notification_channel, and newrelic_notification_destination. Values can be anything.
2. terraform plan

### Important Factoids
Utilize New Relic Account ID and API Key with Environment Variables.

**Comment by dubb-b** [comment]
Also getting this on all our deployments.

**Comment by skuma0404** [comment]
same issue

**Comment by dubb-b** [comment]
```
Error: Cannot query field "aiWorkflowsCreateWorkflow" on type "RootMutationType".
```

Not sure but this started happening earlier today. Been messing with provider versions and it didn't seem to change anything.

**Comment by someshkoli** [comment]
Following for further updates

**Comment by IliaShurygin** [comment]
Hi! We had an incident with workflow API that lasted for a couple of hours. 
The issue has been resolved and all the plans should work fine again.
Sorry for the disruption! 

I have verified that workflow resources are working, but please feel free to re-open the issue or open a new one if something is still broken.

**Comment by jakewan** [comment]
@IliaShurygin Is there any chance a similar incident may be occurring right now? I'm suddenly seeing API issues resulting in similarly-formed errors. In my case, the errors say:

```shell
Error: Cannot query field "variables" on type "DashboardEntity".
```
