### ISSUE TITLE
A typo ? - firehose not firehost

### ISSUE THREAD

**Issue by dreamsjtu** [newrelic/terraform-provider-newrelic#2363]
### Objective
A typo, firehose not firehost

<img width="556" alt="image" src="https://user-images.githubusercontent.com/21008134/236667422-81f81f09-7d29-4814-addb-4721b6799083.png">

**Comment by pranav-new-relic** [comment]
Hi @dreamsjtu, thanks for letting us know about this typo. We'll take a look and update it soon.

**Comment by pranav-new-relic** [comment]
Closing this issue as the reported typos have been corrected in the [updated example](https://github.com/newrelic/terraform-provider-newrelic/blob/main/examples/modules/cloud-integrations/aws/main.tf#L86) on AWS integrations.
