### ISSUE TITLE
Synthetic step monitor crashes plugin 

### ISSUE THREAD

**Issue by mrocheleau** [newrelic/terraform-provider-newrelic#2373]
## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [X] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [X] A list of [affected resources](#affected-resources) and/or data sources
- [X] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [X] Description of the [current behavior](#actual-behavior) (the bug)
- [X] Description of the [expected behavior](#expected-behavior)
- [X] Any related [log output](#debug-output)

### Terraform Version
Terraform v1.1.6
...
+ provider registry.terraform.io/newrelic/newrelic v3.17.1

### Affected Resource(s)
- `newrelic_synthetics_step_monitor`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.

Provider.tf:
```hcl
provider "newrelic" {
  account_id = "redacted"
  api_key = var.newrelic_apikey
  region = "US"                        # Valid regions are US and EU
}
```

newrelic_alerts.tf (only the resource in question):
```hcl
resource "newrelic_synthetics_step_monitor" "syntheticcheck" {
  count                                   = var.enable_synthetics == "1" ? 1 : 0
  name                                    = "${var.environment_name}-synthetic"
  enable_screenshot_on_failure_and_script = true
  locations_public                        = ["US_EAST_1"]
  period                                  = "EVERY_10_MINUTES"
  status                                  = "ENABLED"
  steps {
    ordinal = 0
    type    = "NAVIGATE"
    values  = [
        "https://${var.redacted}/",
        ""]
  }
  steps {
    ordinal = 1
    type    = "SECURE_TEXT_ENTRY"
    values  = [
        var.is_auth0 == "0" ? "id_login" : "1-email",
        "redacted-existing-secure-cred,
    ]
  }
  steps {
    ordinal = 2
    type    = "SECURE_TEXT_ENTRY"
    values  = [
        var.is_auth0 == "0" ? "id_password" : "1-password",
        "redacted-existing-secure-cred",
    ]
  }
  steps {
    ordinal = 3
    type    = "CLICK_ELEMENT"
    values  = [
        var.is_auth0 == "0" ? "input.btn.btn-block.btn-primary.btn--auth" : "1-submit",
    ]
  }
  steps {
    ordinal = 4
    type    = "CLICK_ELEMENT"
    values  = [
        ".NavCourseGroupSelector",
    ]
  }
}
```

### Actual Behavior
Plan worked fine, shows everything as I'd want it to be.  When applying and creating this specific module it crashed with:

│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│   with newrelic_synthetics_step_monitor.syntheticcheck[0],
│   on newrelic_alerts.tf line 165, in resource "newrelic_synthetics_step_monitor" "syntheticcheck":
│  165: resource "newrelic_synthetics_step_monitor" "syntheticcheck" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-newrelic_v3.17.1 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 81 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandStringSlice(...)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_helpers_synthetics.go:188
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandSyntheticsMonitorSteps(...)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_synthetics_step_monitor.go:71
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.buildSyntheticsStepMonitorCreateInput(0xc0001e5180?)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_synthetics_step_monitor.go:16 +0xa25
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicSyntheticsStepMonitorCreate({0x1c8bba8, 0xc0002d6a20}, 0x0?, {0x1994d80?, 0xc0001e5180?})
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_synthetics_step_monitor.go:102 +0x9c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00053b5e0, {0x1c8bbe0, 0xc000685e30}, 0xd?, {0x1994d80, 0xc0001e5180})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00053b5e0, {0x1c8bbe0, 0xc000685e30}, 0xc0005436c0, 0xc0002f9400, {0x1994d80, 0xc0001e5180})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000010078, {0x1c8bbe0?, 0xc000685d10?}, 0xc000309680)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000000000, {0x1c8bbe0?, 0xc000685320?}, 0xc0002f2700)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1a992a0?, 0xc000000000}, {0x1c8bbe0, 0xc000685320}, 0xc0002f2690, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004a4000, {0x1c905e0, 0xc000535380}, 0xc0000ebe60, 0xc00054af00, 0x2288f00, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0004a4000, {0x1c905e0, 0xc000535380}, 0xc0000ebe60, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-newrelic_v3.17.1 plugin crashed!

### Expected Behavior
Expected the resource to be created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Debug Output
N/A

### Panic Output
See above "actual output"

### Important Factoids
If I pre-create the step monitor in New Relic, even if some items are incorrect and don't match the intended configuration, then import that by GUID into my terraform state, an apply afterwards will interact correctly with it and is able to correct any drift.

**Comment by pranav-new-relic** [comment]
Hi @mrocheleau - thanks for reporting this. I've just been able to reproduce the issue, and have been able to mitigate it by removing the empty string "" in the first step, which is causing the error as an empty string isn't expected in this list. Any reason why you'd want to include an empty string? (if it is for the 'User Agent String' in the Navigate step, it is made blank by default if no non-empty string is specified). Thanks!

> ```steps {
>    ordinal = 0
>    type    = "NAVIGATE"
>    values  = [
>        "https://${var.redacted}/"]
>  }
