### ISSUE TITLE
Makefile `gofmt` and `gofmt-fix` targets fail to find issues

### ISSUE THREAD

**Issue by usfdmiller** [newrelic/terraform-provider-newrelic#2377]
I already have a pull request created for this issue, but I suppose creating a bug report as well wouldn't hurt.  The find command used in `gofmt` and `gofmt-fix` will not return any files.

```bash
find . -path "$(EXCLUDEDIR)" -prune -print0 | xargs -0 $(GOFMT) -e -l -s -d ${SRCDIR}
```

While this find command could be updated, it makes much more sense to me to use the existing `GO_FILE` variable.  

```bash
GO_FILES ?= $(shell find $(SRCDIR) -type f -name "*.go" | grep -v -e ".git/" -e '/example/')
```

This find command works as expected, returning all Go files aside form those in the .git and example folders.  The `gofmt` and `gofmt-fix` targets can be updated accordingly

```makefile
gofmt: deps
	@echo "=== $(PROJECT_NAME) === [ gofmt            ]: Checking file format with $(GOFMT)..."
	@$(GOFMT) -e -l -s -d $(GO_FILES)

gofmt-fix: deps
	@echo "=== $(PROJECT_NAME) === [ gofmt-fix        ]: Fixing file format with $(GOFMT)..."
	@$(GOFMT) -e -l -s -w $(GO_FILES)
```

There are very few formatting issues found after implementing this change, probably due to VS Code automatically formatting.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [ ] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [ ] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [ ] Any related [log output](#debug-output)

### Terraform Version
Not a Terraform issue.

### Affected Resource(s)
Please list the resources as a list, for example:
- `gofmt` and `gofmt-fix` in lint.mk

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
Not a Terraform issue.

### Actual Behavior
Nothing, the current `find` command will not return any files to pass to `gofmt`.

### Expected Behavior
Any project file ending in .go, not in the .git folder, should be passed to `gofmt`.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Find a Go file with correct formatting.
2. Use an editor (without automatic formatting) to update the file with incorrect formatting.
3. From the command line, at the project root, run `make gofmt`
4. You should see no output regarding formatting.

### Debug Output
No debug output.

### Panic Output
No panic output.

### References

Like I mentioned, I have a pull request for this change.

- #2370

**Comment by pranav-new-relic** [comment]
Hi @usfdmiller, thanks for reporting this. We did have a look at your PR - thank you for the contribution. We shall take a look at this soon based on our task priority, and get it merged.

**Comment by pranav-new-relic** [comment]
Closing this issue as it has been merged. Thank you for the contribution.
