### ISSUE TITLE
Missing options creating Workloads - general description links, contacts and link to dashboards

### ISSUE THREAD

**Issue by OscarNeira** [newrelic/terraform-provider-newrelic#2381]
Not sure if this is a bug or a missing feature

### Feature Description
Creating workflows with general settings, like links and contacts, is not possible. The one that we need the most is the option to link the dashboards to the workload.

![Screenshot 2023-05-29 at 10 49 39](https://github.com/newrelic/terraform-provider-newrelic/assets/6389828/ee0935b7-cbf1-460d-8c44-66ea891e65ce)

and general settings, as well

![Screenshot 2023-05-29 at 10 48 49](https://github.com/newrelic/terraform-provider-newrelic/assets/6389828/6a0abbb1-306c-4a1f-a7d4-2a8b6008c5c9)

### Describe Alternatives
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?

The alternative for us is doing that manually. However, we do not have access to prod accounts the idea is that prod is completely automated by terraform.

**Comment by pranav-new-relic** [comment]
Hi @OscarNeira - I've had a look at this and it most likely is a feature request; will check with the respective team on this. Thanks for reporting this.

**Comment by bthemad** [comment]
Hi @OscarNeira! Thanks a lot for using Workloads and especially TF provider \\^_^/

There are couple of non-obvious tricks that you can do to achieve almost all your goals:

- In order to link dashboards, just add them to the workload, like any other entity, and it would work.
- The tags for the workload could be added using the `newrelic_entity_tags` resource ([docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/entity_tags))
- If you add a tag with a key `team` and any value, it would be shown in the "Team(s)" block of the General settings.

Now the only limitation we currently have is around Links and Contacts, that is a FR that we have not implemented yet, but I will add link to this issue to our ticket for tracking and would ping you here if / when we would tackle that one.

**Comment by OscarNeira** [comment]
Hi @bthemad, thanks for the reply. The priority is to link the dashboards. However, I cannot make it work. The reason is that the dashboards are in a different file, how I can link or pass the guid to the main file that collects all guides from all my services?


The dashboard file I create the name with a join

resource "newrelic_one_dashboard" "main_dashboard" {
  name = join(" ", [
    upper(var.app_lens.string_lens), upper(var.app_lens.string_main), upper(var.app_lens.string_dashboard),
    upper(var.environment), upper(var.datacenter), upper(var.app_lens.string_terraform),
  ])


I see the guid get exported, do you know how I can fetch it in the other file?

**Comment by pranav-new-relic** [comment]
@OscarNeira if your dashboards are defined in a different file, you can still use the guids exported by these resources (once they're created) in your main file which is where you're defining resources linked to workloads I'm guessing.

For instance, I've tested this out with the following Terraform Configuration

`dashboards.tf`
```hcl
resource newrelic_one_dashboard "sample_dashboard_resource" {
  name = "GH 2381 Workloads Test Dashboard"
  page {
    name = "Page 1"
    widget_line {
      column = 1
      row    = 1
      title  = "Random Title"
      nrql_query {
        query = "XXXXXX"
      }
    }
  }
}
```

`workloads.tf`
```hcl
resource "newrelic_workload" "sample_workload_resource" {
  name = "GH 2381 Sample Workload"
  account_id = XXXXXX
  entity_guids = [newrelic_one_dashboard.sample_dashboard_resource.guid]
  scope_account_ids =  [XXXXXX]
  depends_on = [newrelic_one_dashboard.sample_dashboard_resource]
}
```

`provider.tf`
```
terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
    }
  }
}

provider "newrelic" {
  region = "US"
}
```

and have been able to create the workload linked to the dashboard upon `terraform plan` and `terraform apply`.

<img width="592" alt="image" src="https://github.com/newrelic/terraform-provider-newrelic/assets/127438038/0048b82a-1c4f-4cc7-a9b3-5adca0a6737b">

Let me know if this answers your question.

**Comment by OscarNeira** [comment]
dam, you are fast, i just made it work

**Comment by OscarNeira** [comment]
I did it different, applied tags to the dashboard and call the entity tag query

**Comment by OscarNeira** [comment]
I try your option, more clean

**Comment by OscarNeira** [comment]
both works fine, thanks

**Comment by OscarNeira** [comment]
You can close it or let me know when you get the links and contacts implemented

**Comment by pranav-new-relic** [comment]
@bthemad - your call :)

**Comment by bthemad** [comment]
Since we are tracking it via an FR in our internal system and usually publish in "What's new" section of New Relic, I'd close this one.
