### ISSUE TITLE
Command line init does not locate resource

### ISSUE THREAD

**Issue by Steve24by7** [newrelic/terraform-provider-newrelic#2393]
Running terraform init for simple use case on MAC Ventura 
NRmac:azure$terraform version
Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/azurerm v3.0.0
+ provider registry.terraform.io/newrelic/newrelic v3.24.0

 for [this](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/cloud_integrations_guide#azure) provider:
NRmac:azure$terraform init
Initializing modules...
Downloading git::https://github.com/newrelic/terraform-provider-newrelic.git for newrelic-azure-cloud-integrations...
╷
│ Error: subdir "tree/main/examples/modules/cloud-integrations/azure" not found
│ 
│ 
╵

My main
terraform {
  required_version = "~> 1.0"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
    }
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

provider "newrelic" {
  account_id = 123456
  api_key = "NRAK-xxxxx"
  region = "US"
}

provider "azurerm" {
  features {}

}

module "newrelic-azure-cloud-integrations" {
    source = "github.com/newrelic/terraform-provider-newrelic/tree/main/examples/modules/cloud-integrations/azure"

  newrelic_account_id     = 123456
  name                    = "Steve24by7Azure"
}

however if instead the source line reads as this:
  source = "github.com/newrelic/terraform-provider-newrelic/examples/modules/cloud-integrations/azure"

It works properly.
Clearly during the init, the downloaded files from git are placed in a directory tree that does not have the "tree/main" directories in the path.
NRmac:azure$ls  .terraform/modules/newrelic-azure-cloud-integrations/
CHANGELOG.md				build					scripts
CODE_OF_CONDUCT.md			examples				terraform-registry-manifest.json
CONTRIBUTING.md				go.mod					testing
GNUmakefile				go.sum					tools
LICENSE					main.go					website
README.md				newrelic

**Comment by pranav-new-relic** [comment]
Hi @Steve24by7 - thank you for reporting this issue. You're right - discarding `/tree/main` from the URL of the Azure Cloud Integrations directory gets this module working fine. We did take note of this recently, and have a documentation update to be made in the pipeline to correct this, which will be out with the next release of the Terraform Provider. Thanks!

**Comment by pranav-new-relic** [comment]
Closing this issue, as the changes have been made, which are in the pipeline for the next release. 
https://github.com/newrelic/terraform-provider-newrelic/pull/2396/files#diff-99c5e25b0604fcee3e485a7447f3fc7d163d25be0171c0d0f50abf69e2150d78R31
