### ISSUE TITLE
Fail to disable the partition rule

### ISSUE THREAD

**Issue by hongchhe** [newrelic/terraform-provider-newrelic#2412]
Refer the following screenshots,  when I change the partition rule from true to false, it shows the apply action is successfully. But when I look at the status from the newrelic browser, there is no change and it also shows the enabled status
![image](https://github.com/newrelic/terraform-provider-newrelic/assets/25891193/a350a86d-dd02-4649-9ec4-4d32cd3ea05b)
<img width="1470" alt="Screen Shot 2023-07-07 at 07 41 57" src="https://github.com/newrelic/terraform-provider-newrelic/assets/25891193/444902a6-c130-4b3a-9173-fd7a484abfa3">

Here are my sample code
```
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.25"
    }
  }
}

resource "newrelic_data_partition_rule" "log_test" {
  description           = "my test"
  enabled               = false
  nrql                  = "`Application`='test'"
  retention_policy      = "STANDARD"
  target_data_partition = "Log_test"
}
```

BTW, it works fine when change it from false to true.

### Terraform Version
- 1.4.6

### Affected Resource(s)
Please list the following resource
- `newrelic_data_partition_rule`

### Actual Behavior
Terraform apply shows successful, but the partition rule actually cannot be disabed.

### Expected Behavior
It actually can disable the data_partition_rule status.

**Comment by RavitejaSurampudi** [comment]
@hongchhe Thank you bringing this to us! We will look into it.

**Comment by pranav-new-relic** [comment]
Hi @hongchhe - the fix to this is out with the latest version of the Terraform Provider, [v3.25.1](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.25.1). Can you please try updating the partition rule with this version? Thanks!

**Comment by pranav-new-relic** [comment]
Closing this issue, as the change has been verified with v3.25.2 of the Terraform Provider, using which partition rules succeed to be disabled if `enabled` is updated to `false` (as specified in the description of this issue).

<img width="1262" alt="image" src="https://github.com/newrelic/terraform-provider-newrelic/assets/127438038/a1f6476d-322e-4b3c-8a70-ca02a28dc477">
