### ISSUE TITLE
newrelic_nrql_alert_condition does not support type = location_failure

### ISSUE THREAD

**Issue by ipcechinel** [newrelic/terraform-provider-newrelic#2413]
Hi there,

I'm having problems with the **newrelic_nrql_alert_condition** resource.

It's replacing features that have been deprecated, however _Alert Conditions Synthetics_ isn't supported.

### Terraform Version
```sh
terraform version                                                                       
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/newrelic/newrelic v3.25.0
```

### Affected Resource(s)
- `newrelic_nrql_alert_condition`

### Terraform Configuration
```hcl
terraform {
  required_version = ">= 1.5"

  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "3.25.0"
    }
  }
}

provider "newrelic" {
  account_id = "..."
  api_key = "..."
  region = "US"
}
```

### Actual Behavior
When accessing the [newrelic_synthetics_alert_condition](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_alert_condition) docs, there is a warning that the resource is _legacy_.

It is **recommended** that you use the [newrelic_nrql_drop_rule](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition) resource.

This resource doesn't support the `location_failure` **type**, so I can't import my alert conditions that were _created via UI_.

I tried importing with **static** and **baseline** types, but it's not possible.

### Expected Behavior
The **newrelic_nrql_alert_condition** feature needs to be updated to support the _newrelic_synthetics_alert_condition_ features

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create via UI 1 synthetic monitor
2. Create via UI 1 alert policy for this synthetic monitor (alert condition)
3. Write resource via terraform
4. Try import the alert condition on terraform

### Debug Output
```
> terraform import 'newrelic_nrql_alert_condition.main' XXXX:XXX:location_failure                
Acquiring state lock. This may take a few moments...
newrelic_nrql_alert_condition.main: Importing from ID "XXXX:XXXX:location_failure"...
newrelic_nrql_alert_condition.main: Import prepared!
  Prepared newrelic_nrql_alert_condition for import
newrelic_nrql_alert_condition.main: Refreshing state... [id=XXXXXX:XXXXXX]
╷
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to
│ "newrelic_nrql_alert_condition.main", the provider detected that no object
│ exists with the given id. Only pre-existing objects can be imported; check
│ that the id is correct and that it is associated with the provider's
│ configured region or endpoint, or use "terraform apply" to create a new
│ remote object for this resource.
```

**Comment by mbazhlekova** [comment]
Hi @ipcechinel in the UI, are you creating a `Synthetics` type condition or `NRQL` type? If it's a `Synthetics` type then it can't be imported as a `NRQL` type. For `NRQL` type you'd have to specify a query like this `SELECT count(*) FROM SyntheticCheck WHERE monitorName = '<monitor name>' AND result = 'FAILED'` to handle a Synthetics Monitor failure. This is just an example query that you'd have to modify for your use case.
