### ISSUE TITLE
Error using `newrelic_entity` data source to lookup Key Transactions

### ISSUE THREAD

**Issue by ljrmorgan** [newrelic/terraform-provider-newrelic#2428]
I'm trying to retrieve the guid of a key transaction for use in an NRQL alert condition, but I'm getting an error when using the `newrelic_entity` data source to find the key transaction.

### Terraform Version

```sh
$ terraform -v
Terraform v1.2.7
on darwin_arm64
+ provider registry.terraform.io/newrelic/newrelic v3.25.2
```

### Affected Resource(s)
- [`newrelic_entity` data source](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/entity)

### Terraform Configuration

```hcl
data "newrelic_entity" "this" {
  name = var.key_transaction_name
  type = "KEY_TRANSACTION"
}
```

### Actual Behavior

```
│ Error: interface EntityOutline was not matched against all PossibleTypes: KeyTransactionEntityOutline
```

### Expected Behavior

I expected the key transaction entity to be returned.

### Steps to Reproduce

1. `terraform plan`

### Debug Output

I'm slightly wary of posting the entire debug output because I haven't had time to go through it all and see what is/isn't sensitive, but this is hopefully some use (e.g. a request ID is logged): 
```
2023-07-18T22:17:40.352+0100 [ERROR] provider.terraform-provider-newrelic_v3.25.2: Response contains error diagnostic: @module=sdk.proto tf_proto_version=5.3 tf_provider_addr=provider @caller=/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_severity=ERROR diagnostic_summary="interface EntityOutline was not matched against all PossibleTypes: KeyTransactionEntityOutline" tf_data_source_type=newrelic_entity tf_req_id=c30507cc-71c3-d453-6634-e1d9a44900f8 tf_rpc=ReadDataSource diagnostic_detail= timestamp=2023-07-18T22:17:40.351+0100
```

### Important Factoids

I don't think there is anything special about my account. I can also see the same thing using the `newrelic` CLI tool:

```sh
$ newrelic entity search -n "<key transaction name>"
FATAL interface EntityOutline was not matched against all PossibleTypes: KeyTransactionEntityOutline
```

I suspect the client library being used just doesn't handle key transaction entities

### References
- I found reference to a similar error [here](https://forum.newrelic.com/s/hubtopic/aAX8W0000008dC6WAI/upcoming-endoflife-for-older-versions-of-terraform-new-relic-cli-and-go-cli)

**Comment by pranav-new-relic** [comment]
Hi @ljrmorgan - thank you for reporting this issue. There is a bit of a discrepancy that exists with the `KeyTransactionEntity` type in the backing API which we are trying to address, but are blocked by a few issues. We would advise you to use the `newrelic_key_transaction` data source to query Key Transactions. Thanks!

**Comment by ljrmorgan** [comment]
Thanks for the response @pranav-new-relic! Is there a way to get the key transaction's `guid` from that data source? The `id` that is returned doesn't seem to be a guid.

For context: I'm trying to create a `newrelic_nrql_alert_condition` that references the key transaction, since `newrelic_alert_condition` is deprecated. I have something like this currently:
```hcl
resource "newrelic_nrql_alert_condition" "high_error_rate" {
  nrql {
    query = <<NRQL
    SELECT count(apm.key.transaction.error.count) * 100 / count(apm.key.transaction.duration) AS 'Error %'
    FROM Metric
    WHERE (entity.guid = '${data.newrelic_entity.kt.guid}') AND (transactionType != 'Browser')
    NRQL
  }
  # other arguments omitted
}
```
with the `WHERE` clause being the problematic part

**Comment by pranav-new-relic** [comment]
Hi @ljrmorgan - seems like there currently isn't a way to get the GUID of the created Key Transaction. As this is an old resource that relies on the REST API which doesn't return the GUID of the `KeyTransactionEntity` created, it also appears that changes cannot be made to facilitate exporting GUID from this resource, unfortunately. We'll take a look into how we can mitigate this. However, given the team is a bit occupied with other priorities and deliverables at the moment - while we find time to prioritise this, you can consider using this workaround to query NerdGraph from Terraform in the interim - add the following files to your Terraform configuration.

`query.gql`
```gql
query ($query: String!) {
  actor {
    entitySearch(query: $query) {
      results {
        entities {
          ... on KeyTransactionEntityOutline {
            guid
            name
            accountId
          }
        }
      }
    }
  }
}

```

`variables.tf`
```hcl
variable "graphiql_url" {
  type = string
  default = "https://api.newrelic.com/graphql"
}

variable "api_key" {
  type = string
  default = "Your New Relic API Key"
}

variable "entity_name" {
  type = string
  # Name of the Key Transaction you would like to search for goes here
  default = "random_name"
}
```

`newrelic.tf`
```hcl
terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
    }
    graphql = {
      source = "sullivtr/graphql"
    }
  }
}

locals {
  response = jsondecode(data.graphql_query.sample_query.query_response)
  entities = local.response["data"]["actor"]["entitySearch"]["results"]["entities"]
  entity_guid = length(local.entities) > 0 ? local.entities[0]["guid"] : null
}

provider "newrelic" {
  region = "US" # US or EU
}

provider "graphql" {
  url = var.graphiql_url
  headers = {
    "Content-Type" = "application/json"
    "API-Key" = var.api_key
  }
}

data "graphql_query" "sample_query" {
  query_variables = {
    "query" = "name = '${var.entity_name}'"
  }
  query  = file("query.gql")
}

output "entity_guid" {
  value = local.entity_guid
}
```

Upon running `terraform apply`, `local.entity_guid` would contain the GUID of the matching entity if found, or else, would be `null`. This can be used wherever needed. This is a primitive workaround I came up with - please feel free to customize it to your usecase.
