### ISSUE TITLE
Terraform plan diff reports changes to unchanged newrelic_workflows

### ISSUE THREAD

**Issue by neilfordyce** [newrelic/terraform-provider-newrelic#2433]
### Terraform Version
New Relic Provider v3.25.2
Terraform version 1.1.4
Atlantis version 3.19.0

### Affected Resource(s)
- `newrelic_workflow`

### Terraform Configuration
```hcl
provider "newrelic" {
  account_id = <redacted>
  api_key = <redacted>
  region = <redacted>
}
```

Anonymised version of one of the workflows reporting changes in the plan, but which hasn't actually changed.
```hcl
resource "newrelic_workflow" "workflow_slack" {
  name = "slack"
  muting_rules_handling = "DONT_NOTIFY_FULLY_MUTED_ISSUES"

  issues_filter {
    name = "by_policy"
    type = "FILTER"

    predicate {
      attribute = "labels.policyIds"
      operator = "CONTAINS"
      values = [
        newrelic_alert_policy.my-alert.id
      ]
    }
  }

  destination {
    channel_id = newrelic_notification_channel.channel_slack.id
    notification_triggers = [ "ACTIVATED", "ACKNOWLEDGED", "CLOSED", "OTHER_UPDATES" ]
  }
}
```

### Actual Behavior
`terraform plan` diff reports differences in the newrelic_workflow objects. It reports that destination `type` and `name` will be `(known after apply)` even though these are static strings which should be fixed before apply.

### Expected Behavior
There should be no differences reported, because nothing was changed. 

### Steps to Reproduce
1. Open a project which contains a workflow
1. ```terraform plan```

### Debug Output
Anonymised terraform plan output https://gist.github.com/neilfordyce/20fa0eeaf136563164b5c26fe1a4ecda

### Important Factoids
We're running this using https://www.runatlantis.io

**Comment by amaor-newrelic** [comment]
Hi! Workflows here :) We've opened a bug for the underlying issue and will get to it within the next couple of months! Thanks for your patience!

**Comment by pranav-new-relic** [comment]
@neilfordyce @hopelovesbooks FYI:  a fix to this is out with the latest version (3.26.1) of the Terraform Provider.
Closing this issue, as the fix has been released.
cc @IliaShurygin @amaor-newrelic
