### ISSUE TITLE
OpenTF support

### ISSUE THREAD

**Issue by skyzyx** [newrelic/terraform-provider-newrelic#2451]
https://opentf.org/announcement

We want to understand how this provider is affected by the OpenTF announcement, and what the plans for support are moving forward.

From a technical perspective, I expect that it will be a no-op for the time being as OpenTF anticipates maintaining compat/interop for the foreseeable future. (However, OpenTF has stated that _some_ functionality may be added to OpenTF that is a _superset_ of what's in base Terraform. [[source](https://github.com/opentffoundation/roadmap/issues/24)])

From a process perspective:

1. If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this project) be treated equally on both platforms?

1. Will testing be performed with code targeting both platforms?

1. For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen?

**Comment by NSSPKrishna** [comment]
Hi there,

Thank you for raising this concern. We want to let you know that we had already identified this issue and have been discussing it within our team. We're working on finding the best solution and appreciate your patience. We'll make sure to keep you informed of any developments or decisions made in regard to this matter.

**Comment by kidk** [comment]
Thanks for reaching out @skyzyx 

We've been following the changes with Terraform and Hashicorp closely and have been talking internally and with partners to explore the impact this has on us and New Relic customers.

The good news is that in short term we don't expect things to change. As you mentioned yourself the OpenTF initiative is going to maintain compat/interop for the foreseeable future. As with Pulumi which also uses this provider we will consider any bug or issue equally. If the `compat/interop` ever changes we'll need to see where OpenTF and Terraform are in terms of usage to decide on the path we take forward. I don't think it's worth it making predictions on how this is going to evolve. 

Our goal is to make sure we're providing the right support and tools for the most popular solutions in the market, which will remain so in the future. 

To answer your questions directly
> If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this project) be treated equally on both platforms?
Yes bugs will be treated equally.

> Will testing be performed with code targeting both platforms?
When we start seeing differences between the platforms we'll upgrade our testing platform to catch these. We'll need to explore the effort as our testing is currently tightly coupled to Terraform.

> For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen?
We'll take this on a case by case basis. If superset functionality can be added with backwards compatibility I don't see a reason why not, but it's hard to say if that will be the case.

I hope this helps and removes some of doubts of investing in our platform and OpenTF.

**Comment by skyzyx** [comment]
Your response is greatly appreciated.

This whole situation has created uncertainty at a time when we could really do without it. My company leverages several open-source and SaaS offerings in the Terraform ecosystem, and I've been reaching out across the ecosystem to understand where everyone is on this topic, and identifying what we need to watch out for.

Hoping for the very best from this whole situation, but planning ahead for the absolute worst.
