### ISSUE TITLE
Integration Blocks are not removed when updating newrelic_cloud_aws_integrations

### ISSUE THREAD

**Issue by mBlomsterberg** [newrelic/terraform-provider-newrelic#2457]
Hi there,

## Bug report

The New Relic provider version is "~> 3.26.1".
The Terraform version is set to "v1.5.4". 
The affected resource "newrelic_cloud_aws_integrations". 

The configuration looks as the following: 
```hcl 
resource "newrelic_cloud_aws_integrations" "this" {
   linked_account_id = newrelic_cloud_aws_link_account.this.id
    s3 {
      metrics_polling_interval = 6000
    }
    ecs {
      aws_regions              = ["eu-west-2"]
      fetch_tags               = true
      metrics_polling_interval = 6000
      tag_key                  = "tag key"
      tag_value                = "tag value"
    }
   lambda {
      aws_regions              = ["eu-west-2"]
      fetch_tags               = true
      metrics_polling_interval = 6000
      tag_key                  = "tag key"
      tag_value                = "tag value"
    }
.... and so on.
}
```

### Description of the current behaviour (the bug).
When running `terraform apply` all blocks defined in the resource will be added to the integration overview in New Relic("ecs",  "s3" and "lambda"). However, when removing a block/s in the resource like "ecs" and "lambda" Terraform will remove them from the state but not in New Relic. 

![image](https://github.com/newrelic/terraform-provider-newrelic/assets/98821063/c499b89a-0290-4458-9609-d7b9146a12ff) (First time applying resource)

![image](https://github.com/newrelic/terraform-provider-newrelic/assets/98821063/24237706-573f-4813-8464-9564db9c4de9) 
(Terraform log output after removing blocks)

![image](https://github.com/newrelic/terraform-provider-newrelic/assets/98821063/c499b89a-0290-4458-9609-d7b9146a12ff) (After the removed blocks in resource)

### Description of the expected behaviour.
I expect the resource `newrelic_cloud_aws_integrations` to be reflected in New Relic after changes have been made. 

### Terraform Configuration
```hcl
terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
      version = "~> 3.26.1"
    }
    aws = {
      source = "hashicorp/aws"
      version = "~> 5.11.0"
    }
  }
  required_version = ">= 1.4.0"
}


provider "newrelic" {
  account_id = var.account_id
  api_key    = var.api_key
  region     = var.region
}

provider "aws" {
  region                   = "region"
  shared_config_files      = ["config"]
  shared_credentials_files = ["credentials"]
  profile                  = "profile"
}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Amend blocks in `newrelic_cloud_aws_integrations` resource
3. `terraform apply`

**Comment by Nandu-pns** [comment]
Thanks @mBlomsterberg for reporting this issue. It seems there might be an underlying problem with the API, which is bit unexpected because it was definitely working fine in the past. There's a possibility that this issue could be related to the ongoing cumulous migration, though we can't say for certain yet. We'll dig into it and get back to you based on our current priorities. Thank you !

**Comment by mBlomsterberg** [comment]
Thank you @Nandu-pns. For now, the only workaround seems to be destroying the resource and re-apply.

**Comment by pranav-new-relic** [comment]
Hi @mBlomsterberg, thank you for flagging this. It appears that a tiny bug was introduced into the working procedure which disables existing cloud integrations, which we have addressed  (and fixed in the code) today. The fix will be out with the next release, which we plan to do sometime next week, as we are waiting on a few more fixes/features for a release. We shall keep you posted about this. Thank you!

**Comment by pranav-new-relic** [comment]
Hi, a fix to the issue has been released with the latest version of the provider, [v3.27.0](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.27.0) - this should help remediate the issue 😄 can you please try now, with this version, and let us know what you see? Thanks!

**Comment by mBlomsterberg** [comment]
> Hi, a fix to the issue has been released with the latest version of the provider, [v3.27.0](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.27.0) - this should help remediate the issue 😄 can you please try now, with this version, and let us know what you see? Thanks!

Works!

**Comment by Nandu-pns** [comment]
Thanks for letting us know it now works, hence closing this issue.
