### ISSUE TITLE
Newrelic synthetic simple browser code is not working

### ISSUE THREAD

**Issue by atul29mehta** [newrelic/terraform-provider-newrelic#2464]
Hi Team,

Before 8th Sept my synthetic simple browser code was running fine. After the commit it is giving error to add the value for device orientation and device type. And for both arguments there is no definition found in the latest docs of newrelic terraform.
https://github.com/newrelic/terraform-provider-newrelic/commit/8f4896a61b4bb5ad1b5d6c2da5173aebfe6c55ac
 
This is impacting our production because due to this we are not able to run the terraform code as it is failing with below error.
06 Error: Argument "monitor" has invalid value $monitor.
0 In field "advancedoptions": Expected type "SyntheticssimpleBrowserMonitorAdvancedOptionsInput", found {deviceEmulation:
{deviceOrientation:
)
deviceType: ""}, enableScreenshotOnFailureAndScript: true, responseValidationText:
true}.
"success", uselsvalidation:
© In field "deviceEmulation": Expected type "SyntheticsDeviceEmulationInput", found {deviceorientation:
"", deviceType: ""}.
www In field "deviceorientation": Expected type "SyntheticsDeviceorientation!", found ""
©% In field "deviceType": Expected type "SyntheticsDeviceType!", found ""
with module.baseline.module.synthetics_simple_browser_ monitor [2].newrelic_synthetics_monitor.simple_browser _monitor, on .terraform/modules/baseline/modules/newrelic_synthetics_monitor/simple_browser_monitor/main.tf line 1, in resource
"newrelic_synthetics monitor"
"simple_browser_monitor'
1: resource "newrelic synthetics monitor" "simple browser monitor" {
06 Error: Argument "monitor" has invalid value $monitor.
064 In field "advancedoptions": Expected type "SyntheticsSimpleBrowserMonitorAdvancedoptionsInput", found {deviceEmulation:
{deviceOrientation:
, deviceType:
""}, enablescreenshotOnFailureAndscript: true, responseValidationText: "success", useTIsValidation:
true}.
•* In field "deviceEmulation": Expected type "SyntheticsDeviceEmulationInput", found {deviceorientation: "", deviceType: "").

Earlier with the same code we were not facing any issue.
工

**Comment by mbazhlekova** [comment]
@atul29mehta I'm looking into this issue today. You can roll back to a previous version of the provider in the meantime.

**Comment by amolero-nr** [comment]
@atul29mehta, also, you can find those fields documented in the `Arguments Reference` section [here](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor#argument-reference), under additional arguments for the `BROWSER` monitor.

**Comment by mbazhlekova** [comment]
@atul29mehta We deployed a bug fix for this in the latest version of the provider.
