### ISSUE TITLE
`AWS_` location prefix in synthetic cert checks stripped silently, causes spurious Terraform updates

### ISSUE THREAD

**Issue by reneesoika** [newrelic/terraform-provider-newrelic#2470]
### Terraform Version
```
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.27.1
```

### Affected Resource(s)
- `newrelic_synthetics_cert_check_monitor`

We also use `newrelic_synthetics_script_monitor` resources and haven't seen this issue happening with those.

### Terraform Configuration
```hcl
resource "newrelic_synthetics_cert_check_monitor" "redacted" {
  // redacted
  locations_public       = ["AWS_US_WEST_2"]
  // redacted
}
```

### Actual Behavior
It appears that the New Relic provider is stripping the `AWS_` prefix from the location when the resources are created. However, this means that the remote state does not match the Terraform state, so we are seeing spurious updates for the location:

```
resource "newrelic_synthetics_cert_check_monitor" "redacted" {
        id                     = "redacted"
      ~ locations_public       = [
          - "US_WEST_2",
          + "AWS_US_WEST_2",
        ]
        name                   = "redacted"
        # (6 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

### Expected Behavior
The prefix should not be stripped silently. If the prefix has to be removed, locations with the `AWS_` prefix should cause a clear error.

**Comment by pranav-new-relic** [comment]
Hi @reneesoika - thank you for reporting this. We have been able to reproduce the issue, and shall fix this based on our current task priority.
