### ISSUE TITLE
`data` support for workflows

### ISSUE THREAD

**Issue by gparton** [newrelic/terraform-provider-newrelic#2474]
### Context
I'd like to write a module for our company that creates a policy, adds some NRQL alert conditions, and attaches existing workflows to the policy for notification channels that I'd like to ping whenever an incident is raised for the policy.

### Feature Description
I've noticed in the provider documentation that there is pretty lean support for data sources as compared to resources. I'm trying to plan out a Terraform migration of our manually managed alert policies at my organization & it looks like there isn't any support for `data` sources relating to notification workflows, and the only data source that looks relevant here is being deprecated in the next major release:
![Screenshot 2023-09-22 at 3 44 31 PM](https://github.com/newrelic/terraform-provider-newrelic/assets/10590120/abaf391d-012f-4156-9e57-cc084c5e3ffb)

Is there a roadmap initiative to support such a use case? If not, what is the recommended workflow for creating reusable workflows in Terraform that can be attached to policies? I'd prefer not to create a new workflow for every policy, but that seems illogical considering workflows are reusable in the UI.

**Comment by amaor-newrelic** [comment]
Hi @gparton ! 
Workflows are not reusable, therefore there is no real use for a data source. 
You do only need a single workflow that filters on multiple policies, like so - 
```
    predicate {
      attribute = "labels.policyIds"
      operator = "EXACTLY_MATCHES"
      values = [
        newrelic_alert_policy.policy_a.id,
        newrelic_alert_policy.policy_b.id,
        newrelic_alert_policy.policy_c.id,
      ]
    }

```

**Comment by gparton** [comment]
Oh interesting. Thanks for the reply @amaor-newrelic. So the `workflow` resource needs to be provided the alert policy IDs, instead of creating the policy and passing the workflow ID to the policy. This seems a little backwards coming from a Google Monitoring background but I suppose that's a fine workaround.
