### ISSUE TITLE
Add support for provisioning users

### ISSUE THREAD

**Issue by ankon** [newrelic/terraform-provider-newrelic#2509]
### Feature Description

We currently need to "invite" users each time we on-board a new team member. It would be great if we could do that step through Terraform, ideally by providing the email and user group.

### Describe Alternatives

We're using SSO, so I guess on-demand account creation is an alternative. The problem with that is that it produces a bit of a chicken-egg thing: We still need to assign the user to a group, i.e. still need to go to the UI to "invite" them.

**Comment by pranav-new-relic** [comment]
Hi @ankon, thanks for reporting this. Just to make sure we understand this right - are you referring to the following step in the UI where we add a new user to a group, as a consequence of which an invite is sent to the user?

<img width="1481" alt="image" src="https://github.com/newrelic/terraform-provider-newrelic/assets/127438038/309eeef1-dff1-4ac0-916e-51a681238ea8">

If yes, we have planned work for this feature (user and group management) in the next few months (Q4), so this would be handled as part of that. I'd just like to make sure this is in alignment with what you've mentioned in the description of the issue. Thanks!

**Comment by ankon** [comment]
Yes, roughly that step indeed. Obviously the related parts, too:
* Deleting users
* Changing the user roles
* ...

And, taking into account a SSO setup etc. :)

**Comment by pranav-new-relic** [comment]
Hi @ankon, resources to provision/manage users and groups in the Terraform Provider have recently been released - please check the following out.

- https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/authentication_domain
- https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/user
- https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/user
- https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/group
- https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/group

The "roles" part of this request is still a work in progress as we continue to work on figuring out doables in this space to enable access management as well. This part of the request aligns with the request stated in #1866, so I'd recommend you to follow the other thread where we shall be posting updates in the upcoming few months. I shall be closing this issue. Thank you for reporting!
