### ISSUE TITLE
Support private locations with hmac

### ISSUE THREAD

**Issue by timboven** [newrelic/terraform-provider-newrelic#252]
Our private locations are configured with a hmac but this can't be configured with this provider.
Could you please include an option so that hmac can be configured for private locations.

Something similar is done in a unofficial version: https://github.com/dollarshaveclub/terraform-provider-nrs/blob/master/pkg/provider/resource_nrs_monitor.go#L180

**Comment by zlesnr** [comment]
Hi @timboven, would you mind sketching out what you expect an example resource to look like here?

**Comment by jthurman42** [comment]
It appears that the `newrelic-client-go` does support this now, need to evaluate / test

Ref: https://github.com/newrelic/newrelic-client-go/blob/master/pkg/synthetics/monitors.go#L13

**Comment by HTTP500** [comment]
+1 for having this feature
This is required if one want to enabled VSE (https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/verified-script-execution-private-locations). It will give organizations higher confidence for deploying containerized private minions in their internal networks

**Comment by spolve** [comment]
Hi, do you plan to implement this feature in the near future?

**Comment by dconnolly-sfdc** [comment]
+1 would like to see this option included

**Comment by mbazhlekova** [comment]
Hey @timboven, @HTTP500, @spolve, @dconnolly-sfdc 👋 we added support for private locations with HMAC in version 2.24.1
