### ISSUE TITLE
Newrelic Slack Destination Terraform Authentication Expiry

### ISSUE THREAD

**Issue by 27sumjai** [newrelic/terraform-provider-newrelic#2522]
Hi there,
Using slack destination with newrelic latest terraform code requires us to create slack destination manually in the Newrelic UI and pass its destination id to the following code. We use ping/AD authentication for Newrelic so each time we have to create a slack destination, it requires our ping/SSO/AD credentials.

resource "newrelic_notification_channel" "foo" {
  account_id = 12345678
  name = "slack-example"
  type = "SLACK"
  destination_id = "00b6bd1d-ac06-4d3d-bd72-49551e70f7a8"
  product = "IINT"

  property {
    key = "channelId"
    value = "123456"
  }

  property {
    key = "customDetailsSlack"
    value = "issue id - {{issueId}}"
  }
}

I am just worried that the slack destination will expire as it used some aunthetication in the backend which is associated with a token.
What is the solution that slack destination once created by a user manually do not expire or do not not working if user were to leave the organisation?

thanks
SJ

**Comment by pranav-new-relic** [comment]
Hi @27sumjai - I believe you've received an answer to this query via a fellow colleague at New Relic, but would like to add a brief here - if one were to create a Slack destination in the UI and import it/use the destination ID, it will not expire - so, you wouldn't need to be concerned about the user leaving, and it would be okay to continue to use this procedure to use a Slack destination via Terraform.

cc @amaor-newrelic
