### ISSUE TITLE
Update newrelic_cloud_azure_integrations terraform.io documentation to include warning about potential for duplicate metrics if both Azure Monitor and API Polling are used.

### ISSUE THREAD

**Issue by alaiavee** [newrelic/terraform-provider-newrelic#2530]
### Feature Description
This is a request to update the newrelic_cloud_azure_integrations documentation on terraform.io ([LINK](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/cloud_azure_integrations)) to include a warning that if both Azure Monitor and the API Polling integrations are set up for the same resource types then duplicates may occur.

While the New Relic Azure Monitor documentation does provide the warning below, we are seeing situations where users that are automating the setup with Terraform miss that this scenario can happen and end up with duplicates in their environment because both Azure Monitor and the Azure API polling integration have been set up for the same resource types.

It may also be helpful to mention it here as well:
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/cloud_integrations_guide#azure

Warning in New Relic Azure Monitor documentation ([LINK](https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-monitor/#migrate)):

IMPORTANT
**If both integrations are enabled for the same resource type, you may see duplicate metrics.** This can happen if you use a generic name field to filter your results that can be shared from the Azure monitor and the Azure Polling integrations. The results from multiple resources could be joined unintentionally.
Note that metrics can still be differentiated by faceting using the field collector.name. Also note that rate limits as enforced by Azure will be shared between any current polling integrations and the Azure monitor.

**Comment by pranav-new-relic** [comment]
Thank you for reporting this, @alaiavee. We'll take a closer look at this soon to get things updated.

**Comment by pranav-new-relic** [comment]
This has been added to the documentation. Thanks for reporting this.
