### ISSUE TITLE
Terraform Provider Plugin is Crashing

### ISSUE THREAD

**Issue by moazzamali-tcp** [newrelic/terraform-provider-newrelic#2559]
### There was a outage today on newrelic and after that getting error while performing terraform changes:

Stack trace from the terraform-provider-newrelic_v3.29.0 plugin:

panic: interface conversion: entities.EntityInterface is nil, not *entities.GenericEntity

goroutine 115 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicMonitorDowntimeRead.func1()        
        /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_monitor_downtime.go:245 +0x34a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.RetryContext.func1()
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/retry/wait.go:27 +0x56
github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext.func1()       
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/retry/state.go:110 +0x1ff
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext    
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/retry/state.go:83 +0x1d8

Error: The terraform-provider-newrelic_v3.29.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by pranav-new-relic** [comment]
Hi @moazzamali-tcp, thank you for reporting this! Unfortunately, it could have been that the relevant outage caused a disruption to API calls performed to fetch details of entities from NerdGraph; which in the case of this resource, is  an entity with the GUID of that of the Monitor Downtime - this may have subsequently led to the provider panicking. The error you've attached is usually never expected.

I've tested the monitor downtime resource out sometime ago and now, and find that it is working fine (doesn't seem to return this error anymore) and I'm assuming it is so as the error above should have lasted only during the outage. Can you please try now and let me know if you still see the issue? Thanks!

**Comment by moazzamali-tcp** [comment]
hi @pranav-new-relic  Thanks for response Yes my provider version is working fine.
