### ISSUE TITLE
Workload entity_search_query error

### ISSUE THREAD

**Issue by Jattwood90** [newrelic/terraform-provider-newrelic#2591]
Hi there,

Having an issue creating a New Relic workload via Terraform. The error output suggests I must pass a string value for `entity_search_query` despite this being optional, if I am including `entity_guids`.

### Terraform Version
Terraform v1.7.2
on linux_arm64
+ provider registry.terraform.io/newrelic/newrelic v3.30.0

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_workloads`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.

```hcl
### main.tf ###
terraform {
  required_version = ">= 1.4.4"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.30.0"
    }
  }
  backend "local" {
    path = "/local/terraform.tfstate"
  }
}

provider "newrelic" {
  account_id = "000000"
  api_key    = "NRAK-*********" # usually prefixed with 'NRAK'
  region     = "US"                               # Valid regions are US and EU
}

### workload.tf ###
resource "newrelic_workload" "workload" {
    account_id  = var.account_id
    name        = var.workload_name
    description = var.description
    scope_account_ids = var.scope_account_ids
    
    entity_guids = var.entity_guids

    entity_search_query {
        query = var.query
    }
    
    dynamic "status_config_static" {
        for_each = var.include_status_config_static ? [1] : []
        content {
            description = status_config_static.value.description
            enabled     = status_config_static.value.enabled
            status      = status_config_static.value.status
            summary     = status_config_static.value.summary
        }
    }
}

### variables.tf ###
variable "account_id" {
  type        = number
  description = "New Relic Account to create workload in"
}

variable "description" {
  type        = string
  description = "The description of the workload"
  nullable = true
}

variable "workload_name" {
  type        = string
  description = "The name of the workload"
}

variable "query" {
  type        = string
  description = "The query to search for entities to add to the workload"
  nullable = true
}

variable "scope_account_ids" {
  type        = list(number)
  description = "A list of account ids. Account ids are the ids of the accounts you want to scope the workload to"
  nullable = true
}

variable "entity_guids" {
  type        = list(string)
  description = "A list of entity guids. Entity guids are new relic ids of entities you want to add to the workload"
  nullable = true
}

### parameters.tfvars ###
account_id    = 0000000
workload_name = "TEST WORKLOAD"
description   = null

scope_account_ids = [ 0000000 ]
entity_guids = [ "GUID" ]

query = "" #can't pass false, or null here

## status_config_static block
include_status_config_static  = false
status_config_static = {
    description = null
    enabled = false
    status  = null
    summary = null
}
```

### Actual Behavior
Plan completes, as it believes I am passing a string as per the variable. Cannot pass false or null as it insists the `entity_search_query` block is required. Accepts empty string when running apply then throws error:
```
maximum retries reached: Invalid query  AND type = 'DASHBOARD', details: Provided filter: [ AND type = 'DASHBOARD'] is not a valid NRQL query
```

### Expected Behavior
As I am passing an entity_guid variable, entity_search_query should be optional as per the documentation [here](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workload#argument-reference).
I am aiming to create a resource that can be uploaded to our Terraform Enterprise registry, therefore having a full template with optional/nullable variables is key if I am to avoid creating 2 or 3 versions of the resource depending on needs.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

### Debug Output
Link to gist: https://gist.github.com/Jattwood90/654ca0ef8cece9c4d7f5429923c0fac9 

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Provider docs: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workload#nested-entity_search_query-blocks

Potentially similar issues:
https://github.com/newrelic/terraform-provider-newrelic/issues/1926

**Comment by rferrer-nr** [comment]
We are glad to hear that this could help. If you do not mind, we would like to keep this issue open until we can enhance both the error message and the documentation. These improvements should be implemented shortly.
