### ISSUE TITLE
Feature Request: Implement support for configurable threshold markers in line charts and tables

### ISSUE THREAD

**Issue by dehimb** [newrelic/terraform-provider-newrelic#2647]
### Feature Description
NewRelic has introduced the ability to set [configurable thresholds on line charts and tables](https://docs.newrelic.com/whats-new/2024/04/whats-new-04-22-dashboard-thresholds), enhancing data interpretation. To streamline this process, we aim to enable the configuration of these thresholds via the Terraform provider.

### Describe Alternatives
Currently, the creation of thresholds for line and table charts is a manual process.

**Comment by pranav-new-relic** [comment]
Hi @dehimb, we have planned work for this feature. Work for gathering prerequisites to develop a Terraform resource for this is currently a work in progress, you should see this come soon.

**Comment by pranav-new-relic** [comment]
@dehimb this feature is now out with v3.37.0 of the Provider. See [this section of the documentation](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#threshold) of the `newrelic_one_dashboard` resource (under `line` and `table` widgets) for more details on the usage of these thresholds. 

Thank you for reporting this :)
