### ISSUE TITLE
Resource `newrelic_one_dashboard`: Threshold from/to defaults to 0 with `widget_line`

### ISSUE THREAD

**Issue by jackie-linz** [newrelic/terraform-provider-newrelic#2705]
## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [ ] Any related [log output](#debug-output)

### Terraform Version
`v1.9.0` with `newrelic provider 3.38.1`

### Affected Resource(s)

- `resource_newrelic_one_dashboard`

with

```json
                "threshold": [
                  {
                    "from": 0,
                    "name": "Good",
                    "severity": "success",
                    "to": 200
                  },
                  {
                    "from": 200,
                    "name": "Needs improvement",
                    "severity": "warning",
                    "to": 500
                  },
                  {
                    "from": 500,
                    "name": "Poor",
                    "severity": "critical"
                  }
                ],
```

### Actual Behavior
The `to` value for the `Poor` threshold is set to 0, which is wrong

![image](https://github.com/newrelic/terraform-provider-newrelic/assets/120340761/f479fd97-8354-4eec-83a2-50840af1953b)

### Expected Behavior
The `to` value should be left unset
![image](https://github.com/newrelic/terraform-provider-newrelic/assets/120340761/59402529-e5b1-4588-9930-e48dd5b3e82e)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by vagrawal-newrelic** [comment]
We have fixed this issue and the changes have been released in the current versions of terraform provider. Now if you donot provide `from` or `to` fields in `table` or `line` widget in `newrelic_one_dashboard` resource then it will not get defaulted to 0 instead UI will show a blank value.
Thanks a lot @jackie-linz for raising this concern.
