### ISSUE TITLE
Resource `newrelic_browser_application`: Often rm only returns `application_id` on second apply

### ISSUE THREAD

**Issue by piran-cabiri** [newrelic/terraform-provider-newrelic#2707]
In https://github.com/newrelic/terraform-provider-newrelic/issues/2577 the ability for `newrelic_browser_application` to return the created `application_id` was added, and was released in 3.35.2.

However, I'm not seeing the created `application_id` being consistently returned on the first apply. Sometimes it is, sometimes it isn't, and a second apply shows the state updating the application_id. Checked with 3.35.2 and 3.38.1.

From the debug log when it fails, it looks like a newrelic query doesn't find the created mutation. As it works sometimes, I guess newrelic takes a while to create the resource.

I've attached a minimal [main.tf](https://github.com/user-attachments/files/16070277/main.tf.txt) with an output which I'm using to prove the bug.

### Terraform Version

```
terraform -version                                    
Terraform v1.7.5
on darwin_arm64
+ provider registry.terraform.io/newrelic/newrelic v3.38.1
```

### Affected Resource(s)

- `newrelic_browser_application`

### Terraform Configuration

See attached [main.tf](https://github.com/user-attachments/files/16070277/main.tf.txt) for full file, but:

```
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "3.38.1"
    }
  }
}

resource "newrelic_browser_application" "web" {
  name                        = "my-dev-piran-test3"
  cookies_enabled             = true
  distributed_tracing_enabled = true
  loader_type                 = "SPA"
}

```

### Actual Behavior
`application_id` not always available after NewRelic Browser resource is created (it mostly fails).

### Expected Behavior
`application_id` to always be available after NewRelic Browser resource is created.

### Steps to Reproduce

The first apply I get:
```
% terraform apply                                       

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # newrelic_browser_application.web will be created
  + resource "newrelic_browser_application" "web" {
      + account_id                  = (known after apply)
      + application_id              = (known after apply)
      + cookies_enabled             = true
      + distributed_tracing_enabled = true
      + guid                        = (known after apply)
      + id                          = (known after apply)
      + js_config                   = (known after apply)
      + loader_type                 = "SPA"
      + name                        = "my-dev-piran-test"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + newrelic_browser_account_id = (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

newrelic_browser_application.web: Creating...
newrelic_browser_application.web: Creation complete after 2s [id=NDMxxxxxxxxxxxxxxxxxxxxxx]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
pdb@Chapel tmp % terraform output newrelic_browser_account_id          
╷
│ Warning: No outputs found
```

On the second apply, the state gets updated with the application_id, and the output is set:

```
% terraform apply
newrelic_browser_application.web: Refreshing state... [id=NDMxxxxxxxxxxxxxxxxxxxxxx]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # newrelic_browser_application.web has changed
  ~ resource "newrelic_browser_application" "web" {
      + application_id              = "1588967118"
        id                          = "NDMxxxxxxxxxxxxxxxxxxxxxx"
        name                        = "my-dev-piran-test3"
        # (5 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Changes to Outputs:
  + newrelic_browser_account_id = "1588967118"

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
...
```

I would expect the `application_id` to be available immediately after the resource has been created in the first apply. It sometimes is, but not usually.

### Debug Output

Debug log from a similarly failing first apply is in:
https://gist.github.com/piran-cabiri/bcd4b82be1efb681dad3d2474edde506

### References

`newrelic_browser_application` 's `application_id` return created in response to https://github.com/newrelic/terraform-provider-newrelic/issues/2577

**Comment by pranav-new-relic** [comment]
Hi @piran-cabiri, thank you for reporting this. We've noticed this happen at times as well, especially when integration tests (which capture the behaviour of this resource) keep failing sometimes, owing to some of these attributes not being populated on time.

While we do not have a rigid workaround/fix at the moment, we'll keep you posted when we pick this up and further investigate into this, so we can come up with an apt solution.

**Comment by vinay-newrelic** [comment]
@piran-cabiri This is no longer occurring despite multiple tests. However, we would be happy to hear from you if you are still facing the issue.

**Comment by piran-cabiri** [comment]
Just had a recurrence of this today when creating a new environment. So the problem can STILL occur for me. 

Still on "registry.terraform.io/newrelic/newrelic" version="3.35.2", 

with my resource looking like:
```
# ... with import, or create a new NewRelic Browser application...
resource "newrelic_browser_application" "web_browser" {
  name                        = local.newrelic_browser_name
  cookies_enabled             = true
  distributed_tracing_enabled = true
  loader_type                 = "SPA"
}
```

and my output looking like this:
```
output "newrelic_browser_json" {
  description = "NewRelic Browser config settings as JSON"
  value = {
    ACCOUNT_ID          = nonsensitive(local.newrelic_client_secret["NrAccountId"])
    APPLICATION_ID      = data.newrelic_entity.web_browser.application_id
    APP_NAME            = local.newrelic_browser_name
    LICENSE_KEY         = nonsensitive(local.newrelic_client_secret["LicenseKey"])
    LICENSE_KEY_BROWSER = nonsensitive(local.newrelic_client_secret["LicenseKeyBrowser"])
    TRUSTED_ACCOUNT_KEY = nonsensitive(local.newrelic_client_secret["ParentAccountId"])
  }
}
```

giving me he results:
```
newrelic_browser_json = {
  "ACCOUNT_ID" = "redacted"
  "APPLICATION_ID" = tostring(null)
  "APP_NAME" = "redacted-web-browser"
  "LICENSE_KEY" = "redacted"
  "LICENSE_KEY_BROWSER" = "redacted"
  "TRUSTED_ACCOUNT_KEY" = "redacted"
}
```

where `APPLICATION_ID` should not be null.

Re-running about 60 seconds later returned the correct value for `APPLICATION_ID`. 

I also tested, and [`js_config`](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/browser_application#js_config) was also not set on the first run.

**Comment by vinay-newrelic** [comment]
@piran-cabiri Even after multiple retries , I am still unable to replicate the issue on my side .However, can you please provide your main.tf with the latest changes that have been mentioned above and i will try to see if there something that differentiate your code with mine.

**Comment by piran-cabiri** [comment]
hi @vinay-newrelic. Here's what my main.tf looks like with the wait still in place. We've been running this for some months, and not had a failure of note yet. My [comment on 29-Oct-2024](https://github.com/newrelic/terraform-provider-newrelic/issues/2707#issuecomment-2443751213) was after I tried to remove the wait you see below. This was in a pure 'create' (not a 're-create', which I'll explain...)

For context, we have a number of terraform workspace that we create, update, delete and re-create; these are developer environments or for pull-requests. Therefore, it's important that we can create a NewRelic browser safely when we create a workspace. When we delete the workspace, we don't delete the NewRelic Browser, because it won't delete until 12hrs after it's had traffic. But then if someone re-opens the PR, we need to re-associate with any existing NewRelic Browser, which we find through the `data.newrelic_entity.existing_web_browser` and then load via the `import` statement.

---
This is what we currently use, which does NOT see the problem

The `main.tf` looks like:

```terraform
# This can't be turned into a module, as uses `import` block.

locals {
  # NB: You cannot easily change the name; it doesn't seem to stick, or takes time to changeover
  newrelic_browser_name = "${var.project}-${var.environment}-${terraform.workspace}-web-browser"

  newrelic_client_secret = jsondecode(data.aws_secretsmanager_secret_version.newrelic_client.secret_string)

  dummy_map = {
    "dummy" = "value"
  }
}

# Look for an existing NewRelic Browser application...
data "newrelic_entity" "existing_web_browser" {
  name             = local.newrelic_browser_name
  type             = "APPLICATION"
  domain           = "BROWSER"
  ignore_not_found = true
}

# ... if found, import into terraform ...
import {
  for_each = data.newrelic_entity.existing_web_browser.guid != null && var.current_command != "destroy" ? local.dummy_map : {}

  to = newrelic_browser_application.web
  id = data.newrelic_entity.existing_web_browser.guid
}

# ... with import, or create a new NewRelic Browser application...
resource "newrelic_browser_application" "web" {
  name                        = local.newrelic_browser_name
  cookies_enabled             = true
  distributed_tracing_enabled = true
  loader_type                 = "SPA"
}

# ... which doesn't get created immediately, so wait a little bit ...
resource "time_sleep" "wait_for_newrelic_browser_creation" {
  depends_on = [newrelic_browser_application.web]

  create_duration = "20s"
}

# ... and then query NewRelic for the final values
data "newrelic_entity" "web_browser" {
  name   = local.newrelic_browser_name
  type   = "APPLICATION"
  domain = "BROWSER"

  depends_on = [
    time_sleep.wait_for_newrelic_browser_creation
  ]
}
```

The output is:
```
output "newrelic_browser_json" {
  description = "NewRelic Browser config settings as JSON"
  # marked as 'nonsensitive', as the values appear in plaintext on the browser
  value = {
    ACCOUNT_ID          = nonsensitive(local.newrelic_client_secret["NrAccountId"])
    APPLICATION_ID      = data.newrelic_entity.web_browser.application_id
    APP_NAME            = local.newrelic_browser_name
    LICENSE_KEY         = nonsensitive(local.newrelic_client_secret["LicenseKey"])
    LICENSE_KEY_BROWSER = nonsensitive(local.newrelic_client_secret["LicenseKeyBrowser"])
    TRUSTED_ACCOUNT_KEY = nonsensitive(local.newrelic_client_secret["ParentAccountId"])
  }
}
```

we're actually using terragrunt for these multiple environments, and in our `terragrunt.hcl` we have:
```
[...]
terraform {
  before_hook "remove_browser_from_state" {
    commands = ["destroy"]
    execute  = ["./remove-browser-from-state.sh"]
  }
}
[...]
inputs = {
  current_command = local.current_command
}
```

That `remove-browser-from-state.sh` is:
```shell
#!/bin/bash
set -xe

echo "[INFO]: Removing newrelic_browser_application.web from state"
if [ "$(terraform state list | grep -c "newrelic_browser_application.web")" -gt 0 ]
then  terraform state rm newrelic_browser_application.web
fi
```

---

The failure came when I tried to remove the wait in `wait_for_newrelic_browser_creation` and `web_browser`, and just get the output's `APPLICATION_ID` value directly from `resource.newrelic_browser_application.web.application_id`.

**Comment by gonzalob** [comment]
We're facing this same issue.

I understand (and implemented) the workaround from @piran-cabiri. It works, and at the time introduces a forced delay in applying and permeates an implementation detail. This could be avoided in the same way the AWS provider handles ACM validation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation

I don't clearly understand why is this issue closed. It is reproduceable with the latest provider version (at this time, 3.54.0)
