### ISSUE TITLE
Resource `newrelic_one_dashboard`: Bug in `terraform apply`

### ISSUE THREAD

**Issue by samuelfalico** [newrelic/terraform-provider-newrelic#2718]
Hi there,

I have a problem when I run `terraform apply`, it is returning an error with the reason that the plugin crashed

### Terraform Version
Terraform v1.9.3

### Provider Version
provider registry.terraform.io/newrelic/newrelic v3.40.1

### Actual Behavior
What actually happened?
Error when running `terraform apply`.

### Expected Behavior
What should have happened?
I should have deployed the dashboard.

### Steps to Reproduce
1. `terraform apply`

### Debug Output
[Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.](https://gist.github.com/samuelfalico/6de155c8bb606eb2b9d831c910c633f7)

### Panic Output
[If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.](https://gist.github.com/samuelfalico/6de155c8bb606eb2b9d831c910c633f7)

**Comment by pranav-new-relic** [comment]
@samuelfalico hi 👋 thanks for reporting this issue. From the debug output you've attached, it appears that the error

```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 97 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandDashboardWidgetColorsInput(_, {{0xc000904108, 0x1, 0x1}, 0x0, 0x0, {0x0, 0x0}, {0x0, 0x0}, ...})
        /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_one_dashboard.go:824 +0x3c6
```

can be traced to the following line of code, based on what we see in the snippet above.

https://github.com/newrelic/terraform-provider-newrelic/blob/a9e194c0a4ec0406a900b2943bfd66523c54cc6a/newrelic/structures_newrelic_one_dashboard.go#L819-L824

Both of these help conclude that this erroneous occurrence is supposed to be seen only if the `series_overrides` block in the `colors` argument is empty/nil, which is not supposed to be the case, as `series_overrides` is supposed to comprise arguments `color` and `series_name`, as you may find in the examples [in our docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard).

<img width="298" alt="image" src="https://github.com/user-attachments/assets/3da50eeb-cb62-4e32-9c27-a2ddf46cc845">


Let us know if this helps fix your problem; if it doesn't, please share the Terraform configuration you're seeing this error with so we can help you further. Thanks!
