### ISSUE TITLE
Resource `newrelic_notification_destination`: The resource does not seem to update amended resources 

### ISSUE THREAD

**Issue by mBlomsterberg** [newrelic/terraform-provider-newrelic#2724]
## Bug report
Updating the `property` argument within the `newrelic_notification_destination` resource does not alter the resource despite seeing the change.  

Workaround is to destroy the entire resource and re-apply. 

## Configuration and affected resources 
- `v1.5.5` of Terraform
- `v3.12.0` of the New Relic Provider
- `newrelic_notification_destination` resource
- `property`argument within resource

**Comment by pranav-new-relic** [comment]
Hi @mBlomsterberg, I just tried reproducing this issue but do not seem to be seeing a case in which the changes made to the `property` field in the `newrelic_notification_destination` resource after apply, do not propagate into the changes visible in the UI, with the version you've reported. Can you please upgrade to the latest version of the New Relic Terraform Provider and let us know if you still see this behaviour? If you do, please attach a set of steps to reproduce this issue which shall be helpful for our team to dig deeper into the issue, if any. Thanks!
