### ISSUE TITLE
Resource `newrelic_one_dashboard`: Unable to disable legend in `widget_line`

### ISSUE THREAD

**Issue by mkatana-silkycoders** [newrelic/terraform-provider-newrelic#2736]
Provider version: 3.42.3
Terraform Version: 1.8.4

In widget_line, I am trying to disable the legend via `legend_enabled`. No matter what value this key has, the legend is always enabled. In the Terraform output, I can see Terraform is trying to change the value.

If I set this manually, that works. After applying Terraform Legend just back again,

![image](https://github.com/user-attachments/assets/85c25b6c-0ecc-4e33-af39-c09ecf34b83c)
![image](https://github.com/user-attachments/assets/9865c606-6a80-4440-8529-2f85fa4895db)

via Burp, I found that if I set `legend_enabled = false,` a request to NewRelic is sent without `legend.enabled` set to `false`

![image](https://github.com/user-attachments/assets/a7c00baa-7c8f-447a-a92b-5d37eed01ddd)

with `legend_enabled` set to `true` in the request, I see the correct value: `legend.enabled: true`

**Comment by mkatana-silkycoders** [comment]
via Burp i found.. 

when I set legend_enabled = false, request to new relic is send without **legend_enabled = false**

![image](https://github.com/user-attachments/assets/8ff7a8cf-77d4-4ee8-bd18-b2e795408e73)

**Comment by vinay-newrelic** [comment]
@mkatana-silkycoders The issue has now been resolved.You will now be disable the legend via legend_enabled in widget_line
