### ISSUE TITLE
Feature Request: Add support for Metric Filters to the AWS Cloud Integration Module

### ISSUE THREAD

**Issue by sjauld** [newrelic/terraform-provider-newrelic#2765]
### Feature Description
Currently, using the AWS cloud integration module will stream all AWS metrics to NewRelic. However I only want to stream specific metrics in order to control costs. Adding support for inclusive and exclusive metric filters will enable this.

### Describe Alternatives
N/A

### Additional context
Pull request coming next

**Comment by pranav-new-relic** [comment]
Hey @sjauld, thank you for creating this issue, and in advance for the PR you're going to create to contribute code for this request!

We'd be looking forward to review your changes, while it might take quite a while, given a bunch of other priorities we're working on :)
