### ISSUE TITLE
Create a resource for browser applications

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#309]
The APIs are available to provision browser applications, so we should build around these endpoints in the provider.

**Comment by jthurman42** [comment]
Requires resolution of upstream issue newrelic/newrelic-client-go#135 to complete

**Comment by ctrombley** [comment]
The data source requirement is now supported via the `newrelic_entity` data source.  The name of this ticket has been updated to reflect this.

Work will still be required to provision new browser applications.

**Comment by jthurman42** [comment]
Duplicate of #73
