### ISSUE TITLE
Provide more helpful error messages for ID parsing during imports

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#419]
Here is the current user experience: 

```
terraform import newrelic_nrql_alert_condition.prod_ui_slack_incoming_internal_http_traffic_failing_nrql_condition 159633

Error: unable to parse ID 159633
```

[This error](https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_nrql_alert_condition.go#L158) and others like it could easily be wrapped with some more helpful wording that lays out the required ID format described in the docs: https://www.terraform.io/docs/providers/newrelic/r/nrql_alert_condition.html#import

**Comment by emetcalf9** [comment]
The error message returned here has been changed since this Issue was filed. Closing this out, and a new issue can be created if there needs to be more work done on this.
