### ISSUE TITLE
Feature Request: Multi-location failure synthetics alerts.

### ISSUE THREAD

**Issue by veeravallib** [newrelic/terraform-provider-newrelic#425]
New Relic Provides creation of multi location failures. The current synthetic alert resource allows for creation of single location failure.

Documentation Source - https://docs.newrelic.com/docs/alerts/new-relic-alerts/defining-conditions/multi-location-synthetics-alert-conditions

![image](https://user-images.githubusercontent.com/44437783/75539945-f3b43f80-59cf-11ea-93f8-6a050b871004.png)

This is a different endpoint than the single failure synthetic alert - https://api.newrelic.com/v2/alerts_location_failure_conditions/{id}.json

Request json

`'{
  "location_failure_condition": {
    "name": "string",
    "runbook_url": "string",
    "enabled": "boolean",
    "entities": [
      "string"
    ],
    "terms": [
      {
        "priority": "string",
        "threshold": "integer"
      }
    ],
    "violation_time_limit_seconds": "integer"
  }
}' `

**Comment by ctrombley** [comment]
The enabling work for this enhancement was completed in newrelic/newrelic-client-go#118.

**Comment by zlesnr** [comment]
Given that this is a new endpoint, I'm thinking a new resource makes sense here.  I'll start working that up now that I've found the API docs for it.

**Comment by zlesnr** [comment]
This will make it into the next release.
