### ISSUE TITLE
Create a module for encapsulating alert channels within a policy

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#434]
AC:

* Add an easy-to-use monitoring module for APM applications that abstracts away the need to define full resources
* Publish the module to the Terraform registry

**Comment by worldcompass** [comment]
Hello,  @ctrombley 

I've created such a module in scope of my working task.

If the issue is still relevant, I can publish this module in my GitHub and get back to you.

The module creates an alert policy and attaches the alert channels to it.

**Comment by zlesnr** [comment]
@worldcompass Let's see it if you've still got it.

**Comment by emetcalf9** [comment]
Closing this out because it was marked "Done" on 3/10/2020
