### ISSUE TITLE
Add support for External Service Conditions

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#442]
Build a Terraform resource for provisioning [external service alert conditions](https://rpm.newrelic.com/api/explore/alerts_external_service_conditions/create).

**Comment by kidk** [comment]
As we're moving everything to GraphQL and NRQL alerts I don't think we should spend time on this. If there's a high demand from customers we can reconsider. Closing for now.

**Comment by GeorgeTsilias** [comment]
Is there any update on this?
I'd also like to use Terraform to create alerts for External Services.
There may be a workaround to this (**haven't verified that it actually works) which is quite ugly IMHO, which may look like so:

1. Create a [newrelic_nrql_alert_condition](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition)
2. Query for something like this:
`SELECT average(newrelic.timeslice.value) FROM Metric WHERE appName = '<APP_NAME>' AND metricTimesliceName='External/<External_URL>' AND newrelic.timeslice.value IS NOT NULL <BLAH BLAH> `

but this means that we need to create a new nrql_alert_condition for each external service we want to alert/compare against.
Is there any other way to achieve this before the feature is implemented (if it's implemented at all)?

Thanks in advance for your time!

**Comment by kidk** [comment]
Hi @GeorgeTsilias Thanks for your patience on this. 

You could use a query like this `SELECT average(newrelic.timeslice.value) FROM Metric WHERE appName = 'AppName' AND metricTimesliceName LIKE 'External/%' AND newrelic.timeslice.value IS NOT NULL FACET metricTimesliceName` in combination with a baseline alert. This would trigger on each separate external service if they behave differently from the past. 

This would also work with static alerts, but the threshold would be the same for all external services. If you want a different threshold for each service you would need to create separate alerts. 

Hope this helps
