### ISSUE TITLE
add support for account_id in dashboard widget

### ISSUE THREAD

**Issue by echoAlexey** [newrelic/terraform-provider-newrelic#476]
Hi!

I want to build cross-account dashboard, this requires me to pass "account_id" to my widgets.
At the moment this is not supported. 

From New Relic doc it is possible to pass account_id:

Widget data element | Description
-- | --
account_id  			 | Source account to fetch data from, if not the current account.

https://docs.newrelic.com/docs/insights/insights-api/manage-dashboards/insights-dashboard-api#widget-data

**Comment by sanderblue** [comment]
Hey there! Thanks for the reporting. Unfortunately this is not supported via the Dashboards API which has some limitations regarding cross-account widgets. The [requirements](https://docs.newrelic.com/docs/insights/insights-api/manage-dashboards/insights-dashboard-api#requirements) section of the docs provides a little more insight there. Essentially those types of widgets are not exported by the API.

Related: #154 (for a little more context 🙂)

**Comment by echoAlexey** [comment]
@sanderblue  Hi! I understand that exporting cross-account widget is not supported, but having them created by passing "account_id" as param should be possible, isn't it? 
I see limitation which is preventing us to "view" it, but not making correct call to API with account id.

**Comment by echoAlexey** [comment]
I don't see problem if terraform will have state with "visualization": "inaccessible" and run dashboard re-creation every time, but it will re-create dashboard with correct setup by passing "account_id" in the calls. 
So far terraform resource implementation is limiting us, not the API as you say. So it is not right to close this issue.

**Comment by sanderblue** [comment]
Thanks for the followup. We were discussing the best coarse of action before reopening the ticket. Your points are valid and we'll explore this further 🙂

**Comment by sanderblue** [comment]
Resolved in: #903 

**Update:** With some recent updates to the Dashboards API, we were able to implement this feature. It will go out with the next release. 😎
