### ISSUE TITLE
Docs: Create v1.x to v2.x migration guide

### ISSUE THREAD

**Issue by sanderblue** [newrelic/terraform-provider-newrelic#512]
### Objective
As part of v2.x preparation, we need to include a general migration guide to ensure smooth transition to the next major version.  This guide should be mostly scoped to provider-level config changes (region, account ID, auth keys), with a simple bulleted list of resources that have had contract updates in v2.

### AC
- Create and test a migration guide
- Publish in a prominent location in the repo

**Comment by zlesnr** [comment]
See https://github.com/terraform-providers/terraform-provider-newrelic/pull/667
