### ISSUE TITLE
Create alert_condition by label

### ISSUE THREAD

**Issue by soumyajk** [newrelic/terraform-provider-newrelic#522]
Hi there,

### Terraform Version
Terraform v0.11.14
+ provider.newrelic v1.16.0

### Affected Resource(s)
Please list the resources as a list, for example:
newrelic_alert_condition

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "newrelic_alert_condition" "apm" {
  policy_id = "${var.policy_id}"

  name            = "${var.name}"
  type            = "${var.type}"
  entities        = "${var.entities}"
  metric          = "${var.metric}"
  runbook_url     = "${var.runbook_url}"
  condition_scope = "${var.condition_scope}"

  term {
    duration      = "${var.duration}"
    operator      = "${var.operator}"
    priority      = "${var.priority}"
    threshold     = "${var.threshold}"
    time_function = "${var.time_function}"
  }

  term {
    duration      = "${var.durationb}"
    operator      = "${var.operatorb}"
    priority      = "${var.priorityb}"
    threshold     = "${var.thresholdb}"
    time_function = "${var.time_function}"
  }
}
```
Provider
```
module "xxxxxxxxxxxxx" {
  source    = "../../../../modules/newrelic/alertcondition/apm"
  policy_id = "${module.xxxxxxnewrelic_alert_policy_id}"

  name        = "Error percentage (High)"
  entities    = [365651490]
  type        = "apm_app_metric"
  metric      = "error_percentage"
  runbook_url = ""
  duration    = 5
  operator    = "above"
  priority    = "critical"
  threshold   = "1"
  durationb   = 5
  operatorb   = "above"
  priorityb   = "warning"
  thresholdb  = "1"
}
```
I am importing the data from newrelic api and the entity id there is as above. But, it is actually a label based alert. 

terraform apply output 
```
module.test.newrelic_alert_condition.apm: Modifying... (ID: xxxx:xxxxxxxxx)
  term.#:                        "1" => "2"
  term.1632667949.duration:      "" => "5"
  term.1632667949.operator:      "" => "above"
  term.1632667949.priority:      "" => "warning"
  term.1632667949.threshold:     "" => "1"
  term.1632667949.time_function: "" => "all"
  term.2197571290.duration:      "5" => "5"
  term.2197571290.operator:      "above" => "above"
  term.2197571290.priority:      "critical" => "critical"
  term.2197571290.threshold:     "1" => "1"
  term.2197571290.time_function: "all" => "all"

Error: Error applying plan:

1 error occurred:
        * module.xxxxxxxxxx.apm.newrelic_alert_condition.apm: 1 error occurred:
        * newrelic_alert_condition.apm: 422 response returned: Invalid entity id(s): 365651490.
```

### Expected Behavior
Should have linked to the entities as the api out put allows the above format

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a label based alert on newrelic gui
2.  take out put from newrelic api
3. terraform it.
4. do terraform import 
5. do terraform apply

**Comment by soumyajk** [comment]
@sanderblue  @jthurman42  
Could you please help with is issue.

**Comment by jthurman42** [comment]
Based on the error message, it appears that either the Entity ID that you're using in the module (`365651490`) is either incorrect, or the API key that you are using does not have access to that entity.

Since this is question on how to use the provider, could you please use our Explorer's Hub instead of creating issues (which are intended for bugs/feature requests/etc).  It is available here: https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit

Thanks!

**Comment by soumyajk** [comment]
@jthurman42  entity id is a label id and is valid. Newrelic api is providing the above as the entity id when we create the alert from the gui.  

i shall raise requests on the above link going forward.
