### ISSUE TITLE
Allow dashboard widgets to be configured from a single JSON template

### ISSUE THREAD

**Issue by jsbnr** [newrelic/terraform-provider-newrelic#540]
Configuring dashboards by individually specifying the widgets in HCL makes it very difficult to make changes to even small dashboards. There is considerable toil involved in manually setting all the layout attributes. Editing and refining dashboards should be encouraged and I feel the current solution makes it difficult to  include terraform as part of a workflow for good dashboard maintenance.

I would like to propose that in addition to being able to specify the widgets in HCL we should also be able to provide the widgets en masse via a template file. This would enable the changes to a dashboard to be made in the UI and then the resulting JSON output to be simply loaded into the template.

There is precedence here in the synthetic resource where the script is provided as a template file.

Here is an example of how the much simpler HCL for the dashboard could look:

```
data "template_file" "dash_json" {
  template = file("${path.module}/dashboard.json")
}
resource "newrelic_dashboard" "exampledash" {
  title = "New Relic Terraform Example"
  widgets = data.template_file.dash_json.rendered
  filter {
    event_types = [
        "Transaction"
    ]
    attributes = [
        "appName",
        "name"
    ]
  }
}```

**Comment by jthurman42** [comment]
This could be done with minimal modification to the provider, perhaps adding a `widgets_json` attribute that is mutually exclusive from `widgets`.  There would need to be some work in newrelic/newrelic-client-go to accept the pre-rendered JSON into the dashboard package.

**Comment by trustthewhiterabbit** [comment]
Hi. I am not sure what the status of this request is as it was created 2+ years ago. I was about to raise a similar feature request.

Ideally we would allow users to formulate the dashboards in the UI. Download the json code and have a terraform resource to apply said configuration. JSON files can be stored within the code base and referenced via resource.

Everything in the initial request here is still valid and there is even the ability to import the json within the UI already - it would be great to enable this via api / terraform also..

**Comment by jsbnr** [comment]
@trustthewhiterabbit Im still pushing for this! In the meantime I came up with this alternative which does what you;re looking for: https://github.com/jsbnr/nr-terraform-graphql-json-dashboards
