### ISSUE TITLE
Support the "Connect to Incident Intelligence" option for an alert policy

### ISSUE THREAD

**Issue by skyzyx** [newrelic/terraform-provider-newrelic#612]
### Feature Description

My company is migrating to New Relic, and we would like to see this provider add support for the "Connect to Incident Intelligence" option for an alert policy.

<img width="272" alt="Screen Shot 2020-05-28 at 7 27 08 PM" src="https://user-images.githubusercontent.com/39447/83221971-27684800-a12c-11ea-8a08-e43a9a369482.png">

### Describe Alternatives

I've considered hitting the API directly, but that would complicate the solution I'm aiming for which is to use as much Terraform (and its managed state) as possible.

### Additional context

This is the feature: https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/new-relic-ai/get-started-incident-intelligence

**Comment by zlesnr** [comment]
Hi, thank you for raising the issue.  This feature doesn't look to be supported in the API currently, but I see evidence that its on the way.  Not sure on the timeline though.  We'll need the API support before we can proceed with support in Terraform.

**Comment by skyzyx** [comment]
Understood. Thanks.

**Comment by skyzyx** [comment]
Just following up to see if this is available yet.

/cc @bgoleno

**Comment by mathias-burkl** [comment]
Hi @zlesnr 
is there any update on this request? would be great to have the connect to incident intelligence option in terraform for proper CaC.
Thanks

**Comment by emetcalf9** [comment]
The API work to support this is still in progress, but I do see that we already have this planned to be implemented in the Terraform Provider as part of the API work. Closing the Feature Request now because this work is being tracked internally at New Relic.
