### ISSUE TITLE
Support descriptions on alert conditions

### ISSUE THREAD

**Issue by skyzyx** [newrelic/terraform-provider-newrelic#613]
### Feature Description

My company is migrating to New Relic, and while small, it would be nice to be able to add a description for an alert condition via Terraform. This way, as people are looking through the alert conditions, we can add a note that the resource was created by a Terraform module, the URL of the module, and why they shouldn't manually change it.

<img width="1051" alt="Screen Shot 2020-05-28 at 7 27 34 PM" src="https://user-images.githubusercontent.com/39447/83222281-c725d600-a12c-11ea-8d71-01cd9cf5bc96.png">

**Comment by zlesnr** [comment]
Hi, thanks for reporting the issue.  The 2.x release is due soon, and will include a description for `newrelic_nrql_alert_condition` resource.  For the `newrelic_alert_condition` resource this looks to be a like an API limitation at the moment.  I expect this will include a description when it migrates to GraphQL, but I'm not sure on the timeline there.

**Comment by skyzyx** [comment]
Understood. Thank you.

**Comment by zlesnr** [comment]
2.x has been released, which includes the description on the `newrelic_nrql_alert_condition` resource.  Is this sufficient for your use cases?  If I remember correctly, you are planning to migrate to NRQL alerts, correct @skyzyx ?

**Comment by skyzyx** [comment]
This is awesome, thank you. Presently I'm pinning my module to `~> 1.19`, but I will have time to test the 2.x version after the holiday.

> If I remember correctly, you are planning to migrate to NRQL alerts, correct @skyzyx ?

Yes. I've already rewritten everything in my module to use NRQL alerts.

👍
