### ISSUE TITLE
Implement changes to the documentation site that will allow v1 and v2 docs to be displayed side by side

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#619]
### Objective
Our documentation will need to span two major versions.  We will need to come up with a layout that will support both.

### Acceptance Criteria
- v2 docs can start as a copy of v1 docs
- v2 docs are the first to load/display when the site is visited
- v1 docs should be available but kept out of the way
- v2 navigation is prominent, but v1 can be accessed and browsed easily if desired

### Notes
- A good amount of this work already exists on the master branch.  It's been a while since we touched this so we should proofread all of the work at the resource level.

**Comment by zlesnr** [comment]
I believe this is complete, but we'll need to deploy the release to know for sure.
