### ISSUE TITLE
Carry out existing v1 deprecations

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#620]
### Objective
Many resource attributes have already been deprecated.  They should be removed in the v2 branch.

### Acceptance Criteria
- Deprecated v1 attributes are removed in the master branch

### Notes
- Example of this would be the `configuration`/`config` blocks in the alert channel config
- Remove REST support where possible now that Personal API Key is required
- We will need to search through the existing code base for others.  Ctrl-F "Deprecated" should get us there

**Comment by zlesnr** [comment]
https://github.com/terraform-providers/terraform-provider-newrelic/pull/651

**Comment by zlesnr** [comment]
https://github.com/terraform-providers/terraform-provider-newrelic/pull/652

**Comment by zlesnr** [comment]
https://github.com/terraform-providers/terraform-provider-newrelic/pull/653

**Comment by zlesnr** [comment]
https://github.com/terraform-providers/terraform-provider-newrelic/pull/654
