### ISSUE TITLE
Author a v1 support document

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#622]
### Objective
We will need to communicate our plans to support v1 of the provider.

### Acceptance Criteria
- Decide time frame for v1 support
- Create a document that outlines the support policy for v1 of the TF provider
- Publish in TF documentation, discuss forums, amplify internally at NR

**Comment by zlesnr** [comment]
See https://github.com/terraform-providers/terraform-provider-newrelic/pull/667

We'll want to cut a release and deploy the docs before we amplify the message.
