### ISSUE TITLE
Remove use of REST API for Insight Custom Events queries

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#625]
### Objective
There are Insights queries that occur during the tests for Insights Custom Events resource and data source that are still making use of the REST API.  These can be migrated over to Nerdgraph, eliminating the need for the `insights_query_key` config.

### Acceptance Criteria
- Custom Events resource and data source tests no longer make use of REST APIs 
- `insights_query_key` is no longer required

**Comment by jthurman42** [comment]
The Query key, if configured, creates the go-insights query client [here](https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/config.go#L130) though it is only used in a [test](https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_insights_event_test.go#L70)

Personal API keys can be used instead to query insights via NerdGraph and can either be exposed as a data type, or just used directly in the test .
