### ISSUE TITLE
Private location support for newrelic_synthetics_monitor resource

### ISSUE THREAD

**Issue by elvis-cai** [newrelic/terraform-provider-newrelic#632]
### Feature Description

Currently, newrelic_synthetics_monitor resource only supports public location, since new relic synthetic supports private location as well, it would be great if it support it. 
when I run it with my private location, got `Error: 500 response`

### Describe Alternatives
The workaround for me is to configure private location in new relic web page directly.

**Comment by ctrombley** [comment]
Resolved by #758

**Comment by ctrombley** [comment]
We will track progress on this data source in #758.
