### ISSUE TITLE
Terraform crasher

### ISSUE THREAD

**Issue by skyzyx** [newrelic/terraform-provider-newrelic#646]
Not sure if this is an error on the Terraform side or the Provider side, but I managed to trigger a Terraform crasher when using the New Relic provider. [The top-most error in the stack trace points to code in the Provider](https://gist.github.com/skyzyx/63aeb9f2f32997c7d02b9738b6994c5e#file-crash-log-L1897).

```
panic: interface conversion: interface {} is nil, not map[string]interface {}
```

https://github.com/hashicorp/terraform/issues/25170

**Comment by zlesnr** [comment]
I think I learned how to test that behavior last week while working on your other issue.  That's probably an issue with the structure code, either flatten or expand.

**Comment by zlesnr** [comment]
Looking at this a little closer @skyzyx, do you have the manifest that produced this crash?  It doesn't look like we have tests for the structure of the `newrelic_alert_channel` resource at all, so I can start looking to add some and surface the issue.

**Comment by zlesnr** [comment]
Oh I see it now in the upstream issue you filed.  I'll try to reproduce now.

**Comment by zlesnr** [comment]
The nil pointer here should be resolved in the next release.  Thank you for raising the issue.

**Comment by timothy-spencer** [comment]
Cannot wait for this to get released.  I believe I'm running into this too.

**Comment by zlesnr** [comment]
Give the latest release a try and let me know how it goes @timothy-spencer.
