### ISSUE TITLE
Reflect current account information

### ISSUE THREAD

**Issue by skyzyx** [newrelic/terraform-provider-newrelic#647]
### Feature Description

An ability to _reflect_ current account information. My company has several sub-accounts underneath a master account. I'd like to be able for my Terraform to be able to discern which account it's executing against.

Mostly the account ID and account name. But I'm sure there's other information that could be useful as well.

### Describe Alternatives

Something similar to:

* [aws_caller_identity](https://www.terraform.io/docs/providers/aws/d/caller_identity.html)
* [aws_region](https://www.terraform.io/docs/providers/aws/d/region.html)
* [aws_ip_ranges](https://www.terraform.io/docs/providers/aws/d/ip_ranges.html)
* [datadog_ip_ranges](https://www.terraform.io/docs/providers/datadog/d/ip_ranges.html)
* [digitalocean_account](https://www.terraform.io/docs/providers/do/d/account.html)

**Comment by skyzyx** [comment]
I would be happy to work on this, pending #746.

**Comment by ctrombley** [comment]
@skyzyx A default contextual account ID is required in the [provider block](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/provider_configuration) to bootstrap configurations in 2.x.  The use of Terraform variables could allow you to define this value once and use it elsewhere in your configuration.  

Retrieving account name is not yet solved for, but #732 would make it possible.  

Some resources going forward will also allow for overriding the default account ID with resource-scoped account ID attributes. #732 would also be useful in these cases.

I'd like to mark this issue as a duplicate of #732 unless I've missed something here?

**Comment by skyzyx** [comment]
Yeah, that's fine. I had opened this against the 1.x provider.
