### ISSUE TITLE
Cannot set newrelic_infra_alert_condition resource critical threshold value to 0

### ISSUE THREAD

**Issue by stuntbaboon** [newrelic/terraform-provider-newrelic#660]
### Terraform Version
Terraform - 0.11.14
New Relic provider - 1.18.0 (have also tried 1.19.0, 1.16.0)

### Affected Resource(s)
- newrelic_infra_alert_condition

### Terraform Configuration Files
```hcl
resource "newrelic_infra_alert_condition" "api_gateway_5XX_errors" {
  policy_id = "${newrelic_alert_policy.processing_alert_policy.id}"

  name        = "${local.alarm_prefix}-api-gateway-5XX-errors"
  type        = "infra_metric"
  runbook_url = "${local.runbook_url}"

  integration_provider = "ApiGatewayApi"
  select               = "provider.5xxError.Sum"
  where                = "`provider.apiName` = '${aws_api_gateway_rest_api.api.name}'"
  comparison           = "above"

  critical {
    duration      = 5
    value         = 0
    time_function = "any"
  }

  enabled = "${local.new_relic_resource_alerts_enabled}"
}
```

### Debug Output
N/A - terraform apply completes successfully, but New Relic threshold value is not changed.

### Panic Output
N/A - terraform apply completes successfully, but New Relic threshold value is not changed.

### Expected Behavior
The critical threshold value should be 0 when viewing the alert condition via the New Relic UI.

### Actual Behavior
The critical threshold value is not updated and retains its original value (set via a previous Terraform applied plan).

### Steps to Reproduce
Apply a plan with the above sample newrelic_infra_alert_condition resource.

### Important Factoids
This issue applies to various AWS infrastructure data sources including Lambda and API Gateway.

### References
This discussion post from July 2019 highlights the same issue - https://discuss.newrelic.com/t/setting-infrastructure-alert-condition-threshold-value-to-0-through-terraform/77837

**Comment by outime** [comment]
Reproduced this as well

```
Terraform v0.12.24
+ provider.newrelic v2.1.1
```

**Comment by zlesnr** [comment]
Thank you for filing an issue.  Does `0.0` work?  Also, with the workaround in place for using `0.1`, is that sufficient for this use case, or can you elaborate a bit on the use case?

**Comment by zlesnr** [comment]
Is the condition meant to fire when the total number of 500s is above 0?  That makes some sense to me, and even simply increasing the precision might help here, so `0.000001` or some such.

**Comment by trunet** [comment]
issue still present on 2.2.1
