### ISSUE TITLE
The violationTimeLimit field of a newrelic_nrql_alert_condition is not optional on create

### ISSUE THREAD

**Issue by tomlloyd-dazn** [newrelic/terraform-provider-newrelic#696]
When applying a Terraform plan containing a new `newrelic_nrql_alert_condition` resource, if the `violationTimeLimit` field is missing, then the apply fails and an error is thrown saying that this field cannot be null. However, this seems to contradict the documentation which states that this field is optional.

### Terraform Version
Terraform v0.12.24
+ provider.newrelic v2.0.0

### Affected Resource(s)
- newrelic_nrql_alert_condition

### Terraform Configuration Files
```hcl
resource "newrelic_nrql_alert_condition" "my_test_alert" {
  policy_id = "SOME_POLICY_ID"

  name = "MY TEST ALERT"

  value_function       = "single_value"

  critical {
    threshold_duration      = 600
    operator      = "above"
    threshold     = "1"
    threshold_occurrences = "all"
  }

  nrql {
    query       = "SOME_NRQL"
    evaluation_offset = 5
  }
}
```

### Debug Output
```
Error: Argument "condition" has invalid value $condition.
In field "violationTimeLimit": Expected type "AlertsViolationTimeLimit!", found null., null
```

### Expected Behavior
Terraform apply should complete successfully and an NRWL alert condition should have been created in New Relic.

Note: When you remove the `violationTimeLimit` field from an alert which has already been created, a Terraform apply seems to update the alert successfully and does not fail.

### Actual Behavior
Terraform apply fails with an error.

### Steps to Reproduce
1. Add a new NRQL alert condition without a `violationTimeLimit` field to your plan
2. Run `terraform apply`

**Comment by mike-dazn** [comment]
Additionally, when trying to upgrade from the old alert condition config, the error given is very poor:

```
Error: A downstream error occurred., [{"extensions":{"code":"BAD_USER_INPUT"},"message":"Validation Error"}]

  on new-relic-alerts.tf line 1, in resource "newrelic_nrql_alert_condition" "invocations":
   1: resource "newrelic_nrql_alert_condition" "invocations" {



Error: A downstream error occurred., [{"extensions":{"code":"BAD_USER_INPUT"},"message":"Validation Error"}]

  on new-relic-alerts.tf line 22, in resource "newrelic_nrql_alert_condition" "errors":
  22: resource "newrelic_nrql_alert_condition" "errors" {
```

**Comment by zlesnr** [comment]
Thank you for reporting the issue.  With the manifest provided, I'm able to reproduce the issue.  I can dig in a bit and see where we're at.

**Comment by zlesnr** [comment]
This looks to be an oversight on our part.  We'd set `Optional`, but at least one of the attributes for `violation_time_limit` or the deprecated value `violation_time_limit_seconds` is required.  I wasn't quite able to work out how to set a default value with the right incantation.  In any case, I think https://github.com/newrelic/terraform-provider-newrelic/pull/718 should address the documentation, and also require the user to do the right thing to avoid the GraphQL error coming back to the user.

**Comment by zlesnr** [comment]
This will be fixed in the next release.  Let me know if there is something else required here.

**Comment by mike-dazn** [comment]
Quick question @zlesnr. Alerts created through the UI have the option of never auto-resolving if the violation is still active.  This looks like it makes it impossible to do the same through the Terraform provider?  We've never needed to set a violation time limit in the past and it concerns me if this now is required.  The main NewRelic docs on this do not make any mention of this needing to be required https://docs.newrelic.com/docs/alerts/new-relic-alerts/reviewing-alert-incidents/how-alert-condition-violations-are-closed#time-limit

**Comment by zlesnr** [comment]
Thats an interesting discrepancy.  The GraphQL API has a requirement for that option to be set during create, so my guess is that the UI doesn't make those same API calls to create the alert instance.  Also, I know our UI is in a bit of flux, but I would suspect that the UI will in the future also have this requirement, just don't quote me on that.  I'll follow up with the alerts team about it.  Is leaving the alert open indefinitely a required feature for your environment?

**Comment by zlesnr** [comment]
I've just heard from the alerts team that it will eventually be a required setting in the UI as well, so I think the direction here is just a bit ahead of where the UI is at.  Let me know if I can clarify any of that or something else needs to be addressed here.
