### ISSUE TITLE
account_id(optional) is required for newrelic_nrql_alert_condition

### ISSUE THREAD

**Issue by c-carpenter** [newrelic/terraform-provider-newrelic#697]
### Terraform Version
Terraform v0.12.24
Provider version v2.0.0

### Affected Resource(s)
- newrelic_nrql_alert_condition

### Terraform Configuration Files
```hcl
terraform {
  required_version = "0.12.24"

}

provider newrelic {
  version = "2.0.0"
}

resource newrelic_nrql_alert_condition cpu {
  policy_id      = ######
  name           = "cpu <app name>"
  value_function = "single_value"

  term {
    priority      = "critical"
    duration      = 10
    operator      = "above"
    threshold     = 70
    time_function = "all"
  }

  term {
    priority      = "warning"
    duration      = 5
    operator      = "above"
    threshold     = 50
    time_function = "all"
  }

  nrql {
    query       = "from Metric SELECT average(process.cpu.usage)*100 facet hostname where app = 'persist' and environment = 'testing' and region = 'oregon'"
    since_value = 3 
  }
}
```

### Debug Output
https://gist.github.com/c-carpenter/edec92a7f5c6ff931097efe3e73cb266

### Expected Behavior
What should have happened?
Plan should complete and show output saying an apply would create alert.

### Actual Behavior
What actually happened?
Plan fails saying The argument "account_id" is required, but no definition was found.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Have a newrelic_nrql_alert_condition without an account_id
2. `terraform apply`

### Important Factoids
In my troubleshooting, I noticed that acount_id is not handle in the same manor as other optional parameters in the structures. account_id is missing the `condition.` that other optional parameters have. I do not know if this is the cause, but simply something that stood out to me.
https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/structures_newrelic_nrql_alert_condition.go#L317

[Code showing account_id as optional](https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_nrql_alert_condition.go#L261)
[Docs saying account_id is optional](https://www.terraform.io/docs/providers/newrelic/r/nrql_alert_condition.html)

**Comment by tomlloyd-dazn** [comment]
Hi @c-carpenter, I'm not a maintainer of the project, but I believe the `account_id` field is a required field of the `provider` block, and is not related to the `newrelic_nrql_alert_condition` resource.

**Comment by c-carpenter** [comment]
I dug into the documentation and finally found it mention the requirement. https://www.terraform.io/docs/providers/newrelic/#upgrading-to-2-x

Given that it's required at the provider level, does it make sense as a parameter for resources anymore?

**Comment by sanderblue** [comment]
Hi @c-carpenter, thanks for the feedback. We're in the process of making several updates to the documentation based on the feedback we've received, much of which involves clarity around these sorts of things. 

As for the provider-level `account_id` vs the resource-level `account_id`. There could be scenarios where a top-level (provider-level) account might want to manage resources in other subaccounts, especially for those folks with several accounts/teams.
