### ISSUE TITLE
Version Module as v2

### ISSUE THREAD

**Issue by stack72** [newrelic/terraform-provider-newrelic#721]
In order to be able to use go get of the v2 project, please can the module be updated to v2?

https://blog.golang.org/v2-go-modules

**Comment by ctrombley** [comment]
Hi @stack72 we will look into this, I just want to understand the use case a little better?

**Comment by stack72** [comment]
@ctrombley the use case is just proper go module versioning - without this, you can't run `go get github.com/newrelic/terraform-provider-newrelic v2.1.1` - you would need to know the git hash of the release

**Comment by jthurman42** [comment]
I believe the question was around the use-case for importing the provider, as the supported usage is via pre-compiled binaries distributed as a provider for Terraform, not an import into another Go project.  Are you importing terraform-provider-newrelic into something else and utilizing it in some way?

**Comment by stack72** [comment]
Oh I see! I apologise - yes, I work on pulumi and we have a Pulumi NewRelic provider :)

https://github.com/pulumi/pulumi-newrelic

That uses the upstream provider and we bridge from our provider to this
