### ISSUE TITLE
`newrelic_dashboard` plan is inconsistent

### ISSUE THREAD

**Issue by mrjackdavis** [newrelic/terraform-provider-newrelic#731]
### Terraform Version

Terraform v0.12.28
+ provider.newrelic v1.19.1

### Affected Resource(s)

- newrelic_dashboard

### Terraform Configuration Files
```hcl
resource "newrelic_dashboard" "general_application" {
  title             = "My Dashboard"
  grid_column_count = 12

  filter {
    attributes = []
    event_types = [
      "Transaction",
    ]
  }

  widget {
    title         = "Application Response Time"
    nrql          = <<-EOT
      SELECT median(duration * 1000) AS 'Response time'
      FROM Transaction
      TIMESERIES FACET `appName`
      LIMIT 10
      SINCE 3 days ago
      EXTRAPOLATE
    EOT
    visualization = "faceted_line_chart"

    column = 1
    height = 3
    row    = 1
    width  = 4

    threshold_red    = 500
    threshold_yellow = 300
  }
  widget {
    title         = "Error rates"
    nrql          = <<-EOT
      SELECT percentage(count(*), WHERE error is true) AS 'Error rate'
      FROM Transaction
      TIMESERIES FACET `appName`
      LIMIT 10
      SINCE 3 days ago
      EXTRAPOLATE
    EOT
    visualization = "faceted_line_chart"

    column = 1
    height = 3
    row    = 4
    width  = 4

    threshold_red    = 0
    threshold_yellow = 0
  }
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Once applied, I expect a subsequent apply would show 0 changes

### Actual Behavior
Once applied, subsequent applies show `widget` properties to be out of order. It therefore produces a diff.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`
3. Observe diff

### Important Factoids

N/A

### References

None

**Comment by zlesnr** [comment]
Thank you for reporting the issue.  I've been able to reproduce this with the manifest above.  It looks to me like this is related to the threshold_* settings not round-tripping correctly.  Removing those settings from both widgets make the resource operate like normal.  I can take a closer look to see why those attributes are causing an issue.

**Comment by mrjackdavis** [comment]
@zlesnr removing all instances of `threshold_*` from `widget` alleviated the issue, thanks
