### ISSUE TITLE
PagerDuty channel creation is not idempotent

### ISSUE THREAD

**Issue by olegburca** [newrelic/terraform-provider-newrelic#735]
Hello,

I‘m working on upgrading some of the resources in NewRelic managed by Terraform.
I‘m trying to use latest available terraform version 0.12.25 and newrelic module version 1.18

Got an issue like the description says: PagerDuty channel creation is not idempotent.

Each time I run terraform plan or apply, it says the PagerDuty notification channel needs to be replaced:

```
Terraform will perform the following actions:

  # newrelic_alert_channel.pagerduty must be replaced
-/+ resource "newrelic_alert_channel" "pagerduty" {
      ~ id   = "1234567" -> (known after apply)
        name = "PagerDuty2"
        type = "pagerduty"

      ~ config {
          - headers     = (sensitive value)
          - payload     = (sensitive value)
          + service_key = (sensitive value)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Resource definition is as following:
```
[resource "newrelic_alert_channel" "pagerduty" {
  name = "PagerDuty"
  type = "pagerduty"

  config {
    service_key = "12345678901234567890"
  }
}]
```

At the same time email and webhook channels defined in the same file work just fine, without asking for replacement.

Thank you!

**Comment by zlesnr** [comment]
I believe the solution in https://github.com/newrelic/terraform-provider-newrelic/issues/130 also applies here.  The sensitive information is not returned by the API, so TF has no way to know if the state matches.  The solution in #130 advises ignoring the `config` attribute.

**Comment by olegburca** [comment]
Thank you @zlesnr, it works!
