### ISSUE TITLE
v2.1.2 plugin seems not to be findable by terraform v0.12.24

### ISSUE THREAD

**Issue by timothy-spencer** [newrelic/terraform-provider-newrelic#744]
### Terraform Version
v.0.12.24

### Affected Resource(s)
terraform's plugin download code

### Terraform Configuration Files
```hcl
provider "newrelic" {
  version = ">= 2.1.2"
  region = "US"
}
```

### Debug Output
```
- Checking for available provider plugins...
No provider "newrelic" plugins meet the constraint ">= 2.1.2".
The version constraint is derived from the "version" argument within the
provider "newrelic" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".
To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.
Warning: registry.terraform.io: For users on Terraform 0.13 or greater, this provider has moved to newrelic/newrelic, please update your source for required_providers.
Error: no suitable version is available
```
### Panic Output
None

### Expected Behavior
I expect terraform to be able to find and download the v2.1.2 plugin

### Actual Behavior
It was unable to find the plugin and download it.  I suspect that this has something to do with maybe
terraform's v0.12.24 plugin registry still going to the old repo?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Downloading the plugin by hand and putting it in the .terraform/plugins/darwin_amd64 dir works fine.

### References
None that I know of!

**Comment by zlesnr** [comment]
Thank you for reporting the issue.  It looks like something happened with the release process after we move the repo.  There is a cron somewhere in hashicorp that builds the new binary.  We'll chase that down.

I believe https://releases.hashicorp.com/terraform-provider-newrelic/ is the source for which versions are available.

**Comment by skyzyx** [comment]
Confirmed. Same issue.

**Comment by zlesnr** [comment]
Looks like their cron job kicked off now.  Let me know if the issue persists.
