### ISSUE TITLE
Add a meaningful CONTRIBUTING.md guide

### ISSUE THREAD

**Issue by skyzyx** [newrelic/terraform-provider-newrelic#746]
### Feature Description

A `CONTRIBUTING.md` which not only includes "here's how to fork and submit a PR" (like many are resigned to in the OSS world), but one which helps people start making meaningful contributions who don't have the tribal knowledge that you do. (I've brought this up directly with @jthurman42 before, but wanted to create a specific issue for it.)

It could double as an onboarding guide for new hires at New Relic who join the team working on this project.

Here are some examples from a project which I believe does an excellent job:

* https://golangci-lint.run/contributing/architecture/
* https://golangci-lint.run/contributing/new-linters/

**Comment by zlesnr** [comment]
Thanks for raising this issue.  A CONTRIBUTING.md now exists in the master branch.  Feel free to let me know what else you'd like to see from such a document to kickstart your contributions.
