### ISSUE TITLE
Other nits in the documentation

### ISSUE THREAD

**Issue by skyzyx** [newrelic/terraform-provider-newrelic#748]
In <https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition>, `duration` is documented twice — once correctly, and once incorrectly.

![Screen_Shot_2020-07-02_at_10_06_37_PM](https://user-images.githubusercontent.com/39447/86433850-a400c000-bcb0-11ea-9769-85d87a2707e0.png)

**Comment by ctrombley** [comment]
Resolved by #760

**Comment by skyzyx** [comment]
👍
