### ISSUE TITLE
Odd choices in v2 provider

### ISSUE THREAD

**Issue by skyzyx** [newrelic/terraform-provider-newrelic#749]
I‘m in the process of migrating code written for the 1.19 provider to the 2.x provider, and I noticed that some of the changes seem… _odd_.

https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition

### Example 1

In `1.19`, there was `violation_time_limit_seconds`. This seemed like an odd choice _then_, because it was really an _enum_ rather than a numeric value.

```hcl
resource "newrelic_nrql_alert_condition" "foo" {
  violation_time_limit_seconds = "3600"
}
```

In `2.0`, this has changed to `violation_time_limit` which is exactly that — a set of enum values. Cool. This change makes sense to me.

```hcl
resource "newrelic_nrql_alert_condition" "foo" {
  violation_time_limit = "ONE_HOUR"
}
```

(I would have preferred `1h`, `2h`, `4h`, etc., but whatever. Not a big deal.)

### Example 2

In `1.19`, there was `duration`. This value was calculated in _minutes_ because that's how the value is _actually measured_.

```hcl
resource "newrelic_nrql_alert_condition" "foo" {
  critical {
    duration = 15
  }
}
```

> `duration` - (Required) In minutes, must be in the range of `1` to `120`, inclusive.

In `2.0`, this has changed to `threshold_duration`, which is now calculated thusly:

> […] Value must be a multiple of 60. […] value must be within 120-3600 seconds (inclusive). […] value must be within 120-7200 seconds (inclusive).

```hcl
resource "newrelic_nrql_alert_condition" "foo" {
  critical {
    threshold_duration = 900
  }
}
```

So… since the value must be a multiple of `60`, it's _still calculated in minutes_. And the thresholds still top-out at `60` and `120` for the different types.

So, other than changing the lower bound from 1 minute to 2 minutes, I'm struggling to understand why the provider changed it's time unit for this parameter — especially after `violation_time_limit` (above) moved _away_ from seconds.

----

I bring this up because this is a pain point I'm now having to mitigate for my internal customers. I provide core Terraform modules for monitoring and alerting to the ±75 (fairly independent, working on entirely different projects) development teams I support.

I can attempt to:

* communicate out that everybody needs to multiply this value they set for themselves by `60`.
* mitigate this value by multiplying by `60` inside the module and not passing this breaking change down the line.
* something else?

But without understanding _why_ this change was made (Changes in the underlying API? More granular, second-based ranges coming in the future?), it's hard to know which approach to take (or guidance to give) for _my_ customers with a breaking change that _seems_ unnecessary.

I know this just hit 2.0 which introduced breaking changes, and I hesitate to even ask for another bump to 3.0 to address this. But what happened here?

**Comment by nedl86** [comment]
Hey @skyzyx I work for New Relic but in another team so I'm not _100%_ sure on this, but my guess is that this change was in preparation for some enhancements that will be occurring soon in our alerting pipeline to allow more configurable alerting windows. i.e. Whoever made this change now probably knew that the fixed 1 minute windows aren't long for this world... :)

**Comment by skyzyx** [comment]
> Whoever made this change now probably knew that the fixed 1 minute windows aren't long for this world... :)

Fair enough. That gives me some direction. Thank you.
