### ISSUE TITLE
newrelic_dashboard editable "read_only" not applied

### ISSUE THREAD

**Issue by mdenkinger** [newrelic/terraform-provider-newrelic#752]
### Terraform Version
Terraform v0.12.23

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_dashboard

### Terraform Configuration Files
```hcl
resource "newrelic_dashboard" "some_dashboard" {
  editable = "read_only"
  ....
}
```

### Debug Output
```hcl  
~ resource "newrelic_dashboard" "some_dashboard" {
      ~ editable          = "editable_by_owner" -> "read_only"
}
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior
When applying `editable="read_only"` on a `newrelic_dashboard`, it should be actual changed in New Relic. If this is not possible due to any reasons, it should have provided an error.

### Actual Behavior
Due to the terraform apply process, the changes to `newrelic_dashboard` are success applied. But running this again, shows up these changes again.  

### Steps to Reproduce
1. `terraform apply`
1. `terraform plan`

### References
- ---

**Comment by ctrombley** [comment]
I was able to reproduce configuration drift around the `editable` attribute.  It looks like the change is not being honored by the upstream API.  I started a discussion with the owning internal team about why that might be.

**Comment by mdenkinger** [comment]
@ctrombley thanks for verifying it as a bug. Any update on the discussion with the owning internal team?

**Comment by zlesnr** [comment]
If I were to guess at it, the fix probably won't come until the upstream team ships their new nerdgraph API bits, which has been pushed back from its original date, so I can't offer anything concrete here.  Too, that might be a completely separate resource.

**Comment by kidk** [comment]
We are deprecating the newrelic_dashboard resource: #1297

When migrating your dashboards, please be aware that the permissions are slightly different in the new resource: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#permissions. Please create another ticket if you still feel this is relevant.
