### ISSUE TITLE
TF plan re-creates slack notification channel even when there are no changes

### ISSUE THREAD

**Issue by hgibsonqb** [newrelic/terraform-provider-newrelic#763]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.12.26
+ provider.newrelic v2.1.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_alert_channel (slack)

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "newrelic_alert_channel" "apf_slack" {
  name = "apf_slack"
  type = "slack"

  config {
    url     = var.slack_webhook_url # These config values don't change
    channel = var.slack_channel
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

Terraform plan output
```
 # module.apf_notification_channels.newrelic_alert_channel.apf_slack must be replaced
-/+ resource "newrelic_alert_channel" "apf_slack" {
      ~ id   = "3720481" -> (known after apply)
        name = "apf_slack"
        type = "slack"

      ~ config {
            channel = "appfactory-alerts"
          - headers = (sensitive value)
          - payload = (sensitive value)
          + url     = (sensitive value)
        }
    }

  # module.apf_stg_external_access_monitor.newrelic_alert_policy.apf_monitor_policy must be replaced
-/+ resource "newrelic_alert_policy" "apf_monitor_policy" {
      - account_id          = 2732602 -> null
      ~ channel_ids         = [
          - 3720481,
          - 3720018,
        ] -> (known after apply) # forces replacement
      ~ id                  = "951482" -> (known after apply)
        incident_preference = "PER_CONDITION"
        name                = "apf_monitor_policy-apf-stg"
    }
```

The channel id that it says will be generated/known after apply doesn't change.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Because there were no changes to the slack notification channel configuration, it should not have been changed by plan/apply.

### Actual Behavior
Plan/apply forced a replace of the notification channel which also forced replacement of all alerts that send messages to that channel.

This is only for the slack notification channel, we also have an email notification channel that was not replaced. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create new relic slack notification channel and dependent alerts.
2. Run `terraform apply` to create resources.
3. Run `terraform apply` again with no changes to alert of notification channel configuration.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by sbrinkerhoff** [comment]
Having an identical issue with Terraform v0.12.28, provider v.22.1 on Darwin.

```
resource "newrelic_alert_channel" "slack-team-ops" {
  name = "slack-team-ops"
  type = "slack"

  config {
    channel = "#team-ops"
    url     = "https://hooks.slack.com/services/T12345"
  }

  lifecycle {
    ignore_changes = [
      config[0].url
    ]
  }
}```

If I drop the lifecycle block; it attempts to recreate.

```
  # newrelic_alert_channel.slack-team-ops must be replaced
-/+ resource "newrelic_alert_channel" "slack-team-ops" {
      ~ id   = "3749330" -> (known after apply)
        name = "slack-team-ops"
        type = "slack"

      ~ config {
            channel = "#team-ops"
          - headers = (sensitive value)
          - payload = (sensitive value)
          + url     = (sensitive value)
        }
    }
```

Checking my Terraform state, the value is correctly logged with my intended URL, and it does not seem to change in the UI.  This same config was working ok on 1.19 before we upgraded.

**Comment by davidji99** [comment]
This might be the same issue afflicting https://github.com/newrelic/terraform-provider-newrelic/issues/420.
