### ISSUE TITLE
Add possibility to create resources in subaccounts when you have admin keys from root account

### ISSUE THREAD

**Issue by worldcompass** [newrelic/terraform-provider-newrelic#772]
### Feature Description
Add the possibility to create resources in subaccounts when you have admin keys from the root account
### Describe Alternatives
The alternative consists of creating a user with admin rights withing each subaccount. Afterward, these keys should be used in the credentials manager.

It takes time to generate, these keys and manage them.

On the other hand, I've could use only one pair of keys and change only the account_id variable.

**Comment by jthurman42** [comment]
The 2.x version of the New Relic provider has a limited set of this implemented.  Any resource that is configurable via GraphQL allows for you to specify the AccountID to use, and as long as the key has proper capabilities on the specified account, the resource should be created.

New Relic is actively working to migrate / update REST endpoints into the GraphQL API, and as such we will not be back-porting this ability to the REST API, and favor migrating Terraform resources into NerdGraph.
