### ISSUE TITLE
newrelic_alert_channel: excluding config.headers and config.payload causes diff 

### ISSUE THREAD

**Issue by sanderblue** [newrelic/terraform-provider-newrelic#776]
Report of the issue quoted below:

> My terraform creates an alert channel, but every time I run terraform it wants to recreate the channel, even if nothing has changed with it, which has a cascading effect of wanting to recreate all of the alert policies and conditions

### Terraform Version
0.12.26

### Affected Resource(s)
- **newrelic_alert_channel**

### Terraform Configuration Files

```hcl
variable "pdKey" {}

resource "newrelic_alert_channel" "pagerduty" {
  name = "mh-ced-pagerduty-${var.alertLevel}"
  type = "pagerduty"
  config {
    service_key = var.pdKey
  }
}
```

### Expected Behavior
`terraform apply` should result in nothing happening in this case. 

### Actual Behavior
Terraform thinks there's a diff even though nothing was changed. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Use the example configuration above (replace variables with values)
2. `terraform apply`

**Comment by ctrombley** [comment]
Possible duplicate of #420

**Comment by sanderblue** [comment]
You're correct, this is a duplicate of sorts. Closing.
