### ISSUE TITLE
403 response when adding newrelic_synthetics_label after EOL of Synthetics labels

### ISSUE THREAD

**Issue by timvanderkooi** [newrelic/terraform-provider-newrelic#777]
Looks like the API has changed for managing New Relic labels:
https://discuss.newrelic.com/t/end-of-life-notice-synthetics-labels-and-synthetics-apm-group-by-tag/103781
* After an account has been migrated, the Synthetics labels API will no longer be available to manage labels. Tags can be managed using the tag API moving forward.

### Terraform Version
Terraform v0.12.21

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_synthetics_label

### Expected Behavior
A label should have been added to a New Relic monitor

### Actual Behavior
Error: 403 response returned

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a new monitor resource and a newrelic_synthetics_label that references that resource
2. terraformy apply

### Important Factoids
* On version 2.1.1 of this New Relic provider

**Comment by MAN98** [comment]
Synthetic Labels are replaced by Entity Tags now. Look at this issue to learn more: https://github.com/newrelic/terraform-provider-newrelic/issues/672

**Comment by timvanderkooi** [comment]
@MAN98 thanks. I'll close this as a duplicate.
