### ISSUE TITLE
NewRelic doesn't resort to admin_api_key if personal_api_key doesn't have permission

### ISSUE THREAD

**Issue by venki09** [newrelic/terraform-provider-newrelic#778]
When migrating from 1.x to 2.x version of Newrelic provider, I am running into an issue where if I add the newrelic personal key in addition to the admin key, I am getting an insufficient permission error while running `terraform plan` command. But when I remove the personal key option, the command works (I assume it is using the admin key to authenticate with the API).

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```bash
➜  us-dev-1 git:(nr-2) ✗ terraform -v
2020/07/20 22:39:32 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/07/20 22:39:32 [INFO] Terraform version: 0.12.28
2020/07/20 22:39:32 [INFO] Go runtime version: go1.13.12
2020/07/20 22:39:32 [INFO] CLI args: []string{"/usr/local/bin/terraform", "-v"}
2020/07/20 22:39:32 [DEBUG] Attempting to open CLI config file: /Users/vs033317/.terraformrc
2020/07/20 22:39:32 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/07/20 22:39:32 [INFO] CLI command args: []string{"version", "-v"}
Terraform v0.12.28
2020/07/20 22:39:32 [DEBUG] checking for provider in "."
2020/07/20 22:39:32 [DEBUG] checking for provider in "/usr/local/bin"
2020/07/20 22:39:32 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2020/07/20 22:39:32 [DEBUG] found provider "terraform-provider-newrelic_v2.2.1"
2020/07/20 22:39:32 [DEBUG] found valid plugin: "newrelic", "2.2.1", "/Users/vs033317/venky/appserv_terraform/alerts/RedTape/environments/us-dev-1/.terraform/plugins/darwin_amd64/terraform-provider-newrelic_v2.2.1"
+ provider.newrelic v2.2.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
```bash
data "newrelic_application" "app" {
  name = var.app_name
}
```
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output
```bash
020-07-20T21:51:28.585-0500 [DEBUG] plugin.terraform-provider-newrelic_v2.2.1: time="2020-07-20T21:51:28-05:00" level=debug msg="performing request" method=GET url="https://api.newrelic.com/v2/alerts_channels.json"
2020/07/20 21:51:29 [ERROR] module.redtape_alerts: eval: *terraform.EvalRefresh, err: 401 response returned: User does not have permission.
2020/07/20 21:51:29 [ERROR] module.redtape_alerts: eval: *terraform.EvalSequence, err: 401 response returned: User does not have permission.
2020/07/20 21:51:29 [ERROR] module.redtape_alerts: eval: *terraform.EvalReadData, err: 401 response returned: User does not have permission.
2020/07/20 21:51:29 [ERROR] module.redtape_alerts: eval: *terraform.EvalSequence, err: 401 response returned: User does not have permission.

Warning: Use the `newrelic_entity` data source instead.

  on ../../modules/main.tf line 1, in data "newrelic_application" "app":
   1: data "newrelic_application" "app" {

Error: 401 response returned: User does not have permission.
Error: 401 response returned: User does not have permission.

  on ../../modules/main.tf line 1, in data "newrelic_application" "app":
   1: data "newrelic_application" "app" {
```

### Expected Behavior
* I expected that if the personal_api key doesn't have permission, it will use the admin_api_key because if I don't specify the personal_api_key, it works.

### Actual Behavior
* It throws a 401 error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by jthurman42** [comment]
I agree that is the ideal situation, unfortunately we're spanning between two APIs for a while, and each use a different authentication token.  There is a lot in motion behind the scenes to accomplish this, but for now both keys are required to use the entire collection of data / resources.  This will change over time, with the Personal API key (`api_key`) being the end authentication mechanism, but as that is a fair distance out, we're going to close this issue for now.
