### ISSUE TITLE
limit not set on metric_line_chart widget in newrelic_dashboard resource

### ISSUE THREAD

**Issue by jevon71-work** [newrelic/terraform-provider-newrelic#789]
### Terraform Version
0.12.25

### New Relic Provider versions tested against
- 2.2.1
- 2.3.0

### Affected Resource(s)
- newrelic_dashboard

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "newrelic" {}

variable "application_name" {
  description = "Application name that exists in New Relic account"
  type        = string
}

data "newrelic_entity" "apm_application" {
  name   = var.application_name
  domain = "APM"
  type   = "APPLICATION"
}

resource "newrelic_dashboard" "application_dashboard" {
  title = "My Dashboard"

  widget {
    title         = "My Dashboard-Apdex"
    duration      = 1800000
    visualization = "metric_line_chart"
    entity_ids    = [data.newrelic_entity.apm_application.application_id]
    metric {
      name   = "Apdex"
      values = ["score"]
    }
    limit  = 5
    row    = 2
    column = 1
    width  = 2
  }
}
```

### Debug Output
https://gist.github.com/jevon71-work/14d92dbce9ac0b2e60a118c9b8f4d5aa

### Panic Output
None

### Expected Behavior
limit should be set to 5

### Actual Behavior
limit is set to 0 - subsequent plan asks for the dashboard to be modified and the widget is removed and recreated.

### Steps to Reproduce

1. supply variables
2. `terraform apply`
3. `terraform show`
4. `terraform plan`

### Important Factoids
None

### References
None

**Comment by zlesnr** [comment]
Thank you for reporting the issue.  I'm able to reproduce with the snippet you've given.  I'll see if I can figure out where this is coming from.

**Comment by zlesnr** [comment]
This looks to me like the API is not returning the limit field, even when I can see in the payload that we are setting it.  I've reached out to the team that owns that APIm but due to timezones, there may be a delay.

**Comment by zlesnr** [comment]
It sounds like the API ignores `limit` if `order_by` is not also included.  Could you try to set an `order_by` attribute as well and see if that resolves your issue.  If so, perhaps just a documentation update is warranted here.

**Comment by jevon71-work** [comment]
@zlesnr order_by does not appear to be an attribute I can set via New Relic (https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/dashboard).  Can you tell me what values I should provide to this attribute to get it to work?

**Comment by jevon71-work** [comment]
Never mind @zlesnr - I tried "hacking" and found I could use "score" as a valid value for `order_by`.  Can you please ensure the documentation gets updated with this and then I will be happy for the issue to be closed as resolved.
