### ISSUE TITLE
newrelic_alert_channel is created in the wrong account

### ISSUE THREAD

**Issue by w32-blaster** [newrelic/terraform-provider-newrelic#790]
### Feature Description
When using the terraform provider in a multi account setup, where one sub account is only used for authenticating users, it is not possible to create the newrelic_alert_channel in a specific account. This is possible when creating alert policies and alert conditions.

### Additional context
Ideally when you have multiple accounts, you want to manage the resources in one account by one terraform state. This works fine for the alert policies and conditions but not for the channel. Adding a policy to a channel which was created in a different account is not possible either.

**Comment by jthurman42** [comment]
Notification channels have not yet migrated to the new API endpoint that supports cross-account access.  Thus, whatever account the Admin API key is configured for would be used.  This is not true for Policies or NRQL alert conditions which use the API key.

The work-around until the API has been migrated is to create an aliased provider with the correct Admin API key for the account you want the notification channel created on.
