### ISSUE TITLE
Alert condition Access restricted

### ISSUE THREAD

**Issue by komueller** [newrelic/terraform-provider-newrelic#803]
We are using New Relic-terraform provider 2.3.0. If we want to create an NRQL-Alert-condition we get Access restricted. Our user has Admin-rights + Addon-role Alert-manager. Our user is able to create alert_channels & alert_policies. Can u guys please help us? Manual creation of alert_condition also works fine.

### Terraform Version
v0.12.29

### Affected Resource(s)
- newrelic_nrql_alert_condition

### Terraform Configuration Files
```hcl
# module.tf
resource "newrelic_nrql_alert_condition" "condition" {
  account_id           = var.newrelic_provider_account_id
  policy_id            = newrelic_alert_policy.policy_with_channels.id
  type                 = "static"
  name                 = "${var.team_name}-lambda-errors"
  description          = "Alert when an error occurs in any Lambda"
  runbook_url          = "https://www.example.com"
  enabled              = true
  value_function       = "single_value"
  violation_time_limit = "one_hour"

  nrql {
    query             = "SELECT sum(provider.errors.Sum) FROM ServerlessSample FACET `provider.functionName` WHERE providerAccountId = '${var.newrelic_provider_account_id}'"
    evaluation_offset = 3
  }

  critical {
    operator              = "above"
    threshold             = 0
    threshold_duration    = 300
    threshold_occurrences = "at_least_once"
  }
}


# main.tf
provider "newrelic" {
  version = "~> 2.3"
  api_key = data.aws_secretsmanager_secret_version.new_relic_api_key.secret_string
  admin_api_key = data.aws_secretsmanager_secret_version.new_relic_admin_api_key.secret_string
  account_id = local.newrelic_external_account_id
  region = "US"
}

module "alert" {
  source                       = "../../modules/new_relic/alerts/lambda"
  team_name                    = local.team_name
  newrelic_provider_account_id = local.newrelic_provider_account_id
  environment                   = local.environment
  slack_hook                   = local.slack_hook
}
```

### Debug Output
Error: Access restricted., null

  on ../../modules/new_relic/alerts/lambda/alert_condition.tf line 32, in resource "newrelic_nrql_alert_condition" "condition":
  32: resource "newrelic_nrql_alert_condition" "condition" {

### Expected Behavior
Alert condition successfully created.

### Actual Behavior
Access restricted

### Steps to Reproduce
1. `terraform apply`

**Comment by zlesnr** [comment]
Hi thank you for the report.  Can you confirm that the user has one of the roles mentioned here please?  https://github.com/newrelic/terraform-provider-newrelic/blob/fe4c1ad19e26d344bfbb21a1b8db354d3571e685/website/docs/index.html.markdown#resources

**Comment by jdsskn** [comment]
Thanks for your reply, The User is Admin and has AlertManager-AddOn-Role.

**Comment by zlesnr** [comment]
Looking closer at the manifest you provided, I see a few account_id references there that make me think there may be a conflict.  I see `var.newrelic_provider_account_id`, `local.newrelic_provider_account_id` and `local.newrelic_external_account_id` in play here.  Can you reduce the example here just to prove out the issue seen here?  My guess is that perhaps the account ID being used for the create is where the user lacks permission.  I'd expect a "permission denied" if the API key was not known, but the "access restricted" makes me thing that the Key itself is known.

**Comment by jdsskn** [comment]
Thank you for the hint! We finally got it working 👍 
We had to use the "external_account_id" instead of the "provider_account_id" in our module-call.
