### ISSUE TITLE
1.x to 2.4.0 Upgrade- critical{threshold_occurrences='all'} value stored as ALL. Causes continual update.

### ISSUE THREAD

**Issue by nathanweddle** [newrelic/terraform-provider-newrelic#829]
### Terraform Version
```
Terraform v0.12.29
+ provider.newrelic v2.4.2
```

### Affected Resource(s)
- newrelic_nrql_alert_condition

### Terraform Configuration Files
```hcl
# create a warning condition for high cpu
resource "newrelic_nrql_alert_condition" "warn_cpu" {
  account_id           = local.account_id
  policy_id            = var.warn_policy_id
  name                 = "${local.service} >${local.warn_cpu_percent}% of cpu quota"
  runbook_url          = local.runbook
  violation_time_limit = "twenty_four_hours"
  value_function       = "single_value"

  critical {
    threshold_duration    = 240 //seconds
    operator              = "above"
    threshold             = local.warn_cpu_percent
    threshold_occurrences = "all"
  }

  nrql {
    query             = "SELECT (percentile(cpu_usage_core_count, 75) / max(cpu_shares)) * 100 from cf_docker_container_cpu where service_name='infrastructure-alerts-${var.service}' and environment = '${var.env}'"
    evaluation_offset = 2
  }
}
```

### Debug Output
https://gist.github.com/nathanweddle/44f4595aea8f28a00bb333277c3ac4aa

### Panic Output
N/A

### Expected Behavior
Condition is not updated when `terraform apply` is run.

### Actual Behavior
The Terraform Provider should not recognize `all` as different from `ALL`. Either value is valid. 
```HCL
 critical {
            duration              = 0
            operator              = "above"
            threshold             = 4
          ~ threshold_duration    = 60 -> 120
          ~ threshold_occurrences = "ALL" -> "all"
        }

```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a NRQL Condition with a 2.4.0 New Relic Provider. 
2. Set the `threshold_occurrences` in a `critical` to `all`
3. Apply the changes and create the condition
4. Run `terraform apply` again and you should see a change like the above example.

### Important Factoids
N/A

### References
N/A

**Comment by zlesnr** [comment]
I thought this would be a quick fix, but when I made the change, other parts of the code started failing, and I wasn't able to figure out why.  As a workaround to this, could you match the new case of `ALL` here?  That should resolve the issue where TF continues to try and change the thing, though I agree we shouldn't care about the case.  We try not to for many other attributes, but there seems to be something funny going on with this one that I couldn't nail down yesterday.
