### ISSUE TITLE
NR Graph QL API returns "Access denied" when we do a terraform plan or apply with valid API keys

### ISSUE THREAD

**Issue by schmickie** [newrelic/terraform-provider-newrelic#833]
My team just updated from a 1.x version of the New Relic terraform provider to 2.5.0. Whenever we run a terraform plan, we get back multiple "Access denied" responses from New Relic. From turning on terraform trace logging, the errors seem to be coming from New Relic's GraphQL API. We have our NEW_RELIC_ADMIN_API_KEY env var set to an admin key (starting with "NRAA") and our NEW_RELIC_API_KEY set to a personal key for the same account (starting with "NRAK"). We have tested calls to graph QL on this site https://api.newrelic.com/graphiql using the same personal key and they work. 

### Terraform Version
`$ terraform -v`
`Terraform v0.12.29`
`+ provider.newrelic v2.5.0`

### Affected Resource(s)
We don't even get that far. We can't even get a plan due to the "Access denied." errors.

### Terraform Configuration Files
I'm not sure that our terraform configuration files are relevant to the issue, since we don't even get to a terraform plan. It's the NR Graph QL API calls that are failing.

### Debug Output
The trace output contained our NR API keys, so I just did debug level. I can provide sanitized trace level output if needed.
https://gist.github.com/schmickie/dea5a7bcf14bb829101a8aa8668086aa

### Panic Output
N/A

### Expected Behavior
We can do a terraform plan without getting errors from the NR API.

### Actual Behavior
We followed the instructions on how to set our API keys in the env vars with the appropriate key types, and we get "Access denied" from the Graph QL API calls.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
`export NEW_RELIC_REGION="US"`
`export NEW_RELIC_ACCOUNT_ID=297177`
`export NEW_RELIC_ADMIN_API_KEY=NRAA-xxxxxxxx`
`export NEW_RELIC_API_KEY=NRAK-xxxxx`
`terraform plan`

### Important Factoids
N/A

### References
N/A

**Comment by zlesnr** [comment]
Hi, thank you for the report.  What do you have currently set on your `provider{}` definition?  If you verified the query against the graphiql interface, then they key should have access in TF as well.  I expect that something else is getting in the way here.  I'll have a look through your logs in the mean time.

**Comment by schmickie** [comment]
```$ cat provider.tf
provider "newrelic" {
    account_id = 297117
    region = "US"
}

**Comment by zlesnr** [comment]
I notice that the `account_id` is not the same compared to what is in your environment variable in the original post.  If you're using the environment variable, you can likely just remove the line from the provider, but double check that ID to make sure its the right account.

**Comment by zlesnr** [comment]
I think this is where we make the recommendations about environment variables.  https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/provider_configuration

**Comment by schmickie** [comment]
OMG you are our hero! We paired all day on this and missed that somehow. Thank you so much! I fixed the account_id in the provider and now it works. I will close out the issue.

Would it make sense on the terraform provider side to potentially add helpful messages in the case of NerdGraph returning "Access denied" (e.g., "Access denied. Please check that your account ID and API key values are set and are correct.")?

**Comment by zlesnr** [comment]
I've made a note about improving the message in the client.  After looking at the code, I'm not sure about letting users know that their environment variable differs from what was set on the provider.  You can see where we make that determination here: 
https://github.com/newrelic/terraform-provider-newrelic/blob/master/newrelic/provider.go#L30

**Comment by schmickie** [comment]
Thanks!
