### ISSUE TITLE
Supporting icon of type "aws" in dashboards

### ISSUE THREAD

**Issue by vinuthnag** [newrelic/terraform-provider-newrelic#838]
While importing the dashboard, the Icon type of dashboard is "aws".While trying to apply the imported dashboard, terraform unable to identify the icon of type "aws".Can you please add support for this Icon.
These are the possible Icon values that I found.
https://github.com/newrelic/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_dashboard.go#L13

**Comment by zlesnr** [comment]
Another good catch.  Would you like to submit a PR for this change?

**Comment by kidk** [comment]
We are deprecating the newrelic_dashboard resource: https://github.com/newrelic/terraform-provider-newrelic/issues/1297

Icons are no longer supported in the new New Relic dashboards. Please create another ticket if you still feel this is relevant.
