### ISSUE TITLE
NR provider 2.5.0 | newrelic_infra_alert_condition - Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by deshdeep-airwallex** [newrelic/terraform-provider-newrelic#841]
Hi there,

Error: Provider produced inconsistent result after apply When applying changes to module.service-monitoring.newrelic_infra_alert_condition.memory_usage, provider "registry.terraform.io/-/newrelic" produced an unexpected new value for was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
 issue tracker.
 Error: resource not found on .terraform/modules/service-monitoring/alerts.tf line 111, in resource  "newrelic_infra_alert_condition" "cpu_usage": 111: resource "newrelic_infra_alert_condition" "cpu_usage" { ERROR: Job failed: exit code 1

### Terraform Version
terraform_0.12.23_linux_amd64.zip

### Affected Resource(s)
-  newrelic_infra_alert_condition

### Terraform Configuration Files
```
resource "newrelic_infra_alert_condition" "cpu_usage" {
  policy_id  = newrelic_alert_policy.infraPolicy.id
  name       = "High CPU usage"
  type       = "infra_metric"
  event      = "SystemSample"
  select     = "cpuPercent"
  comparison = "above"
  where      = "(`applicationId` = '${data.newrelic_application.app.id}')"

  critical {
    duration      = 5
    value         = var.cpu_usage_threshold
    time_function = "all"
  }
}
```

### Expected Behavior
Plan should have applied correctly.

### Actual Behavior
```
Error: Provider produced inconsistent result after apply When applying changes to
module.service-monitoring.newrelic_infra_alert_condition.memory_usage, 
provider "registry.terraform.io/-/newrelic" produced an unexpected new value for was present, 
but now absent.
This is a bug in the provider, which should be reported in the provider's own issue tracker.
Error: resource not found
   on .terraform/modules/service-monitoring/alerts.tf line 111, 
in resource "newrelic_infra_alert_condition" "cpu_usage":
  111: resource "newrelic_infra_alert_condition" "cpu_usage" {
 ERROR: Job failed: exit code 1
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

Apply a plan containing a newrelic_infra_alert_condition resource using Terraform 0.12.23 and NR provider 1.19.0 - Works 
Apply the same plan using the previous step's state using using Terraform 0.12.23 and NR provider 2.5.0 - Doesn't work

**Comment by zlesnr** [comment]
Using the following manifest, I'm unable to reproduce this issue.

```
resource "newrelic_alert_policy" "z" {
  incident_preference = "PER_CONDITION"
  name                = "Zach is Testing"
}

resource "newrelic_infra_alert_condition" "z" {
  policy_id  = newrelic_alert_policy.z.id
  name       = "High CPU usage"
  type       = "infra_metric"
  event      = "SystemSample"
  select     = "cpuPercent"
  comparison = "above"
  where      = "(`applicationId` = 'test')"

  critical {
    duration      = 5
    value         = 10
    time_function = "all"
  }
}
```

May I see the full manifest please, as well as the data source for `newrelic_application`?  Also, it should be noted that in the future, NRQL alerts will be the only alerts, so you may want to think about transitioning any other alerts you have to the `newrelic_nrql_alert_condition`.  The same is true for `newrelic_entitiy` I believe.

**Comment by VStefanov** [comment]
Hello @zlesnr,
Hope you are doing well!

I got the same error by using the latest 2.6.0 provider.
I am trying to create Alert for Kubernetes containers with High CPU. Here is the full configuration file:

```
provider "newrelic" {
  account_id = var.newrelic_account_id
  api_key = var.newrelic_api_key
  admin_api_key=var.newrelic_admin_api_key
}

resource "newrelic_alert_policy" "test-policy" {
  name                = "Test policy - dev"
  incident_preference = "PER_CONDITION"
}

resource "newrelic_infra_alert_condition" "container_cpu_usage" {
  policy_id  = newrelic_alert_policy.test-policy.id
  name       = "Container High CPU"
  type       = "infra_metric"
  event      = "K8sContainerSample"
  select     = "(cpuUsedCores/cpuLimitCores)*100"
  where      = "namespace = 'dev-env'"
  comparison = "above"

  critical {
    duration      = 5
    value         = 85
    time_function = "all"
  }
  warning {
    duration      = 5
    value         = 75
    time_function = "all"
  }
}
```

The tf plan goes well and after I run tf apply it throws:

```
Error: Provider produced inconsistent result after apply

When applying changes to newrelic_infra_alert_condition.container_cpu_usage,
provider "registry.terraform.io/-/newrelic" produced an unexpected new value
for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

It creates the policy and the alert, but it does not update the state file for some reason.

**Comment by zlesnr** [comment]
Oh I missed your last update, my apologies.  I'm back on the pager this week, so I can try to reproduce again.

**Comment by zlesnr** [comment]
This seems to me like potentially a corrupted state file.  I downloaded the version of TF mentioned in the OP, and used exactly the resource provided here by @VStefanov, and I get clean applies when I checkout and build the provider from `v2.6.0`.

```
❯ ./terraform version
Terraform v0.12.23
+ provider.newrelic (unversioned) <-- built from the git checkout of v2.6.0
```

What if you destroy the resource in question and recreate it?  I'd expect that to refresh the contents of the state file and perhaps this would go away.
