### ISSUE TITLE
Cannot disable "Violation time limit" for NRQL alerts

### ISSUE THREAD

**Issue by michalkisielewski** [newrelic/terraform-provider-newrelic#842]
Hi there,

I wanted to create an NRQL alert (`newrelic_nrql_alert_condition`) without enabling the "Violation time limit". However, it is required to provide either `violation_time_limit` or `violation_time_limit_seconds`, while non of these support "zero" value which would make it disabled.

### Terraform Version
v0.12.29

### Affected Resource(s)
- newrelic_nrql_alert_condition

### Terraform Configuration Files
Config file from documentation:
```hcl
resource "newrelic_nrql_alert_condition" "foo" {
  account_id           = <Your Account ID>
  policy_id            = newrelic_alert_policy.foo.id
  type                 = "static"
  name                 = "foo"
  enabled              = true
  value_function       = "single_value"
  violation_time_limit = "one_hour"

  nrql {
    query             = "SELECT average(duration) FROM Transaction where appName = 'Your App'"
    evaluation_offset = 3
  }

  critical {
    operator              = "above"
    threshold             = 5.5
    threshold_duration    = 300
    threshold_occurrences = "ALL"
  }
}
```

### Output
One of these errors will occur:
- Error: "violation_time_limit": one of `violation_time_limit,violation_time_limit_seconds` must be specified
- Error: expected violation_time_limit_seconds to be one of [3600 7200 14400 28800 43200 86400]
- Error: expected violation_time_limit to be one of [ONE_HOUR TWO_HOURS FOUR_HOURS EIGHT_HOURS TWELVE_HOURS TWENTY_FOUR_HOURS]

### Expected Behavior
It should be possible to disable Violation time limit, so these properties should support "zero" value.

### Actual Behavior
It is not possible to turn of Violation time limit via Terraform in newest provider.

### Steps to Reproduce
1. `terraform plan`

**Comment by zlesnr** [comment]
Hi, thank you for raising the issue.  What version of the provider are you on?  We may have fixed this already.

**Comment by zlesnr** [comment]
I was remembering a different attribute.  It looks like you are correct, and zero is not a valid attribute for the API.  I'm confirming that with the alerts team.

**Comment by zlesnr** [comment]
I've confirmed with the alerts team, that zero is not a valid attribute going forward and users must place limits on how long a violation will remain open.

**Comment by michalkisielewski** [comment]
@zlesnr thanks for the information. Still it is inconsistent, cause I can turn it off in the web UI 😉

**Comment by zlesnr** [comment]
Only for now @michalkisielewski.  I believe that will be less true once the REST API is dropped.
