### ISSUE TITLE
cannot create resource "newrelic_infra_alert_condition" of type "infra_host_not_reporting"

### ISSUE THREAD

**Issue by dbonfigli** [newrelic/terraform-provider-newrelic#843]
Starting from version 2.4.0 it is impossible to create a resource  ```newrelic_infra_alert_condition``` of type ```infra_host_not_reporting```.

### Terraform Version
From 2.4.0 up.

### Affected Resource(s)
```newrelic_infra_alert_condition``` of type ```newrelic_infra_alert_condition```.

### Debug Output
```
module.host_not_reporting_alert.newrelic_infra_alert_condition.host_not_reporting: Creating...

Error: value is not supported by condition type infra_host_not_reporting

  on ../../../modules/newrelic_infra_host_not_reporting_alert/main.tf line 9, in resource "newrelic_infra_alert_condition" "host_not_reporting":
   9: resource "newrelic_infra_alert_condition" "host_not_reporting" {
```

### Expected Behavior
I expected to create the resource.

### Actual Behavior
An error occours like reported in the debug output above.

### Steps to Reproduce
Use this:
```hcl
resource "newrelic_infra_alert_condition" "host_not_reporting" {
  policy_id = "xxx"
  name       = "Host Not Reporting"
  type       = "infra_host_not_reporting"
  critical {
    duration      = var.crit_duration
  }
}
```
and then `terraform apply`.

### Important Factoids
I think the commit 920ec678 created the problem.

**Comment by zlesnr** [comment]
Thank you for raising the issue.  I'm not seeing `920ec678`, but perhaps you mean `e75713c7751b667aac798156ec9d9703920ec678` since this looks like what you are referencing.

**Comment by dbonfigli** [comment]
> but perhaps you mean e75713c7751b667aac798156ec9d9703920ec678

yes, you are right, I meant that commit.
