### ISSUE TITLE
Add support for creating private locations

### ISSUE THREAD

**Issue by jasonmcintosh** [newrelic/terraform-provider-newrelic#845]
### Feature Description
Right now, you have to create a private location manually.  

### Describe Alternatives
When monitoring private datacenter locations, being able to add a synthetic minion, then add synthetic checks to that minion would allow an all-in-one deployment of synthetic checks.

### Additional context
Add any other context here.

**Comment by zlesnr** [comment]
Thank you for raising the issue.  This certainly sounds useful.

**Comment by jthurman42** [comment]
This isn't currently supported by the Synthetics API.
