### ISSUE TITLE
Can't create newrelic_entity for a NR One dashboard due to unsupported VIZ domain

### ISSUE THREAD

**Issue by schmickie** [newrelic/terraform-provider-newrelic#849]
I have defined a dashboard using newrelic_dashboard. It has already been applied and exists in NR One. I then defined newrelic_entity and newrelic_entity_tags resources for this dashboard. I have the “name” for the newrelic_entity set to the title for the dashboard, since dashboards don’t have a name attribute. I set the domain to APM and the type to DASHBOARD, but the terraform provider returns the following error (where XXXX is my dashboard’s title).

Error: the name ‘XXXX’ does not match any New Relic One entity for the given search parameters

I wasn’t sure if the domain was supposed to be APM, so I tried every other possible option for that attribute, and they all give me the same error. It must be possible to set up a newrelic_entity (and associated tags) for a dashboard because DASHBOARD is one of the options for type on newrelic_entity. 

I used the graphql interface to look up the dashboard, and it looks like the domain is supposed to be VIZ, but the provider doesn't support that option.

Error: expected domain to be one of [APM BROWSER INFRA MOBILE SYNTH], got VIZ

### Terraform Version
```
$ terraform -v
2020/08/18 14:35:54 [INFO] Terraform version: 0.12.18
2020/08/18 14:35:54 [INFO] Go runtime version: go1.12.13
2020/08/18 14:35:54 [INFO] CLI args: []string{"C:\\Users\\lestes\\Dev\\tools\\terraform.exe", "-v"}
2020/08/18 14:35:54 [DEBUG] Attempting to open CLI config file: C:\Users\lestes\AppData\Roaming\terraform.rc
2020/08/18 14:35:54 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/08/18 14:35:54 [INFO] CLI command args: []string{"version", "-v"}
Terraform v0.12.18
2020/08/18 14:35:54 [DEBUG] checking for provider in "."
2020/08/18 14:35:54 [DEBUG] checking for provider in "C:\\Users\\lestes\\Dev\\tools"
2020/08/18 14:35:54 [DEBUG] checking for provider in ".terraform\\plugins\\windows_amd64"
2020/08/18 14:35:54 [DEBUG] found provider "terraform-provider-newrelic_v2.5.0.exe"
2020/08/18 14:35:54 [DEBUG] found valid plugin: "newrelic", "2.5.0", "C:\\Users\\lestes\\dev\\rapi\\nr-automation\\.terraform\\plugins\\windows_amd64\\terraform-provider-newrelic_v2.5.0.exe"
+ provider.newrelic v2.5.0

Your version of Terraform is out of date! The latest version
is 0.13.0. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_dashboard
- newrelic_entity

### Terraform Configuration Files
```
resource "newrelic_dashboard" "sgp-zuul-blazerous-slo" {
    title = "sgp.zuul (Blazerous) SLO Dashboard"

    widget {
        title = "Handle Request Error Rate (SLO < 1%)"
        visualization = "faceted_line_chart"
        nrql = "from Metric select average(`handle-request.error_rate.value`)*100 where rfc190Scope LIKE '%sgp.zuul%' FACET rfc190Scope TIMESERIES LIMIT 1000"
        column = 1
        row = 1
    }
}
data "newrelic_entity" "sgp-zuul-blazerous-slo-dashboard" {

    name = newrelic_dashboard.sgp-zuul-blazerous-slo.title
    domain = "APM"
    type = "DASHBOARD"
}
```

### Debug Output
https://gist.github.com/schmickie/48542160e31634ca691b90f6488f3baf

### Expected Behavior
It should let me specify the proper domain VIZ and find my dashboard.

### Actual Behavior
It tells me no such entity can be found and/or that VIZ is not a proper domain.

### Steps to Reproduce
1. define newrelic_dashboard and newrelic_entity with domain APM, type DASHBOARD, and name matching dashboard's title.
2. `terraform apply`
3. Error: the name ‘XXXX’ does not match any New Relic One entity for the given search parameters

1. define newrelic_dashboard and newrelic_entity with domain VIZ, type DASHBOARD, and name matching dashboard's title.
2. `terraform apply`
3. Error: expected domain to be one of [APM BROWSER INFRA MOBILE SYNTH], got VIZ

**Comment by schmickie** [comment]
It turns out that you can specify the entity with no domain for dashboards and that works:

data "newrelic_entity" "rapi-redge-general-dashboard" {
    name = newrelic_dashboard.rapi-redge-general.title
    type = "DASHBOARD"
}

It would be great to see the documentation updated to 1) either mention that no domain is needed for dashboards or 2) add VIZ to the domain options for dashboards.

**Comment by zlesnr** [comment]
Thank you @schmickie.  Strange that the domain isn't required, but perhaps that means "search all domains".  In any case, we should update the docs for that detail.  Is that a PR that you're interested in making?

**Comment by schmickie** [comment]
@zlesnr Heya. I tried to submit a branch to make a PR for this change but got:
> git push --set-upstream origin fix-docs
remote: Permission to newrelic/terraform-provider-newrelic.git denied to schmickie.
fatal: unable to access 'https://github.com/newrelic/terraform-provider-newrelic.git/': The requested URL returned error: 403

Are there instructions somewhere for what I need to do to get permissions to submit a branch or do you need to do something on your end?

**Comment by zlesnr** [comment]
Oh, you can fork the repo and then send the PR from your fork.  That way there is no special access required there.  Once we merge your change, you'll want to pull that change into your fork as well so when you send future PRs ;) it will be up to date.

**Comment by schmickie** [comment]
PR CREATED - https://github.com/newrelic/terraform-provider-newrelic/pull/858

**Comment by schmickie** [comment]
It got a bunch of lint and unit test failures. Can I get some guidance on how I can figure out what the issues are fix them? Is there anyway to test things locally before committing and waiting for the PR checks to run?

**Comment by zlesnr** [comment]
You can `make test` and `make lint` locally to see where it's.  You can also browse the site locally if you use `make docs` and browse to http://localhost:6060/pkg/github.com/newrelic/terraform-provider-newrelic/v2

**Comment by schmickie** [comment]
This issue can be closed. There was a work around, and the core issue has now been fixed with the merge of https://github.com/newrelic/terraform-provider-newrelic/pull/895.

**Comment by zlesnr** [comment]
Nice, thanks for the contribution @schmickie.
