### ISSUE TITLE
Creating New Relic Infrastructure Alerts using Terraform - Alerts don't trigger

### ISSUE THREAD

**Issue by vickatte** [newrelic/terraform-provider-newrelic#855]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
 + Terraform v0.12.29
+ provider.aws v3.2.0
+ provider.newrelic v2.4.2

### Affected Resource(s)
Please list the resources as a list, for example:
- GCP CloudSQL

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.


data "newrelic_alert_policy" "new_relic_policy_gcp_p4" {
  name = "GCP P4"
}

resource "newrelic_infra_alert_condition" "disk_alert" {
  policy_id  = data.newrelic_alert_policy.new_relic_policy_gcp_p4.id
  name       = "GCP High Disk Utilisation 2"
  type       = "infra_metric"
  event      = "GcpCloudSqlSample"
  select     = "database.disk.Utilization"
  comparison = "above"
  
  critical {
    duration      = 5
    value         = 0.11
    time_function = "all"
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
Terraform correctly creates the resource in New Relic.

### Actual Behavior
What actually happened?
Terraform correctly creates the resource in New Relic. However, the alerts do not trigger when the thresholds are reached.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a GCP CLOUDSQL instance
2. Create NR infra alerts using script above and set the condition so that alerts should trigger
3. Check NR if alerts triggered.

**Comment by zlesnr** [comment]
Hi @vickatte, thank you for raising the issue.  Using the HCL you provided, it looks to me like Terraform is doing the correct thing here, so I suspect that perhaps the alert is misconfigured for the desired result.  Are you able to check the resource that Terraform created for this just to make sure its configured like you expect?

Also, I don't know if it helps your current situation, but I think you should be able to use NRQL conditions for this.  From the Alerts team, the NRQL alerts are the future so you'll want to update to use `newrelic_nrql_alert_condition` at some point in the future.

**Comment by vickatte** [comment]
Hello @zlesnr ,

I have  manually (on the UI ) created infra alerts with the exact same configuration as the one created with Terraform. Those created manually alert OK, but the alerts created via Terraform do not alert. So it is not clear where the diff is that is causing the issue.


Interestingly, I had initially started with the NRQL alerts but could not get this to trigger alerts - neither through Terraform or through manually created conditions. Here is what I did:


```

data "newrelic_alert_policy" "new_relic_policy_gcp_p4" {
  name = "GCP P4"
}

resource "newrelic_nrql_alert_condition" "nrql_alert_condition" {
  type                 = "static"
  name                 = "MyAlertTesing"
  policy_id            = data.newrelic_alert_policy.new_relic_policy_gcp_p4.id
  description          = "testing"
  enabled              = true
  value_function       = "single_value"
  runbook_url          = var.runbook_url
  violation_time_limit = "TWENTY_FOUR_HOURS"
  baseline_direction   = null

  nrql {
    query = "SELECT average(`database.disk.Utilization` * 100) from GcpCloudSqlSample FACET displayName and database.disk.Utilization IS NOT NULL" 

    evaluation_offset = 3
  }

  critical {
    operator              = "above"
    threshold             = 0.1
    threshold_duration    = 300
    threshold_occurrences = "all"
  }

}

```

That is the NRQL alert I created with TF, but neither would that trigger alerts even when it seemed like the thresholds were met. I suspect I am getting the query wrong.

**Comment by ctrombley** [comment]
Hi @vickatte , 

Can you retrieve the JSON payloads for the UI-based condition and the Terraform-provisioned condition and paste them both here?  Here's a command to retrieve the payloads:

```
curl -v -X GET --header "X-Api-Key: <ADMIN_API_KEY>" "https://infra-api.newrelic.com/v2/alerts/conditions/<CONDITION_ID>"
```

To get the individual condition IDs, you can use the following list endpoint (the policy ID is available in the Alerts UI):
```
curl -v -X GET --header "X-Api-Key: <ADMIN_API_KEY>" "https://infra-api.newrelic.com/v2/alerts/conditions?policy_id=<POLICY_ID>"

**Comment by vickatte** [comment]
Hello @ctrombley 

Thanks for your help - are these curls right?  When I run them I get the following:


```
curl -v -X GET --header "X-Api-Key: NRAA-xxxxxxxxxxxxxxxxxxxxxxxxxxx" "https://infra-api.newrelic.com/v2/alerts/conditions?policy_id=mypolicyid"

{"data":[],"meta":{"limit":50,"offset":0,"total":0},"links":{}}
* Connection #0 to host infra-api.newrelic.com left intact
```

**Comment by ctrombley** [comment]
That payload looks like you are authenticating correctly, but the empty `data` array makes me think the policy ID being passed is not correct.  Can you verify that the ID you're passing is the policy that your conditions have been created in?  You can find the policy ID directly under the policy name in the alerts UI 

Also can you check which region your account is based in?  If you're in the EU region you'll need to use `infra-api.eu.newrelic.com` instead.

**Comment by vickatte** [comment]
Yes, I am based in the EU - so I have changed the URL to infra-api.eu.newrelic.com and am getting some results now.

Somethings strange seemed to be happening in our account. I have a policy that has 13 alert conditions associated with it. But when I  run 
```
curl -v -X GET --header "X-Api-Key: NRAA-xxxxxxxxxxxxxxxxxxxxxxxxxxx" "https://infra-api.eu.newrelic.com/v2/alerts/conditions?policy_id=mypolicyid"
```
I do not get all the 13 alert conditions - just a few - these

```
{
   "data":[
      {
         "type":"infra_metric",
         "name":"GCP CloudSQL Alert - Disk Utilisation (TEST) - 2",
         "enabled":true,
         "id":331266,
         "violation_close_timer":24,
         "created_at_epoch_millis":1598286384181,
         "updated_at_epoch_millis":1598286384326,
         "policy_id":34782,
         "event_type":"GcpCloudSqlSample",
         "select_value":"database.disk.Utilization",
         "comparison":"above",
         "critical_threshold":{
            "value":0.1,
            "duration_minutes":5,
            "time_function":"all"
         },
         "integration_provider":"GcpCloudSql"
      },
      {
         "type":"infra_metric",
         "name":" CloudSQL - Disk utilisation (TEST)",
         "enabled":false,
         "id":331153,
         "violation_close_timer":24,
         "created_at_epoch_millis":1598271507799,
         "updated_at_epoch_millis":1598275469567,
         "policy_id":34782,
         "event_type":"GcpCloudSqlSample",
         "select_value":"database.disk.Utilization",
         "comparison":"above",
         "critical_threshold":{
            "value":0.01,
            "duration_minutes":5,
            "time_function":"all"
         },
         "integration_provider":"GcpCloudSql"
      },
      {
         "type":"infra_metric",
         "name":"GCP CloudSQL Alert - Disk utilisation",
         "enabled":true,
         "id":330959,
         "violation_close_timer":24,
         "created_at_epoch_millis":1598009146910,
         "updated_at_epoch_millis":1598032148385,
         "policy_id":34782,
         "event_type":"GcpCloudSqlSample",
         "select_value":"database.disk.Utilization",
         "comparison":"above",
         "critical_threshold":{
            "value":0.7,
            "duration_minutes":5,
            "time_function":"all"
         },
         "integration_provider":"GcpCloudSql",
         "description":"Alert when the CloudSQL disk utilisation exceeds 70%."
      },
      {
         "type":"infra_metric",
         "name":"GCP CloudSQL Alert - Instance down",
         "enabled":true,
         "id":330888,
         "violation_close_timer":24,
         "created_at_epoch_millis":1597934565324,
         "updated_at_epoch_millis":1598032290391,
         "policy_id":34782,
         "event_type":"GcpCloudSqlSample",
         "select_value":"database.Up",
         "comparison":"below",
         "critical_threshold":{
            "value":1,
            "duration_minutes":5,
            "time_function":"all"
         },
         "integration_provider":"GcpCloudSql",
         "description":"Trigger alert when a GCP CloudSQL instance goes down"
      }
   ],
   "meta":{
      "limit":50,
      "offset":0,
      "total":4
   },
   "links":{
      
   }
}
```

Why is this?

Interestingly, the infrastructure alerts condition don't have condition_id displayed on the UI - at least I cannot see where they are displayed.

Following advice from @zlesnr,  I have switched to NRQL alert conditions.

**Comment by ctrombley** [comment]
@vickatte I think you only saw a subset of conditions because this endpoint only enumerates Infra conditions.    @zlesnr 's advice is on point - we are recommending NRQL conditions for future-facing observability configurations.
