### ISSUE TITLE
data for newrelic_alert_policy occurring during plan but is causing failures in planning

### ISSUE THREAD

**Issue by mmalave1** [newrelic/terraform-provider-newrelic#861]
The resource is being created in one module and then the data is referencing it in a separate module. Im running on terraform 0.12.26 with new relic on 2.1. The names for the resource and data match but the plan fails. Terraform allows for data to behave differently as in the [data sources docs](https://www.terraform.io/docs/configuration/data-sources.html?_ga=2.56661802.1459232800.1598884564-1905130703.1598559441). Ideally this would be handled where: “Query constraint arguments may refer to values that cannot be determined until after configuration is applied”

```
resource "newrelic_alert_policy" "incident-policy" {
  name                = "${var.service} INCIDENT"
  channel_ids         = [var.channel_id]
  incident_preference = "PER_CONDITION_AND_TARGET"

}
```
in a separate module:

```
data "newrelic_alert_policy" "incident" {
  name = "${local.service} INCIDENT"
}
```
this fails with the error:

```
Error: the name 'TEAM INCIDENT ' does not match any New Relic alert policy

[81] on service-ime/vars.tf line 22, in data "newrelic_alert_policy" "inc":

[82] 22: data "newrelic_alert_policy" "inc" {
```

**Comment by sanderblue** [comment]
Hi @mmalave1, can you share more of your configuration (sensitive details redacted)? My first hunch is this doesn't seem like a New Relic provider issue, this seems more like a Terraform configuration issue.  We need to a bit more context to better understand the relationship between the modules and resources. 

But at first glance, using `local.service` and `var.service` seems a little suspect. Without other information, I would try renaming one of those variables and maybe namespace it with a prefix `var.my_module_service` or `local.my_other_module_service` to just to rule that out.

**Comment by mmalave1** [comment]
> Hi @mmalave1, can you share more of your configuration (sensitive details redacted)? My first hunch is this doesn't seem like a New Relic provider issue, this seems more like a Terraform configuration issue. We need to a bit more context to better understand the relationship between the modules and resources.
> 
> But at first glance, using `local.service` and `var.service` seems a little suspect. Without other information, I would try renaming one of those variables and maybe namespace it with a prefix `var.my_module_service` or `local.my_other_module_service` to just to rule that out.

For versions, Im running on terraform 0.12.26 with new relic on 2.1.

The configuration generally looks like this:
`- newrelic
|
`- service-a
|
`- service-b

Where within the newrelic module I have the empty variable:
```
variable "service" {
  default = "value"
}
```

And in service-a, I have the value created and pass it into the module block

```
locals {
  service = "TEAM"
}

module "newrelic" {
  source         = "../newrelic"
  service = local.service
}

```
In practice, for the service name, both local and var produce equivalent values because var inherits it as it passes through the module block. 

As, the problem is not the naming here. The names could actually be totally different but, ideally, would not fail in the plan stage. Rather return as "COMPUTED" in planning. 

Note: I converted from using an output from one module to another to using the data to get the policy ids because I am handling multiple environments and the new relic resources would have to be created first. Because terraform is trying to fetch the values during a plan rather than only at the apply stage for these data sources, the resources are blocked from creation.

**Comment by mmalave1** [comment]
Closing issue as data being evaluated at plan is expected and should fail when resource does not exist.
