### ISSUE TITLE
Enable to use Terraform with a service API KEY instead of Personal API KEY

### ISSUE THREAD

**Issue by kaizer113** [newrelic/terraform-provider-newrelic#872]
### Feature Description
we don't use personal terraform
we have a root service account, which does terraforming
Personal API keys are a no go for us
we don't let people run stuff on their own anymore, all is run via central services
we'd like to be able to use an API key not associated to a personal user account.
thanks
Lionel

**Comment by zlesnr** [comment]
For the service account, can you create a Personal API key that you can use with Terraform?

**Comment by skyzyx** [comment]
@kaizer113:

One thing I've done to clarify the terminology for people I support is that "Personal Key" is a _proper noun_, not an _adjective_. You can have a _personal_ Personal Key, and a _personal_ Admin Key. Also your service account can have a Personal Key and Admin Key.

The naming can be confusing, but the concept that you're looking for is already supported.

**Comment by kaizer113** [comment]
We have Okta AUM integration, we don't want to create an Okta account for a service.
thanks

**Comment by zlesnr** [comment]
Good input @skyzyx and thank you for the response @kaizer113.  Unfortunately this is not something we will be able to fix in this project.  The desire for a service API key has been reported upstream, but there is no commitment or timeline on this making it into the product.  At present, creating an account for the service user and creating a Personal API key is the only workaround I'm aware of to meet this constraint.

**Comment by skyzyx** [comment]
> We have Okta AUM integration, we don't want to create an Okta account for a service.

I think you'll have to. That's what we did. I don't think there's another way around it.

You have to provision a "user" in Okta (which syncs with New Relic, then generate credentials for that "user". We just have one "user" account that is designated as the New Relic service account.

**Comment by kaizer113** [comment]
thanks
