### ISSUE TITLE
fill_option": is not Optional 

### ISSUE THREAD

**Issue by kaizer113** [newrelic/terraform-provider-newrelic#875]
"fill_option": is documented as Optional and appears Optional in the code (resource_newrelic_nrql_alert_condition.go), however not providing it creates runtimes error.

Error: Argument "condition" has invalid value $condition.
In field "signal": Expected type "AlertsNrqlConditionSignalInput", found {fillOption: "", fillValue: null}.
In field "fillOption": Expected type "AlertsFillOption", found ""., null

**Comment by zlesnr** [comment]
Thank you for the report.  Can you tell me if you continue to see this issue on `v2.7.1`?

**Comment by Zayeem** [comment]
@zlesnr Experiencing the same issue with the new version v2.7.1 even though it is marked as Optional in the schema

**Comment by zlesnr** [comment]
Can you post the resource for me to reproduce please?

**Comment by zlesnr** [comment]
The following is working as expected for me.

```
cy" "z" {
  incident_preference = "PER_POLICY"
  name                = "Zach is Testing"
}

resource "newrelic_nrql_alert_condition" "test" {
  policy_id            = newrelic_alert_policy.z.id
  name                 = "tf-test-zleslie-recreate-error"
  runbook_url          = ""
  violation_time_limit = "twenty_four_hours"
  value_function       = "single_value"

  critical {
    threshold_duration    = 240
    operator              = "above"
    threshold             = 90
    threshold_occurrences = "all"
  }

  nrql {
    query             = "SELECT count(*) FROM TransactionError WHERE appName like '%Dummy App%'"
    evaluation_offset = 3
  }
}```

This is on `v2.7.1`.

**Comment by kaizer113** [comment]
thanks if works fine now in 2.7.1

**Comment by zlesnr** [comment]
Oh good to hear.  Let us know if you run into any other issues.
