### ISSUE TITLE
Update EU Infrastructure API Endpoint

### ISSUE THREAD

**Issue by martynlanglands** [newrelic/terraform-provider-newrelic#880]
### Feature Description
Running terraform with Infra_alert generates a 403 as the url endpoint is not correct.

### Describe Alternatives
Using the https://infra-api.eu.newrelic.com/v2/alerts generates a 403 response.

The actual endpoint is = https://infrastructure-alert.service.eu.newrelic.com/v2/alerts

The header should not include the `X-Api-Key` header instead it should be "Api-Key"

### Additional context

The documented new relic command for listing infra alert conditions specifies 

`#curl -v -X GET --header "X-Api-Key: NRRA-(omitted)" "https://infra-api.eu.newrelic.com/v2/alerts/conditions?policy_id=46373"`

`* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=New Relic, Inc.; CN=*.eu.newrelic.com
*  start date: Oct 19 00:00:00 2018 GMT
*  expire date: Oct 23 12:00:00 2020 GMT
*  subjectAltName: host "infra-api.eu.newrelic.com" matched cert's "*.eu.newrelic.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /v2/alerts/conditions?policy_id=46373 HTTP/1.1
> Host: infra-api.eu.newrelic.com
> User-Agent: curl/7.64.1
> Accept: */*
> X-Api-Key: NRRA-(omitted)
> 
< HTTP/1.1 401 Unauthorized
< Content-Length: 16
< Content-Type: text/plain; charset=utf-8
< Date: Tue, 15 Sep 2020 08:43:43 GMT
< 
* Connection #0 to host infra-api.eu.newrelic.com left intact
Invalid API key.* Closing connection 0`

However the above command fails and performs a redirect - the actual working command for infra_alerts is 

`curl -v -X GET --header "Api-Key: NRAK-(omitted)" "https://infrastructure-alert.service.eu.newrelic.com/v2/alerts/conditions?policy_id=46373"
`
< HTTP/1.1 200 OK
< Proxied-By: Service Gateway
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Content-Security-Policy: frame-ancestors *.newrelic.com
< Content-Length: 575
< Content-Type: application/json
< Date: Tue, 15 Sep 2020 08:44:44 GMT
< 
{"data":[{"type":"infra_metric","name":"dev - martyn - BinLogReplicationLatency","enabled":false,"filter":{"and":[{"is":{"entityId":"3375455152209217644"}}]},"id":334989,"violation_close_timer":24,"created_at_epoch_millis":1600086770932,"updated_at_epoch_millis":1600099943523,"policy_id":46373,"event_type":"DatastoreSample","select_value":"provider.auroraBinlogReplicaLag.Maximum","comparison":"above","critical_threshold":{"value":20,"duration_minutes":5,"time_function":"all"},"integration_provider":"RdsDbInstance"}],"meta":{"limit":50,"offset":0,"total":1},"links":{}}
* Connection #0 to host infrastructure-alert.service.eu.newrelic.com left intact
* Closing connection 0

**Comment by zlesnr** [comment]
Hi, thank you for the report.  It looks like you are using two different API keys to perform those curls.  Can you confirm the working API key against first endpoint?

**Comment by sanderblue** [comment]
Hi @martynlanglands, the EU URL for our Infrastructure API hasn't changed. It appears you're using a non-admin API key in your first `curl` example while also using the `X-Api-Key` header. Your API key should _not_ start with `NRRA-` for this API call. You want to use the API key that starts with **`NRAA-`** with `X-Api-Key` header.

The below call worked for me using my `NRAA` admin API key.
```
curl -v -X GET --header "X-Api-Key: ${NEW_RELIC_ADMIN_API_KEY}" "https://infra-api.eu.newrelic.com/v2/alerts/conditions?policy_id=712732"
```
```
> GET /v2/alerts/conditions?policy_id=712732 HTTP/1.1
> Host: infra-api.eu.newrelic.com
> User-Agent: curl/7.64.1
> Accept: */*
> X-Api-Key: NRAA-****** # Using NRAA- (my admin API key)
> 
< HTTP/1.1 200 OK
< Content-Length: 64
< Content-Type: application/json
< Date: Wed, 23 Sep 2020 17:06:49 GMT
< 
{"data":[],"meta":{"limit":50,"offset":0,"total":0},"links":{}}
* Connection #0 to host infra-api.eu.newrelic.com left intact
* Closing connection 0
```
