### ISSUE TITLE
"Error: 500 response returned" when performing a terraform plan/apply with data resources

### ISSUE THREAD

**Issue by tomcart90** [newrelic/terraform-provider-newrelic#883]
### Summary
When performing a terraform plan or apply I frequently see a "Error: 500 response returned" error coming from our data.newrelic_synthetics_monitor_location resource which causes the plan or apply to error out. This happens very frequently, maybe 50% of the time when performing a plan or apply.

### Terraform Version
Terraform v0.13.2

### Affected Resource(s)
- data.newrelic_synthetics_monitor_location

### Terraform Configuration Files
```hcl
data "newrelic_synthetics_monitor_location" "newrelic_corp_minion" {
  label = "newrelic-corp-minion"
}
```

### Debug Output
https://gist.github.com/tomcart90/be1edddb10de51bb501eb4c59b3a28e2 (can't provide the full log as there may be sensitive information)

### Expected Behavior
A terraform plan or apply when reading from a `data.newrelic_synthetics_monitor_location` resource doesn't produce an error.

### Actual Behavior
When attempting to read a `data.newrelic_synthetics_monitor_location` (which points at one of our private locations) resource during a terraform plan or apply I frequently get a 500 error returned.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Using an EU new relic account.

**Comment by tomcart90** [comment]
Update: this happens even when not attempting to read a `data.newrelic_synthetics_monitor_location` resource.

**Comment by tomcart90** [comment]
Update: the issue seems to happen for a couple of data resources in our case, either `newrelic_synthetics_monitor_location` or `newrelic_alert_policy`. I'm able to reproduce the issue when running a terraform apply or plan where the same data resources are queried multiple times due to the data resource being defined within a module, of which there are many instantiations (15+).

**Comment by tomcart90** [comment]
This is still a persistent issue in our environment and is causing terraform plan and apply actions to regularly fail.

**Comment by sanderblue** [comment]
Hi @tomcart90, we need more information about your configuration to start debugging this. Since your data source isn't causing the issue according to your comment, we need more information, otherwise we're just guessing what your configuration looks like. Your log output says you're on v2.7.0 of the provider. Is this still correct? Please provide additional configuration details (sensitive data redacted) and more log output so we have context of what's happening during the process. 🙂
