### ISSUE TITLE
newrelic_alert_channel creates channel in master account

### ISSUE THREAD

**Issue by KrystianOcado** [newrelic/terraform-provider-newrelic#890]
Hello!

It seems that newrelic_alert_channel creates channel on master instead of account defined using NEW_RELIC_ACCOUNT_ID. Other resources, like newrelic_alert_policy seems to work.

### Terraform Version

```
Terraform v0.13.3
+ provider registry.terraform.io/newrelic/newrelic v2.7.2
```

### Affected Resource(s)

- newrelic_alert_channel

### Terraform Configuration Files
```hcl
terraform {
  backend "s3" {
  }

  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
      version = "2.7.2"
    }
  }

  required_version = ">= 0.13"
}

resource "newrelic_alert_channel" "ewoks-pager-duty" {
  name = "Krystian Test 1"
  type = "pagerduty"

  config {
    service_key = "foo123"
  }
}
```

### Debug Output

```
terraform apply tf.plan                       
newrelic_alert_channel.ewoks-pager-duty: Destroying... [id=xxx]
newrelic_alert_channel.ewoks-pager-duty: Destruction complete after 1s
newrelic_alert_channel.ewoks-pager-duty: Creating...
newrelic_alert_channel.ewoks-pager-duty: Creation complete after 4s [id=xxx]
```

### Expected Behavior
newrelic_alert_channel should be created in sub account, not master account.

### Actual Behavior
newrelic_alert_channel is created in master account.

### Steps to Reproduce

1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- It might be a cause of GH-840

If you need anything else, please let me know.

**Comment by sanderblue** [comment]
Hi @KrystianOcado, thanks for reporting. Since it looks like you are using environment variables to configure the provider, are you also setting `NEW_RELIC_API_KEY` and `NEW_RELIC_ADMIN_API_KEY`? 

Also, can you provide us with the configuration of the other resources that work, such as the `newrelic_alert_policy` you mentioned? 🙂
