### ISSUE TITLE
Destroy resources command is not working properly

### ISSUE THREAD

**Issue by aurelienlair** [newrelic/terraform-provider-newrelic#918]
### Terraform Version
v0.13.2

### Newrelic Version
v2.7.5

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_synthetics_monitor
- newrelic_synthetics_monitor_script
- newrelic_alert_policy
- newrelic_nrql_alert_condition
- newrelic_alert_channel

### Terraform Configuration Files
Please get in touch with [Darren Doyle](ddoyle@newrelic.com) to access the source code as he is following ourself in the Terraform integration.

### Expected Behavior
To be able to update any resource by destroying via `terraform destroy` it and recreating from scratch so we could make
changes to existing New Relic resources.

### Actual Behavior
By deploying production resources, then staging resources, at this point if I make any change to the production resources (title, labels whatever...) and I try to deploy again the production resources they should replace the previous ones (ie. old ones should be destroyed and new ones should be created) while right now they are not removed and recreated (some of them are removed, some others no so we're in a hybrid bad situation).

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Running `clean-up`
rm -Rvf .terraform && rm -Rvf terraform.tfstate terraform.tfstate.backup && rm -Rvf output.tf
2. Running `init` staging package
terraform init -upgrade ./{MY_PACKAGE}/staging
3. Running `plan` on staging package
terraform plan ./{MY_PACKAGE}/staging
4. Running `apply` on staging package
module.staging_{MY_PACKAGE}...
terraform apply ./{MY_PACKAGE}/staging
Apply complete! Resources: 16 added, 0 changed, 0 destroyed.
5. Running `clean-up`
rm -Rvf .terraform && rm -Rvf terraform.tfstate terraform.tfstate.backup && rm -Rvf output.tf
6. Running `init` production package
terraform init -upgrade ./{MY_PACKAGE}/prod
7. Running `plan` on production package
terraform plan ./{MY_PACKAGE}/prod
8. Running `apply` on production package
terraform apply ./{MY_PACKAGE}/prod
module.production_{MY_PACKAGE}...
Apply complete! Resources: 16 added, 0 changed, 0 destroyed.
9. Running `clean-up`
rm -Rvf .terraform && rm -Rvf terraform.tfstate terraform.tfstate.backup && rm -Rvf output.tf
10. Running `init` staging package
terraform init -upgrade ./{MY_PACKAGE}/staging
11. Running `plan` on staging package
terraform plan ./{MY_PACKAGE}/staging
12. Running `apply` on staging package
module.staging_{MY_PACKAGE}...
terraform apply ./{MY_PACKAGE}/staging
Apply complete! Resources: 16 added, 0 changed, 0 destroyed.
Error: **400** response returned: Invalid name specified: 'XXXXX'; a monitor with that name already exists.
  on {MY_PACKAGE}/synthetics/main.tf line 1, in resource "newrelic_synthetics_monitor" "{MY_PACKAGE}":
   1: resource "newrelic_synthetics_monitor" "{MY_PACKAGE}" {
(which is correct as it indeed exists)
13. Trying to destroy `staging` resources
terraform destroy ./{MY_PACKAGE}/staging
Destroy complete! Resources: 14 destroyed.

**Comment by zlesnr** [comment]
Hi, thank you for the report.  Is it just the `newrelic_synthetics_monitor` that you are having trouble destroying?

**Comment by aurelienlair** [comment]
Hi Zach,
I'm afraid that not only `newrelic_synthetics_monitor` is impacted but everything :-(
Consider that I did the above manipulation on a configuration with:
- 1 synthetics script API based
- 1 API script 
- 2 alert policies (1 with 3 alert conditions NRQL based and 1 with 1 alert condition NRQL based)
- 1 email + 1 slack channels for the both alert policies incidents

Before running step 10 in Staging I have changed code by:
- adding a comment on the the API script
- updating the name of 1 of the alert conditions
- updating the name of 1 of the alert policies

What happens is anyhow I see that the alert policy channels are duplicated every time we run `terraform apply` is this normal?
Consider that I used channels which were in use by other checks before eveb step 1.
![duplicated_channels](https://user-images.githubusercontent.com/2820749/94796564-3fecb580-03df-11eb-8f10-6a5baaa3e7b8.png)

Second is after step 10 there are duplicated alert policies
![duplicated_policies](https://user-images.githubusercontent.com/2820749/94796698-6874af80-03df-11eb-83f4-27fa1f9f43c3.png)

Last but not least when I run step 13 I still see entities such as the policies, the synthetic checks and so on
![policies_not_removed](https://user-images.githubusercontent.com/2820749/94796807-8fcb7c80-03df-11eb-8cb6-5c3ce71b4617.png)
![synthetics_not_removed](https://user-images.githubusercontent.com/2820749/94796817-93f79a00-03df-11eb-8583-619409a5ce70.png)

I hope my exhaustive report will help because it's quite critical, we have duplication in the entities, we have other not removed... the consequence is it's not stable and we have to manually delete, check etc.. hence it's not sustainable as you can imagine.
As I told to [Darren Doyle](ddoyle@newrelic.com) the reason could also be an incorrect usage by our team in that case thanks to the code provided by Darren I guess you could understand which could be the potential mistakes and let us know.

Best Regards
Aurélien

**Comment by zlesnr** [comment]
Thank you for the response.  I'd like to see the code please.  The best way for me to debug this is to be able to copy your code and reproduce the issue as closely as I can.  Then I can see what is happening from an API level, and not just what appears in the UI.  Let me know if a representative snippet can be provided for debug.

**Comment by zlesnr** [comment]
I've extracted the handful of resources you mention in the top post and attempted to recreate the issue.  All of the resources I have in play are destroyed like I expect.  Are you certain that the resources you point out weren't duplicated perhaps by a previous version, potentially by a bug that has already been fixed?  For example, if you delete what remains after a destroy, and then recreate with an apply, do the resources still not get deleted when you perform another destroy?

**Comment by aurelienlair** [comment]
> Are you certain that the resources you point out weren't duplicated perhaps by a previous version, potentially by a bug that has already been fixed

Unless it has been fixed after 4 PM yesterday yes I am certain because before doing the tests I manually deleted everything.

Did you exactly do step 1 to 13? Have you verified on New Relic one that everything is indeed destroyed? Cause looking at it now I can see duplicated resources for instance.
![screenshot-one eu newrelic com-2020 10 02-09_31_11](https://user-images.githubusercontent.com/2820749/94898792-72a3b600-0492-11eb-9e18-e1c20d0b6730.png)

I'm afraid you did not reproduce exactly the problem for some reason. Can I invite you on our Slack channel so we could have a session to talk about this?

**Comment by zlesnr** [comment]
Sure, though if you know where I went wrong in reproducing the issue, please advise.  I can give the sample that I'm working with that operates correctly.

**Comment by zlesnr** [comment]
This is what I've used to attempt to reproduce your issue:
```hcl
provider "newrelic" {
}
data "newrelic_entity" "app" {
  name = "Dummy App"
}
resource "newrelic_alert_policy" "z" {
  incident_preference = "PER_POLICY"
  name                = "zleslie-test"
}
resource "newrelic_nrql_alert_condition" "test" {
  policy_id            = newrelic_alert_policy.z.id
  name                 = "zleslie-test"
  runbook_url          = ""
  violation_time_limit = "twenty_four_hours"
  value_function       = "single_value"
  critical {
    threshold_duration    = 240
    operator              = "above"
    threshold             = 90
    threshold_occurrences = "all"
  }
  nrql {
    query             = "SELECT count(*) FROM TransactionError WHERE appName like '%Dummy App%'"
    evaluation_offset = 3
  }
}
resource "newrelic_infra_alert_condition" "container_cpu_usage" {
  policy_id  = newrelic_alert_policy.z.id
  name       = "zleslie-test"
  type       = "infra_metric"
  event      = "K8sContainerSample"
  select     = "(cpuUsedCores/cpuLimitCores)*100"
  where      = "namespace = 'prod-env'"
  comparison = "above"
  critical {
    duration      = 5
    value         = 85
    time_function = "all"
  }
  warning {
    duration      = 5
    value         = 75
    time_function = "all"
  }
}
resource "newrelic_alert_channel" "email" {
  name = "zleslie-test"
  type = "email"
  config {
    recipients              = "zleslie@newrelic.com"
    include_json_attachment = "1"
  }
}
resource "newrelic_alert_policy_channel" "alert_email" {
  policy_id = newrelic_alert_policy.z.id
  channel_ids = [
    newrelic_alert_channel.email.id
  ]
}
resource "newrelic_synthetics_monitor_script" "api_booking_get_activities_script" {
  monitor_id = newrelic_synthetics_monitor.api_booking_get_activities.id
  text       = data.template_file.api_booking_get_activities.rendered
}
resource "newrelic_synthetics_monitor" "api_booking_get_activities" {
  name      = "zleslie-test"
  type      = "SCRIPT_API"
  frequency = 5
  status    = "ENABLED"
  # Milan - Dublin
  locations = ["AWS_EU_SOUTH_1", "AWS_EU_WEST_1"]
}
data "template_file" "api_booking_get_activities" {
  template = templatefile("scriptapi.tmpl", {
    bad_response_in_get_activities_request             = "test"
    bad_number_of_activities_in_get_activities_request = "test"
    bad_response_login_request_get_activities          = "test"
    client_id = "test"
    client_secret = "test"
  })
}
resource "newrelic_entity_tags" "server" {
  guid = data.newrelic_entity.app.guid
  tag {
    key    = "VIP"
    values = ["SingleNode"]
  }
  tag {
    key    = "Environment"
    values = ["cluster"]
  }
  tag {
    key    = "Tech"
    values = ["Rancher", "Farmer"]
  }
}
```

**Comment by zlesnr** [comment]
This was resolved on a call where we discovered that the terraform state file was being removed, and so duplicates were being created, and old resources were not being cleaned up with a destroy.
