### ISSUE TITLE
Error: 401 response returned: Bad API Key or no API Key provided, null

### ISSUE THREAD

**Issue by davetron5000** [newrelic/terraform-provider-newrelic#951]
## Please include the following with your bug report

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)

   ```
   provider "newrelic" {
     api_key    = var.new_relic_api_key
     account_id = "«my account id»"
     region     = "US"
     version    = "~> 2.12.0"
   }
   ```
- [x] A list of [affected resources](#affected-resources) and/or data sources

   * This data stanza is the only thing I have:

      ```
      data "newrelic_entity" "hermes" {
         name = "Hermes"
      }
      ```

- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)

   Above is all I have
- [x] Description of the [current behavior](#actual-behavior) (the bug)

   I get the error `Error: 401 response returned: Bad API Key or no API Key provided, null`.  I am on the new relic one account type.  I tried the API key show in the integrations section.  This key works with the REST API and with CURL but did not work with terraform.  I then [these instructions](https://docs.newrelic.com/docs/apis/nerdgraph/examples/use-nerdgraph-manage-license-keys-personal-api-keys) to create a personal API key using the GraphQL api.  The key has the prefix NRB.  Using *that* key results in the same error.  I have also tried setting this via an environment variable and no affect.

- [x] Description of the [expected behavior](#expected-behavior)

   Expecting not to get an error.
- [X] Any related [log output](#debug-output)

   There is not anything I can see when I do `TF_LOG=debug terraform plan` I would provide a gist but it's full of api keys and sensitive values being debugged from other plugins.

### Terraform Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/github v2.9.2
+ provider registry.terraform.io/newrelic/newrelic v2.12.0
+ provider registry.terraform.io/pagerduty/pagerduty v1.7.10
+ provider registry.terraform.io/terraform-providers/heroku v2.4.1
```

### Affected Resource(s)

`newrelic_entity`

### Terraform Configuration

see above

### Actual Behavior

Error: 401 response returned: Bad API Key or no API Key provided, null

### Expected Behavior

Not to get an error

### Steps to Reproduce

1. Create a brand new NewRelic account
1. Generate a person API key as described above
1. connect an app to New Relic in the normal way outside of Terraform
1. configure the data source as shown above
1. `terraform plan`

### Debug

This is only those debug lines that have "relic" in them: https://gist.github.com/davetron5000/7550a9fc01709ef4091fdde24dd2ae68

Reason is that sensitive values are all over this output and I'm not confident I can exicse them all

**Comment by ctrombley** [comment]
Hi @davetron5000 ,

It appears you followed directions to create a new Browser ingest key, not a Personal API key.  Luckily you should already have a personal API key provisioned if you're able to run queries against Nerdgraph.  Try the following query in the Graphiql interface:

```graphql
{
  actor {
    apiAccess {
      keySearch(query: {types: USER}) {
        nextCursor
        keys {
          ... on ApiAccessUserKey {
            key
            name
          }
        }
      }
    }
  }
}

```

You're looking for a key that begins with `NRAK-` in the query results.  That's the one you should be using with the Terraform provider.  Please try it out and let us know if you're able to get things working.

**Comment by davetron5000** [comment]
Wow, that worked, thanks!

Now: how could I have figured that out?  New Relic seems to be going through some sort of account transition, so I think a lot of documentation is in flux.  Is this something that could be appropriate in this repo's e.g. README or something?

**Comment by ctrombley** [comment]
We are aware of the problem.  We are working to simplify it and in the interim it seems like there is still a lot of confusion, especially where authenticating against the APIs is concerned.  In this case we'll make the docs clearer about what the example you found does, and also include a clear example for creating and retrieving a Personal API key.  We also hope to streamline the process of finding the right keys out of the gate with improved UI/UX.

**Comment by ctrombley** [comment]
We'll also include a section in this repo's README and/or Getting started guide with the advice I posted here.

**Comment by davetron5000** [comment]
If it helps, I made #953 which is basically the instructions I put in our internal docs for generating and viewing this key.  If there's a better way to do it, let me know and I'm happy to help.  Also happy to let you do it if that's your preference :)
