### ISSUE TITLE
Support Single Condition blocks in newrelic_alert_muting_rule

### ISSUE THREAD

**Issue by Kiran01bm** [newrelic/terraform-provider-newrelic#958]
### Feature Description
Support `newrelic_alert_muting_rule` to have single Conditions blocks.

### Describe Alternatives
Currently I am duplicating the the Single Condition check with an AND operator. Also referred the Tests and found something similar being done - https://github.com/newrelic/terraform-provider-newrelic/blob/c38d008e84ac879d95ce38d0c167a09a77c40746/newrelic/resource_newrelic_alert_muting_rule_test.go#L60-L72

### Additional context
One of my use-case is to mute all alarms that are tagged to a specific alert policy. I would intend to define the newrelic_alert_muting_rule as `Intended` below but having to do a `Workaround`.

#### Intended
```
resource "newrelic_alert_muting_rule" "muting_rule" {
    name = var.muting_rule_name
    enabled = var.muting_rule_status
    description = var.muting_rule_description
    condition {
        conditions {
            attribute   = "policyName"
            operator    = "IN"
            values      = var.alert_policy_names
        }
    }
}
```

#### Workaround
```
resource "newrelic_alert_muting_rule" "muting_rule" {
    name = var.muting_rule_name
    enabled = var.muting_rule_status
    description = var.muting_rule_description
    condition {
        conditions {
            attribute   = "policyName"
            operator    = "IN"
            values      = var.alert_policy_names
        }
        conditions {
            attribute   = "policyName"
            operator    = "IN"
            values      = var.alert_policy_names
        }
        operator = "AND"
    }
}
```

**Comment by zlesnr** [comment]
The following works for me on the latest version.  This seems to work as expected.
```
resource "newrelic_alert_muting_rule" "muting_rule" {
    name = "name goes here"
    enabled = false
    description = "description goes here"
    condition {
        conditions {
            attribute   = "policyName"
            operator    = "IN"
            values      = [newrelic_alert_policy.z.name]
        }
        operator = "AND"
    }
}
```

**Comment by Kiran01bm** [comment]
Thank you. Actually, I just tested this on the same version of the provider that I was using `provider "newrelic" { version = "2.9.0" }` and it works with the additional `operator = "AND"`.

Kind of weird that we have to input a logical operator when there is none needed.

**Comment by zlesnr** [comment]
I agree, though I think that's just what the API requires.  I'll close this out since it sounds like its working for you.  Let us know if anything else comes up.
