### ISSUE TITLE
NR provider keeps trying to apply the same aggregation_window change in newrelic_nrql_alert_condition

### ISSUE THREAD

**Issue by jaloren** [newrelic/terraform-provider-newrelic#963]
## Your New Relic `provider` 

```
provider "newrelic" {
  region        = "US"
  admin_api_key = var.admin_api_key
  api_key       = var.personal_api_key
  account_id    = "89496"
  version       = "2.11.0"
}
```
## Affected resources

Affects all of our newrelic_nrql_alert_condition. We have over 300 of them.

```
  ~ resource "newrelic_nrql_alert_condition" "service_available" {
        account_id                     = placeholder
      - aggregation_window             = 60 -> null
        close_violations_on_expiration = false
        enabled                        = true
        expiration_duration            = 0
        fill_option                    = "none"
        fill_value                     = 0
        id                             = "placeholder"
        name                           = "placeholder"
        open_violation_on_expiration   = false
        policy_id                      = placeholder
        type                           = "static"
        value_function                 = "SINGLE_VALUE"
        violation_time_limit           = "TWENTY_FOUR_HOURS"

        critical {
            duration              = 0
            operator              = "below"
            threshold             = 2
            threshold_duration    = 300
            threshold_occurrences = "all"
        }

        nrql {
            evaluation_offset = 20
            query             = "SELECT latest('provider.runningCount') FROM ComputeSample WHERE entityName = 'placeholder'"
        }
    }
```

## Current Behavior

According to the [docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#aggregation_window), this is optional. Consequently, we do not have the aggregation_window set in the 
terraform resource newrelic_nrql_alert_condition. However, when do a terraform apply, the plan shows a delta indicating that terraform will try to set the aggregation window from 60 to null. 

The apply completes successfully. However, when the next plan or apply is run, the plan shows the exact same changeset to be applied.

## Expected Behavior

The plan should not show any delta or after the first successfully apply, it should not show the exact same delta in subsequent terraform plans.

**Comment by ctrombley** [comment]
Resolved by #961
