### ISSUE TITLE
Add schedule support to newrelic_alert_muting_rule resources

### ISSUE THREAD

**Issue by andywinslow** [newrelic/terraform-provider-newrelic#966]
### Feature Description
Please add schedule support to the newrelic_alert_muting_rule resource. The API looks like it fully supports muting rules with a schedule and I would very much like to manage my scheduled muting rules programmatically with terraform.

### Describe Alternatives
I think the two alternatives available today would be: 
1. Manually manage muting rules via the New Relic UI.
2. Script the creation/deletion of muting rules via the  NerdGraph API following the partial examples for query/mutation at the bottom of [this New Relic Documentation page](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications).

**Comment by jthurman42** [comment]
This was resolved in #1167, and available in the [docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_muting_rule)
