### ISSUE TITLE
Provide support to schedule Monitor Downtime

### ISSUE THREAD

**Issue by nvyshnev** [newrelic/terraform-provider-newrelic#980]
### Feature Description
Please provide a terraform support to schedule the monitor downtime/maintenance windows. 

### Describe Alternatives
It's possible to manually schedule a monitor downtime.

### Additional context
A feature request https://discuss.newrelic.com/t/feature-idea-is-there-an-api-for-monitor-downtime/73089

**Comment by ctrombley** [comment]
Hi @nvyshnev, is there any reason [alert muting rules](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_muting_rule) will not work for you?

**Comment by nvyshnev** [comment]
@ctrombley, from what i can see, muting rules :
- can be scheduled for start-end date/time **_but do not have a possibility to repeat it_** (e.g on a daily/weekly basis)
- a condition needs to be specified (**_not a synthetic monitor that i want to disable)_**

For my use case, i need to mute an existing synthetics monitor on a daily basis for a given time range. As for now, i don't see that 'muting rules' functionality will solve this.

**Comment by nvyshnev** [comment]
@ctrombley  Does my answer make sense? Will this feature be implemented some time soon?

**Comment by zlesnr** [comment]
Hi @nvyshnev, it sounds to me like both of those items are feature request of the API.  The first bullet point you have there I believe is already planned.  I'm waiting to hear back from the Alerts team on the second bullet point.  We can only really implement what the API is providing, so there isn't something we can do currently to address the gap in features you'd like to see.  I'll wait to confirm that the second bullet you have there is captured somewhere internally.

**Comment by zlesnr** [comment]
It sounds like the features I mentioned will also support the ability to suppress the violation from a synthetics monitor.

**Comment by emetcalf9** [comment]
The ability to configure Muting Rules repeating is available now, and these can be set up to target the Conditions for the Monitor to prevent them from creating notifications.

I still don't see a way to schedule downtime on the Monitor directly in Terraform, so I will leave this Issue open for the Synthetics team to review this.

**Comment by pranav-new-relic** [comment]
Hi everyone, we shall be closing this issue as this is outdated now - Monitor Downtimes earlier were based on a REST API but are now being shifted to NerdGraph, and once this is out, we shall be able to evaluate building a Terraform Resource for this. We shall keep you posted if there is an update. Thanks!
