### ISSUE TITLE
newrelic_alert_channel of type webhook gets recreated without any changes

### ISSUE THREAD

**Issue by dvishniakov** [newrelic/terraform-provider-newrelic#984]
- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
0.13.1

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alert_channel `

### Terraform Configuration
```hcl
provider "newrelic" {
  version = ">= 2.13, < 2.14"
}

resource "newrelic_alert_channel" "prod" {
  name = "test"
  type = "webhook"

  config {
    base_url = "https://${var.base_url}"

    # Authentication
    auth_type     = "BASIC"
    auth_username = "auth_username"
    auth_password = "auth_password"

    # Request headers
    headers = {
      "account_id" = tostring(var.account_id)
    }

    # Request body
    # !! payload_type is required contrary to the documentation. Error is: "payload_type is required when using payload".
    payload_type = "application/json"
    payload_string = templatefile("${path.module}/payload.json", {
      hostname         = var.hostname,
      cms_account_name = var.cms_account_name,
      cms_customer_id  = var.cms_customer_id,
    })
  }
}
```

Redacted file `payload.json`:
```
{
  "notification_channels": [
    {
      "type": "webhook",
      "endpoint": "https://${hostname}/rest_path",
      "credentials": {
        "username": "username@example.com",
        "password": "password"
      }
    }
  ],
  "alert_cycle_key": "$INCIDENT_ID",
  "alert_title": "$CONDITION_NAME",
  "pretty_event_details": {
    "required_tags": "'cmsaccountname:${cms_account_name}','cmscustomerid:${cms_customer_id}'",
    "description": "$DESCRIPTION",
    "incident_url": "$INCIDENT_URL",
    "policy_url": "$POLICY_URL",
    "severity": "CRITICAL"
  },
  "text_only_msg": {
    "event_details": "$EVENT_DETAILS",
    "targets": "$TARGETS"
  },
  "targets": "$TARGETS",
  "flatten_target": true,
  "map_attributes": {
    "hostname": "{{target_0_name}}",
    "event_title": "[$EVENT_STATE]$CONDITION_NAME | Business Service: {{target_0_labels_label.BusinessService}} | Device: {{target_0_name}}"
  }
}

```

### Actual Behavior
```
  # newrelic_alert_channel.prod must be replaced
-/+ resource "newrelic_alert_channel" "prod" {
      ~ id   = "12345" -> (known after apply)
        name = "test"
        type = "webhook"

      ~ config {
            auth_password  = (sensitive value)
          + auth_type      = (sensitive value)
            auth_username  = "admin"
            base_url       = (sensitive value)
            headers        = (sensitive value)
          - payload        = (sensitive value)
          ~ payload_string = (sensitive value)
            payload_type   = "application/json"
        }
    }
```

### Expected Behavior
Resource should not be recreated.

### Steps to Reproduce
1. `terraform apply`, then `terraform plan`

### In addition
- `auth_type` property probably is not retrieved from NR properly (indicated by addition of the property)
- `payload_type` property is required despite the documentation, which says it's required for `payload` only. May be documentation needs to be corrected.
- `payload_string` is expected to be recreated. I'm not sure why.

**Comment by zlesnr** [comment]
I believe the solution here is the same as in https://github.com/newrelic/terraform-provider-newrelic/issues/130.  Let me know if that works for you.

**Comment by dvishniakov** [comment]
@zlesnr , I can try to `ignore_changes` when I have some time, but I have 3 huge concerns:
1. Only some fields with sensitive data are expected to be changed. `auth_type` is even expected to be **added**, which is probably a miss inside the resource I/O rather than something related to #130.
2. `payload` is expected to be removed while it was not configured in the code - another hint about resource input/output.
3. Ignoring changes to `payload_string` will probably lead to skip of any updates to the payload file, which is not the expected behavior.

**Comment by zlesnr** [comment]
Yes, I agree this is not ideal.  The issue, if I recall correctly, is that the API doesn't currently return the sensitive data to us, so we've no way to know if the attributes have changed.  So the current workaround is to either deal with the constant updates, or ignore them.  We can revisit this to see if anything has changed in this area, as its been this way for some time now, but I suspect we're waiting for API updates before we can improve the situation in the provider.

**Comment by zlesnr** [comment]
We're waiting for API updates before we can proceed as mentioned.  I caught up the the Alerts team about this and am hearing that these updates may land within the quarter or soon after.  We can follow up in TF when those changes land on the API.

**Comment by SiddhantAgarwal17** [comment]
@zlesnr  Any updates on this? Are the relevant APIs now available to proceed with this? With a significant number of policies to be associated with webhook, re-creation just contributes to the additional and unwanted execution to apply the changes.

**Comment by baNROne** [comment]
@dvishniakov I've been taking a look at this and wanted to let you know where it stands currently.

> `auth_type` is even expected to be added

They channels API endpoint doesn't return an `auth_type` value so Terraform sees it as missing. I've created a ticket to address this. However, [channels are scheduled to be deprecated](https://discuss.newrelic.com/t/big-news-for-alerts-and-applied-intelligence/161436), so I don't want to get your hopes up that this field will be added to the API before the deprecation occurs. Since `auth_type` is an optional field and has only one possible value, you can leave it off when creating the resource even if you're supplying `auth_username` and `auth_password`.

> `payload` is expected to be removed while it was not configured in the code

Due to the way Go handles json marshaling, keys are alphabetized when the stored object is converted to a string representation. If the keys in your payload  string (e.g. `payload.json` shared above) are not alphabetized the provider will see this as a different value that will need to be updated. Because its parent, `payload`, is configured with `ForceNew: true`, presumably because of the potential for it to contain sensitive information, `payload` will be destroyed and recreated. Ensuring your `payload_string` keys are alphabetized should prevent the `payload` and `payload_string` from being destroyed and recreated, so long as they haven't changed.
